#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@go-aliyundrive-webdav[-1]
	add ucitrack go-aliyundrive-webdav
	set ucitrack.@go-aliyundrive-webdav[-1].init=go-aliyundrive-webdav
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
