#!/bin/sh /etc/rc.common
#-- Copyright (C) 2018 dz <dingzhong110@gmail.com>

START=98

re=0

start(){
	enable=$(uci get bbr.config.enabled)
	if [ $enable -eq 1 ]; then
		echo "enable"
		insmod tcp_bbr
		sleep 3
		echo "tcp_bbr" > /etc/modules.d/bbr
		sed -i '/bbr/d' /etc/sysctl.conf
		echo "net.ipv4.tcp_congestion_control=bbr" >> /etc/sysctl.conf
		echo "net.core.default_qdisc=fq" >> /etc/sysctl.conf
		sysctl -p
		if [ $re -eq 0 ]; then
			echo $re
			sysctl -p
		fi 
	fi
}

stop(){
    enable=$(uci get bbr.config.enabled)	
    if [ $enable -ne 1 ]; then
	echo "disable"
	rmmod tcp_bbr
	echo "net.ipv4.tcp_congestion_control=cubic" >> /etc/sysctl.conf
	sed -i '/bbr/d' /etc/sysctl.conf
	sed -i '/net.core.default_qdisc/d' /etc/sysctl.conf
	sysctl -p
	sed -i '/net.ipv4.tcp_congestion_control/d' /etc/sysctl.conf
	sysctl -p
	    if [ $re -ne 1 ]; then
			echo $re
			sysctl -p
        fi 
	fi
}

restart(){
	re=1
	stop
	start
	sysctl -p
}