#!/bin/sh

uci set firewall.@defaults[0].flow_offloading=1
uci commit firewall

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@flowoffload[-1]
	add ucitrack flowoffload
	set ucitrack.@flowoffload[-1].init=flowoffload
	commit ucitrack
EOF

if [ $(uname -m | grep 'x86') != "" ] && [ -n $(uci show wireless) ]
then
	uci set flowoffload.@flow[0].bbr=1
	uci commit flowoffload
fi

exit 0
