#!/bin/sh

# replace existing mwan ucitrack entry
uci -q batch <<-EOF >/dev/null
	del ucitrack.@appfilter[-1]
	add ucitrack appfilter
	set ucitrack.@appfilter[-1].exec="/usr/bin/oaf_rule reload"
	commit ucitrack
EOF

# remove LuCI cache
rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
