#!/bin/sh /etc/rc.common

START=99
STOP=99
UPNPBRIDGE_BIN="/usr/sbin/upnpbridge"

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

# UPnPbridge bridges SSDP datagrams between interfaces.
# At least 2 interfaces must be specified on the command line.
#
# Usage: ./upnpbridge-orig eth0 br-lan [...]

INTERFACES="eth0 br-lan"

start() {
        service_start $UPNPBRIDGE_BIN $INTERFACES
}

stop() {
        service_stop $UPNPBRIDGE_BIN
}

reload() {
        service_reload $UPNPBRIDGE_BIN
}

