#!/bin/sh /etc/rc.common
START=99
STOP=10


start() {
flag=$(ps | grep "/usr/bin/serverchan/serverchan" | grep -v "grep" | wc -l)
if [ $flag -eq 0 ] ;then
/usr/bin/serverchan/serverchan &
else
/usr/bin/serverchan/serverchan crontab
fi
}
stop() {
kill -9 `pgrep -f /usr/bin/serverchan/serverchan`
}
