#!/bin/sh /etc/rc.common
# Created By [CTCGFW]Project OpenWRT
# https://github.com/project-openwrt

START=90
STOP=10

enable="$(uci get gost.@gost[0].enable)"
run_command="$(uci get gost.@gost[0].run_command)"

start()
{
	stop

	[ "${enable}" -ne "1" ] && exit 0
	/usr/bin/gost ${run_command} &
}

stop()
{
	killall -9 "gost" > "/dev/null" 2>&1
}
