#define TOPAZ_PLATFORM
#define TOPAZ_FPGA_PLATFORM 0
#define TOPAZ_EMAC_NULL_BUF_WR
#undef TOPAZ_FPGA_UMCTL1
#define PLATFORM_WMAC_MODE ap
#undef PLATFORM_DEFAULT_BOARD_ID
#define ARC_HW_REV_NEEDS_TLBMISS_FIX
#define TOPAZ_VNET_WR_STAGING 0
