#!/bin/sh
#
# Copyright (C) 2011-2014 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

case "$board" in
alfa-network,ap121f|\
buffalo,bhr-4grv2|\
engenius,ecb1750|\
etactica,eg200|\
glinet,gl-ar300m-lite|\
glinet,gl-ar300m-nand|\
glinet,gl-ar300m-nor|\
glinet,gl-ar300m16|\
glinet,gl-ar750s-nor|\
glinet,gl-ar750s-nor-nand|\
librerouter,librerouter-v1|\
netgear,ex6400|\
netgear,ex7300|\
netgear,wndr4300-v2|\
netgear,wndr4500-v3|\
netgear,wnr1000-v2|\
netgear,wnr2000-v3|\
netgear,wnr2200-8m|\
netgear,wnr2200-16m|\
netgear,wnr612-v2|\
ocedo,koala|\
ocedo,raccoon|\
openmesh,om5p-ac-v2|\
yuncore,a770|\
yuncore,a782|\
yuncore,xd4200)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x10000" "0x10000"
	;;
buffalo,wzr-hp-ag300h)
	ubootenv_add_uci_config "/dev/mtd3" "0x0" "0x10000" "0x10000"
	;;
glinet,gl-ar150)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x8000" "0x10000"
	;;
netgear,wndr3700|\
netgear,wndr3700-v2)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x10000"
	;;
netgear,wndr3700-v4|\
netgear,wndr4300)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x40000" "0x20000"
	;;
qihoo,c301)
	ubootenv_add_uci_config "/dev/mtd9" "0x0" "0x10000" "0x10000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
