#!/bin/sh
#
# Copyright (C) 2016 LEDE
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/ipq806x.sh
. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(ipq806x_board_name)

case "$board" in
ea8500)
	ubootenv_add_uci_config "/dev/mtd10" "0x0" "0x20000" "0x20000"
	;;
nbg6817)
	ubootenv_add_uci_config "/dev/mtdblock9" "0x0" "0x10000" "0x10000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
