#!/bin/sh
#
# Copyright (C) 2012-2014 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

case "$board" in
cloudengines,pogoe02|\
cloudengines,pogoplugv4|\
iom,ix2-200|\
linksys,viper|\
raidsonic,ib-nas62x0|\
seagate,dockstar|\
zyxel,nsa310b|\
zyxel,nsa325)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x20000"
	;;
linksys,audi)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x4000" "0x4000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
