#!/bin/sh
#
# Copyright (C) 2012-2014 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

case "$board" in
dockstar|\
guruplug-server-plus|\
ib62x0|\
linksys-viper|\
nsa310b|\
nsa325|\
pogo_e02|\
sheevaplug|\
sheevaplug-esata)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x20000" "0x20000"
	;;
linksys-audi)
	ubootenv_add_uci_config "/dev/mtd1" "0x0" "0x4000" "0x4000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
