#!/bin/sh
#
# Copyright (C) 2016 LEDE
#

[ -f /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

case "$board" in
	traverse,ls1043v | \
	traverse,ls1043s)
		ubootenv_add_uci_config "/dev/mtd1" "0x40000" "0x2000"  "0x20000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
