#!/bin/sh

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

ubootenv_add_mtd() {
	local idx="$(find_mtd_index "${1}")"
	[ -n "$idx" ] && \
		ubootenv_add_uci_config "/dev/mtd$idx" "${2}" "${3}" "${4}"
}

ubootenv_add_sys_mtd() {
	local idx="$(find_mtd_index "${1}")"
	[ -n "$idx" ] && \
		ubootenv_add_uci_sys_config "/dev/mtd$idx" "${2}" "${3}" "${4}"
}

[ "$board" = "xiaomi,ax6000" ] && {
	ubootenv_add_mtd "0:appsblenv" "0x0" "0x10000" "0x20000"
	ubootenv_add_sys_mtd "bdata" "0x0" "0x10000" "0x20000"
}

config_load ubootenv
config_foreach ubootenv_add_app_config

exit 0
