#!/bin/sh
str1="cgi-bin/luci"
str2=`uci get uhttpd.main.index_page`
result=$(echo $str2 | grep "$str1")
if [ -z "$result" ]
then
	uci -q batch <<-EOF >/dev/null
		add_list uhttpd.main.index_page='cgi-bin/luci'
		commit uhttpd
	EOF
fi	
uci -q batch <<-EOF >/dev/null
	set luci.main.lang=zh_cn
	commit luci
EOF
exit 0
