#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org
. /lib/functions.sh

START=50

DEFAULT=/etc/default/cpulimit


start() {
 /usr/bin/cpulimit.sh start &
}

stop() {
  killall -9 cpulimit
}

