#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@unblockmusic[-1]
	add ucitrack unblockmusic
	set ucitrack.@unblockmusic[-1].init=unblockmusic
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
