#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vpn-policy-routing[-1]
	add ucitrack vpn-policy-routing
	set ucitrack.@vpn-policy-routing[-1].init=vpn-policy-routing
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
