export KBUILD_VERBOSE=1
export ARCH=arm64
obj-m := ftv310_vpu_driver.o
ftv310_vpu_driver-objs = ftv310_vpu_drv.o ftv310e.o ftv310_vpu_dec.o ftv310_vpu_fence.o ftv310_vpu_cache.o ftv310_vpu_mmu.o ftv310_vpu_vcmd.o ftv310_vpu_vcmd_slice.o vcmdswhwregisters.o bidirect_list.o devicemgr.o ftv310_vpu_dmabuf.o ftv310_vpu_fs.o ftv310_vpu_drm.o ftv310_vpu_dec400.o ftv310_vpu_cache.o
KDIR := /home/PHY/jam/NXP865/k510/linux-imx
PWD := $(shell pwd)
default:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean::
	$(MAKE) -C $(KDIR) M=$(PWD) clean
	-rm -f .version
