include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI for Samba4
LUCI_DEPENDS:=+samba4x-server
LUCI_PKGARCH:=all
PKG_VERSION:=1.0
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature