#!/bin/sh

uci batch <<__EOF__

delete network.wan.solos0

add_list network.wan.solos0="ActivateLine=Abort"
add_list network.wan.solos0="Retrain=EnableAll"
add_list network.wan.solos0="DetectNoise=Enable"
add_list network.wan.solos0="BisMCapability=Disable"
add_list network.wan.solos0="BisACapability=Disable"
add_list network.wan.solos0="ActivateLine=Start"

commit network
__EOF__
