#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Roaring Penguing PPPoE Server
LUCI_DEPENDS:=+rp-pppoe-server

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
