#!/bin/sh

LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")
wan_ip=$(ubus call network.interface.wan status | grep "address" | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}')
sed -i '1,100d' /etc/fullconenat/fullconenat-ip
echo "$wan_ip" >> /etc/fullconenat/fullconenat-ip
ip=$(cat /etc/fullconenat/fullconenat-ip|sed -n '1p')
ip1=$(cat /etc/fullconenat/fullconenat-ip1|sed -n '1p')


ubus call network.interface.wan status | grep "address" | grep -oE '[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}'
if [ "$?" == "0" ]; then
	iptables -t nat -L -n --line-numbers | grep FULLCONENAT
	if [ "$?" == "0" ]; then
		if [[ $(echo $ip|tr '.' '+'|bc) -eq $(echo $ip1|tr '.' '+'|bc) ]] ; then
			echo '['$LOGTIME'] fullconenat No Problem.'
		else
			echo '['$LOGTIME'] Problem decteted, restarting fullconenat...'
			/etc/init.d/fullconenat restart
		fi
	else
		echo '['$LOGTIME'] Problem decteted, restarting fullconenat...'
		/etc/init.d/fullconenat restart
	fi
else
	echo '['$LOGTIME'] Waiting for network connection.'
fi

	sed -i '1,100d' /etc/fullconenat/fullconenat-ip
	sed -i '1,100d' /etc/fullconenat/fullconenat-ip1
	echo "$wan_ip" >> /etc/fullconenat/fullconenat-ip1
