#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-server[-1]
	add ucitrack pppoe-server
	set ucitrack.@pppoe-server[-1].init=pppoe-server
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
