#
# Copyright (C) 2017 TDT AG <development@tdt.de>
#
# This is free software, licensed under the Apache License Version 2.0.
# See https://www.apache.org/licenses/LICENSE-2.0 for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Link Aggregation (Channel Bonding)
LUCI_DEPENDS:=+proto-bonding
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Helge Mader <ma@dev.tdt.de>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
