#!/bin/sh /etc/rc.common

START=50
STOP=10

enabled="$(uci get verysync.config.enabled)"
port="$(uci get verysync.config.port)"
profile="$(uci get verysync.config.profile)"

start() {
	[ "${enabled}" == "1" ] || exit 0
	export HOME="/root/"
	verysync -gui-address="0.0.0.0:${port}" -logfile="/var/log/verysync.log" -home="${profile}" -no-browser >/dev/null 2>&1 &
}

stop() {
	killall verysync >/dev/null 2>&1
}
