#!/bin/sh /etc/rc.common

START=60

start(){
	enabled=$(uci get qosv4.@qos_settings[0].enable)
	[ "$enabled" -eq 1 ] &&  /usr/bin/qosv4 start
}

stop(){
	/usr/bin/qosv4 stop
}
restart(){
	/etc/init.d/qosv4 stop
	/etc/init.d/qosv4 start
}
