#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start()
{
  rfc=4096  
  cc=$(grep -c processor /proc/cpuinfo)  
  rsfe=$(echo $cc*$rfc | bc)  
  sysctl -w net.core.rps_sock_flow_entries=$rsfe  
  for fileRps in $(ls /sys/class/net/eth*/queues/rx-*/rps_cpus)  
  do
      echo $cc > $fileRps  
  done
        
  for fileRfc in $(ls /sys/class/net/eth*/queues/rx-*/rps_flow_cnt)  
  do
      echo $rfc > $fileRfc  
  done

  for fileRps in $(ls /sys/class/net/eth*/queues/tx-*/xps_cpus)  
  do
      echo $cc > $fileRps  
  done
  
  a=$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq)
  b=$(echo -n ' : ')
  c=$(cat /proc/cpuinfo | grep 'core id' | sort -u | wc -l)
  d=$(echo -n ' Core ')
  e=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
  f=$(echo -n ' Thread ')
  g=${a}${b}${c}${d}${e}${f}
  echo $g > /tmp/sysinfo/model
  
  [ -f /etc/index.htm ] && mv /etc/index.htm /usr/lib/lua/luci/view/admin_status/index.htm
}



