#!/bin/sh /etc/rc.common
# Copyright (C) 2017 lean <coolsnowwolf@gmail.com>

START=99

start()
{
  rfc=4096  
  cc=$(grep -c processor /proc/cpuinfo)  
  rsfe=$(echo $cc*$rfc | bc)  
  sysctl -w net.core.rps_sock_flow_entries=$rsfe  
  for fileRps in $(ls /sys/class/net/eth*/queues/rx-*/rps_cpus)  
  do
      echo $cc > $fileRps  
  done
        
  for fileRfc in $(ls /sys/class/net/eth*/queues/rx-*/rps_flow_cnt)  
  do
      echo $rfc > $fileRfc  
  done

  for fileRps in $(ls /sys/class/net/eth*/queues/tx-*/xps_cpus)  
  do
      echo $cc > $fileRps  
  done
  
  a=$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq)
  b=$(echo -n ' x ')
  c=$(cat /proc/cpuinfo | grep 'processor' | wc -l)
  f=${a}${b}${c}
  echo $f > /tmp/sysinfo/model
}



