#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci for Music Remote Center
LUCI_DEPENDS:=+alsa-utils +forked-daapd
LUCI_PKGARCH:=all
PKG_VERSION:=1
PKG_RELEASE:=5

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature

