#!/bin/sh /etc/rc.common

START=99

start() {
	enable=$(uci get serverchan.@serverchan[0].enabled)
	if [ $enable -eq 1 ]; then	
		echo "enable"
		kill -9 $(ps | grep serverchan.sh | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
		sleep 1
		nohup /usr/share/serverchan/serverchan.sh > /var/log/serverchan.file 2>&1 &
	fi
}

stop() {
	enable=$(uci get serverchan.@serverchan[0].enabled)
	if [ $enable -ne 1 ]; then
		echo "stop!"
		kill $(pidof serverchan) >/dev/null 2>&1
		kill -9 $(ps | grep serverchan.sh | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
	fi
}

restart(){
	stop
	sleep 2
	start
	echo "restarted."
}