#!/bin/sh /etc/rc.common
#
# Copyright (C) 2018 rosysong@rosinson.com
#

. /lib/nft-qos/nft-qos.sh

START=60
USE_PROCD=1

nft_qos_init_config() {
	config_load nft-qos
	nft_qos_append_header
	nft_qos_append_commands
	nft_qos_init
}

service_triggers() {
	procd_add_reload_trigger nft-qos
}

start_service() {
	nft_qos_flush qos
	nft_qos_init_config
	nft_qos_start
}

stop_service() {
	nft_qos_flush qos
	rm -f $NFT_QOS_SCRIPT_FILE
}
