/***************************************************************
Copyright Statement:

This software/firmware and related documentation (EcoNet Software) 
are protected under relevant copyright laws. The information contained herein 
is confidential and proprietary to EcoNet (HK) Limited (EcoNet) and/or 
its licensors. Without the prior written permission of EcoNet and/or its licensors, 
any reproduction, modification, use or disclosure of EcoNet Software, and 
information contained herein, in whole or in part, shall be strictly prohibited.

EcoNet (HK) Limited  EcoNet. ALL RIGHTS RESERVED.

BY OPENING OR USING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY 
ACKNOWLEDGES AND AGREES THAT THE SOFTWARE/FIRMWARE AND ITS 
DOCUMENTATIONS (ECONET SOFTWARE) RECEIVED FROM ECONET 
AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON AN AS IS 
BASIS ONLY. ECONET EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, 
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, 
OR NON-INFRINGEMENT. NOR DOES ECONET PROVIDE ANY WARRANTY 
WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTIES WHICH 
MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE ECONET SOFTWARE. 
RECEIVER AGREES TO LOOK ONLY TO SUCH THIRD PARTIES FOR ANY AND ALL 
WARRANTY CLAIMS RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES 
THAT IT IS RECEIVERS SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD 
PARTY ALL PROPER LICENSES CONTAINED IN ECONET SOFTWARE.

ECONET SHALL NOT BE RESPONSIBLE FOR ANY ECONET SOFTWARE RELEASES 
MADE TO RECEIVERS SPECIFICATION OR CONFORMING TO A PARTICULAR 
STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND 
ECONET'S ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE ECONET 
SOFTWARE RELEASED HEREUNDER SHALL BE, AT ECONET'S SOLE OPTION, TO 
REVISE OR REPLACE THE ECONET SOFTWARE AT ISSUE OR REFUND ANY SOFTWARE 
LICENSE FEES OR SERVICE CHARGES PAID BY RECEIVER TO ECONET FOR SUCH 
ECONET SOFTWARE.
***************************************************************/

#ifndef __UAPI_ECNT_GLOBAL_MACRO_H_
#define __UAPI_ECNT_GLOBAL_MACRO_H_

#define NO_OPERATION  	0
#define NO_HEADER		1
#define HTML_HEADER		2

#define MAX_ARG_NUM		3
#define MAX_NODE_NAME	32

#if/*TCSUPPORT_COMPILE*/ defined(TCSUPPORT_CMCC)
#define PVC_NUM 	1
#else/*TCSUPPORT_COMPILE*/
/*Wan related*/
#ifndef PURE_BRIDGE
	#define PVC_NUM 8
#else
	#define PVC_NUM 4
#endif
#endif/*TCSUPPORT_COMPILE*/

#define MAX_SERVICE_NUM 8
#define MAX_SMUX_NUM 8
#define MAX_WAN_IF_INDEX  (PVC_NUM*MAX_SMUX_NUM)

#define WAN_ENCAP_DYN_INT		0
#define WAN_ENCAP_STATIC_INT	1
#define WAN_ENCAP_PPP_INT		2
#define WAN_ENCAP_BRIDGE_INT	3
#define WAN_ENCAP_NONE_INT		4
#define MAX_LANHOST2_ENTRY_NUM	68

#if defined(TCSUPPORT_CUC)
#define CUC_MAX_SSID_NUM		4
#define CUC_MAX_SSIDAC_NUM		4
#endif
#define ECNT_UID				668
#define ECNT_GID				ECNT_UID
#endif/* __ECNT_GLOBAL_MACRO_H_ */

