#!/bin/sh

uci -q batch <<-EOF >/dev/null
          delete ucitrack.@cpulimit[-1]
          add ucitrack cpulimit
          set ucitrack.@cpulimit[-1].init=cpulimit
          commit ucitrack
EOF

chmod 777 /etc/init.d/cpulimit
chmod 777 /usr/bin/cpulimit.sh
/etc/init.d/cpulimit enable

rm -f /tmp/luci-indexcache
exit 0
