#ifndef _XPON_CONST_H_
#define _XPON_CONST_H_

#include "xpon_public_const.h"

#define SC_PLOAM_NUM_DELIMITER_BYTES 3
#define XPON_QUEUE_NUMBER 8
#define XPON_SHAPING_NUMBER 32
#define XPON_CHANNEL_NUMBER 32
#define GPON_OMCI_INTERFACE 0x1ff
#define GPON_MAX_ANI_INTERFACE 256
#define GPON_ALARM_MAX_NUM 15
#define EPON_1G_MAX_LLID_NUM 8
#define EPON_LLID_MAX_NUM 32

typedef enum {
	GPON_INT_PLOAMD_RECV = 0,
	GPON_INT_PLOAMU_SEND,
	GPON_INT_SN_REQ_RECV,
	GPON_INT_SN_ONU_SEND_O3,
	GPON_INT_RANGING_REQ_RECV,
	GPON_INT_ONU_SEND_O4,
	GPON_INT_SN_REQ_CRS,
	GPON_INT_LOS_GEN_DEL,
	GPON_INT_AES_KEY_SWITCH_DONE,
	GPON_INT_TOD_UPDATE_DONE,
	GPON_INT_TOD_1PPS,
	GPON_INT_DYING_GASP_SEND,
	GPON_INT_RX_ERR = 16,
	GPON_INT_FIFO_ERR,
	GPON_INT_BST_SGL_DIFF,
	GPON_INT_TX_LATE_START,
	GPON_INT_RX_EOF_ERR,
	GPON_INT_RX_GEM_INTLV_ERR,
	GPON_INT_BFIFO_FULL,
	GPON_INT_SFIFO_FULL,
	GPON_INT_O5_EQD_ADJ_DONE,
	GPON_INT_OLT_DS_FEC_CHG,
	GPON_INT_ONU_US_FEC_CHG,
	GPON_INT_POP_UP_RECV_IN_O6,
	GPON_INT_FWI,
	GPON_INT_LWI,
	GPON_INT_BWM_STOP_TIME_ERR,
} GPON_INTERRUPT_MASK_T;

typedef enum {
	GPON_EQD_OFFSET_FLAG_ADD = 0,
	GPON_EQD_OFFSET_FLAG_SUBTRACT,
} GPON_EQD_OFFSET_FLAG_t;

#endif
