#ifndef _XPON_EPON_IOCTL_H_
#define _XPON_EPON_IOCTL_H_

enum {
	EPON_IOCTL_SET_LLID_ENABLE_MASK = 1,
	EPON_IOCTL_LLID_DEREGISTER,
	EPON_IOCTL_LLID_DISCV_RGSTACK,
	EPON_IOCTL_SET_LLID_KEY,
	EPON_IOCTL_GET_LLID_KEY,
	EPON_IOCTL_SET_LLID_TX_FEC,
	EPON_IOCTL_GET_LLID_TX_FEC,
	EPON_IOCTL_SET_LLID_RX_FEC,
	EPON_IOCTL_GET_LLID_RX_FEC,
	EPON_IOCTL_SET_LLID_MAC,
	EPON_IOCTL_GET_LLID_KEY_INUSE,
	EPON_IOCTL_MAC_RST,
	EPON_IOCTL_SET_LLID_DBA_THRSHLD_NUM,
	EPON_IOCTL_GET_LLID_DBA_THRSHLD_NUM,
	EPON_IOCTL_SET_LLID_DBA_THROD,
	EPON_IOCTL_GET_LLID_DBA_THROD,
	EPON_IOCTL_SET_MPCP_TIME,
	EPON_IOCTL_GET_MPCP_TIME,
	EPON_IOCTL_SET_HOLDOVER_CFG,
	EPON_IOCTL_GET_HOLDOVER_CFG,
	EPON_IOCTL_GET_TX_ETH_MIB,
	EPON_IOCTL_GET_RX_ETH_MIB,
	EPON_IOCTL_CLR_TX_RX_MIB,
	EPON_IOCTL_POWER_CTL,
	EPON_IOCTL_AUTH_FAIL_CTL,
	EPON_IOCTL_SET_SILENCETIME,
	EPON_IOCTL_SET_DEBUG_LEVEL,
	EPON_IOCTL_SET_PHY_BURST_EN,
	EPON_IOCTL_SET_DYING_GASP_MODE,
	EPON_IOCTL_GET_DYING_GASP_MODE,
	EPON_IOCTL_SET_DYING_GASP_NUM,
	EPON_IOCTL_GET_DYING_GASP_NUM,
	EPON_IOCTL_SET_10G_LLID_KEY,
	EPON_IOCTL_GET_10G_LLID_KEY,
	EPON_IOCTL_GET_EPON_MODE,
	EPON_IOCTL_SET_EPON_MODE,
	EPON_IOCTL_SET_DPOE_LLID_KEY,
	EPON_IOCTL_SET_MACSEC_INFO,
	EPON_IOCTL_XPON_LED_CTL,
};

#define EPON_IOCTL_SET_LLID_DBA_QUE_NUM EPON_IOCTL_SET_LLID_DBA_THRSHLD_NUM
#define EPON_IOCTL_GET_LLID_DBA_QUE_NUM EPON_IOCTL_GET_LLID_DBA_THRSHLD_NUM
#define EPON_IOCTL_MACSEC_INFO EPON_IOCTL_SET_MACSEC_INFO

#endif
