#!/bin/sh

info()
{

		#获取CPU工作频率
	MHz=`grep 'MHz' /proc/cpuinfo | cut -c11- |sed -n '1p'`

	sensors >/dev/null

	if [ $? -eq 0 ];then

		#获取CPU核心1温度
	a=`sensors | grep 'Core 0' | cut -c10-24`

	else
	a=""
	fi
}

out()
{
	info
	echo "$MHz MHz $a "
}

out

