#!/bin/sh /etc/rc.common
# Copyright (C) 2007-2012 OpenWrt.org

START=90

CONFIGFILE_COMMENTS="/tmp/dhcp_comments.conf"

cappend() {
	local value="$1"

	echo "${value#--}" >> $CONFIGFILE_COMMENTS
}

dhcp_comment_add() {
	config_host(){
		config_get comments "$1" comments
		config_get ip "$1" ip
		config_get mac "$1" mac
		if [ -n "$ip" -a -n "$ip" -o -n "$comments" ]; then
			[ -n "$mac" ] && mac="-"
	 		[ -n "$ip" ] && ip="-"
			cappend "$comments $mac $ip"
		else
			break
		fi
	}
	config_load devcom
	config_foreach config_host host
}

start(){
	rm CONFIGFILE_COMMENTS 2>/dev/null
	dhcp_comment_add
}