{+fast-redirects{s@&plid=\d+&uid=@&plid=7038006&uid=@} }
hot.vrs.sohu.com/vrs_flash.action\?vid=
{+fast-redirects{s@/Main.swf\?(?!plid)@/Main.swf?plid=7038006&@} }
tv.sohu.com/upload/swf/201.*?/Main.swf\?
{+fast-redirects{s@http://tv.sohu.com/upload/swf/.*?/PlayerShell.swf@http://update.adbyby.com/swf/sohu_livezb.swf@} }
tv.sohu.com/upload/swf/.*?/PlayerShell.swf\?
{+fast-redirects{s@pl.youku.com/playlist/m3u8\?keyframe=0&.*@update.adbyby.com/youku.m3u8@} }
pl.youku.com/playlist/m3u8\?keyframe=0&

