#!/bin/sh

/etc/init.d/xlnetacc enabled || exit 0
[ "$INTERFACE" != "$(uci get xlnetacc.general.network)" ] && exit 0

case "$ACTION" in
	ifup)
		/etc/init.d/xlnetacc start
		;;
	ifdown)
		/etc/init.d/xlnetacc stop
		;;
esac
