/***************************************************************
Copyright Statement:

This software/firmware and related documentation (AIROHA Software) 
are protected under relevant copyright laws. The information contained herein 
is confidential and proprietary to AIROHA Limited (AIROHA) and/or 
its licensors. Without the prior written permission of AIROHA and/or its licensors, 
any reproduction, modification, use or disclosure of AIROHA Software, and 
information contained herein, in whole or in part, shall be strictly prohibited.

AIROHA Limited AIROHA. ALL RIGHTS RESERVED.

BY OPENING OR USING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY 
ACKNOWLEDGES AND AGREES THAT THE SOFTWARE/FIRMWARE AND ITS 
DOCUMENTATIONS (AIROHA SOFTWARE) RECEIVED FROM AIROHA 
AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON AN AS IS 
BASIS ONLY. AIROHA EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, 
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, 
OR NON-INFRINGEMENT. NOR DOES AIROHA PROVIDE ANY WARRANTY 
WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTIES WHICH 
MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE AIROHA SOFTWARE. 
RECEIVER AGREES TO LOOK ONLY TO SUCH THIRD PARTIES FOR ANY AND ALL 
WARRANTY CLAIMS RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES 
THAT IT IS RECEIVERS SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD 
PARTY ALL PROPER LICENSES CONTAINED IN AIROHA SOFTWARE.

AIROHA SHALL NOT BE RESPONSIBLE FOR ANY AIROHA SOFTWARE RELEASES 
MADE TO RECEIVERS SPECIFICATION OR CONFORMING TO A PARTICULAR 
STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND 
AIROHA'S ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE AIROHA 
SOFTWARE RELEASED HEREUNDER SHALL BE, AT AIROHA'S SOLE OPTION, TO 
REVISE OR REPLACE THE AIROHA SOFTWARE AT ISSUE OR REFUND ANY SOFTWARE 
LICENSE FEES OR SERVICE CHARGES PAID BY RECEIVER TO AIROHA FOR SUCH 
AIROHA SOFTWARE.
***************************************************************/

#ifndef __UAPI_ECNT_EVENT_SERDES_H_
#define __UAPI_ECNT_EVENT_SERDES_H_

/************************************************************************
*               I N C L U D E S
************************************************************************/
#ifdef __KERNEL__
#include <linux/types.h>
#include <linux/ioctl.h>
#else
#include <stdint.h>
#include <sys/ioctl.h>
#endif

/************************************************************************
*               D E F I N E S   &   C O N S T A N T S
************************************************************************/
#define SERDES_CFG_DEV							("/dev/serdes_cfg")
#define SERDES_CFG_IOC_MAGIC					(0xAA)

#define SERDES_CFG_IOCTL_GET_PORT_CNT			_IOWR(SERDES_CFG_IOC_MAGIC, 0,  serdesCfgIoctl_t *) 
#if 0 /* Unused */
#define SERDES_CFG_IOCTL_GET_IF_CNT				_IOWR(SERDES_CFG_IOC_MAGIC, 1,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_PORT_NAME			_IOWR(SERDES_CFG_IOC_MAGIC, 2,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_IF_NAME			_IOWR(SERDES_CFG_IOC_MAGIC, 3,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_ETHER_TYPE_NAME	_IOWR(SERDES_CFG_IOC_MAGIC, 4,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_ETHER_TYPE_CNT		_IOWR(SERDES_CFG_IOC_MAGIC, 5,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_CHECK_SERDES_ARG		_IOWR(SERDES_CFG_IOC_MAGIC, 6,  serdesCfgIoctl_t *) 
#endif
#define SERDES_CFG_IOCTL_GET_PORT_ENV_NAME		_IOWR(SERDES_CFG_IOC_MAGIC, 7,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_IF_SEL				_IOWR(SERDES_CFG_IOC_MAGIC, 8,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_ETHER_TYPE_SEL		_IOWR(SERDES_CFG_IOC_MAGIC, 9,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_USAGE				_IOWR(SERDES_CFG_IOC_MAGIC, 10,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_GET_STATUS				_IOWR(SERDES_CFG_IOC_MAGIC, 11,  serdesCfgIoctl_t *) 
#define SERDES_CFG_IOCTL_SET_ETHSEL_ETHTYPE		_IOWR(SERDES_CFG_IOC_MAGIC, 12,  serdesCfgIoctl_t *)

#define UNKNOW_SERDES_IF						(0xFF)

#ifdef TCSUPPORT_BOARD_SELECT
#define SERDES_CFG_IOCTL_GET_PHY_TYPE_SEL       _IOWR(SERDES_CFG_IOC_MAGIC, 13,  serdesCfgIoctl_t *)
#define PORT_NAME_SIZE							(16)
#define RET_STRING_LEN_MAX						(128)
#else
#define RET_STRING_LEN_MAX						(2048)
#endif

#define	SERDES_IF_SEL_OFFSET					(0)
#define	SERDES_IF_SEL_MASK						(0xF)
#define	SERDES_ETHER_TYPE_SEL_OFFSET			(4)
#define	SERDES_ETHER_TYPE_SEL_MASK				(0xF)
#define	SERDES_PHY_SEL_OFFSET					(8)
#define	SERDES_PHY_SEL_MASK						(0xF)

#ifdef TCSUPPORT_BOARD_SELECT

typedef enum ECNT_EVENT_SYSTEM_SERDES_PORT {
	ECNT_EVENT_SERDES_PORT_0 	= 0,
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* for 7523/7581/7552 */
	ECNT_EVENT_PON_HSGMII		= 0,	/* 7523 serdes IF 0 */
	ECNT_EVENT_SERDES_PORT_1	= 1,
	ECNT_EVENT_SERDES_SEL_ETHER = 1,	/* 7581 serdes IF 1 */
	ECNT_EVENT_USB3_HSGMII		= 1,	/* 7523 serdes IF 1 */
	ECNT_EVENT_SERDES_PORT_2	= 2,
	ECNT_EVENT_SERDES_SEL_WIFI1	= 2,	/* 7581 serdes IF 2 */
	ECNT_EVENT_PCIE0_HSGMII		= 2,	/* 7523 serdes IF 2 */
	ECNT_EVENT_SERDES_PORT_3	= 3,
	ECNT_EVENT_SERDES_SEL_WIFI2	= 3,	/* 7581 serdes IF 3 */
	ECNT_EVENT_PCIE1_HSGMII		= 3,	/* 7523 serdes IF 3 */
	ECNT_EVENT_SERDES_PORT_4	= 4,
	ECNT_EVENT_SERDES_SEL_USB1	= 4,	/* 7581 serdes IF 4 */
	ECNT_EVENT_SERDES_PORT_5	= 5,
	ECNT_EVENT_SERDES_SEL_USB2	= 5,	/* for 7581 */
	ECNT_EVENT_SERDES_PORT_6	= 6,
	ECNT_EVENT_SERDES_PORT_7	= 7,
	ECNT_EVENT_SERDES_PORT_8	= 8,
	ECNT_EVENT_SERDES_PORT_9	= 9,
} ECNT_EVENT_SYSTEM_SERDES_SEL_t;

/* SerDes I/F */
typedef enum ECNT_EVENT_SYSTEM_SERDES_IF{
	ECNT_EVENT_SERDES_PON_PON			= 0,	/* for 7523/7581/7552 */
	ECNT_EVENT_SERDES_ETHER_XFI			= 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE		= 0,	/* for 7523 */
	ECNT_EVENT_SERDES_WIFI2_PCIE		= 0,	/* for 7523 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_2LANE	= 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_USB30		= 0,	
	ECNT_EVENT_SERDES_USB2_USB30		= 0,	
	
	ECNT_EVENT_SERDES_PON_XFI			= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_USXGMII		= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_1LANE	= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE1_1LANE	= 1,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_HSGMII		= 1,	/* for 7523 */
	ECNT_EVENT_SERDES_USB2_PCIE2_1LANE	= 1,	/* for 7552 */
	
	ECNT_EVENT_SERDES_PON_USXGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_HSGMII		= 2,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_NONE			= 2,	/* for 7583 serdes-5 */
		
	ECNT_EVENT_SERDES_PON_HSGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_ETHER_5G_BASER	= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_USXGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_USXGMII		= 3,	/* for 7581 */
	ECNT_EVENT_SERDES_USB1_SGMII		= 3,	/* for 7583 serdes-5 */
	
	ECNT_EVENT_SERDES_WIFI1_XFI			= 4,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_XFI			= 4,	/* for 7581 */
	
	ECNT_EVENT_SERDES_PON_NONE			= 4,	/* for 7583 serdes-1 */
	ECNT_EVENT_SERDES_ETHER_NONE		= 4,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_WIFI1_NONE		= 5,	/* for 7583 serdes-3 */
	ECNT_EVENT_SERDES_WIFI2_NONE		= 5,	/* for 7583 serdes-4 */
	ECNT_EVENT_SERDES_PON_SGMII			= 5,	/* for 7583 serdes-1 */
	
	ECNT_EVENT_SERDES_ETHER_FTTR_OLT	= 5,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_IF_PCIE_G3_1LANE	= 5,
	ECNT_EVENT_SERDES_IF_PCIE_G2_1LANE	= 6,
	ECNT_EVENT_SERDES_ETHER_SGMII		= 6,	/* for 7583 serdes-2 */
	ECNT_EVENT_SERDES_WIFI2_SGMII		= 6,	/* for 7583 serdes-4 */
	ECNT_EVENT_SERDES_IF_USB30			= 7,
	ECNT_EVENT_SERDES_IF_USB20_ONLY		= 8,
	ECNT_EVENT_SERDES_IF_USB20_HSGMII	= 9,
} ECNT_EVENT_SYSTEM_SERDES_IF_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_TYPE_NONE = 0,
	ECNT_EVENT_SERDES_ETHER_TYPE_LAN = 1,
	ECNT_EVENT_SERDES_ETHER_TYPE_WAN,
	ECNT_EVENT_SERDES_ETHER_TYPE_MAX,
	ECNT_EVENT_SERDES_ETHER_TYPE_ERROR = -1,
} ECNT_EVENT_SYSTEM_SERDES_ETHER_TYPE_SEL_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_PHY_NONE = 0,
	ECNT_EVENT_SERDES_PHY_AN8811,
	ECNT_EVENT_SERDES_PHY_A,
	ECNT_EVENT_SERDES_PHY_B,
	ECNT_EVENT_SERDES_PHY_C,
	ECNT_EVENT_SERDES_PHY_D,
	ECNT_EVENT_SERDES_PHY_E,
	ECNT_EVENT_SERDES_PHY_DSL,
	ECNT_EVENT_SERDES_PHY_F,
	ECNT_EVENT_SERDES_PHY_MAX,
	ECNT_EVENT_SERDES_PHY_ERROR = -1,
} ECNT_EVENT_SYSTEM_SERDES_PHY_SEL_t;

#else

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_TYPE_NONE = 0,
	ECNT_EVENT_SERDES_ETHER_TYPE_LAN = 1,
	ECNT_EVENT_SERDES_ETHER_TYPE_WAN,
	ECNT_EVENT_SERDES_ETHER_TYPE_MAX,
} ECNT_EVENT_SYSTEM_SERDES_ETHER_TYPE_SEL_t;

/* SerDes-Port */
typedef enum {
#ifdef TCSUPPORT_CPU_AN7552
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* 7581 serdes IF 0 */
	ECNT_EVENT_SERDES_SEL_MAX,
	ECNT_EVENT_SERDES_SEL_WIFI1,
	ECNT_EVENT_SERDES_SEL_WIFI2,
	ECNT_EVENT_SERDES_SEL_ETHER,
#else
	ECNT_EVENT_SERDES_SEL_PON	= 0,	/* 7581 serdes IF 0 */
	ECNT_EVENT_PON_HSGMII		= 0,	/* 7523 serdes IF 0 */
	ECNT_EVENT_SERDES_SEL_ETHER = 1,	/* 7581 serdes IF 1 */
	ECNT_EVENT_USB3_HSGMII		= 1,	/* 7523 serdes IF 1 */
	ECNT_EVENT_SERDES_SEL_WIFI1 = 2,	/* 7581 serdes IF 2 */
	ECNT_EVENT_PCIE0_HSGMII		= 2,	/* 7523 serdes IF 2 */
	ECNT_EVENT_SERDES_SEL_WIFI2 = 3,	/* 7581 serdes IF 3 */
	ECNT_EVENT_PCIE1_HSGMII		= 3,	/* 7523 serdes IF 3 */
	ECNT_EVENT_SERDES_SEL_USB1,			/* 7581 serdes IF 4 */
	ECNT_EVENT_SERDES_SEL_USB2,			/* 7581 serdes IF 5 */
	ECNT_EVENT_SERDES_SEL_MAX,
#endif
}ECNT_EVENT_SYSTEM_SERDES_SEL_t;

/* ether type */
typedef enum {
	ECNT_EVENT_SERDES_PHY_NONE = 0,
	ECNT_EVENT_SERDES_PHY_AN8811,
	ECNT_EVENT_SERDES_PHY_A,
	ECNT_EVENT_SERDES_PHY_B,
	ECNT_EVENT_SERDES_PHY_C,
	ECNT_EVENT_SERDES_PHY_D,
	ECNT_EVENT_SERDES_PHY_E,
	ECNT_EVENT_SERDES_PHY_DSL,
	ECNT_EVENT_SERDES_PHY_F,
	ECNT_EVENT_SERDES_PHY_MAX,
} ECNT_EVENT_SYSTEM_SERDES_PHY_SEL_t;

/* SerDes-PON */
typedef enum {
#ifdef TCSUPPORT_CPU_AN7552
	ECNT_EVENT_SERDES_PON_PON = 0,
	ECNT_EVENT_SERDES_PON_HSGMII,
	ECNT_EVENT_SERDES_PON_NONE,
	ECNT_EVENT_SERDES_PON_MAX,
	ECNT_EVENT_SERDES_PON_XFI,			/* for 7581 */
	ECNT_EVENT_SERDES_PON_USXGMII,
#else
	ECNT_EVENT_SERDES_PON_PON = 0,
	ECNT_EVENT_SERDES_PON_HSGMII,
	ECNT_EVENT_SERDES_PON_XFI,		/* for 7581 */
	ECNT_EVENT_SERDES_PON_USXGMII,
	ECNT_EVENT_SERDES_PON_NONE,		/* for 7581 */
	ECNT_EVENT_SERDES_PON_MAX,

#endif
	
}ECNT_EVENT_SYSTEM_SERDES_PON_SEL_t;

/* SerDes-Ethernet */
typedef enum {
	ECNT_EVENT_SERDES_ETHER_XFI = 0,
	ECNT_EVENT_SERDES_ETHER_USXGMII,
	ECNT_EVENT_SERDES_ETHER_HSGMII,
	ECNT_EVENT_SERDES_ETHER_5G_BASER,
	ECNT_EVENT_SERDES_ETHER_NONE,
	ECNT_EVENT_SERDES_ETHER_MAX,
}ECNT_EVENT_SYSTEM_SERDES_ETHER_SEL_t;

/* SerDes-WiFi1 */
typedef enum {
	ECNT_EVENT_SERDES_WIFI1_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_PCIE = 0,			/* for 7523 */
	ECNT_EVENT_SERDES_WIFI1_PCIE0_1LANE,		/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_HSGMII,
	ECNT_EVENT_SERDES_WIFI1_USXGMII,
	ECNT_EVENT_SERDES_WIFI1_XFI,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI1_MAX,
}ECNT_EVENT_SYSTEM_SERDES_WIFI1_SEL_t;

/* SerDes-WiFi2 */
typedef enum {
	ECNT_EVENT_SERDES_WIFI2_PCIE0_2LANE = 0,	/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_PCIE = 0,			/* for 7523 */
	ECNT_EVENT_SERDES_WIFI2_PCIE1_1LANE,		/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_HSGMII,
	ECNT_EVENT_SERDES_WIFI2_USXGMII,
	ECNT_EVENT_SERDES_WIFI2_XFI,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_WIFI2_MAX,
}ECNT_EVENT_SYSTEM_SERDES_WIFI2_SEL_t;

/* SerDes-USB1 */
typedef enum {
	ECNT_EVENT_SERDES_USB1_USB30 = 0,
	ECNT_EVENT_SERDES_USB1_HSGMII,
	ECNT_EVENT_SERDES_USB1_NONE,				/* for 7581 */
	ECNT_EVENT_SERDES_USB1_MAX,
}ECNT_EVENT_SYSTEM_SERDES_USB1_SEL_t;

 /* SerDes-USB2 */
typedef enum {
	ECNT_EVENT_SERDES_USB2_USB30 = 0,
	ECNT_EVENT_SERDES_USB2_PCIE2_1LANE,
	ECNT_EVENT_SERDES_USB2_NONE,
	ECNT_EVENT_SERDES_USB2_MAX,
}ECNT_EVENT_SYSTEM_SERDES_USB2_SEL_t;

#endif

/************************************************************************
*               M A C R O S
************************************************************************/

/************************************************************************
*               D A T A   T Y P E S
************************************************************************/
typedef struct {
	ECNT_EVENT_SYSTEM_SERDES_SEL_t port_idx;
	int port_cnt;
	uint8_t serdes_if;
	int serdes_if_cnt;
	ECNT_EVENT_SYSTEM_SERDES_ETHER_TYPE_SEL_t ether_type;
	int ether_type_cnt;
	char name[RET_STRING_LEN_MAX];
	ECNT_EVENT_SYSTEM_SERDES_PHY_SEL_t phy_sel;
} serdesCfgIoctl_t ;

/************************************************************************
*               D A T A   D E C L A R A T I O N S
************************************************************************/

/************************************************************************
*               F U N C T I O N   D E C L A R A T I O N S
                I N L I N E  F U N C T I O N  D E F I N I T I O N S
*************************************************************************/

#endif/* __UAPI_ECNT_EVENT_SERDES_H_ */

