#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@kodexplorer[-1]
	add ucitrack kodexplorer
	set ucitrack.@kodexplorer[-1].init=kodexplorer
	commit ucitrack
EOF

/etc/init.d/php7-fpm disable && /etc/init.d/php7-fpm stop
rm -rf /tmp/luci-*cache
exit 0
