#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

LOGFILE="/var/etc/nps.log"
tmpconf="/tmp/etc/nps.conf"

nps_header() {
	local enabled server_addr server_port protocol vkey compress crypt log_level

	config_get enabled $1 enabled
	config_get server_addr $1 server_addr
	config_get server_port $1 server_port
	config_get protocol $1 protocol
	config_get vkey $1 vkey
	config_get compress $1 compress
	config_get crypt $1 crypt
	config_get log_level $1 log_level

	[ -f $tmpconf ] && rm $tmpconf
	echo "[common]" >$tmpconf
	echo "server_addr=${server_addr}:${server_port}" >>$tmpconf
	echo "conn_type=${protocol}" >>$tmpconf
	echo "vkey=${vkey}" >>$tmpconf

	nps_write_bool compress $1
	nps_write_bool crypt $1

	Log_level=$log_level
	Enabled=$enabled
}

nps_write_bool() {
	local opt="$1"
	local config="$2"
	local val

	config_get_bool val $config "$opt"
	if [ "$val" -eq 0 ]; then
		echo "${opt}=false" >> $tmpconf
	else
		echo "${opt}=true" >> $tmpconf
	fi
}

start() {
	config_load nps
	config_foreach nps_header nps

	if [ "$Enabled" = "0" ];then
		stop
	else
		logger -t FRPC 'Starting Nps service'
		service_start /usr/bin/npc -config=$tmpconf -log_level=$Log_level -log_path=$LOGFILE
	fi

	return 0
}

stop() {
	service_stop /usr/bin/npc
	rm $tmpconf
	logger -t FRPC 'Nps service stopped' 
	return 0
}
