#!/bin/sh

[ -f "/etc/mwan3.user" ] && {
	. /lib/functions.sh

	config_load mwan3
	config_get_bool enabled globals 'enabled' '0'
	[ ${enabled} -gt 0 ] || exit 0

	config_get enabled "$INTERFACE" enabled 0
	[ "${enabled}" = "1" ] || exit 0
	env -i ACTION="$ACTION" INTERFACE="$INTERFACE" DEVICE="$DEVICE" \
		/bin/sh /etc/mwan3.user
}

exit 0
