#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shairport-sync[-1]
	add ucitrack shairport-sync
	set ucitrack.@shairport-sync[-1].init=shairport-sync
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
