#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@passwall[-1]
	add ucitrack passwall
	set ucitrack.@passwall[-1].init=passwall
	commit ucitrack
EOF

rm -rf /tmp/luci-indexcache /tmp/luci-modulecache

exit 0
