#!/bin/sh /etc/rc.common
#
# Copyright (C) 2020 Jerryk
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

USE_PROCD=1
START=25

NAME=jd-dailybonus
CRON_FILE=/etc/crontabs/root
JD_SCRIPT=/usr/share/jd-dailybonus/JD_DailyBonus.js



del_cron() {
	sed -i '/jd-dailybonus/d' $CRON_FILE
	/etc/init.d/cron restart
}

start_service(){
	/usr/share/jd-dailybonus/newapp.sh -s
}

stop_service() {
    del_cron
}

service_triggers() {
	procd_add_reload_trigger "jd-dailybonus"
}