#!/bin/sh /etc/rc.common
#
# Copyright (C) 2020 Jerryk
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=25
STOP=10

NAME=jd-dailybonus
CRON_FILE=/etc/crontabs/root


del_cron() {
	sed -i '/jd-dailybonus/d' $CRON_FILE
	/etc/init.d/cron restart
}

start_service(){
	sh /usr/share/jd-dailybonus/newapp.sh -s
}

stop_service() {
    del_cron
}

service_triggers() {
	procd_add_reload_trigger "jd-dailybonus"
}
