#!/bin/sh
chmod 755 /etc/init.d/netspeedtest /etc/init.d/speedtest >/dev/null 2>&1
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netspeedtest[-1]
	add ucitrack netspeedtest
	set ucitrack.@netspeedtest[-1].init=netspeedtest
	commit ucitrack
EOF
rm -rf /tmp/luci-modulecache /tmp/luci-indexcache*
exit 0
