.\" @(#)ccalpdf.1
.TH ccalpdf 1 "4 October 2003"
.SH NAME
ccalpdf \- generates a calendar together with Chinese calendar in PDF
.SH SYNOPSIS
\f3ccalpdf\f1
[
.B \-g|\-b
] [
.B \-o
.I file
] [ [
.I month
]
.I year
]
.SH DESCRIPTION
The
.B ccalpdf
script writes a Gregorian calendar together with Chinese calendar in PDF
to standard output.
If the
.I year
operand is specified, a calendar for that year is written.
If no operands are specified, a calendar for the current month is written.
.SH OPTIONS
.TP
.B \-g
Outputs simplified Chinese characters. This is the default.
.TP
.B \-b
Outputs traditional Chinese characters.
.TP
.B \-o \fIfile\fP
Outputs the calendar to
.I file
instead of standard output.
.SH OPERANDS
The following operands are supported:
.TP 8
.I month
Specify the month to be displayed, represented as a decimal integer from
.B 1
(January) to
.B 12
(December).
The default is the current month.
.TP
.I year
Specify the year for which the calendar is displayed,
represented as a decimal integer from
.B 1645
to
.BR 9999 .
However, accuracy will gradually decrease beyond 300 years
from Year 2000.  The default is the current year.
.SH "EXIT STATUS"
The following exit values are returned:
.PD 0
.TP 10
.B 0
Successful completion.
.TP
.B >0
An error occurred.
.PD
.SH "SEE ALSO"
.BR ccal (1)
.RE
