#!/bin/sh /etc/rc.common

START=19

reload() {
	/usr/sbin/mwan3 restart
}

boot() {
	. /lib/config/uci.sh
	uci_toggle_state mwan3 globals enabled "1"
}

start() {
	/usr/sbin/mwan3 start
}

stop() {
	/usr/sbin/mwan3 stop
}
