#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tranmsmission[-1]
	add ucitrack transmission
	set ucitrack.@transmission[-1].init=transmission
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
