/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
**                        Module HostInterfaceExtended1                       **
**                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
*******************************************************************************/

/* Register AQWriteAddrHigh **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

/* This register defines the high 16 bit address for the 48 bit write         **
** address.                                                                   */

`define AQWriteAddrHighRegAddrs                                         16'h5FF0
`define AQ_WRITE_ADDR_HIGH_MSB                                                15
`define AQ_WRITE_ADDR_HIGH_LSB                                                 0
`define AQ_WRITE_ADDR_HIGH_BLK                                                 0
`define AQ_WRITE_ADDR_HIGH_Count                                               1
`define AQ_WRITE_ADDR_HIGH_FieldMask                                32'h0000FFFF
`define AQ_WRITE_ADDR_HIGH_ReadMask                                 32'h0000FFFF
`define AQ_WRITE_ADDR_HIGH_WriteMask                                32'h0000FFFF
`define AQ_WRITE_ADDR_HIGH_ResetValue                               32'h00000000

/* 16 bit high address for write. */
`define AQ_WRITE_ADDR_HIGH_ADDRESS_MSB                                        15
`define AQ_WRITE_ADDR_HIGH_ADDRESS_LSB                                         0
`define AQ_WRITE_ADDR_HIGH_ADDRESS_SIZE                                       16

/* Register AQReadAddrHigh **
** ~~~~~~~~~~~~~~~~~~~~~~~ */

/* This register defines the high 16 bit address for the 48 bit read address. */

`define AQReadAddrHighRegAddrs                                          16'h5FF1
`define AQ_READ_ADDR_HIGH_MSB                                                 15
`define AQ_READ_ADDR_HIGH_LSB                                                  0
`define AQ_READ_ADDR_HIGH_BLK                                                  0
`define AQ_READ_ADDR_HIGH_Count                                                1
`define AQ_READ_ADDR_HIGH_FieldMask                                 32'h0000FFFF
`define AQ_READ_ADDR_HIGH_ReadMask                                  32'h0000FFFF
`define AQ_READ_ADDR_HIGH_WriteMask                                 32'h0000FFFF
`define AQ_READ_ADDR_HIGH_ResetValue                                32'h00000000

/* 16 bit high address for read. */
`define AQ_READ_ADDR_HIGH_ADDRESS_MSB                                         15
`define AQ_READ_ADDR_HIGH_ADDRESS_LSB                                          0
`define AQ_READ_ADDR_HIGH_ADDRESS_SIZE                                        16

/* Register gcTotalWriteValidWSTRB **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total Write Valid WSTRB Register. Total Write Data count in terms of 64    **
** bits. This register has no reset value.                                    */

`define gcTotalWriteValidWSTRBRegAddrs                                  16'h5FF2
`define GC_TOTAL_WRITE_VALID_WSTRB_MSB                                        15
`define GC_TOTAL_WRITE_VALID_WSTRB_LSB                                         0
`define GC_TOTAL_WRITE_VALID_WSTRB_BLK                                         0
`define GC_TOTAL_WRITE_VALID_WSTRB_Count                                       1
`define GC_TOTAL_WRITE_VALID_WSTRB_FieldMask                        32'hFFFFFFFF
`define GC_TOTAL_WRITE_VALID_WSTRB_ReadMask                         32'hFFFFFFFF
`define GC_TOTAL_WRITE_VALID_WSTRB_WriteMask                        32'h00000000
`define GC_TOTAL_WRITE_VALID_WSTRB_ResetValue                       32'h00000000

/* Total write data count in terms of 64bits. */
`define GC_TOTAL_WRITE_VALID_WSTRB_COUNT_MSB                                  31
`define GC_TOTAL_WRITE_VALID_WSTRB_COUNT_LSB                                   0
`define GC_TOTAL_WRITE_VALID_WSTRB_COUNT_SIZE                                 32

/* Register gcTotalWriteValidWSTRBOCB **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total Write Valid WSTRB On Chip Buffer Register. Total Write Data count On **
** Chip Buffer in terms of 64 bits. This register has no reset value.         */

`define gcTotalWriteValidWSTRBOCBRegAddrs                               16'h5FF3
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_MSB                                     15
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_LSB                                      0
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_BLK                                      0
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_Count                                    1
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_FieldMask                     32'hFFFFFFFF
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_ReadMask                      32'hFFFFFFFF
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_WriteMask                     32'h00000000
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_ResetValue                    32'h00000000

/* Total write data count in terms of 64bits. */
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_COUNT_MSB                               31
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_COUNT_LSB                                0
`define GC_TOTAL_WRITE_VALID_WSTRBOCB_COUNT_SIZE                              32

