/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** L2 ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_L2Ch0Rd                                               16'h0001
`define GC_ProbeCount_L2Ch0RdMiss                                           16'h0002
`define GC_ProbeCount_L2Ch0Wr                                               16'h0003
`define GC_ProbeCount_L2Ch0WrMIss                                           16'h0004
`define GC_ProbeCount_L2Ch1Rd                                               16'h0005
`define GC_ProbeCount_L2Ch1RdMiss                                           16'h0006
`define GC_ProbeCount_L2Ch1Wr                                               16'h0007
`define GC_ProbeCount_L2Ch1WrMIss                                           16'h0008
`define GC_ProbeCount_L2Ch2Rd                                               16'h0009
`define GC_ProbeCount_L2Ch2RdMiss                                           16'h000a
`define GC_ProbeCount_L2Ch2Wr                                               16'h000b
`define GC_ProbeCount_L2Ch2WrMIss                                           16'h000c
`define GC_ProbeCount_L2Ch3Rd                                               16'h000d
`define GC_ProbeCount_L2Ch3RdMiss                                           16'h000e
`define GC_ProbeCount_L2Ch3Wr                                               16'h000f
`define GC_ProbeCount_L2Ch3WrMIss                                           16'h0010
`define GC_ProbeCount_L2Ch4Rd                                               16'h0011
`define GC_ProbeCount_L2Ch4RdMiss                                           16'h0012
`define GC_ProbeCount_L2Ch4Wr                                               16'h0013
`define GC_ProbeCount_L2Ch4WrMIss                                           16'h0014
`define GC_ProbeCount_L2Ch5Rd                                               16'h0015
`define GC_ProbeCount_L2Ch5RdMiss                                           16'h0016
`define GC_ProbeCount_L2Ch5Wr                                               16'h0017
`define GC_ProbeCount_L2Ch5WrMIss                                           16'h0018
`define GC_ProbeCount_L2Ch6Rd                                               16'h0019
`define GC_ProbeCount_L2Ch6RdMiss                                           16'h001a
`define GC_ProbeCount_L2Ch6Wr                                               16'h001b
`define GC_ProbeCount_L2Ch6WrMIss                                           16'h001c
`define GC_ProbeCount_L2Ch7Rd                                               16'h001d
`define GC_ProbeCount_L2Ch7RdMiss                                           16'h001e
`define GC_ProbeCount_L2Ch7Wr                                               16'h001f
`define GC_ProbeCount_L2Ch7WrMIss                                           16'h0020
`define GC_ProbeCycle_L2GlobalTimerStartLo                                  16'h00fa
`define GC_ProbeCycle_L2GlobalTimerStartHi                                  16'h00fb
`define GC_ProbeCycle_L2GlobalTimerEndLo                                    16'h00fc
`define GC_ProbeCycle_L2GlobalTimerEndHi                                    16'h00fd
`define GC_ProbeCycle_L2GlobalTimerLo                                       16'h00fe
`define GC_ProbeCycle_L2GlobalTimerHi                                       16'h00ff
