/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** DIR ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCycle_DirBank0OutOfPendingTags                              16'h0001
`define GC_ProbeCycle_DirBank1OutOfPendingTags                              16'h0002
`define GC_ProbeCycle_DirBank2OutOfPendingTags                              16'h0003
`define GC_ProbeCycle_DirBank3OutOfPendingTags                              16'h0004
`define GC_ProbeCycle_DirCcxCacheReqGblTxRemoteHit                          16'h0005
`define GC_ProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit                     16'h0006
`define GC_ProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit                     16'h0007
`define GC_ProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit                    16'h0008
`define GC_ProbeCycle_DirCcxCacheInputReqGblTx                              16'h0009
`define GC_ProbeCycle_DirCcxCacheInputReqGblNonTx                           16'h000a
`define GC_ProbeCycle_DirCcxCacheInputReqAttrib                             16'h000b
`define GC_ProbeCycle_DirBankCoherencyStall                                 16'h000c
`define GC_ProbeCycle_DirGlobalTimerStartLo                                 16'h00fa
`define GC_ProbeCycle_DirGlobalTimerStartHi                                 16'h00fb
`define GC_ProbeCycle_DirGlobalTimerEndLo                                   16'h00fc
`define GC_ProbeCycle_DirGlobalTimerEndHi                                   16'h00fd
`define GC_ProbeCycle_DirGlobalTimerLo                                      16'h00fe
`define GC_ProbeCycle_DirGlobalTimerHi                                      16'h00ff
