/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** WD ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_WdVsGroup                                             16'h0001
`define GC_ProbeCount_WdTcsGroup                                            16'h0002
`define GC_ProbeCount_WdTesGroup                                            16'h0003
`define GC_ProbeCount_WdGsGroup                                             16'h0004
`define GC_ProbeCount_WdVsThread                                            16'h0005
`define GC_ProbeCount_WdTcsThread                                           16'h0006
`define GC_ProbeCount_WdTesThread                                           16'h0007
`define GC_ProbeCount_WdGsThread                                            16'h0008
`define GC_ProbeCount_WdGpipeGroupCluster0                                  16'h0010
`define GC_ProbeCount_WdGpipeGroupCluster1                                  16'h0011
`define GC_ProbeCount_WdGpipeGroupCluster2                                  16'h0012
`define GC_ProbeCount_WdGpipeGroupCluster3                                  16'h0013
`define GC_ProbeCount_WdGpipeGroupCluster4                                  16'h0014
`define GC_ProbeCount_WdGpipeGroupCluster5                                  16'h0015
`define GC_ProbeCount_WdGpipeGroupCluster6                                  16'h0016
`define GC_ProbeCount_WdGpipeGroupCluster7                                  16'h0017
`define GC_ProbeCount_WdGpipeDataCycleCluster0                              16'h0018
`define GC_ProbeCount_WdGpipeDataCycleCluster1                              16'h0019
`define GC_ProbeCount_WdGpipeDataCycleCluster2                              16'h001a
`define GC_ProbeCount_WdGpipeDataCycleCluster3                              16'h001b
`define GC_ProbeCount_WdGpipeDataCycleCluster4                              16'h001c
`define GC_ProbeCount_WdGpipeDataCycleCluster5                              16'h001d
`define GC_ProbeCount_WdGpipeDataCycleCluster6                              16'h001e
`define GC_ProbeCount_WdGpipeDataCycleCluster7                              16'h001f
`define GC_ProbeCount_Wd2TfbCluster0                                        16'h0020
`define GC_ProbeCount_Wd2TfbCluster1                                        16'h0021
`define GC_ProbeCount_Wd2TfbCluster2                                        16'h0022
`define GC_ProbeCount_Wd2TfbCluster3                                        16'h0023
`define GC_ProbeCount_Wd2TfbCluster4                                        16'h0024
`define GC_ProbeCount_Wd2TfbCluster5                                        16'h0025
`define GC_ProbeCount_Wd2TfbCluster6                                        16'h0026
`define GC_ProbeCount_Wd2TfbCluster7                                        16'h0027
`define GC_ProbeCount_Wd2FpaTrxTotal                                        16'h0030
`define GC_ProbeCount_Wd2FpaTrxCluster                                      16'h0031
`define GC_ProbeCount_WdTpgDataRCacheReq                                    16'h0032
`define GC_ProbeCount_WdTpgDataRCacheMiss                                   16'h0033
`define GC_ProbeCount_WdDrawTotal                                           16'h0034
`define GC_ProbeCount_WdTwTrigger                                           16'h0035
`define GC_ProbeCount_Fe2WdState                                            16'h0036
`define GC_ProbeCount_Wd2TfbState                                           16'h0037
`define GC_ProbeCount_Wd2FpaState                                           16'h0038
`define GC_ProbeCount_Fe2WdToken                                            16'h0039
`define GC_ProbeCount_Fe2WdStateFlush                                       16'h003a
`define GC_ProbeCount_Fe2WdSemaphore                                        16'h003b
`define GC_ProbeCycle_WdBusy                                                16'h0050
`define GC_ProbeCycle_WdVsWaitAac                                           16'h0051
`define GC_ProbeCycle_WdTcsWaitAac                                          16'h0052
`define GC_ProbeCycle_WdTesWaitAac                                          16'h0053
`define GC_ProbeCycle_WdGsWaitAac                                           16'h0054
`define GC_ProbeCycle_WdWaitGpipe                                           16'h0055
`define GC_ProbeCycle_WdVldAndTfbNotRdyAll                                  16'h0056
`define GC_ProbeCycle_WdVldAndFpaNotRdyAll                                  16'h0057
`define GC_ProbeCycle_Wd2TfbNotVldData                                      16'h0058
`define GC_ProbeCycle_Wd2FpaNotVldData                                      16'h0059
`define GC_ProbeCycle_WdRdyAndPpaNotVld                                     16'h005a
`define GC_ProbeCycle_WdTfbWaitCompletion                                   16'h005b
`define GC_ProbeCycle_WdVsGroupTotalLatency                                 16'h005c
`define GC_ProbeCycle_WdTcsGroupTotalLatency                                16'h005d
`define GC_ProbeCycle_WdTesGroupTotalLatency                                16'h005e
`define GC_ProbeCycle_WdGsGroupTotalLatency                                 16'h005f
`define GC_ProbeCycle_WdTotalSemaphoreStall                                 16'h0060
`define GC_ProbeCycle_WdBalanceWaitSemaphore                                16'h0061
`define GC_ProbeCycle_WdBalanceWaitEvent                                    16'h0062
`define GC_ProbeCycle_WdBalanceWaitPsDone                                   16'h0063
`define GC_ProbeCycle_WdBalanceWaitGpipeFlush                               16'h0064
`define GC_ProbeCycle_WdSmallBatchWaitUniformTxAlloc                        16'h0065
`define GC_ProbeCycle_WdAnyBltBusy                                          16'h0066
`define GC_ProbeState_WdTsGsEnable                                          16'h0080
`define GC_ProbeState_WdUscConfig                                           16'h0081
`define GC_ProbeCycle_WdGlobalTimerStartLo                                  16'h00fa
`define GC_ProbeCycle_WdGlobalTimerStartHi                                  16'h00fb
`define GC_ProbeCycle_WdGlobalTimerEndLo                                    16'h00fc
`define GC_ProbeCycle_WdGlobalTimerEndHi                                    16'h00fd
`define GC_ProbeCycle_WdGlobalTimerLo                                       16'h00fe
`define GC_ProbeCycle_WdGlobalTimerHi                                       16'h00ff
