/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** SE ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_SeInputTri                                            16'h0001
`define GC_ProbeCount_SeOutputTri                                           16'h0002
`define GC_ProbeCount_SeClipTri                                             16'h0003
`define GC_ProbeCount_SeInputCycles                                         16'h0004
`define GC_ProbeCount_SeFloatPipeActiveCycles                               16'h0005
`define GC_ProbeCycle_SeFloatPipeStarveCycles                               16'h0006
`define GC_ProbeCycle_SeBusy                                                16'h0010
`define GC_ProbeCycle_SeVldAndRaRdy                                         16'h0011
`define GC_ProbeCycle_SeVldAndRaNotRdy                                      16'h0012
`define GC_ProbeCycle_Se2RaNotVldData                                       16'h0013
`define GC_ProbeCycle_SeGlobalTimerStartLo                                  16'h00fa
`define GC_ProbeCycle_SeGlobalTimerStartHi                                  16'h00fb
`define GC_ProbeCycle_SeGlobalTimerEndLo                                    16'h00fc
`define GC_ProbeCycle_SeGlobalTimerEndHi                                    16'h00fd
`define GC_ProbeCycle_SeGlobalTimerLo                                       16'h00fe
`define GC_ProbeCycle_SeGlobalTimerHi                                       16'h00ff
`define GC_FPGA_ProbeCount_SeInputTri                                            16'h0801
`define GC_FPGA_ProbeCount_OutputTri                                             16'h0802
`define GC_FPGA_ProbeCount_SeInputLine                                           16'h0803
`define GC_FPGA_ProbeCount_OutputLine                                            16'h0804
`define GC_FPGA_ProbeCount_ClipTri                                               16'h0805
`define GC_FPGA_ProbeCount_ClipLine                                              16'h0806
`define GC_FPGA_ProbeCount_CullTri                                               16'h0807
`define GC_FPGA_ProbeCount_CullLine                                              16'h0808
`define GC_FPGA_ProbeCount_ZeroLenLine                                           16'h0809
`define GC_FPGA_ProbeCycle_SeBusy                                                16'h0c01
`define GC_FPGA_ProbeCycle_PaNotVldAndSeRdySeBusy                                16'h0c02
`define GC_FPGA_ProbeCycle_SeVldAndRaRdy                                         16'h0c03
`define GC_FPGA_ProbeCycle_SeVldAndRaNotRdy                                      16'h0c04
`define GC_FPGA_ProbeCycle_SeNotVldAndRaRdy                                      16'h0c05
`define GC_FPGA_ProbeCycle_SeNotVldAndRaNotRdy                                   16'h0c06
