/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** FPA ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_FpaInputVtx                                           16'h0001
`define GC_ProbeCount_FpaInputPrim                                          16'h0002
`define GC_ProbeCount_FpaOutputPrim                                         16'h0003
`define GC_ProbeCount_FpaInputTri                                           16'h0004
`define GC_ProbeCount_FpaInputLine                                          16'h0005
`define GC_ProbeCount_FpaInputPoint                                         16'h0006
`define GC_ProbeCount_FpaDropPrim                                           16'h0008
`define GC_ProbeCount_FpaCullPrim                                           16'h0009
`define GC_ProbeCount_FpaFrustumClipPrim                                    16'h000a
`define GC_ProbeCycle_FpaFrustumClipActive                                  16'h000b
`define GC_ProbeCycle_FpaBusy                                               16'h0010
`define GC_ProbeCycle_ReqFpaVldAndUscRdy                                    16'h0011
`define GC_ProbeCycle_ReqFpaVldAndUscNotRdy                                 16'h0012
`define GC_ProbeCycle_DataUscVldAndFpaRdy                                   16'h0013
`define GC_ProbeCycle_DataUscVldAndFpaNotRdy                                16'h0014
`define GC_ProbeCycle_FpaVldAndSeRdy                                        16'h0015
`define GC_ProbeCycle_FpaVldAndSeNotRdy                                     16'h0016
`define GC_ProbeCycle_Fpa2UscRdTotalLatency                                 16'h0017
`define GC_ProbeCycle_FpaUscReqStallByCredit                                16'h0018
`define GC_ProbeCycle_FpaUscDataNotAvailable                                16'h0019
`define GC_ProbeCount_FpaCommonCorePLAVCycle                                16'h001a
`define GC_ProbeCount_FpaCommonCoreClipCycle                                16'h001b
`define GC_ProbeCycle_Fpa2SeNotVldData                                      16'h001c
`define GC_ProbeCycle_FpaGlobalTimerStartLo                                 16'h00fa
`define GC_ProbeCycle_FpaGlobalTimerStartHi                                 16'h00fb
`define GC_ProbeCycle_FpaGlobalTimerEndLo                                   16'h00fc
`define GC_ProbeCycle_FpaGlobalTimerEndHi                                   16'h00fd
`define GC_ProbeCycle_FpaGlobalTimerLo                                      16'h00fe
`define GC_ProbeCycle_FpaGlobalTimerHi                                      16'h00ff
`define GC_64BIT_ProbeCount_ClipOutputPrimLo                                      16'h1001
`define GC_64BIT_ProbeCount_ClipOutputPrimHi                                      16'h1002
