/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** PA ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCycle_PaGlobalTimerStartLo                                  16'h00fa
`define GC_ProbeCycle_PaGlobalTimerStartHi                                  16'h00fb
`define GC_ProbeCycle_PaGlobalTimerEndLo                                    16'h00fc
`define GC_ProbeCycle_PaGlobalTimerEndHi                                    16'h00fd
`define GC_ProbeCycle_PaGlobalTimerLo                                       16'h00fe
`define GC_ProbeCycle_PaGlobalTimerHi                                       16'h00ff
`define GC_FPGA_ProbeCount_InputVtx                                              16'h0801
`define GC_FPGA_ProbeCount_InputPrim                                             16'h0802
`define GC_FPGA_ProbeCount_OutputPrim                                            16'h0803
`define GC_FPGA_ProbeCount_PaInputTri                                            16'h0804
`define GC_FPGA_ProbeCount_PaInputLine                                           16'h0805
`define GC_FPGA_ProbeCount_InputPoint                                            16'h0806
`define GC_FPGA_ProbeCount_2PlaneClipPrim                                        16'h0807
`define GC_FPGA_ProbeCount_4PlaneClipPrim                                        16'h0808
`define GC_FPGA_ProbeCount_6PlaneClipPrim                                        16'h0809
`define GC_FPGA_ProbeCount_TrivialRejPrim                                        16'h080a
`define GC_FPGA_ProbeCount_ZeroAreaPrim                                          16'h080b
`define GC_FPGA_ProbeCount_ZeroWPrim                                             16'h080c
`define GC_FPGA_ProbeCount_BackFacePrim                                          16'h080d
`define GC_FPGA_ProbeCount_DropPrim                                              16'h080e
`define GC_FPGA_ProbeCount_6PlaneClipDropPrim                                    16'h080f
`define GC_FPGA_ProbeCount_NoDupVtx                                              16'h0810
`define GC_FPGA_ProbeCycle_PaBusy                                                16'h0c01
`define GC_FPGA_ProbeCycle_TfbVldAndPARdy                                        16'h0c02
`define GC_FPGA_ProbeCycle_TfbVldAndPANotRdy                                     16'h0c03
`define GC_FPGA_ProbeCycle_TfbNotVldAndPARdy                                     16'h0c04
`define GC_FPGA_ProbeCycle_TfbNotVldAndPANotRdy                                  16'h0c05
`define GC_FPGA_ProbeCycle_TfbNotVldAndPARdyPaBusy                               16'h0c06
`define GC_FPGA_ProbeCycle_PaVldAndSeRdy                                         16'h0c07
`define GC_FPGA_ProbeCycle_PaVldAndSeNotRdy                                      16'h0c08
`define GC_FPGA_ProbeCycle_PaNotVldAndSeRdy                                      16'h0c09
`define GC_FPGA_ProbeCycle_PaNotVldAndSeNotRdy                                   16'h0c0a
`define GC_FPGA_ProbeCycle_PaVldAndUscRdy                                        16'h0c0b
`define GC_FPGA_ProbeCycle_PaVldAndUscNotRdy                                     16'h0c0c
`define GC_FPGA_ProbeCycle_PaNotVldAndUscRdy                                     16'h0c0d
`define GC_FPGA_ProbeCycle_PaNotVldAndUscNotRdy                                  16'h0c0e
`define GC_FPGA_ProbeCycle_UscVldAndPaRdy                                        16'h0c0f
`define GC_FPGA_ProbeCycle_UscVldAndPaNotRdy                                     16'h0c10
`define GC_FPGA_ProbeCycle_UscNotVldAndPaRdy                                     16'h0c11
`define GC_FPGA_ProbeCycle_UscNotVldAndPaNotRdy                                  16'h0c12
`define GC_FPGA_ProbeCycle_PaVldAndShRdy                                         16'h0c13
`define GC_FPGA_ProbeCycle_PaVldAndShNotRdy                                      16'h0c14
`define GC_FPGA_ProbeCycle_PaNotVldAndShRdy                                      16'h0c15
`define GC_FPGA_ProbeCycle_PaNotVldAndShNotRdy                                   16'h0c16
`define GC_FPGA_ProbeCycle_PaVldAndMcRdy                                         16'h0c17
`define GC_FPGA_ProbeCycle_PaVldAndMcNotRdy                                      16'h0c18
`define GC_FPGA_ProbeCycle_PaNotVldAndMcRdy                                      16'h0c19
`define GC_FPGA_ProbeCycle_PaNotVldAndMcNotRdy                                   16'h0c1a
