/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** APPINFO ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_FPGA_ProbeState_OpNum                                                 16'h0401
`define GC_FPGA_ProbeState_OpTyp                                                 16'h0402
`define GC_FPGA_ProbeState_DrawNum                                               16'h0403
`define GC_FPGA_ProbeState_BlitNum                                               16'h0404
`define GC_FPGA_ProbeState_ComputeNum                                            16'h0405
`define GC_FPGA_ProbeState_ResolveNum                                            16'h0406
`define GC_FPGA_ProbeState_VsId                                                  16'h0407
`define GC_FPGA_ProbeState_TcsId                                                 16'h0408
`define GC_FPGA_ProbeState_TesId                                                 16'h0409
`define GC_FPGA_ProbeState_GsId                                                  16'h040a
`define GC_FPGA_ProbeState_PsId                                                  16'h040b
`define GC_FPGA_ProbeState_CsId                                                  16'h040c
