/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** HI ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_AXIRdByte                                             16'h0001
`define GC_ProbeCount_AXIRdByteHi                                           16'h0010
`define GC_ProbeCount_AXIWrByte                                             16'h0002
`define GC_ProbeCount_AXIWrByteHi                                           16'h0011
`define GC_ProbeCount_AXIRdTotalReq                                         16'h0003
`define GC_ProbeCount_AXIWrTotalReq                                         16'h0004
`define GC_ProbeCount_HiTotalBltEvent                                       16'h0005
`define GC_ProbeCount_HiTotalPeEvent                                        16'h0006
`define GC_ProbeCount_HiTotalFeEvent                                        16'h0007
`define GC_ProbeCount_HiTotalEvent                                          16'h0008
`define GC_ProbeCount_HiTotalEventReadAck                                   16'h0009
`define GC_ProbeCount_HiL2CacheMiss                                         16'h000a
`define GC_ProbeCount_HiL2CacheHit                                          16'h000b
`define GC_ProbeCount_HiMmuMasterCacheReq                                   16'h000c
`define GC_ProbeCount_HiMmuMasterCacheMiss                                  16'h000d
`define GC_ProbeCount_HiMmuSlaveCacheReq                                    16'h000e
`define GC_ProbeCount_HiMmuSlaveCacheMiss                                   16'h000f
`define GC_ProbeCycle_AXIARVALIDAndNotARREADY                               16'h0040
`define GC_ProbeCycle_AXIAWVALIDAndNotAWREADY                               16'h0041
`define GC_ProbeCycle_AXIWVALIDAndNotWREADY                                 16'h0042
`define GC_ProbeCycle_AXIRdMaxOutstanding                                   16'h0046
`define GC_ProbeCycle_AXIWrMaxOutstanding                                   16'h0047
`define GC_ProbeCycle_AXIRdMaxLatency                                       16'h0048
`define GC_ProbeCycle_AXIWrMaxLatency                                       16'h0049
`define GC_ProbeCycle_AXIRdTotalLatency                                     16'h004a
`define GC_ProbeCycle_AXIWrTotalLatency                                     16'h004b
`define GC_ProbeCycle_HiBusy                                                16'h0052
`define GC_ProbeCycle_GpuBusy                                               16'h0053
`define GC_ProbeCycle_HiGlobalTimerStartLo                                  16'h00fa
`define GC_ProbeCycle_HiGlobalTimerStartHi                                  16'h00fb
`define GC_ProbeCycle_HiGlobalTimerEndLo                                    16'h00fc
`define GC_ProbeCycle_HiGlobalTimerEndHi                                    16'h00fd
`define GC_ProbeCycle_HiGlobalTimerLo                                       16'h00fe
`define GC_ProbeCycle_HiGlobalTimerHi                                       16'h00ff
`define GC_FPGA_ProbeCount_AXI0RdByte                                            16'h0801
`define GC_FPGA_ProbeCount_AXI0WrByte                                            16'h0802
`define GC_FPGA_ProbeCount_AXI0Rd16ByteReq                                       16'h0803
`define GC_FPGA_ProbeCount_AXI0Rd32ByteReq                                       16'h0804
`define GC_FPGA_ProbeCount_AXI0Rd64ByteReq                                       16'h0805
`define GC_FPGA_ProbeCount_AXI0Rd128ByteReq                                      16'h0806
`define GC_FPGA_ProbeCount_AXI0Rd256ByteReq                                      16'h0807
`define GC_FPGA_ProbeCount_AXI0Wr16ByteReq                                       16'h0808
`define GC_FPGA_ProbeCount_AXI0Wr32ByteReq                                       16'h0809
`define GC_FPGA_ProbeCount_AXI0Wr64ByteReq                                       16'h080a
`define GC_FPGA_ProbeCount_AXI0Wr128ByteReq                                      16'h080b
`define GC_FPGA_ProbeCount_AXI0Wr256ByteReq                                      16'h080c
`define GC_FPGA_ProbeCount_AXI0ExtLat0_100                                       16'h080d
`define GC_FPGA_ProbeCount_AXI0ExtLat100_200                                     16'h080e
`define GC_FPGA_ProbeCount_AXI0ExtLat200_300                                     16'h080f
`define GC_FPGA_ProbeCount_AXI0ExtLat300_400                                     16'h0810
`define GC_FPGA_ProbeCount_AXI0ExtLat400_500                                     16'h0811
`define GC_FPGA_ProbeCount_AXI0ExtLatLt500                                       16'h0812
`define GC_FPGA_ProbeCount_AXI1RdByte                                            16'h0813
`define GC_FPGA_ProbeCount_AXI1WrByte                                            16'h0814
`define GC_FPGA_ProbeCount_AXI1Rd16ByteReq                                       16'h0815
`define GC_FPGA_ProbeCount_AXI1Rd32ByteReq                                       16'h0816
`define GC_FPGA_ProbeCount_AXI1Rd64ByteReq                                       16'h0817
`define GC_FPGA_ProbeCount_AXI1Rd128ByteReq                                      16'h0818
`define GC_FPGA_ProbeCount_AXI1Rd256ByteReq                                      16'h0819
`define GC_FPGA_ProbeCount_AXI1Wr16ByteReq                                       16'h081a
`define GC_FPGA_ProbeCount_AXI1Wr32ByteReq                                       16'h081b
`define GC_FPGA_ProbeCount_AXI1Wr64ByteReq                                       16'h081c
`define GC_FPGA_ProbeCount_AXI1Wr128ByteReq                                      16'h081d
`define GC_FPGA_ProbeCount_AXI1Wr256ByteReq                                      16'h081e
`define GC_FPGA_ProbeCount_AXI1ExtLat0_100                                       16'h081f
`define GC_FPGA_ProbeCount_AXI1ExtLat100_200                                     16'h0820
`define GC_FPGA_ProbeCount_AXI1ExtLat200_300                                     16'h0821
`define GC_FPGA_ProbeCount_AXI1ExtLat300_400                                     16'h0822
`define GC_FPGA_ProbeCount_AXI1ExtLat400_500                                     16'h0823
`define GC_FPGA_ProbeCount_AXI1ExtLatLt500                                       16'h0824
`define GC_FPGA_ProbeCycle_AXI0ARVALIDAndNotARREADY                              16'h0c01
`define GC_FPGA_ProbeCycle_AXI0NotARVALIDAndARREADY                              16'h0c02
`define GC_FPGA_ProbeCycle_AXI0AWVALIDAndNotAWREADY                              16'h0c03
`define GC_FPGA_ProbeCycle_AXI0NotAWVALIDAndAWREADY                              16'h0c04
`define GC_FPGA_ProbeCycle_AXI0WVALIDAndNotWREADY                                16'h0c05
`define GC_FPGA_ProbeCycle_AXI0NotWVALIDAndWREADY                                16'h0c06
`define GC_FPGA_ProbeCycle_AXI1ARVALIDAndNotARREADY                              16'h0c07
`define GC_FPGA_ProbeCycle_AXI1NotARVALIDAndARREADY                              16'h0c08
`define GC_FPGA_ProbeCycle_AXI1AWVALIDAndNotAWREADY                              16'h0c09
`define GC_FPGA_ProbeCycle_AXI1NotAWVALIDAndAWREADY                              16'h0c0a
`define GC_FPGA_ProbeCycle_AXI1WVALIDAndNotWREADY                                16'h0c0b
`define GC_FPGA_ProbeCycle_AXI1NotWVALIDAndWREADY                                16'h0c0c
`define GC_FPGA_ProbeCycle_TotalCycle                                            16'h0c0d
`define GC_FPGA_ProbeCycle_TotalIdleCycle                                        16'h0c0e
