/*******************************************************************************
**                                                                            **
** Copyright (c) 2025, Phytium Technology Co., Ltd.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
** TFB ProbeCounter. Generated by $(AQARCH)/reg/Probe/Makefile         *|
**                                                                            **
********************************************************************************/

`define GC_ProbeCount_TfbUscRdReq                                           16'h0001
`define GC_ProbeCount_TfbUscWrReq                                           16'h0002
`define GC_ProbeCount_TfbVldAndPpaRdy                                       16'h0003
`define GC_ProbeCycle_TfbVldAndPpaNotRdy                                    16'h0015
`define GC_ProbeCycle_TfbBusy                                               16'h0010
`define GC_ProbeCycle_Tfb2UscRdTotalLatency                                 16'h0011
`define GC_ProbeCycle_Tfb2UscWrTotalLatency                                 16'h0012
`define GC_ProbeCycle_TfbRdReqAndUscNotRdy                                  16'h0013
`define GC_ProbeCycle_TfbWrReqAndUscNotRdy                                  16'h0014
`define GC_ProbeCycle_TfbDataUscVldAndTfbRdy                                16'h0016
`define GC_ProbeCycle_TfbDataUscVldAndTfbNotRdy                             16'h0017
`define GC_ProbeCycle_TfbDataTfbVldAndUscRdy                                16'h0018
`define GC_ProbeCycle_TfbDataTfbVldAndUscNotRdy                             16'h0019
`define GC_ProbeCycle_TfbUscReqStallByCredit                                16'h001a
`define GC_ProbeCycle_TfbUscDataNotAvailable                                16'h001b
`define GC_ProbeCycle_TfbGlobalTimerStartLo                                 16'h00fa
`define GC_ProbeCycle_TfbGlobalTimerStartHi                                 16'h00fb
`define GC_ProbeCycle_TfbGlobalTimerEndLo                                   16'h00fc
`define GC_ProbeCycle_TfbGlobalTimerEndHi                                   16'h00fd
`define GC_ProbeCycle_TfbGlobalTimerLo                                      16'h00fe
`define GC_ProbeCycle_TfbGlobalTimerHi                                      16'h00ff
`define GC_FPGA_ProbeCount_Component                                             16'h0801
`define GC_FPGA_ProbeCount_Descriptor                                            16'h0802
`define GC_64BIT_ProbeCount_TfbPrimFromGsLo                                       16'h1001
`define GC_64BIT_ProbeCount_TfbPrimFromGsHi                                       16'h1002
