/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                              ~~~~~~~~~~~~~~~~                              **
**                              Module MultiChip                              **
**                              ~~~~~~~~~~~~~~~~                              **
*******************************************************************************/

/* Register gcregMultiChipControl **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Multi-chip co-operation control. */

`define gcregMultiChipControlRegAddrs                                   16'h0E80
`define GCREG_MULTI_CHIP_CONTROL_MSB                                          15
`define GCREG_MULTI_CHIP_CONTROL_LSB                                           0
`define GCREG_MULTI_CHIP_CONTROL_BLK                                           0
`define GCREG_MULTI_CHIP_CONTROL_Count                                         1
`define GCREG_MULTI_CHIP_CONTROL_FieldMask                          32'hF1FFFF77
`define GCREG_MULTI_CHIP_CONTROL_ReadMask                           32'hF1FFFF77
`define GCREG_MULTI_CHIP_CONTROL_WriteMask                          32'hF1FFFF77
`define GCREG_MULTI_CHIP_CONTROL_ResetValue                         32'h00000000

/* Multi-chip mode. */
`define GCREG_MULTI_CHIP_CONTROL_MODE_MSB                                      2
`define GCREG_MULTI_CHIP_CONTROL_MODE_LSB                                      0
`define GCREG_MULTI_CHIP_CONTROL_MODE_SIZE                                     3
/* This chip runs its own context. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_OFF                                 3'h0
/* This chip renders only a part of the context. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_WINDOW                              3'h1
/* This chip runs in the context in 16x16 interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED16X16                    3'h2
/* This chip runs in the context in 32x32 interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED32X32                    3'h3
/* This chip runs in the context in 64x64 interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED64X64                    3'h4
/* This chip runs in the context in 128x64 interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED128X64                   3'h5
/* This chip runs in the context in 128x128 interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED128X128                  3'h6
/* This chip runs in the context interleaved mode. */
`define   GCREG_MULTI_CHIP_CONTROL_MODE_INTERLEAVED                         3'h7

/* Multi-chip load balancing mode. */
`define GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_MSB                         6
`define GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_LSB                         4
`define GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SIZE                        3
/* the framebuffer is partitioned to 1 set. */
`define   GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SET1                   3'h0
/* the framebuffer is partitioned to 2 sets. */
`define   GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SET2                   3'h1
/* the framebuffer is partitioned to 3 sets. */
`define   GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SET3                   3'h2
/* the framebuffer is partitioned to 4 sets. */
`define   GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SET4                   3'h3
/* the framebuffer is partitioned to 8 sets. */
`define   GCREG_MULTI_CHIP_CONTROL_LOAD_BALANCE_MODE_SET8                   3'h7

`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET0_MSB                         8
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET0_LSB                         8
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET0_SIZE                        1
/* Block set0 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET0_MAPPED                 1'h1
/* Block set0 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET0_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET1_MSB                         9
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET1_LSB                         9
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET1_SIZE                        1
/* Block set1 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET1_MAPPED                 1'h1
/* Block set1 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET1_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET2_MSB                        10
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET2_LSB                        10
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET2_SIZE                        1
/* Block set2 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET2_MAPPED                 1'h1
/* Block set2 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET2_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET3_MSB                        11
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET3_LSB                        11
`define GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET3_SIZE                        1
/* Block set3 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET3_MAPPED                 1'h1
/* Block set3 is mapped to GPU0 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU0_MAPPING_SET3_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET0_MSB                        12
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET0_LSB                        12
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET0_SIZE                        1
/* Block set0 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET0_MAPPED                 1'h1
/* Block set0 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET0_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET1_MSB                        13
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET1_LSB                        13
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET1_SIZE                        1
/* Block set1 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET1_MAPPED                 1'h1
/* Block set1 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET1_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET2_MSB                        14
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET2_LSB                        14
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET2_SIZE                        1
/* Block set2 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET2_MAPPED                 1'h1
/* Block set2 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET2_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET3_MSB                        15
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET3_LSB                        15
`define GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET3_SIZE                        1
/* Block set3 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET3_MAPPED                 1'h1
/* Block set3 is mapped to GPU1 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU1_MAPPING_SET3_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET0_MSB                        16
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET0_LSB                        16
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET0_SIZE                        1
/* Block set0 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET0_MAPPED                 1'h1
/* Block set0 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET0_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET1_MSB                        17
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET1_LSB                        17
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET1_SIZE                        1
/* Block set1 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET1_MAPPED                 1'h1
/* Block set1 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET1_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET2_MSB                        18
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET2_LSB                        18
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET2_SIZE                        1
/* Block set2 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET2_MAPPED                 1'h1
/* Block set2 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET2_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET3_MSB                        19
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET3_LSB                        19
`define GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET3_SIZE                        1
/* Block set3 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET3_MAPPED                 1'h1
/* Block set3 is mapped to GPU2 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU2_MAPPING_SET3_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET0_MSB                        20
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET0_LSB                        20
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET0_SIZE                        1
/* Block set0 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET0_MAPPED                 1'h1
/* Block set0 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET0_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET1_MSB                        21
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET1_LSB                        21
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET1_SIZE                        1
/* Block set1 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET1_MAPPED                 1'h1
/* Block set1 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET1_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET2_MSB                        22
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET2_LSB                        22
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET2_SIZE                        1
/* Block set2 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET2_MAPPED                 1'h1
/* Block set2 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET2_UNMAPPED               1'h0

`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET3_MSB                        23
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET3_LSB                        23
`define GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET3_SIZE                        1
/* Block set3 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET3_MAPPED                 1'h1
/* Block set3 is mapped to GPU3 */
`define   GCREG_MULTI_CHIP_CONTROL_GPU3_MAPPING_SET3_UNMAPPED               1'h0

/* Simplified CheckerBoard Mode. */
`define GCREG_MULTI_CHIP_CONTROL_SIMPLIFIED_CHECKERBOARD_MODE_MSB             24
`define GCREG_MULTI_CHIP_CONTROL_SIMPLIFIED_CHECKERBOARD_MODE_LSB             24
`define GCREG_MULTI_CHIP_CONTROL_SIMPLIFIED_CHECKERBOARD_MODE_SIZE             1
`define   GCREG_MULTI_CHIP_CONTROL_SIMPLIFIED_CHECKERBOARD_MODE_DISABLED    1'h0
`define   GCREG_MULTI_CHIP_CONTROL_SIMPLIFIED_CHECKERBOARD_MODE_ENABLED     1'h1

/* each bit represent one GPU enable for GPU0~3 */
`define GCREG_MULTI_CHIP_CONTROL_ENABLE_GPU_ENABLE_MSB                        31
`define GCREG_MULTI_CHIP_CONTROL_ENABLE_GPU_ENABLE_LSB                        28
`define GCREG_MULTI_CHIP_CONTROL_ENABLE_GPU_ENABLE_SIZE                        4

/* Register gcregMultiChipTopLeft **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Top left coordinate of rendering window for this chip. */

`define gcregMultiChipTopLeftRegAddrs                                   16'h0E81
`define GCREG_MULTI_CHIP_TOP_LEFT_MSB                                         15
`define GCREG_MULTI_CHIP_TOP_LEFT_LSB                                          0
`define GCREG_MULTI_CHIP_TOP_LEFT_BLK                                          0
`define GCREG_MULTI_CHIP_TOP_LEFT_Count                                        1
`define GCREG_MULTI_CHIP_TOP_LEFT_FieldMask                         32'h7FFF7FFF
`define GCREG_MULTI_CHIP_TOP_LEFT_ReadMask                          32'h7FFF7FFF
`define GCREG_MULTI_CHIP_TOP_LEFT_WriteMask                         32'h7FFF7FFF
`define GCREG_MULTI_CHIP_TOP_LEFT_ResetValue                        32'h00000000

`define GCREG_MULTI_CHIP_TOP_LEFT_Y_MSB                                       30
`define GCREG_MULTI_CHIP_TOP_LEFT_Y_LSB                                       16
`define GCREG_MULTI_CHIP_TOP_LEFT_Y_SIZE                                      15

`define GCREG_MULTI_CHIP_TOP_LEFT_X_MSB                                       14
`define GCREG_MULTI_CHIP_TOP_LEFT_X_LSB                                        0
`define GCREG_MULTI_CHIP_TOP_LEFT_X_SIZE                                      15

/* Register gcregMultiChipBottomRight **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Bottom right coordinate of rendering window for this chip. */

`define gcregMultiChipBottomRightRegAddrs                               16'h0E82
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_MSB                                     15
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_LSB                                      0
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_BLK                                      0
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_Count                                    1
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_FieldMask                     32'h7FFF7FFF
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_ReadMask                      32'h7FFF7FFF
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_WriteMask                     32'h7FFF7FFF
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_ResetValue                    32'h00000000

`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_Y_MSB                                   30
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_Y_LSB                                   16
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_Y_SIZE                                  15

`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_X_MSB                                   14
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_X_LSB                                    0
`define GCREG_MULTI_CHIP_BOTTOM_RIGHT_X_SIZE                                  15

/* Register gcregMultiChipSetMapping **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Block set 4~7 mapped to GPU0~3 */

`define gcregMultiChipSetMappingRegAddrs                                16'h0E83
`define GCREG_MULTI_CHIP_SET_MAPPING_MSB                                      15
`define GCREG_MULTI_CHIP_SET_MAPPING_LSB                                       0
`define GCREG_MULTI_CHIP_SET_MAPPING_BLK                                       0
`define GCREG_MULTI_CHIP_SET_MAPPING_Count                                     1
`define GCREG_MULTI_CHIP_SET_MAPPING_FieldMask                      32'h0000FFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_ReadMask                       32'h0000FFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_WriteMask                      32'h0000FFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_ResetValue                     32'h00000000

/* Whether block set4~7 is mapped to GPU0 */
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU0_MSB                                  3
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU0_LSB                                  0
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU0_SIZE                                 4

/* Whether block set4~7 is mapped to GPU1 */
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU1_MSB                                  7
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU1_LSB                                  4
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU1_SIZE                                 4

/* Whether block set4~7 is mapped to GPU2 */
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU2_MSB                                 11
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU2_LSB                                  8
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU2_SIZE                                 4

/* Whether block set4~7 is mapped to GPU3 */
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU3_MSB                                 15
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU3_LSB                                 12
`define GCREG_MULTI_CHIP_SET_MAPPING_GPU3_SIZE                                 4

/* Register gcregMultiChipSetMappingEx **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Block set 0~7 mapped to GPU4~7 */

`define gcregMultiChipSetMappingExRegAddrs                              16'h0E84
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_MSB                                   15
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_LSB                                    0
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_BLK                                    0
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_Count                                  1
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_FieldMask                   32'hFFFFFFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_ReadMask                    32'hFFFFFFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_WriteMask                   32'hFFFFFFFF
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_ResetValue                  32'h00000000

/* Whether block set0~7 is mapped to GPU4 */
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU4_MSB                               7
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU4_LSB                               0
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU4_SIZE                              8

/* Whether block set0~7 is mapped to GPU5 */
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU5_MSB                              15
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU5_LSB                               8
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU5_SIZE                              8

/* Whether block set0~7 is mapped to GPU6 */
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU6_MSB                              23
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU6_LSB                              16
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU6_SIZE                              8

/* Whether block set0~7 is mapped to GPU7 */
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU7_MSB                              31
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU7_LSB                              24
`define GCREG_MULTI_CHIP_SET_MAPPING_EX_GPU7_SIZE                              8

/* Register gcregMultiChipControlEx **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Multi-chip co-operation control Ex. */

`define gcregMultiChipControlExRegAddrs                                 16'h0E85
`define GCREG_MULTI_CHIP_CONTROL_EX_MSB                                       15
`define GCREG_MULTI_CHIP_CONTROL_EX_LSB                                        0
`define GCREG_MULTI_CHIP_CONTROL_EX_BLK                                        0
`define GCREG_MULTI_CHIP_CONTROL_EX_Count                                      1
`define GCREG_MULTI_CHIP_CONTROL_EX_FieldMask                       32'h0000FFFF
`define GCREG_MULTI_CHIP_CONTROL_EX_ReadMask                        32'h0000FFFF
`define GCREG_MULTI_CHIP_CONTROL_EX_WriteMask                       32'h0000FFFF
`define GCREG_MULTI_CHIP_CONTROL_EX_ResetValue                      32'h00000000

/* Each bit represent one GPU enable for GPU4~19 */
`define GCREG_MULTI_CHIP_CONTROL_EX_ENABLE_GPU_ENABLE_MSB                     15
`define GCREG_MULTI_CHIP_CONTROL_EX_ENABLE_GPU_ENABLE_LSB                      0
`define GCREG_MULTI_CHIP_CONTROL_EX_ENABLE_GPU_ENABLE_SIZE                    16

