/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                             ~~~~~~~~~~~~~~~~~~                             **
**                             Module Performance                             **
**                             ~~~~~~~~~~~~~~~~~~                             **
*******************************************************************************/

/* Register gcregPCTimeStamp **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Cycle counter (time stamp). */

`define gcregPCTimeStampRegAddrs                                        16'h4C00
`define GCREG_PC_TIME_STAMP_MSB                                               15
`define GCREG_PC_TIME_STAMP_LSB                                                0
`define GCREG_PC_TIME_STAMP_BLK                                                0
`define GCREG_PC_TIME_STAMP_Count                                              1
`define GCREG_PC_TIME_STAMP_FieldMask                               32'hFFFFFFFF
`define GCREG_PC_TIME_STAMP_ReadMask                                32'hFFFFFFFF
`define GCREG_PC_TIME_STAMP_WriteMask                               32'hFFFFFFFF
`define GCREG_PC_TIME_STAMP_ResetValue                              32'h00000000

`define GCREG_PC_TIME_STAMP_COUNTER_MSB                                       31
`define GCREG_PC_TIME_STAMP_COUNTER_LSB                                        0
`define GCREG_PC_TIME_STAMP_COUNTER_SIZE                                      32

/* Register gcregPCComamdBytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from FE Command. */

`define gcregPCComamdBytesFetchedRegAddrs                               16'h4C01
`define GCREG_PC_COMAMD_BYTES_FETCHED_MSB                                     15
`define GCREG_PC_COMAMD_BYTES_FETCHED_LSB                                      0
`define GCREG_PC_COMAMD_BYTES_FETCHED_BLK                                      0
`define GCREG_PC_COMAMD_BYTES_FETCHED_Count                                    1
`define GCREG_PC_COMAMD_BYTES_FETCHED_FieldMask                     32'hFFFFFFFF
`define GCREG_PC_COMAMD_BYTES_FETCHED_ReadMask                      32'hFFFFFFFF
`define GCREG_PC_COMAMD_BYTES_FETCHED_WriteMask                     32'hFFFFFFFF
`define GCREG_PC_COMAMD_BYTES_FETCHED_ResetValue                    32'h00000000

`define GCREG_PC_COMAMD_BYTES_FETCHED_COUNTER_MSB                             31
`define GCREG_PC_COMAMD_BYTES_FETCHED_COUNTER_LSB                              0
`define GCREG_PC_COMAMD_BYTES_FETCHED_COUNTER_SIZE                            32

/* Register gcregPCDrawCommands **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Draw Commands. */

`define gcregPCDrawCommandsRegAddrs                                     16'h4C02
`define GCREG_PC_DRAW_COMMANDS_MSB                                            15
`define GCREG_PC_DRAW_COMMANDS_LSB                                             0
`define GCREG_PC_DRAW_COMMANDS_BLK                                             0
`define GCREG_PC_DRAW_COMMANDS_Count                                           1
`define GCREG_PC_DRAW_COMMANDS_FieldMask                            32'hFFFFFFFF
`define GCREG_PC_DRAW_COMMANDS_ReadMask                             32'hFFFFFFFF
`define GCREG_PC_DRAW_COMMANDS_WriteMask                            32'hFFFFFFFF
`define GCREG_PC_DRAW_COMMANDS_ResetValue                           32'h00000000

`define GCREG_PC_DRAW_COMMANDS_COUNTER_MSB                                    31
`define GCREG_PC_DRAW_COMMANDS_COUNTER_LSB                                     0
`define GCREG_PC_DRAW_COMMANDS_COUNTER_SIZE                                   32

/* Register gcregPCIndexBytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from FE Index Cache. */

`define gcregPCIndexBytesFetchedRegAddrs                                16'h4C03
`define GCREG_PC_INDEX_BYTES_FETCHED_MSB                                      15
`define GCREG_PC_INDEX_BYTES_FETCHED_LSB                                       0
`define GCREG_PC_INDEX_BYTES_FETCHED_BLK                                       0
`define GCREG_PC_INDEX_BYTES_FETCHED_Count                                     1
`define GCREG_PC_INDEX_BYTES_FETCHED_FieldMask                      32'hFFFFFFFF
`define GCREG_PC_INDEX_BYTES_FETCHED_ReadMask                       32'hFFFFFFFF
`define GCREG_PC_INDEX_BYTES_FETCHED_WriteMask                      32'hFFFFFFFF
`define GCREG_PC_INDEX_BYTES_FETCHED_ResetValue                     32'h00000000

`define GCREG_PC_INDEX_BYTES_FETCHED_COUNTER_MSB                              31
`define GCREG_PC_INDEX_BYTES_FETCHED_COUNTER_LSB                               0
`define GCREG_PC_INDEX_BYTES_FETCHED_COUNTER_SIZE                             32

/* Register gcregPCIndexCacheHit **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of hits in FE Index Cache. */

`define gcregPCIndexCacheHitRegAddrs                                    16'h4C04
`define GCREG_PC_INDEX_CACHE_HIT_MSB                                          15
`define GCREG_PC_INDEX_CACHE_HIT_LSB                                           0
`define GCREG_PC_INDEX_CACHE_HIT_BLK                                           0
`define GCREG_PC_INDEX_CACHE_HIT_Count                                         1
`define GCREG_PC_INDEX_CACHE_HIT_FieldMask                          32'hFFFFFFFF
`define GCREG_PC_INDEX_CACHE_HIT_ReadMask                           32'hFFFFFFFF
`define GCREG_PC_INDEX_CACHE_HIT_WriteMask                          32'hFFFFFFFF
`define GCREG_PC_INDEX_CACHE_HIT_ResetValue                         32'h00000000

`define GCREG_PC_INDEX_CACHE_HIT_COUNTER_MSB                                  31
`define GCREG_PC_INDEX_CACHE_HIT_COUNTER_LSB                                   0
`define GCREG_PC_INDEX_CACHE_HIT_COUNTER_SIZE                                 32

/* Register gcregPCVertexCount **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of vertices send from FE. */

`define gcregPCVertexCountRegAddrs                                      16'h4C05
`define GCREG_PC_VERTEX_COUNT_MSB                                             15
`define GCREG_PC_VERTEX_COUNT_LSB                                              0
`define GCREG_PC_VERTEX_COUNT_BLK                                              0
`define GCREG_PC_VERTEX_COUNT_Count                                            1
`define GCREG_PC_VERTEX_COUNT_FieldMask                             32'hFFFFFFFF
`define GCREG_PC_VERTEX_COUNT_ReadMask                              32'hFFFFFFFF
`define GCREG_PC_VERTEX_COUNT_WriteMask                             32'hFFFFFFFF
`define GCREG_PC_VERTEX_COUNT_ResetValue                            32'h00000000

`define GCREG_PC_VERTEX_COUNT_COUNTER_MSB                                     31
`define GCREG_PC_VERTEX_COUNT_COUNTER_LSB                                      0
`define GCREG_PC_VERTEX_COUNT_COUNTER_SIZE                                    32

/* Register gcregPCVertexBytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from FE Vertex Cache. */

`define gcregPCVertexBytesFetchedRegAddrs                               16'h4C06
`define GCREG_PC_VERTEX_BYTES_FETCHED_MSB                                     15
`define GCREG_PC_VERTEX_BYTES_FETCHED_LSB                                      0
`define GCREG_PC_VERTEX_BYTES_FETCHED_BLK                                      0
`define GCREG_PC_VERTEX_BYTES_FETCHED_Count                                    1
`define GCREG_PC_VERTEX_BYTES_FETCHED_FieldMask                     32'hFFFFFFFF
`define GCREG_PC_VERTEX_BYTES_FETCHED_ReadMask                      32'hFFFFFFFF
`define GCREG_PC_VERTEX_BYTES_FETCHED_WriteMask                     32'hFFFFFFFF
`define GCREG_PC_VERTEX_BYTES_FETCHED_ResetValue                    32'h00000000

`define GCREG_PC_VERTEX_BYTES_FETCHED_COUNTER_MSB                             31
`define GCREG_PC_VERTEX_BYTES_FETCHED_COUNTER_LSB                              0
`define GCREG_PC_VERTEX_BYTES_FETCHED_COUNTER_SIZE                            32

/* Register gcregPCTotalVertex **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of input vertices to PA. */

`define gcregPCTotalVertexRegAddrs                                      16'h4C07
`define GCREG_PC_TOTAL_VERTEX_MSB                                             15
`define GCREG_PC_TOTAL_VERTEX_LSB                                              0
`define GCREG_PC_TOTAL_VERTEX_BLK                                              0
`define GCREG_PC_TOTAL_VERTEX_Count                                            1
`define GCREG_PC_TOTAL_VERTEX_FieldMask                             32'hFFFFFFFF
`define GCREG_PC_TOTAL_VERTEX_ReadMask                              32'hFFFFFFFF
`define GCREG_PC_TOTAL_VERTEX_WriteMask                             32'hFFFFFFFF
`define GCREG_PC_TOTAL_VERTEX_ResetValue                            32'h00000000

`define GCREG_PC_TOTAL_VERTEX_COUNTER_MSB                                     31
`define GCREG_PC_TOTAL_VERTEX_COUNTER_LSB                                      0
`define GCREG_PC_TOTAL_VERTEX_COUNTER_SIZE                                    32

/* Register gcregPCTotalPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of assembled primitives. */

`define gcregPCTotalPrimitiveRegAddrs                                   16'h4C08
`define GCREG_PC_TOTAL_PRIMITIVE_MSB                                          15
`define GCREG_PC_TOTAL_PRIMITIVE_LSB                                           0
`define GCREG_PC_TOTAL_PRIMITIVE_BLK                                           0
`define GCREG_PC_TOTAL_PRIMITIVE_Count                                         1
`define GCREG_PC_TOTAL_PRIMITIVE_FieldMask                          32'hFFFFFFFF
`define GCREG_PC_TOTAL_PRIMITIVE_ReadMask                           32'hFFFFFFFF
`define GCREG_PC_TOTAL_PRIMITIVE_WriteMask                          32'hFFFFFFFF
`define GCREG_PC_TOTAL_PRIMITIVE_ResetValue                         32'h00000000

`define GCREG_PC_TOTAL_PRIMITIVE_COUNTER_MSB                                  31
`define GCREG_PC_TOTAL_PRIMITIVE_COUNTER_LSB                                   0
`define GCREG_PC_TOTAL_PRIMITIVE_COUNTER_SIZE                                 32

/* Register gcregPCTrivialRejectPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of trivial rejected primitives. */

`define gcregPCTrivialRejectPrimitiveRegAddrs                           16'h4C09
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_MSB                                 15
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_LSB                                  0
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_BLK                                  0
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_Count                                1
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_FieldMask                 32'hFFFFFFFF
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_ReadMask                  32'hFFFFFFFF
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_WriteMask                 32'hFFFFFFFF
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_ResetValue                32'h00000000

`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_COUNTER_MSB                         31
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_COUNTER_LSB                          0
`define GCREG_PC_TRIVIAL_REJECT_PRIMITIVE_COUNTER_SIZE                        32

/* Register gcregPCCulledPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of culled primitives. */

`define gcregPCCulledPrimitiveRegAddrs                                  16'h4C0A
`define GCREG_PC_CULLED_PRIMITIVE_MSB                                         15
`define GCREG_PC_CULLED_PRIMITIVE_LSB                                          0
`define GCREG_PC_CULLED_PRIMITIVE_BLK                                          0
`define GCREG_PC_CULLED_PRIMITIVE_Count                                        1
`define GCREG_PC_CULLED_PRIMITIVE_FieldMask                         32'hFFFFFFFF
`define GCREG_PC_CULLED_PRIMITIVE_ReadMask                          32'hFFFFFFFF
`define GCREG_PC_CULLED_PRIMITIVE_WriteMask                         32'hFFFFFFFF
`define GCREG_PC_CULLED_PRIMITIVE_ResetValue                        32'h00000000

`define GCREG_PC_CULLED_PRIMITIVE_COUNTER_MSB                                 31
`define GCREG_PC_CULLED_PRIMITIVE_COUNTER_LSB                                  0
`define GCREG_PC_CULLED_PRIMITIVE_COUNTER_SIZE                                32

/* Register gcregPCDepthClippedPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of front-Z clipped primitives. */

`define gcregPCDepthClippedPrimitiveRegAddrs                            16'h4C0B
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_MSB                                  15
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_LSB                                   0
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_BLK                                   0
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_Count                                 1
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_FieldMask                  32'hFFFFFFFF
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_ReadMask                   32'hFFFFFFFF
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_WriteMask                  32'hFFFFFFFF
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_ResetValue                 32'h00000000

`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_COUNTER_MSB                          31
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_COUNTER_LSB                           0
`define GCREG_PC_DEPTH_CLIPPED_PRIMITIVE_COUNTER_SIZE                         32

/* Register gcregPCFrustumClippedPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of frustum clipped primitives. */

`define gcregPCFrustumClippedPrimitiveRegAddrs                          16'h4C0C
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_MSB                                15
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_LSB                                 0
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_BLK                                 0
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_Count                               1
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_FieldMask                32'hFFFFFFFF
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_ReadMask                 32'hFFFFFFFF
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_WriteMask                32'hFFFFFFFF
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_ResetValue               32'h00000000

`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_COUNTER_MSB                        31
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_COUNTER_LSB                         0
`define GCREG_PC_FRUSTUM_CLIPPED_PRIMITIVE_COUNTER_SIZE                       32

/* Register gcregPCOutputPrimitive **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of primitives sent to SE. */

`define gcregPCOutputPrimitiveRegAddrs                                  16'h4C0D
`define GCREG_PC_OUTPUT_PRIMITIVE_MSB                                         15
`define GCREG_PC_OUTPUT_PRIMITIVE_LSB                                          0
`define GCREG_PC_OUTPUT_PRIMITIVE_BLK                                          0
`define GCREG_PC_OUTPUT_PRIMITIVE_Count                                        1
`define GCREG_PC_OUTPUT_PRIMITIVE_FieldMask                         32'hFFFFFFFF
`define GCREG_PC_OUTPUT_PRIMITIVE_ReadMask                          32'hFFFFFFFF
`define GCREG_PC_OUTPUT_PRIMITIVE_WriteMask                         32'hFFFFFFFF
`define GCREG_PC_OUTPUT_PRIMITIVE_ResetValue                        32'h00000000

`define GCREG_PC_OUTPUT_PRIMITIVE_COUNTER_MSB                                 31
`define GCREG_PC_OUTPUT_PRIMITIVE_COUNTER_LSB                                  0
`define GCREG_PC_OUTPUT_PRIMITIVE_COUNTER_SIZE                                32

/* Register gcregPCCulledTriangles **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of culled triangles in SE. */

`define gcregPCCulledTrianglesRegAddrs                                  16'h4C0E
`define GCREG_PC_CULLED_TRIANGLES_MSB                                         15
`define GCREG_PC_CULLED_TRIANGLES_LSB                                          0
`define GCREG_PC_CULLED_TRIANGLES_BLK                                          0
`define GCREG_PC_CULLED_TRIANGLES_Count                                        1
`define GCREG_PC_CULLED_TRIANGLES_FieldMask                         32'hFFFFFFFF
`define GCREG_PC_CULLED_TRIANGLES_ReadMask                          32'hFFFFFFFF
`define GCREG_PC_CULLED_TRIANGLES_WriteMask                         32'hFFFFFFFF
`define GCREG_PC_CULLED_TRIANGLES_ResetValue                        32'h00000000

`define GCREG_PC_CULLED_TRIANGLES_COUNTER_MSB                                 31
`define GCREG_PC_CULLED_TRIANGLES_COUNTER_LSB                                  0
`define GCREG_PC_CULLED_TRIANGLES_COUNTER_SIZE                                32

/* Register gcregPCCulledLines **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of culled lines in SE. */

`define gcregPCCulledLinesRegAddrs                                      16'h4C0F
`define GCREG_PC_CULLED_LINES_MSB                                             15
`define GCREG_PC_CULLED_LINES_LSB                                              0
`define GCREG_PC_CULLED_LINES_BLK                                              0
`define GCREG_PC_CULLED_LINES_Count                                            1
`define GCREG_PC_CULLED_LINES_FieldMask                             32'hFFFFFFFF
`define GCREG_PC_CULLED_LINES_ReadMask                              32'hFFFFFFFF
`define GCREG_PC_CULLED_LINES_WriteMask                             32'hFFFFFFFF
`define GCREG_PC_CULLED_LINES_ResetValue                            32'h00000000

`define GCREG_PC_CULLED_LINES_COUNTER_MSB                                     31
`define GCREG_PC_CULLED_LINES_COUNTER_LSB                                      0
`define GCREG_PC_CULLED_LINES_COUNTER_SIZE                                    32

/* Register gcregPCCulledRectangles **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of culled rectangles in SE. */

`define gcregPCCulledRectanglesRegAddrs                                 16'h4C10
`define GCREG_PC_CULLED_RECTANGLES_MSB                                        15
`define GCREG_PC_CULLED_RECTANGLES_LSB                                         0
`define GCREG_PC_CULLED_RECTANGLES_BLK                                         0
`define GCREG_PC_CULLED_RECTANGLES_Count                                       1
`define GCREG_PC_CULLED_RECTANGLES_FieldMask                        32'hFFFFFFFF
`define GCREG_PC_CULLED_RECTANGLES_ReadMask                         32'hFFFFFFFF
`define GCREG_PC_CULLED_RECTANGLES_WriteMask                        32'hFFFFFFFF
`define GCREG_PC_CULLED_RECTANGLES_ResetValue                       32'h00000000

`define GCREG_PC_CULLED_RECTANGLES_COUNTER_MSB                                31
`define GCREG_PC_CULLED_RECTANGLES_COUNTER_LSB                                 0
`define GCREG_PC_CULLED_RECTANGLES_COUNTER_SIZE                               32

/* Register gcregPCClippedTriangles **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of clipped triangles in SE. */

`define gcregPCClippedTrianglesRegAddrs                                 16'h4C11
`define GCREG_PC_CLIPPED_TRIANGLES_MSB                                        15
`define GCREG_PC_CLIPPED_TRIANGLES_LSB                                         0
`define GCREG_PC_CLIPPED_TRIANGLES_BLK                                         0
`define GCREG_PC_CLIPPED_TRIANGLES_Count                                       1
`define GCREG_PC_CLIPPED_TRIANGLES_FieldMask                        32'hFFFFFFFF
`define GCREG_PC_CLIPPED_TRIANGLES_ReadMask                         32'hFFFFFFFF
`define GCREG_PC_CLIPPED_TRIANGLES_WriteMask                        32'hFFFFFFFF
`define GCREG_PC_CLIPPED_TRIANGLES_ResetValue                       32'h00000000

`define GCREG_PC_CLIPPED_TRIANGLES_COUNTER_MSB                                31
`define GCREG_PC_CLIPPED_TRIANGLES_COUNTER_LSB                                 0
`define GCREG_PC_CLIPPED_TRIANGLES_COUNTER_SIZE                               32

/* Register gcregPCClippedLines **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of clipped lines in SE. */

`define gcregPCClippedLinesRegAddrs                                     16'h4C12
`define GCREG_PC_CLIPPED_LINES_MSB                                            15
`define GCREG_PC_CLIPPED_LINES_LSB                                             0
`define GCREG_PC_CLIPPED_LINES_BLK                                             0
`define GCREG_PC_CLIPPED_LINES_Count                                           1
`define GCREG_PC_CLIPPED_LINES_FieldMask                            32'hFFFFFFFF
`define GCREG_PC_CLIPPED_LINES_ReadMask                             32'hFFFFFFFF
`define GCREG_PC_CLIPPED_LINES_WriteMask                            32'hFFFFFFFF
`define GCREG_PC_CLIPPED_LINES_ResetValue                           32'h00000000

`define GCREG_PC_CLIPPED_LINES_COUNTER_MSB                                    31
`define GCREG_PC_CLIPPED_LINES_COUNTER_LSB                                     0
`define GCREG_PC_CLIPPED_LINES_COUNTER_SIZE                                   32

/* Register gcregPCClippedRectangles **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of clipped rectangles in SE. */

`define gcregPCClippedRectanglesRegAddrs                                16'h4C13
`define GCREG_PC_CLIPPED_RECTANGLES_MSB                                       15
`define GCREG_PC_CLIPPED_RECTANGLES_LSB                                        0
`define GCREG_PC_CLIPPED_RECTANGLES_BLK                                        0
`define GCREG_PC_CLIPPED_RECTANGLES_Count                                      1
`define GCREG_PC_CLIPPED_RECTANGLES_FieldMask                       32'hFFFFFFFF
`define GCREG_PC_CLIPPED_RECTANGLES_ReadMask                        32'hFFFFFFFF
`define GCREG_PC_CLIPPED_RECTANGLES_WriteMask                       32'hFFFFFFFF
`define GCREG_PC_CLIPPED_RECTANGLES_ResetValue                      32'h00000000

`define GCREG_PC_CLIPPED_RECTANGLES_COUNTER_MSB                               31
`define GCREG_PC_CLIPPED_RECTANGLES_COUNTER_LSB                                0
`define GCREG_PC_CLIPPED_RECTANGLES_COUNTER_SIZE                              32

/* Register gcregPCRasterizedPrimitives **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of primitives coming into RA. */

`define gcregPCRasterizedPrimitivesRegAddrs                             16'h4C14
`define GCREG_PC_RASTERIZED_PRIMITIVES_MSB                                    15
`define GCREG_PC_RASTERIZED_PRIMITIVES_LSB                                     0
`define GCREG_PC_RASTERIZED_PRIMITIVES_BLK                                     0
`define GCREG_PC_RASTERIZED_PRIMITIVES_Count                                   1
`define GCREG_PC_RASTERIZED_PRIMITIVES_FieldMask                    32'hFFFFFFFF
`define GCREG_PC_RASTERIZED_PRIMITIVES_ReadMask                     32'hFFFFFFFF
`define GCREG_PC_RASTERIZED_PRIMITIVES_WriteMask                    32'hFFFFFFFF
`define GCREG_PC_RASTERIZED_PRIMITIVES_ResetValue                   32'h00000000

`define GCREG_PC_RASTERIZED_PRIMITIVES_COUNTER_MSB                            31
`define GCREG_PC_RASTERIZED_PRIMITIVES_COUNTER_LSB                             0
`define GCREG_PC_RASTERIZED_PRIMITIVES_COUNTER_SIZE                           32

/* Register gcregPCTotalQuads **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of quads rasterized. */

`define gcregPCTotalQuadsRegAddrs                                       16'h4C15
`define GCREG_PC_TOTAL_QUADS_MSB                                              15
`define GCREG_PC_TOTAL_QUADS_LSB                                               0
`define GCREG_PC_TOTAL_QUADS_BLK                                               0
`define GCREG_PC_TOTAL_QUADS_Count                                             1
`define GCREG_PC_TOTAL_QUADS_FieldMask                              32'hFFFFFFFF
`define GCREG_PC_TOTAL_QUADS_ReadMask                               32'hFFFFFFFF
`define GCREG_PC_TOTAL_QUADS_WriteMask                              32'hFFFFFFFF
`define GCREG_PC_TOTAL_QUADS_ResetValue                             32'h00000000

`define GCREG_PC_TOTAL_QUADS_COUNTER_MSB                                      31
`define GCREG_PC_TOTAL_QUADS_COUNTER_LSB                                       0
`define GCREG_PC_TOTAL_QUADS_COUNTER_SIZE                                     32

/* Register gcregPCCulledHZ **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of quads culled by HZ. */

`define gcregPCCulledHZRegAddrs                                         16'h4C16
`define GCREG_PC_CULLED_HZ_MSB                                                15
`define GCREG_PC_CULLED_HZ_LSB                                                 0
`define GCREG_PC_CULLED_HZ_BLK                                                 0
`define GCREG_PC_CULLED_HZ_Count                                               1
`define GCREG_PC_CULLED_HZ_FieldMask                                32'hFFFFFFFF
`define GCREG_PC_CULLED_HZ_ReadMask                                 32'hFFFFFFFF
`define GCREG_PC_CULLED_HZ_WriteMask                                32'hFFFFFFFF
`define GCREG_PC_CULLED_HZ_ResetValue                               32'h00000000

`define GCREG_PC_CULLED_HZ_COUNTER_MSB                                        31
`define GCREG_PC_CULLED_HZ_COUNTER_LSB                                         0
`define GCREG_PC_CULLED_HZ_COUNTER_SIZE                                       32

/* Register gcregPCCulledEEZ **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of quads culled by EEZ. */

`define gcregPCCulledEEZRegAddrs                                        16'h4C17
`define GCREG_PC_CULLED_EEZ_MSB                                               15
`define GCREG_PC_CULLED_EEZ_LSB                                                0
`define GCREG_PC_CULLED_EEZ_BLK                                                0
`define GCREG_PC_CULLED_EEZ_Count                                              1
`define GCREG_PC_CULLED_EEZ_FieldMask                               32'hFFFFFFFF
`define GCREG_PC_CULLED_EEZ_ReadMask                                32'hFFFFFFFF
`define GCREG_PC_CULLED_EEZ_WriteMask                               32'hFFFFFFFF
`define GCREG_PC_CULLED_EEZ_ResetValue                              32'h00000000

`define GCREG_PC_CULLED_EEZ_COUNTER_MSB                                       31
`define GCREG_PC_CULLED_EEZ_COUNTER_LSB                                        0
`define GCREG_PC_CULLED_EEZ_COUNTER_SIZE                                      32

/* Register gcregPCValidQuads **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of valid quads sent to PS. */

`define gcregPCValidQuadsRegAddrs                                       16'h4C18
`define GCREG_PC_VALID_QUADS_MSB                                              15
`define GCREG_PC_VALID_QUADS_LSB                                               0
`define GCREG_PC_VALID_QUADS_BLK                                               0
`define GCREG_PC_VALID_QUADS_Count                                             1
`define GCREG_PC_VALID_QUADS_FieldMask                              32'hFFFFFFFF
`define GCREG_PC_VALID_QUADS_ReadMask                               32'hFFFFFFFF
`define GCREG_PC_VALID_QUADS_WriteMask                              32'hFFFFFFFF
`define GCREG_PC_VALID_QUADS_ResetValue                             32'h00000000

`define GCREG_PC_VALID_QUADS_COUNTER_MSB                                      31
`define GCREG_PC_VALID_QUADS_COUNTER_LSB                                       0
`define GCREG_PC_VALID_QUADS_COUNTER_SIZE                                     32

/* Register gcregPCValidPixels **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of valid pixels sent to PS. */

`define gcregPCValidPixelsRegAddrs                                      16'h4C19
`define GCREG_PC_VALID_PIXELS_MSB                                             15
`define GCREG_PC_VALID_PIXELS_LSB                                              0
`define GCREG_PC_VALID_PIXELS_BLK                                              0
`define GCREG_PC_VALID_PIXELS_Count                                            1
`define GCREG_PC_VALID_PIXELS_FieldMask                             32'hFFFFFFFF
`define GCREG_PC_VALID_PIXELS_ReadMask                              32'hFFFFFFFF
`define GCREG_PC_VALID_PIXELS_WriteMask                             32'hFFFFFFFF
`define GCREG_PC_VALID_PIXELS_ResetValue                            32'h00000000

`define GCREG_PC_VALID_PIXELS_COUNTER_MSB                                     31
`define GCREG_PC_VALID_PIXELS_COUNTER_LSB                                      0
`define GCREG_PC_VALID_PIXELS_COUNTER_SIZE                                    32

/* Register gcregPCHZCacheRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of HZ cache requests. */

`define gcregPCHZCacheRequestsRegAddrs                                  16'h4C1A
`define GCREG_PCHZ_CACHE_REQUESTS_MSB                                         15
`define GCREG_PCHZ_CACHE_REQUESTS_LSB                                          0
`define GCREG_PCHZ_CACHE_REQUESTS_BLK                                          0
`define GCREG_PCHZ_CACHE_REQUESTS_Count                                        1
`define GCREG_PCHZ_CACHE_REQUESTS_FieldMask                         32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_REQUESTS_ReadMask                          32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_REQUESTS_WriteMask                         32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_REQUESTS_ResetValue                        32'h00000000

`define GCREG_PCHZ_CACHE_REQUESTS_COUNTER_MSB                                 31
`define GCREG_PCHZ_CACHE_REQUESTS_COUNTER_LSB                                  0
`define GCREG_PCHZ_CACHE_REQUESTS_COUNTER_SIZE                                32

/* Register gcregPCHZCacheMisses **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of HZ cache misses. */

`define gcregPCHZCacheMissesRegAddrs                                    16'h4C1B
`define GCREG_PCHZ_CACHE_MISSES_MSB                                           15
`define GCREG_PCHZ_CACHE_MISSES_LSB                                            0
`define GCREG_PCHZ_CACHE_MISSES_BLK                                            0
`define GCREG_PCHZ_CACHE_MISSES_Count                                          1
`define GCREG_PCHZ_CACHE_MISSES_FieldMask                           32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_MISSES_ReadMask                            32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_MISSES_WriteMask                           32'hFFFFFFFF
`define GCREG_PCHZ_CACHE_MISSES_ResetValue                          32'h00000000

`define GCREG_PCHZ_CACHE_MISSES_COUNTER_MSB                                   31
`define GCREG_PCHZ_CACHE_MISSES_COUNTER_LSB                                    0
`define GCREG_PCHZ_CACHE_MISSES_COUNTER_SIZE                                  32

/* Register gcregPCHZBytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from HZ cache. */

`define gcregPCHZBytesFetchedRegAddrs                                   16'h4C1C
`define GCREG_PCHZ_BYTES_FETCHED_MSB                                          15
`define GCREG_PCHZ_BYTES_FETCHED_LSB                                           0
`define GCREG_PCHZ_BYTES_FETCHED_BLK                                           0
`define GCREG_PCHZ_BYTES_FETCHED_Count                                         1
`define GCREG_PCHZ_BYTES_FETCHED_FieldMask                          32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_FETCHED_ReadMask                           32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_FETCHED_WriteMask                          32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_FETCHED_ResetValue                         32'h00000000

`define GCREG_PCHZ_BYTES_FETCHED_COUNTER_MSB                                  31
`define GCREG_PCHZ_BYTES_FETCHED_COUNTER_LSB                                   0
`define GCREG_PCHZ_BYTES_FETCHED_COUNTER_SIZE                                 32

/* Register gcregPCEZCacheRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of EZ cache requests. */

`define gcregPCEZCacheRequestsRegAddrs                                  16'h4C1D
`define GCREG_PCEZ_CACHE_REQUESTS_MSB                                         15
`define GCREG_PCEZ_CACHE_REQUESTS_LSB                                          0
`define GCREG_PCEZ_CACHE_REQUESTS_BLK                                          0
`define GCREG_PCEZ_CACHE_REQUESTS_Count                                        1
`define GCREG_PCEZ_CACHE_REQUESTS_FieldMask                         32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_REQUESTS_ReadMask                          32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_REQUESTS_WriteMask                         32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_REQUESTS_ResetValue                        32'h00000000

`define GCREG_PCEZ_CACHE_REQUESTS_COUNTER_MSB                                 31
`define GCREG_PCEZ_CACHE_REQUESTS_COUNTER_LSB                                  0
`define GCREG_PCEZ_CACHE_REQUESTS_COUNTER_SIZE                                32

/* Register gcregPCEZCacheMisses **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of EZ cache misses. */

`define gcregPCEZCacheMissesRegAddrs                                    16'h4C1E
`define GCREG_PCEZ_CACHE_MISSES_MSB                                           15
`define GCREG_PCEZ_CACHE_MISSES_LSB                                            0
`define GCREG_PCEZ_CACHE_MISSES_BLK                                            0
`define GCREG_PCEZ_CACHE_MISSES_Count                                          1
`define GCREG_PCEZ_CACHE_MISSES_FieldMask                           32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_MISSES_ReadMask                            32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_MISSES_WriteMask                           32'hFFFFFFFF
`define GCREG_PCEZ_CACHE_MISSES_ResetValue                          32'h00000000

`define GCREG_PCEZ_CACHE_MISSES_COUNTER_MSB                                   31
`define GCREG_PCEZ_CACHE_MISSES_COUNTER_LSB                                    0
`define GCREG_PCEZ_CACHE_MISSES_COUNTER_SIZE                                  32

/* Register gcregPCEZBytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from EZ cache. */

`define gcregPCEZBytesFetchedRegAddrs                                   16'h4C1F
`define GCREG_PCEZ_BYTES_FETCHED_MSB                                          15
`define GCREG_PCEZ_BYTES_FETCHED_LSB                                           0
`define GCREG_PCEZ_BYTES_FETCHED_BLK                                           0
`define GCREG_PCEZ_BYTES_FETCHED_Count                                         1
`define GCREG_PCEZ_BYTES_FETCHED_FieldMask                          32'hFFFFFFFF
`define GCREG_PCEZ_BYTES_FETCHED_ReadMask                           32'hFFFFFFFF
`define GCREG_PCEZ_BYTES_FETCHED_WriteMask                          32'hFFFFFFFF
`define GCREG_PCEZ_BYTES_FETCHED_ResetValue                         32'h00000000

`define GCREG_PCEZ_BYTES_FETCHED_COUNTER_MSB                                  31
`define GCREG_PCEZ_BYTES_FETCHED_COUNTER_LSB                                   0
`define GCREG_PCEZ_BYTES_FETCHED_COUNTER_SIZE                                 32

/* Register gcregPCColorKilledPixels (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels killed by color pipe. One for each pixel pipe. */

`define gcregPCColorKilledPixelsRegAddrs                                13'h0984
`define GCREG_PC_COLOR_KILLED_PIXELS_MSB                                      15
`define GCREG_PC_COLOR_KILLED_PIXELS_LSB                                       3
`define GCREG_PC_COLOR_KILLED_PIXELS_BLK                                       3
`define GCREG_PC_COLOR_KILLED_PIXELS_Count                                     8
`define GCREG_PC_COLOR_KILLED_PIXELS_FieldMask                      32'hFFFFFFFF
`define GCREG_PC_COLOR_KILLED_PIXELS_ReadMask                       32'hFFFFFFFF
`define GCREG_PC_COLOR_KILLED_PIXELS_WriteMask                      32'hFFFFFFFF
`define GCREG_PC_COLOR_KILLED_PIXELS_ResetValue                     32'h00000000

`define GCREG_PC_COLOR_KILLED_PIXELS_COUNTER_MSB                              31
`define GCREG_PC_COLOR_KILLED_PIXELS_COUNTER_LSB                               0
`define GCREG_PC_COLOR_KILLED_PIXELS_COUNTER_SIZE                             32

/* Register gcregPCDepthKilledPixels (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels killed by depth pipe. One for each pixel pipe. */

`define gcregPCDepthKilledPixelsRegAddrs                                13'h0985
`define GCREG_PC_DEPTH_KILLED_PIXELS_MSB                                      15
`define GCREG_PC_DEPTH_KILLED_PIXELS_LSB                                       3
`define GCREG_PC_DEPTH_KILLED_PIXELS_BLK                                       3
`define GCREG_PC_DEPTH_KILLED_PIXELS_Count                                     8
`define GCREG_PC_DEPTH_KILLED_PIXELS_FieldMask                      32'hFFFFFFFF
`define GCREG_PC_DEPTH_KILLED_PIXELS_ReadMask                       32'hFFFFFFFF
`define GCREG_PC_DEPTH_KILLED_PIXELS_WriteMask                      32'hFFFFFFFF
`define GCREG_PC_DEPTH_KILLED_PIXELS_ResetValue                     32'h00000000

`define GCREG_PC_DEPTH_KILLED_PIXELS_COUNTER_MSB                              31
`define GCREG_PC_DEPTH_KILLED_PIXELS_COUNTER_LSB                               0
`define GCREG_PC_DEPTH_KILLED_PIXELS_COUNTER_SIZE                             32

/* Register gcregPCStencilKilledPixels (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels killed by stencil pipe. One for each pixel pipe. */

`define gcregPCStencilKilledPixelsRegAddrs                              13'h0986
`define GCREG_PC_STENCIL_KILLED_PIXELS_MSB                                    15
`define GCREG_PC_STENCIL_KILLED_PIXELS_LSB                                     3
`define GCREG_PC_STENCIL_KILLED_PIXELS_BLK                                     3
`define GCREG_PC_STENCIL_KILLED_PIXELS_Count                                   8
`define GCREG_PC_STENCIL_KILLED_PIXELS_FieldMask                    32'hFFFFFFFF
`define GCREG_PC_STENCIL_KILLED_PIXELS_ReadMask                     32'hFFFFFFFF
`define GCREG_PC_STENCIL_KILLED_PIXELS_WriteMask                    32'hFFFFFFFF
`define GCREG_PC_STENCIL_KILLED_PIXELS_ResetValue                   32'h00000000

`define GCREG_PC_STENCIL_KILLED_PIXELS_COUNTER_MSB                            31
`define GCREG_PC_STENCIL_KILLED_PIXELS_COUNTER_LSB                             0
`define GCREG_PC_STENCIL_KILLED_PIXELS_COUNTER_SIZE                           32

/* Register gcregPCColorRenderedPixels (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels rendered by color pipe. One for each pixel pipe. */

`define gcregPCColorRenderedPixelsRegAddrs                              13'h0987
`define GCREG_PC_COLOR_RENDERED_PIXELS_MSB                                    15
`define GCREG_PC_COLOR_RENDERED_PIXELS_LSB                                     3
`define GCREG_PC_COLOR_RENDERED_PIXELS_BLK                                     3
`define GCREG_PC_COLOR_RENDERED_PIXELS_Count                                   8
`define GCREG_PC_COLOR_RENDERED_PIXELS_FieldMask                    32'hFFFFFFFF
`define GCREG_PC_COLOR_RENDERED_PIXELS_ReadMask                     32'hFFFFFFFF
`define GCREG_PC_COLOR_RENDERED_PIXELS_WriteMask                    32'hFFFFFFFF
`define GCREG_PC_COLOR_RENDERED_PIXELS_ResetValue                   32'h00000000

`define GCREG_PC_COLOR_RENDERED_PIXELS_COUNTER_MSB                            31
`define GCREG_PC_COLOR_RENDERED_PIXELS_COUNTER_LSB                             0
`define GCREG_PC_COLOR_RENDERED_PIXELS_COUNTER_SIZE                           32

/* Register gcregPCDepthRenderedPixels (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels rendered by depth pipe. One for each pixel pipe. */

`define gcregPCDepthRenderedPixelsRegAddrs                              13'h0988
`define GCREG_PC_DEPTH_RENDERED_PIXELS_MSB                                    15
`define GCREG_PC_DEPTH_RENDERED_PIXELS_LSB                                     3
`define GCREG_PC_DEPTH_RENDERED_PIXELS_BLK                                     3
`define GCREG_PC_DEPTH_RENDERED_PIXELS_Count                                   8
`define GCREG_PC_DEPTH_RENDERED_PIXELS_FieldMask                    32'hFFFFFFFF
`define GCREG_PC_DEPTH_RENDERED_PIXELS_ReadMask                     32'hFFFFFFFF
`define GCREG_PC_DEPTH_RENDERED_PIXELS_WriteMask                    32'hFFFFFFFF
`define GCREG_PC_DEPTH_RENDERED_PIXELS_ResetValue                   32'h00000000

`define GCREG_PC_DEPTH_RENDERED_PIXELS_COUNTER_MSB                            31
`define GCREG_PC_DEPTH_RENDERED_PIXELS_COUNTER_LSB                             0
`define GCREG_PC_DEPTH_RENDERED_PIXELS_COUNTER_SIZE                           32

/* Register gcregPCCCacheRequests (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Color Cache requests. One for each pixel pipe. */

`define gcregPCCCacheRequestsRegAddrs                                   13'h0989
`define GCREG_PCC_CACHE_REQUESTS_MSB                                          15
`define GCREG_PCC_CACHE_REQUESTS_LSB                                           3
`define GCREG_PCC_CACHE_REQUESTS_BLK                                           3
`define GCREG_PCC_CACHE_REQUESTS_Count                                         8
`define GCREG_PCC_CACHE_REQUESTS_FieldMask                          32'hFFFFFFFF
`define GCREG_PCC_CACHE_REQUESTS_ReadMask                           32'hFFFFFFFF
`define GCREG_PCC_CACHE_REQUESTS_WriteMask                          32'hFFFFFFFF
`define GCREG_PCC_CACHE_REQUESTS_ResetValue                         32'h00000000

`define GCREG_PCC_CACHE_REQUESTS_COUNTER_MSB                                  31
`define GCREG_PCC_CACHE_REQUESTS_COUNTER_LSB                                   0
`define GCREG_PCC_CACHE_REQUESTS_COUNTER_SIZE                                 32

/* Register gcregPCCCacheMisses (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Color Cache misses. One for each pixel pipe. */

`define gcregPCCCacheMissesRegAddrs                                     13'h098A
`define GCREG_PCC_CACHE_MISSES_MSB                                            15
`define GCREG_PCC_CACHE_MISSES_LSB                                             3
`define GCREG_PCC_CACHE_MISSES_BLK                                             3
`define GCREG_PCC_CACHE_MISSES_Count                                           8
`define GCREG_PCC_CACHE_MISSES_FieldMask                            32'hFFFFFFFF
`define GCREG_PCC_CACHE_MISSES_ReadMask                             32'hFFFFFFFF
`define GCREG_PCC_CACHE_MISSES_WriteMask                            32'hFFFFFFFF
`define GCREG_PCC_CACHE_MISSES_ResetValue                           32'h00000000

`define GCREG_PCC_CACHE_MISSES_COUNTER_MSB                                    31
`define GCREG_PCC_CACHE_MISSES_COUNTER_LSB                                     0
`define GCREG_PCC_CACHE_MISSES_COUNTER_SIZE                                   32

/* Register gcregPCCCacheBytesFetched (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from Color Cache. One for each pixel pipe. */

`define gcregPCCCacheBytesFetchedRegAddrs                               13'h098B
`define GCREG_PCC_CACHE_BYTES_FETCHED_MSB                                     15
`define GCREG_PCC_CACHE_BYTES_FETCHED_LSB                                      3
`define GCREG_PCC_CACHE_BYTES_FETCHED_BLK                                      3
`define GCREG_PCC_CACHE_BYTES_FETCHED_Count                                    8
`define GCREG_PCC_CACHE_BYTES_FETCHED_FieldMask                     32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_FETCHED_ReadMask                      32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_FETCHED_WriteMask                     32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_FETCHED_ResetValue                    32'h00000000

`define GCREG_PCC_CACHE_BYTES_FETCHED_COUNTER_MSB                             31
`define GCREG_PCC_CACHE_BYTES_FETCHED_COUNTER_LSB                              0
`define GCREG_PCC_CACHE_BYTES_FETCHED_COUNTER_SIZE                            32

/* Register gcregPCCCacheBytesWritten (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte writes from Color Cache. One for each pixel pipe. */

`define gcregPCCCacheBytesWrittenRegAddrs                               13'h098C
`define GCREG_PCC_CACHE_BYTES_WRITTEN_MSB                                     15
`define GCREG_PCC_CACHE_BYTES_WRITTEN_LSB                                      3
`define GCREG_PCC_CACHE_BYTES_WRITTEN_BLK                                      3
`define GCREG_PCC_CACHE_BYTES_WRITTEN_Count                                    8
`define GCREG_PCC_CACHE_BYTES_WRITTEN_FieldMask                     32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_WRITTEN_ReadMask                      32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_WRITTEN_WriteMask                     32'hFFFFFFFF
`define GCREG_PCC_CACHE_BYTES_WRITTEN_ResetValue                    32'h00000000

`define GCREG_PCC_CACHE_BYTES_WRITTEN_COUNTER_MSB                             31
`define GCREG_PCC_CACHE_BYTES_WRITTEN_COUNTER_LSB                              0
`define GCREG_PCC_CACHE_BYTES_WRITTEN_COUNTER_SIZE                            32

/* Register gcregPCZCacheRequests (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Depth Cache requests. One for each pixel pipe. */

`define gcregPCZCacheRequestsRegAddrs                                   13'h098D
`define GCREG_PCZ_CACHE_REQUESTS_MSB                                          15
`define GCREG_PCZ_CACHE_REQUESTS_LSB                                           3
`define GCREG_PCZ_CACHE_REQUESTS_BLK                                           3
`define GCREG_PCZ_CACHE_REQUESTS_Count                                         8
`define GCREG_PCZ_CACHE_REQUESTS_FieldMask                          32'hFFFFFFFF
`define GCREG_PCZ_CACHE_REQUESTS_ReadMask                           32'hFFFFFFFF
`define GCREG_PCZ_CACHE_REQUESTS_WriteMask                          32'hFFFFFFFF
`define GCREG_PCZ_CACHE_REQUESTS_ResetValue                         32'h00000000

`define GCREG_PCZ_CACHE_REQUESTS_COUNTER_MSB                                  31
`define GCREG_PCZ_CACHE_REQUESTS_COUNTER_LSB                                   0
`define GCREG_PCZ_CACHE_REQUESTS_COUNTER_SIZE                                 32

/* Register gcregPCZCacheMisses (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Depth Cache misses. One for each pixel pipe. */

`define gcregPCZCacheMissesRegAddrs                                     13'h098E
`define GCREG_PCZ_CACHE_MISSES_MSB                                            15
`define GCREG_PCZ_CACHE_MISSES_LSB                                             3
`define GCREG_PCZ_CACHE_MISSES_BLK                                             3
`define GCREG_PCZ_CACHE_MISSES_Count                                           8
`define GCREG_PCZ_CACHE_MISSES_FieldMask                            32'hFFFFFFFF
`define GCREG_PCZ_CACHE_MISSES_ReadMask                             32'hFFFFFFFF
`define GCREG_PCZ_CACHE_MISSES_WriteMask                            32'hFFFFFFFF
`define GCREG_PCZ_CACHE_MISSES_ResetValue                           32'h00000000

`define GCREG_PCZ_CACHE_MISSES_COUNTER_MSB                                    31
`define GCREG_PCZ_CACHE_MISSES_COUNTER_LSB                                     0
`define GCREG_PCZ_CACHE_MISSES_COUNTER_SIZE                                   32

/* Register gcregPCZCacheBytesFetched (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from Depth Cache. One for each pixel pipe. */

`define gcregPCZCacheBytesFetchedRegAddrs                               13'h098F
`define GCREG_PCZ_CACHE_BYTES_FETCHED_MSB                                     15
`define GCREG_PCZ_CACHE_BYTES_FETCHED_LSB                                      3
`define GCREG_PCZ_CACHE_BYTES_FETCHED_BLK                                      3
`define GCREG_PCZ_CACHE_BYTES_FETCHED_Count                                    8
`define GCREG_PCZ_CACHE_BYTES_FETCHED_FieldMask                     32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_FETCHED_ReadMask                      32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_FETCHED_WriteMask                     32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_FETCHED_ResetValue                    32'h00000000

`define GCREG_PCZ_CACHE_BYTES_FETCHED_COUNTER_MSB                             31
`define GCREG_PCZ_CACHE_BYTES_FETCHED_COUNTER_LSB                              0
`define GCREG_PCZ_CACHE_BYTES_FETCHED_COUNTER_SIZE                            32

/* Register gcregPCZCacheBytesWritten (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte writes from Depth Cache. One for each pixel pipe. */

`define gcregPCZCacheBytesWrittenRegAddrs                               13'h0990
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_MSB                                     15
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_LSB                                      3
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_BLK                                      3
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_Count                                    8
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_FieldMask                     32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_ReadMask                      32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_WriteMask                     32'hFFFFFFFF
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_ResetValue                    32'h00000000

`define GCREG_PCZ_CACHE_BYTES_WRITTEN_COUNTER_MSB                             31
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_COUNTER_LSB                              0
`define GCREG_PCZ_CACHE_BYTES_WRITTEN_COUNTER_SIZE                            32

/* Register gcregPCHZBytesWritten (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte writes from HZ buffer. One for each pixel pipe. */

`define gcregPCHZBytesWrittenRegAddrs                                   13'h0991
`define GCREG_PCHZ_BYTES_WRITTEN_MSB                                          15
`define GCREG_PCHZ_BYTES_WRITTEN_LSB                                           3
`define GCREG_PCHZ_BYTES_WRITTEN_BLK                                           3
`define GCREG_PCHZ_BYTES_WRITTEN_Count                                         8
`define GCREG_PCHZ_BYTES_WRITTEN_FieldMask                          32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_WRITTEN_ReadMask                           32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_WRITTEN_WriteMask                          32'hFFFFFFFF
`define GCREG_PCHZ_BYTES_WRITTEN_ResetValue                         32'h00000000

`define GCREG_PCHZ_BYTES_WRITTEN_COUNTER_MSB                                  31
`define GCREG_PCHZ_BYTES_WRITTEN_COUNTER_LSB                                   0
`define GCREG_PCHZ_BYTES_WRITTEN_COUNTER_SIZE                                 32

/* Register gcregPCTexelRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of texel requests. */

`define gcregPCTexelRequestsRegAddrs                                    16'h4C90
`define GCREG_PC_TEXEL_REQUESTS_MSB                                           15
`define GCREG_PC_TEXEL_REQUESTS_LSB                                            0
`define GCREG_PC_TEXEL_REQUESTS_BLK                                            0
`define GCREG_PC_TEXEL_REQUESTS_Count                                          1
`define GCREG_PC_TEXEL_REQUESTS_FieldMask                           32'hFFFFFFFF
`define GCREG_PC_TEXEL_REQUESTS_ReadMask                            32'hFFFFFFFF
`define GCREG_PC_TEXEL_REQUESTS_WriteMask                           32'hFFFFFFFF
`define GCREG_PC_TEXEL_REQUESTS_ResetValue                          32'h00000000

`define GCREG_PC_TEXEL_REQUESTS_COUNTER_MSB                                   31
`define GCREG_PC_TEXEL_REQUESTS_COUNTER_LSB                                    0
`define GCREG_PC_TEXEL_REQUESTS_COUNTER_SIZE                                  32

/* Register gcregPCBilinearRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of bi-linear texel requests. */

`define gcregPCBilinearRequestsRegAddrs                                 16'h4C91
`define GCREG_PC_BILINEAR_REQUESTS_MSB                                        15
`define GCREG_PC_BILINEAR_REQUESTS_LSB                                         0
`define GCREG_PC_BILINEAR_REQUESTS_BLK                                         0
`define GCREG_PC_BILINEAR_REQUESTS_Count                                       1
`define GCREG_PC_BILINEAR_REQUESTS_FieldMask                        32'hFFFFFFFF
`define GCREG_PC_BILINEAR_REQUESTS_ReadMask                         32'hFFFFFFFF
`define GCREG_PC_BILINEAR_REQUESTS_WriteMask                        32'hFFFFFFFF
`define GCREG_PC_BILINEAR_REQUESTS_ResetValue                       32'h00000000

`define GCREG_PC_BILINEAR_REQUESTS_COUNTER_MSB                                31
`define GCREG_PC_BILINEAR_REQUESTS_COUNTER_LSB                                 0
`define GCREG_PC_BILINEAR_REQUESTS_COUNTER_SIZE                               32

/* Register gcregPCTrilinearRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of tri-linear texel requests. */

`define gcregPCTrilinearRequestsRegAddrs                                16'h4C92
`define GCREG_PC_TRILINEAR_REQUESTS_MSB                                       15
`define GCREG_PC_TRILINEAR_REQUESTS_LSB                                        0
`define GCREG_PC_TRILINEAR_REQUESTS_BLK                                        0
`define GCREG_PC_TRILINEAR_REQUESTS_Count                                      1
`define GCREG_PC_TRILINEAR_REQUESTS_FieldMask                       32'hFFFFFFFF
`define GCREG_PC_TRILINEAR_REQUESTS_ReadMask                        32'hFFFFFFFF
`define GCREG_PC_TRILINEAR_REQUESTS_WriteMask                       32'hFFFFFFFF
`define GCREG_PC_TRILINEAR_REQUESTS_ResetValue                      32'h00000000

`define GCREG_PC_TRILINEAR_REQUESTS_COUNTER_MSB                               31
`define GCREG_PC_TRILINEAR_REQUESTS_COUNTER_LSB                                0
`define GCREG_PC_TRILINEAR_REQUESTS_COUNTER_SIZE                              32

/* Register gcregPCDiscardedRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of discarded texel requests. */

`define gcregPCDiscardedRequestsRegAddrs                                16'h4C93
`define GCREG_PC_DISCARDED_REQUESTS_MSB                                       15
`define GCREG_PC_DISCARDED_REQUESTS_LSB                                        0
`define GCREG_PC_DISCARDED_REQUESTS_BLK                                        0
`define GCREG_PC_DISCARDED_REQUESTS_Count                                      1
`define GCREG_PC_DISCARDED_REQUESTS_FieldMask                       32'hFFFFFFFF
`define GCREG_PC_DISCARDED_REQUESTS_ReadMask                        32'hFFFFFFFF
`define GCREG_PC_DISCARDED_REQUESTS_WriteMask                       32'hFFFFFFFF
`define GCREG_PC_DISCARDED_REQUESTS_ResetValue                      32'h00000000

`define GCREG_PC_DISCARDED_REQUESTS_COUNTER_MSB                               31
`define GCREG_PC_DISCARDED_REQUESTS_COUNTER_LSB                                0
`define GCREG_PC_DISCARDED_REQUESTS_COUNTER_SIZE                              32

/* Register gcregPCTXCacheRequests (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Texture Cache requests. One for each MC. */

`define gcregPCTXCacheRequestsRegAddrs                                  13'h0993
`define GCREG_PCTX_CACHE_REQUESTS_MSB                                         15
`define GCREG_PCTX_CACHE_REQUESTS_LSB                                          3
`define GCREG_PCTX_CACHE_REQUESTS_BLK                                          3
`define GCREG_PCTX_CACHE_REQUESTS_Count                                        8
`define GCREG_PCTX_CACHE_REQUESTS_FieldMask                         32'hFFFFFFFF
`define GCREG_PCTX_CACHE_REQUESTS_ReadMask                          32'hFFFFFFFF
`define GCREG_PCTX_CACHE_REQUESTS_WriteMask                         32'hFFFFFFFF
`define GCREG_PCTX_CACHE_REQUESTS_ResetValue                        32'h00000000

`define GCREG_PCTX_CACHE_REQUESTS_COUNTER_MSB                                 31
`define GCREG_PCTX_CACHE_REQUESTS_COUNTER_LSB                                  0
`define GCREG_PCTX_CACHE_REQUESTS_COUNTER_SIZE                                32

/* Register gcregPCTXCacheMisses (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of Texture Cache misses. One for each MC. */

`define gcregPCTXCacheMissesRegAddrs                                    13'h0994
`define GCREG_PCTX_CACHE_MISSES_MSB                                           15
`define GCREG_PCTX_CACHE_MISSES_LSB                                            3
`define GCREG_PCTX_CACHE_MISSES_BLK                                            3
`define GCREG_PCTX_CACHE_MISSES_Count                                          8
`define GCREG_PCTX_CACHE_MISSES_FieldMask                           32'hFFFFFFFF
`define GCREG_PCTX_CACHE_MISSES_ReadMask                            32'hFFFFFFFF
`define GCREG_PCTX_CACHE_MISSES_WriteMask                           32'hFFFFFFFF
`define GCREG_PCTX_CACHE_MISSES_ResetValue                          32'h00000000

`define GCREG_PCTX_CACHE_MISSES_COUNTER_MSB                                   31
`define GCREG_PCTX_CACHE_MISSES_COUNTER_LSB                                    0
`define GCREG_PCTX_CACHE_MISSES_COUNTER_SIZE                                  32

/* Register gcregPCTXBytesFetched (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from Texture Cache. One for each MC. */

`define gcregPCTXBytesFetchedRegAddrs                                   13'h0995
`define GCREG_PCTX_BYTES_FETCHED_MSB                                          15
`define GCREG_PCTX_BYTES_FETCHED_LSB                                           3
`define GCREG_PCTX_BYTES_FETCHED_BLK                                           3
`define GCREG_PCTX_BYTES_FETCHED_Count                                         8
`define GCREG_PCTX_BYTES_FETCHED_FieldMask                          32'hFFFFFFFF
`define GCREG_PCTX_BYTES_FETCHED_ReadMask                           32'hFFFFFFFF
`define GCREG_PCTX_BYTES_FETCHED_WriteMask                          32'hFFFFFFFF
`define GCREG_PCTX_BYTES_FETCHED_ResetValue                         32'h00000000

`define GCREG_PCTX_BYTES_FETCHED_COUNTER_MSB                                  31
`define GCREG_PCTX_BYTES_FETCHED_COUNTER_LSB                                   0
`define GCREG_PCTX_BYTES_FETCHED_COUNTER_SIZE                                 32

/* Register gcregPCVertexInstructions **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of VS instructions executed. */

`define gcregPCVertexInstructionsRegAddrs                               16'h4C94
`define GCREG_PC_VERTEX_INSTRUCTIONS_MSB                                      15
`define GCREG_PC_VERTEX_INSTRUCTIONS_LSB                                       0
`define GCREG_PC_VERTEX_INSTRUCTIONS_BLK                                       0
`define GCREG_PC_VERTEX_INSTRUCTIONS_Count                                     1
`define GCREG_PC_VERTEX_INSTRUCTIONS_FieldMask                      32'hFFFFFFFF
`define GCREG_PC_VERTEX_INSTRUCTIONS_ReadMask                       32'hFFFFFFFF
`define GCREG_PC_VERTEX_INSTRUCTIONS_WriteMask                      32'hFFFFFFFF
`define GCREG_PC_VERTEX_INSTRUCTIONS_ResetValue                     32'h00000000

`define GCREG_PC_VERTEX_INSTRUCTIONS_COUNTER_MSB                              31
`define GCREG_PC_VERTEX_INSTRUCTIONS_COUNTER_LSB                               0
`define GCREG_PC_VERTEX_INSTRUCTIONS_COUNTER_SIZE                             32

/* Register gcregPCVertexBranches **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of VS branch instructions executed. */

`define gcregPCVertexBranchesRegAddrs                                   16'h4C95
`define GCREG_PC_VERTEX_BRANCHES_MSB                                          15
`define GCREG_PC_VERTEX_BRANCHES_LSB                                           0
`define GCREG_PC_VERTEX_BRANCHES_BLK                                           0
`define GCREG_PC_VERTEX_BRANCHES_Count                                         1
`define GCREG_PC_VERTEX_BRANCHES_FieldMask                          32'hFFFFFFFF
`define GCREG_PC_VERTEX_BRANCHES_ReadMask                           32'hFFFFFFFF
`define GCREG_PC_VERTEX_BRANCHES_WriteMask                          32'hFFFFFFFF
`define GCREG_PC_VERTEX_BRANCHES_ResetValue                         32'h00000000

`define GCREG_PC_VERTEX_BRANCHES_COUNTER_MSB                                  31
`define GCREG_PC_VERTEX_BRANCHES_COUNTER_LSB                                   0
`define GCREG_PC_VERTEX_BRANCHES_COUNTER_SIZE                                 32

/* Register gcregPCVertexTextures **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of VS texture instructions executed. */

`define gcregPCVertexTexturesRegAddrs                                   16'h4C96
`define GCREG_PC_VERTEX_TEXTURES_MSB                                          15
`define GCREG_PC_VERTEX_TEXTURES_LSB                                           0
`define GCREG_PC_VERTEX_TEXTURES_BLK                                           0
`define GCREG_PC_VERTEX_TEXTURES_Count                                         1
`define GCREG_PC_VERTEX_TEXTURES_FieldMask                          32'hFFFFFFFF
`define GCREG_PC_VERTEX_TEXTURES_ReadMask                           32'hFFFFFFFF
`define GCREG_PC_VERTEX_TEXTURES_WriteMask                          32'hFFFFFFFF
`define GCREG_PC_VERTEX_TEXTURES_ResetValue                         32'h00000000

`define GCREG_PC_VERTEX_TEXTURES_COUNTER_MSB                                  31
`define GCREG_PC_VERTEX_TEXTURES_COUNTER_LSB                                   0
`define GCREG_PC_VERTEX_TEXTURES_COUNTER_SIZE                                 32

/* Register gcregPCVerticesRendered **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of vertices shaded. */

`define gcregPCVerticesRenderedRegAddrs                                 16'h4C97
`define GCREG_PC_VERTICES_RENDERED_MSB                                        15
`define GCREG_PC_VERTICES_RENDERED_LSB                                         0
`define GCREG_PC_VERTICES_RENDERED_BLK                                         0
`define GCREG_PC_VERTICES_RENDERED_Count                                       1
`define GCREG_PC_VERTICES_RENDERED_FieldMask                        32'hFFFFFFFF
`define GCREG_PC_VERTICES_RENDERED_ReadMask                         32'hFFFFFFFF
`define GCREG_PC_VERTICES_RENDERED_WriteMask                        32'hFFFFFFFF
`define GCREG_PC_VERTICES_RENDERED_ResetValue                       32'h00000000

`define GCREG_PC_VERTICES_RENDERED_COUNTER_MSB                                31
`define GCREG_PC_VERTICES_RENDERED_COUNTER_LSB                                 0
`define GCREG_PC_VERTICES_RENDERED_COUNTER_SIZE                               32

/* Register gcregPCPixelInstructions **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Total number of PS instructions executed. */

`define gcregPCPixelInstructionsRegAddrs                                16'h4CB0
`define GCREG_PC_PIXEL_INSTRUCTIONS_MSB                                       15
`define GCREG_PC_PIXEL_INSTRUCTIONS_LSB                                        0
`define GCREG_PC_PIXEL_INSTRUCTIONS_BLK                                        0
`define GCREG_PC_PIXEL_INSTRUCTIONS_Count                                      1
`define GCREG_PC_PIXEL_INSTRUCTIONS_FieldMask                       32'hFFFFFFFF
`define GCREG_PC_PIXEL_INSTRUCTIONS_ReadMask                        32'hFFFFFFFF
`define GCREG_PC_PIXEL_INSTRUCTIONS_WriteMask                       32'hFFFFFFFF
`define GCREG_PC_PIXEL_INSTRUCTIONS_ResetValue                      32'h00000000

`define GCREG_PC_PIXEL_INSTRUCTIONS_COUNTER_MSB                               31
`define GCREG_PC_PIXEL_INSTRUCTIONS_COUNTER_LSB                                0
`define GCREG_PC_PIXEL_INSTRUCTIONS_COUNTER_SIZE                              32

/* Register gcregPCPixelBranches **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of PS branch instructions executed. */

`define gcregPCPixelBranchesRegAddrs                                    16'h4CB1
`define GCREG_PC_PIXEL_BRANCHES_MSB                                           15
`define GCREG_PC_PIXEL_BRANCHES_LSB                                            0
`define GCREG_PC_PIXEL_BRANCHES_BLK                                            0
`define GCREG_PC_PIXEL_BRANCHES_Count                                          1
`define GCREG_PC_PIXEL_BRANCHES_FieldMask                           32'hFFFFFFFF
`define GCREG_PC_PIXEL_BRANCHES_ReadMask                            32'hFFFFFFFF
`define GCREG_PC_PIXEL_BRANCHES_WriteMask                           32'hFFFFFFFF
`define GCREG_PC_PIXEL_BRANCHES_ResetValue                          32'h00000000

`define GCREG_PC_PIXEL_BRANCHES_COUNTER_MSB                                   31
`define GCREG_PC_PIXEL_BRANCHES_COUNTER_LSB                                    0
`define GCREG_PC_PIXEL_BRANCHES_COUNTER_SIZE                                  32

/* Register gcregPCPixelTextures **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of PS texture instructions executed. */

`define gcregPCPixelTexturesRegAddrs                                    16'h4CB2
`define GCREG_PC_PIXEL_TEXTURES_MSB                                           15
`define GCREG_PC_PIXEL_TEXTURES_LSB                                            0
`define GCREG_PC_PIXEL_TEXTURES_BLK                                            0
`define GCREG_PC_PIXEL_TEXTURES_Count                                          1
`define GCREG_PC_PIXEL_TEXTURES_FieldMask                           32'hFFFFFFFF
`define GCREG_PC_PIXEL_TEXTURES_ReadMask                            32'hFFFFFFFF
`define GCREG_PC_PIXEL_TEXTURES_WriteMask                           32'hFFFFFFFF
`define GCREG_PC_PIXEL_TEXTURES_ResetValue                          32'h00000000

`define GCREG_PC_PIXEL_TEXTURES_COUNTER_MSB                                   31
`define GCREG_PC_PIXEL_TEXTURES_COUNTER_LSB                                    0
`define GCREG_PC_PIXEL_TEXTURES_COUNTER_SIZE                                  32

/* Register gcregPCPixelsRendered **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of pixels shaded. */

`define gcregPCPixelsRenderedRegAddrs                                   16'h4CB3
`define GCREG_PC_PIXELS_RENDERED_MSB                                          15
`define GCREG_PC_PIXELS_RENDERED_LSB                                           0
`define GCREG_PC_PIXELS_RENDERED_BLK                                           0
`define GCREG_PC_PIXELS_RENDERED_Count                                         1
`define GCREG_PC_PIXELS_RENDERED_FieldMask                          32'hFFFFFFFF
`define GCREG_PC_PIXELS_RENDERED_ReadMask                           32'hFFFFFFFF
`define GCREG_PC_PIXELS_RENDERED_WriteMask                          32'hFFFFFFFF
`define GCREG_PC_PIXELS_RENDERED_ResetValue                         32'h00000000

`define GCREG_PC_PIXELS_RENDERED_COUNTER_MSB                                  31
`define GCREG_PC_PIXELS_RENDERED_COUNTER_LSB                                   0
`define GCREG_PC_PIXELS_RENDERED_COUNTER_SIZE                                 32

/* Register gcregPCLoadInstructions **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of load instructions. */

`define gcregPCLoadInstructionsRegAddrs                                 16'h4CB4
`define GCREG_PC_LOAD_INSTRUCTIONS_MSB                                        15
`define GCREG_PC_LOAD_INSTRUCTIONS_LSB                                         0
`define GCREG_PC_LOAD_INSTRUCTIONS_BLK                                         0
`define GCREG_PC_LOAD_INSTRUCTIONS_Count                                       1
`define GCREG_PC_LOAD_INSTRUCTIONS_FieldMask                        32'hFFFFFFFF
`define GCREG_PC_LOAD_INSTRUCTIONS_ReadMask                         32'hFFFFFFFF
`define GCREG_PC_LOAD_INSTRUCTIONS_WriteMask                        32'hFFFFFFFF
`define GCREG_PC_LOAD_INSTRUCTIONS_ResetValue                       32'h00000000

`define GCREG_PC_LOAD_INSTRUCTIONS_COUNTER_MSB                                31
`define GCREG_PC_LOAD_INSTRUCTIONS_COUNTER_LSB                                 0
`define GCREG_PC_LOAD_INSTRUCTIONS_COUNTER_SIZE                               32

/* Register gcregPCStoreInstructions **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of store instructions. */

`define gcregPCStoreInstructionsRegAddrs                                16'h4CB5
`define GCREG_PC_STORE_INSTRUCTIONS_MSB                                       15
`define GCREG_PC_STORE_INSTRUCTIONS_LSB                                        0
`define GCREG_PC_STORE_INSTRUCTIONS_BLK                                        0
`define GCREG_PC_STORE_INSTRUCTIONS_Count                                      1
`define GCREG_PC_STORE_INSTRUCTIONS_FieldMask                       32'hFFFFFFFF
`define GCREG_PC_STORE_INSTRUCTIONS_ReadMask                        32'hFFFFFFFF
`define GCREG_PC_STORE_INSTRUCTIONS_WriteMask                       32'hFFFFFFFF
`define GCREG_PC_STORE_INSTRUCTIONS_ResetValue                      32'h00000000

`define GCREG_PC_STORE_INSTRUCTIONS_COUNTER_MSB                               31
`define GCREG_PC_STORE_INSTRUCTIONS_COUNTER_LSB                                0
`define GCREG_PC_STORE_INSTRUCTIONS_COUNTER_SIZE                              32

/* Register gcregPCL1LoadRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of L1 Cache read requests. */

`define gcregPCL1LoadRequestsRegAddrs                                   16'h4CB6
`define GCREG_PCL1_LOAD_REQUESTS_MSB                                          15
`define GCREG_PCL1_LOAD_REQUESTS_LSB                                           0
`define GCREG_PCL1_LOAD_REQUESTS_BLK                                           0
`define GCREG_PCL1_LOAD_REQUESTS_Count                                         1
`define GCREG_PCL1_LOAD_REQUESTS_FieldMask                          32'hFFFFFFFF
`define GCREG_PCL1_LOAD_REQUESTS_ReadMask                           32'hFFFFFFFF
`define GCREG_PCL1_LOAD_REQUESTS_WriteMask                          32'hFFFFFFFF
`define GCREG_PCL1_LOAD_REQUESTS_ResetValue                         32'h00000000

`define GCREG_PCL1_LOAD_REQUESTS_COUNTER_MSB                                  31
`define GCREG_PCL1_LOAD_REQUESTS_COUNTER_LSB                                   0
`define GCREG_PCL1_LOAD_REQUESTS_COUNTER_SIZE                                 32

/* Register gcregPCL1StoreRequests **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of L1 Cache write requests. */

`define gcregPCL1StoreRequestsRegAddrs                                  16'h4CB7
`define GCREG_PCL1_STORE_REQUESTS_MSB                                         15
`define GCREG_PCL1_STORE_REQUESTS_LSB                                          0
`define GCREG_PCL1_STORE_REQUESTS_BLK                                          0
`define GCREG_PCL1_STORE_REQUESTS_Count                                        1
`define GCREG_PCL1_STORE_REQUESTS_FieldMask                         32'hFFFFFFFF
`define GCREG_PCL1_STORE_REQUESTS_ReadMask                          32'hFFFFFFFF
`define GCREG_PCL1_STORE_REQUESTS_WriteMask                         32'hFFFFFFFF
`define GCREG_PCL1_STORE_REQUESTS_ResetValue                        32'h00000000

`define GCREG_PCL1_STORE_REQUESTS_COUNTER_MSB                                 31
`define GCREG_PCL1_STORE_REQUESTS_COUNTER_LSB                                  0
`define GCREG_PCL1_STORE_REQUESTS_COUNTER_SIZE                                32

/* Register gcregPCL1Misses **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of L1 Cache misses. */

`define gcregPCL1MissesRegAddrs                                         16'h4CB8
`define GCREG_PCL1_MISSES_MSB                                                 15
`define GCREG_PCL1_MISSES_LSB                                                  0
`define GCREG_PCL1_MISSES_BLK                                                  0
`define GCREG_PCL1_MISSES_Count                                                1
`define GCREG_PCL1_MISSES_FieldMask                                 32'hFFFFFFFF
`define GCREG_PCL1_MISSES_ReadMask                                  32'hFFFFFFFF
`define GCREG_PCL1_MISSES_WriteMask                                 32'hFFFFFFFF
`define GCREG_PCL1_MISSES_ResetValue                                32'h00000000

`define GCREG_PCL1_MISSES_COUNTER_MSB                                         31
`define GCREG_PCL1_MISSES_COUNTER_LSB                                          0
`define GCREG_PCL1_MISSES_COUNTER_SIZE                                        32

/* Register gcregPCL1BytesFetched **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte fetches from L1 Cache. */

`define gcregPCL1BytesFetchedRegAddrs                                   16'h4CB9
`define GCREG_PCL1_BYTES_FETCHED_MSB                                          15
`define GCREG_PCL1_BYTES_FETCHED_LSB                                           0
`define GCREG_PCL1_BYTES_FETCHED_BLK                                           0
`define GCREG_PCL1_BYTES_FETCHED_Count                                         1
`define GCREG_PCL1_BYTES_FETCHED_FieldMask                          32'hFFFFFFFF
`define GCREG_PCL1_BYTES_FETCHED_ReadMask                           32'hFFFFFFFF
`define GCREG_PCL1_BYTES_FETCHED_WriteMask                          32'hFFFFFFFF
`define GCREG_PCL1_BYTES_FETCHED_ResetValue                         32'h00000000

`define GCREG_PCL1_BYTES_FETCHED_COUNTER_MSB                                  31
`define GCREG_PCL1_BYTES_FETCHED_COUNTER_LSB                                   0
`define GCREG_PCL1_BYTES_FETCHED_COUNTER_SIZE                                 32

/* Register gcregPCL1BytesWritten **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Number of 8-byte written from L1 Cache. */

`define gcregPCL1BytesWrittenRegAddrs                                   16'h4CBA
`define GCREG_PCL1_BYTES_WRITTEN_MSB                                          15
`define GCREG_PCL1_BYTES_WRITTEN_LSB                                           0
`define GCREG_PCL1_BYTES_WRITTEN_BLK                                           0
`define GCREG_PCL1_BYTES_WRITTEN_Count                                         1
`define GCREG_PCL1_BYTES_WRITTEN_FieldMask                          32'hFFFFFFFF
`define GCREG_PCL1_BYTES_WRITTEN_ReadMask                           32'hFFFFFFFF
`define GCREG_PCL1_BYTES_WRITTEN_WriteMask                          32'hFFFFFFFF
`define GCREG_PCL1_BYTES_WRITTEN_ResetValue                         32'h00000000

`define GCREG_PCL1_BYTES_WRITTEN_COUNTER_MSB                                  31
`define GCREG_PCL1_BYTES_WRITTEN_COUNTER_LSB                                   0
`define GCREG_PCL1_BYTES_WRITTEN_COUNTER_SIZE                                 32

