/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
**                              ~~~~~~~~~~~~~~~~~                             **
**                              Module Raytracing                             **
**                              ~~~~~~~~~~~~~~~~~                             **
*******************************************************************************/

/* Register gcregRtCacheCtrl **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */
`define gcregRtCacheCtrlRegAddrs                                        16'hE000
`define GCREG_RT_CACHE_CTRL_MSB                                               15
`define GCREG_RT_CACHE_CTRL_LSB                                                0
`define GCREG_RT_CACHE_CTRL_BLK                                                0
`define GCREG_RT_CACHE_CTRL_Count                                              1
`define GCREG_RT_CACHE_CTRL_FieldMask                               32'h00000001
`define GCREG_RT_CACHE_CTRL_ReadMask                                32'h00000001
`define GCREG_RT_CACHE_CTRL_WriteMask                               32'h00000001
`define GCREG_RT_CACHE_CTRL_ResetValue                              32'h00000000

/* RT Cache clear bit */
`define GCREG_RT_CACHE_CTRL_CLEAR_CACHE_MSB                                    0
`define GCREG_RT_CACHE_CTRL_CLEAR_CACHE_LSB                                    0
`define GCREG_RT_CACHE_CTRL_CLEAR_CACHE_SIZE                                   1
`define   GCREG_RT_CACHE_CTRL_CLEAR_CACHE_DISABLE                           1'h0
`define   GCREG_RT_CACHE_CTRL_CLEAR_CACHE_ENABLE                            1'h1

/* Register gcregRtCoreCtrl **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */
`define gcregRtCoreCtrlRegAddrs                                         16'hE001
`define GCREG_RT_CORE_CTRL_MSB                                                15
`define GCREG_RT_CORE_CTRL_LSB                                                 0
`define GCREG_RT_CORE_CTRL_BLK                                                 0
`define GCREG_RT_CORE_CTRL_Count                                               1
`define GCREG_RT_CORE_CTRL_FieldMask                                32'h00000001
`define GCREG_RT_CORE_CTRL_ReadMask                                 32'h00000001
`define GCREG_RT_CORE_CTRL_WriteMask                                32'h00000001
`define GCREG_RT_CORE_CTRL_ResetValue                               32'h00000000

/* RT Op bit */
`define GCREG_RT_CORE_CTRL_OP_MSB                                              0
`define GCREG_RT_CORE_CTRL_OP_LSB                                              0
`define GCREG_RT_CORE_CTRL_OP_SIZE                                             1
`define   GCREG_RT_CORE_CTRL_OP_DISABLE                                     1'h0
`define   GCREG_RT_CORE_CTRL_OP_ENABLE                                      1'h1

/* Register gcregGcAsBuildCmd **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */
`define gcregGcAsBuildCmdRegAddrs                                       16'hE002
`define GCREG_GC_AS_BUILD_CMD_MSB                                             15
`define GCREG_GC_AS_BUILD_CMD_LSB                                              0
`define GCREG_GC_AS_BUILD_CMD_BLK                                              0
`define GCREG_GC_AS_BUILD_CMD_Count                                            1
`define GCREG_GC_AS_BUILD_CMD_FieldMask                             32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ReadMask                              32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_WriteMask                             32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ResetValue                            32'h00000000

/* AS build command length for RT Core */
`define GCREG_GC_AS_BUILD_CMD_LENGTH_MSB                                      31
`define GCREG_GC_AS_BUILD_CMD_LENGTH_LSB                                       0
`define GCREG_GC_AS_BUILD_CMD_LENGTH_SIZE                                     32

/* Register gcregGcAsBuildCmdAddr0 **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
`define gcregGcAsBuildCmdAddr0RegAddrs                                  16'hE003
`define GCREG_GC_AS_BUILD_CMD_ADDR0_MSB                                       15
`define GCREG_GC_AS_BUILD_CMD_ADDR0_LSB                                        0
`define GCREG_GC_AS_BUILD_CMD_ADDR0_BLK                                        0
`define GCREG_GC_AS_BUILD_CMD_ADDR0_Count                                      1
`define GCREG_GC_AS_BUILD_CMD_ADDR0_FieldMask                       32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR0_ReadMask                        32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR0_WriteMask                       32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR0_ResetValue                      32'h00000000

/* AS build command lower 32bits address */
`define GCREG_GC_AS_BUILD_CMD_ADDR0_ADDR_LOW_MSB                              31
`define GCREG_GC_AS_BUILD_CMD_ADDR0_ADDR_LOW_LSB                               0
`define GCREG_GC_AS_BUILD_CMD_ADDR0_ADDR_LOW_SIZE                             32

/* Register gcregGcAsBuildCmdAddr1 **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */
`define gcregGcAsBuildCmdAddr1RegAddrs                                  16'hE004
`define GCREG_GC_AS_BUILD_CMD_ADDR1_MSB                                       15
`define GCREG_GC_AS_BUILD_CMD_ADDR1_LSB                                        0
`define GCREG_GC_AS_BUILD_CMD_ADDR1_BLK                                        0
`define GCREG_GC_AS_BUILD_CMD_ADDR1_Count                                      1
`define GCREG_GC_AS_BUILD_CMD_ADDR1_FieldMask                       32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR1_ReadMask                        32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR1_WriteMask                       32'hFFFFFFFF
`define GCREG_GC_AS_BUILD_CMD_ADDR1_ResetValue                      32'h00000000

/* AS build command upper 32bits address */
`define GCREG_GC_AS_BUILD_CMD_ADDR1_ADDR_HIGH_MSB                             31
`define GCREG_GC_AS_BUILD_CMD_ADDR1_ADDR_HIGH_LSB                              0
`define GCREG_GC_AS_BUILD_CMD_ADDR1_ADDR_HIGH_SIZE                            32

