#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@scutclient[-1]
	add ucitrack scutclient
	set ucitrack.@scutclient[-1].init=scutclient
	commit ucitrack
	delete scutclient.@luci[-1]
	add scutclient luci
	commit scutclient
EOF
rm -f /tmp/luci-indexcache
/etc/init.d/scutclient enable
exit 0
