#
# Copyright (C) 2017 Dan Luedtke <mail@danrl.com>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Cloudshark capture tool Web UI
LUCI_DEPENDS:=+cshark
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Luka Perkov <luka@openwrt.org>

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
