#!/bin/sh /etc/rc.common

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

CONFIG=/etc/shadowsocksr-server.json

start() {
	service_start /usr/bin/ssr-server -c $CONFIG -u
}

stop() {
	service_stop /usr/bin/ssr-server
}
