#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-relay[-1]
	add ucitrack pppoe-relay
	set ucitrack.@pppoe-relay[-1].init=pppoe-relay
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
