#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@brook[-1]
	add ucitrack brook
	set ucitrack.@brook[-1].init=brook
	commit ucitrack
	delete firewall.brook
	set firewall.brook=include
	set firewall.brook.type=script
	set firewall.brook.path=/var/etc/brook.include
	set firewall.brook.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0