#!/bin/sh /etc/rc.common
START=99
STOP=10

start() {
	enable=$(uci get serverchan.serverchan.serverchan_enable)
	if [ $enable -eq 1 ]; then	
		echo "enable"
		kill -9 $(ps | grep serverchan/serverchan | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
		sleep 1
		nohup /usr/bin/serverchan/serverchan 2>&1 &
	fi
}

stop() {
	enable=$(uci get serverchan.serverchan.serverchan_enable)
	if [ $enable -ne 1 ]; then
		echo 'stop!'
		kill $(pidof serverchan) >/dev/null 2>&1
		kill -9 $(ps | grep serverchan | grep -v "grep" | awk '{print $1}') >/dev/null 2>&1
	fi
}

restart(){
	stop
	sleep 1
	start
	echo "restarted."
}