#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.wrtbwmon
	set firewall.wrtbwmon=include
	set firewall.wrtbwmon.type=script
	set firewall.wrtbwmon.path='/etc/wrtbwmon.include'
	set firewall.wrtbwmon.reload=1
  commit firewall
EOF

/etc/init.d/wrtbwmon enable
/etc/init.d/wrtbwmon start
exit 0
