#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	add ucitrack qbittorrent
	set ucitrack.@qbittorrent[-1].init=qbittorrent
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache*
exit 0
