#!/bin/sh /etc/rc.common

START=95
STOP=10
SERVICE_DAEMONIZE=1

NAME=xlnetacc

start() {
	pidof "${NAME}.sh" >/dev/null 2>&1 && return

	config_load "$NAME"
	config_get_bool enabled "general" "enabled" 0
	config_get_bool down_acc "general" "down_acc" 0
	config_get_bool up_acc "general" "up_acc" 0
	config_get network "general" "network"
	config_get account "general" "account"
	config_get encrypt "general" "encrypt"
	( [ $enabled -eq 0 ] || [ $down_acc -eq 0 -a $up_acc -eq 0 ] || [ -z "$account" -o -z "$encrypt" -o -z "$network" ] ) && return

	logger -p "daemon.notice" -t "$NAME" "XLNetAcc is starting ..."
	service_start /usr/bin/${NAME}.sh --start
}

stop() {
	pidof "${NAME}.sh" >/dev/null 2>&1 || return

	local pid spid
	for pid in $(pidof "${NAME}.sh"); do
		kill $pid >/dev/null 2>&1
		echo "Stop XLNetAcc process PID: $pid"
		for spid in $(pgrep -P $pid "sleep"); do
			kill $spid >/dev/null 2>&1
			echo "Stop XLNetAcc process SPID: $spid"
		done
	done
	logger -p "daemon.notice" -t "$NAME" "XLNetAcc has stoped."
}

restart() {
	stop
	sleep 1
	start
}
