#!/bin/sh


echo '[$(date "+%Y-%m-%d %H:%M:%S")] 正在检测ShadowsocksR运行状态.'
/usr/bin/ssr-check www.google.com 80 3 1

if [ "$?" == "0" ]; then
	echo '[$(date "+%Y-%m-%d %H:%M:%S")] GFW列表域名访问正常,ShadowsocksR运行正常.'
else
	echo '['$LOGTIME'] GFW列表域名无法访问.'
	/usr/bin/ssr-check www.baidu.com 80 3 1
	if [ "$?" == "0" ]; then
		echo '[$(date "+%Y-%m-%d %H:%M:%S")] 国内域名访问正常,正在重启ShadowsocksR'
		/etc/init.d/shadowsocksr restart
	else
		echo '[$(date "+%Y-%m-%d %H:%M:%S")] 未连接互联网,请检查设备状态.'
	fi
fi
