/***************************************************************
Copyright Statement:

This software/firmware and related documentation (“EcoNet Software”) 
are protected under relevant copyright laws. The information contained herein 
is confidential and proprietary to EcoNet (HK) Limited (“EcoNet”) and/or 
its licensors. Without the prior written permission of EcoNet and/or its licensors, 
any reproduction, modification, use or disclosure of EcoNet Software, and 
information contained herein, in whole or in part, shall be strictly prohibited.

EcoNet (HK) Limited  EcoNet. ALL RIGHTS RESERVED.

BY OPENING OR USING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY 
ACKNOWLEDGES AND AGREES THAT THE SOFTWARE/FIRMWARE AND ITS 
DOCUMENTATIONS (“ECONET SOFTWARE”) RECEIVED FROM ECONET 
AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER ON AN “AS IS” 
BASIS ONLY. ECONET EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, 
WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED 
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, 
OR NON-INFRINGEMENT. NOR DOES ECONET PROVIDE ANY WARRANTY 
WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTIES WHICH 
MAY BE USED BY, INCORPORATED IN, OR SUPPLIED WITH THE ECONET SOFTWARE. 
RECEIVER AGREES TO LOOK ONLY TO SUCH THIRD PARTIES FOR ANY AND ALL 
WARRANTY CLAIMS RELATING THERETO. RECEIVER EXPRESSLY ACKNOWLEDGES 
THAT IT IS RECEIVER’S SOLE RESPONSIBILITY TO OBTAIN FROM ANY THIRD 
PARTY ALL PROPER LICENSES CONTAINED IN ECONET SOFTWARE.

ECONET SHALL NOT BE RESPONSIBLE FOR ANY ECONET SOFTWARE RELEASES 
MADE TO RECEIVER’S SPECIFICATION OR CONFORMING TO A PARTICULAR 
STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND 
ECONET'S ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE ECONET 
SOFTWARE RELEASED HEREUNDER SHALL BE, AT ECONET'S SOLE OPTION, TO 
REVISE OR REPLACE THE ECONET SOFTWARE AT ISSUE OR REFUND ANY SOFTWARE 
LICENSE FEES OR SERVICE CHARGES PAID BY RECEIVER TO ECONET FOR SUCH 
ECONET SOFTWARE.
***************************************************************/
#ifndef __EPON_MSG_ROUTE_H
#define __EPON_MSG_ROUTE_H

#define MAX_NAME_LENTH		64

typedef enum
{
	EPON_MSG_DETECT_LOS,
    EPON_MSG_DETECT_READY,
    EPON_MSG_LOS_ENABLE_TYPEB,
    EPON_MSG_TRUE_LOS,
    EPON_MSG_TRUE_READY,
    EPON_MSG_RCV_DISCOVERY_GATE,
    EPON_MSG_SEND_REGISTER_REQ,
    EPON_MSG_RCV_REGISTER_MSG,
    EPON_MSG_RCV_ACK_REGISTER,
    EPON_MSG_RCV_NACK_REGISTER,
    EPON_MSG_RCV_RE_REGISTER,
    EPON_MSG_RCV_DE_REGISTER,
    EPON_MSG_CHANHE_TO_SILENT,
    EPON_MSG_TX_POWER_CHANGE,

/*************please add above*********************/
	EPON_MSG_MAX_NUM
}EPON_MSG_ROUTE_TYPE;

typedef struct msg_event_action_s {
    int 	event;
	char 	name[MAX_NAME_LENTH];
	int 	(*func)(void* data);
}msg_event_action_t,*msg_event_action_ptr;

int epon_msg_route_dispatch(EPON_MSG_ROUTE_TYPE type,void *paramters);

#endif

