#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@sccustom[-1]
	add ucitrack sccustom
	set ucitrack.@sccustom[-1].init=sccustom
	commit ucitrack
EOF

rm -rf /tmp/luci-*
chmod 755 /etc/init.d/sccustom
chmod 755 /usr/bin/serverchan/*
exit 0