#ifndef _FMGR_EVENT_H_
#define _FMGR_EVENT_H_

#include "common/mgr_sdi.h"

#define CONST_TRAP_CMD_ID_MASK						0x00FF
#define CONST_TRAP_GROUP_ID_MASK					0xFF00

typedef enum {
	TRAP_GROUP_GPON 		= XMCS_EVENT_TYPE_GPON,
	TRAP_GROUP_EPON 		= XMCS_EVENT_TYPE_EPON,
} FMGR_TrapGroup_t ;

typedef enum {
#ifdef TCSUPPORT_WAN_GPON
	GPON_TRAP_DETECT_LOS 		= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_LOS),
	GPON_TRAP_PHY_READY			= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_PHY_READY),
	GPON_TRAP_DEACTIVATE		= ((TRAP_GROUP_GPON<<8) + XMCS_EVNET_GPON_DEACTIVATE),
	GPON_TRAP_ACTIVATE			= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_ACTIVATE),
	GPON_TRAP_TCONT_ALLOCED		= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_TCONT_ALLOCED),
	GPON_TRAP_MODE_CHANGED		= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_MODE_CHANGE), //Whan OMCI receives GPON Mode Changed, OMCI must clear GPON setting
	GPON_TRAP_PHY_TRANS_ALARM	= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_PHY_TRANS_ALARM),
	GPON_TRAP_DISABLE       	= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_DISABLE),
	GPON_TRAP_ENABLE        	= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_GPON_ENABLE),
#endif /* TCSUPPORT_WAN_GPON */
#ifdef TCSUPPORT_WAN_EPON
	EPON_TRAP_DETECT_LOS 		= ((TRAP_GROUP_EPON<<8) + XMCS_EVENT_EPON_LOS),
	EPON_TRAP_PHY_READY			= ((TRAP_GROUP_EPON<<8) + XMCS_EVENT_EPON_PHY_READY),
	EPON_TRAP_DEREGISTER		= ((TRAP_GROUP_EPON<<8) + XMCS_EVENT_EPON_DEREGISTER),
	EPON_TRAP_REGISTER			= ((TRAP_GROUP_EPON<<8) + XMCS_EVENT_EPON_REGISTER),
	EPON_TRAP_DENIED			= ((TRAP_GROUP_EPON<<8) + XMCS_EVENT_EPON_DENIED),
	EPON_TRAP_MODE_CHANGED		= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_EPON_MODE_CHANGE), //Whan OAM receives EPON Mode Changed, OAM must clear EPON setting
	EPON_TRAP_PHY_TRANS_ALARM	= ((TRAP_GROUP_GPON<<8) + XMCS_EVENT_EPON_PHY_TRANS_ALARM),
#endif /* TCSUPPORT_WAN_EPON */
} FMGR_PonTrapIndex_t ;

#endif /* _FMGR_EVENT_H_ */
