NOTDETECTED="Nie wykryto żadnego urządzenia!"
NODEVICE="Brak urządzenia"
PINERROR="Błąd kodu PIN"
CONNECTED="Połączony"
CONNECT="Połącz"
DISCONNECTED="Rozłączony"
DISCONNECT="Rozłącz"
NOINFO="Brak informacji"
