#if 1  //mark A60972 FPGA code

#ifndef _A60972_REG_H_

#define _A60972_REG_H_

#if A60972_SERDES

#define PMA_TOP_BASE                                 0x00000000

#define XPON_PMA_BASE                                0x00000000

#define XFI_PMA_BASE                                 0x00000000

#define A60972_DUMMY_NAME                            0

/* ===================== A60972 PMA TOP Register ===================== */
#define PMA_TOP_PHYD_TX_CLK0                        (PMA_TOP_BASE+0x0000)
#define PMA_TOP_PHYD_TX_CLK1                        (PMA_TOP_BASE+0x0004)
#define PMA_TOP_PHYD_TX_CLK2                        (PMA_TOP_BASE+0x0008)
#define PMA_TOP_PHYD_TX_CLK3                        (PMA_TOP_BASE+0x000C)
#define PMA_TOP_PHYD_TX_D0                          (PMA_TOP_BASE+0x0010)
#define PMA_TOP_PHYD_TX_D1                          (PMA_TOP_BASE+0x0014)
#define PMA_TOP_PHYD_TX_D2                          (PMA_TOP_BASE+0x0018)
#define PMA_TOP_PHYD_TX_D3                          (PMA_TOP_BASE+0x001C)
#define PMA_TOP_PHYD_TX_D4                          (PMA_TOP_BASE+0x0020)
#define PMA_TOP_PHYD_TX_D5                          (PMA_TOP_BASE+0x0024)
#define PMA_TOP_PHYD_TX_D6                          (PMA_TOP_BASE+0x0028)
#define PMA_TOP_PHYD_TX_D7                          (PMA_TOP_BASE+0x002C)
#define PMA_TOP_PHYD_TX_D8                          (PMA_TOP_BASE+0x0030)
#define PMA_TOP_PHYD_TX_D9                          (PMA_TOP_BASE+0x0034)
#define PMA_TOP_PHYD_TX_D10                         (PMA_TOP_BASE+0x0038)
#define PMA_TOP_PHYD_TX_D11                         (PMA_TOP_BASE+0x003C)
#define PMA_TOP_PHYD_TX_D12                         (PMA_TOP_BASE+0x0040)
#define PMA_TOP_PHYD_TX_D13                         (PMA_TOP_BASE+0x0044)
#define PMA_TOP_PHYD_TX_D14                         (PMA_TOP_BASE+0x0048)
#define PMA_TOP_PHYD_TX_D15                         (PMA_TOP_BASE+0x004C)
#define PMA_TOP_PHYD_TX_D16                         (PMA_TOP_BASE+0x0050)
#define PMA_TOP_PHYD_TX_D17                         (PMA_TOP_BASE+0x0054)
#define PMA_TOP_PHYD_TX_D18                         (PMA_TOP_BASE+0x0058)
#define PMA_TOP_PHYD_TX_D19                         (PMA_TOP_BASE+0x005C)
#define PMA_TOP_PHYD_TX_D20                         (PMA_TOP_BASE+0x0060)
#define PMA_TOP_PHYD_TX_D21                         (PMA_TOP_BASE+0x0064)
#define PMA_TOP_PHYD_TX_D22                         (PMA_TOP_BASE+0x0068)
#define PMA_TOP_PHYD_TX_D23                         (PMA_TOP_BASE+0x006C)
#define PMA_TOP_PHYD_TX_D24                         (PMA_TOP_BASE+0x0070)
#define PMA_TOP_PHYD_TX_D25                         (PMA_TOP_BASE+0x0074)
#define PMA_TOP_PHYD_TX_EN0                         (PMA_TOP_BASE+0x0078)
#define PMA_TOP_PHYD_TX_EN1                         (PMA_TOP_BASE+0x007C)
#define PMA_TOP_PHYD_TX_EN2                         (PMA_TOP_BASE+0x0080)
#define PMA_TOP_PHYD_TX_EN3                         (PMA_TOP_BASE+0x0084)
#define PMA_TOP_PHYD_TX_BV0                         (PMA_TOP_BASE+0x0088)
#define PMA_TOP_PHYD_TX_BV1                         (PMA_TOP_BASE+0x008C)
#define PMA_TOP_PHYD_TX_BV2                         (PMA_TOP_BASE+0x0090)
#define PMA_TOP_PHYD_TX_BV3                         (PMA_TOP_BASE+0x0094)
#define PMA_TOP_PHYD_TX_BIT_DLY0                    (PMA_TOP_BASE+0x0098)
#define PMA_TOP_PHYD_TX_BIT_DLY1                    (PMA_TOP_BASE+0x009C)
#define PMA_TOP_PHYD_TX_BIT_DLY2                    (PMA_TOP_BASE+0x0100)
#define PMA_TOP_PHYD_TX_BIT_DLY3                    (PMA_TOP_BASE+0x0104)
#define PMA_TOP_PHYD_TX_PARITY0                     (PMA_TOP_BASE+0x0108)
#define PMA_TOP_PHYD_TX_PARITY1                     (PMA_TOP_BASE+0x010C)
#define PMA_TOP_PHYD_TX_PARITY2                     (PMA_TOP_BASE+0x0110)
#define PMA_TOP_PHYD_TX_PARITY3                     (PMA_TOP_BASE+0x0114)
#define PMA_TOP_PHYD_RX_CLK0                        (PMA_TOP_BASE+0x0118)
#define PMA_TOP_PHYD_RX_CLK1                        (PMA_TOP_BASE+0x011C)
#define PMA_TOP_PHYD_RX_CLK2                        (PMA_TOP_BASE+0x0120)
#define PMA_TOP_PHYD_RX_CLK3                        (PMA_TOP_BASE+0x0124)
#define PMA_TOP_PHYD_RX_D0                          (PMA_TOP_BASE+0x0128)
#define PMA_TOP_PHYD_RX_D1                          (PMA_TOP_BASE+0x012C)
#define PMA_TOP_PHYD_RX_D2                          (PMA_TOP_BASE+0x0130)
#define PMA_TOP_PHYD_RX_D3                          (PMA_TOP_BASE+0x0134)
#define PMA_TOP_PHYD_RX_D4                          (PMA_TOP_BASE+0x0138)
#define PMA_TOP_PHYD_RX_D5                          (PMA_TOP_BASE+0x013C)
#define PMA_TOP_PHYD_RX_D6                          (PMA_TOP_BASE+0x0140)
#define PMA_TOP_PHYD_RX_D7                          (PMA_TOP_BASE+0x0144)
#define PMA_TOP_PHYD_RX_D8                          (PMA_TOP_BASE+0x0148)
#define PMA_TOP_PHYD_RX_D9                          (PMA_TOP_BASE+0x014C)
#define PMA_TOP_PHYD_RX_D10                         (PMA_TOP_BASE+0x0150)
#define PMA_TOP_PHYD_RX_D11                         (PMA_TOP_BASE+0x0154)
#define PMA_TOP_PHYD_RX_D12                         (PMA_TOP_BASE+0x0158)
#define PMA_TOP_PHYD_RX_D13                         (PMA_TOP_BASE+0x015C)
#define PMA_TOP_PHYD_RX_D14                         (PMA_TOP_BASE+0x0160)
#define PMA_TOP_PHYD_RX_D15                         (PMA_TOP_BASE+0x0164)
#define PMA_TOP_PHYD_RX_D16                         (PMA_TOP_BASE+0x0168)
#define PMA_TOP_PHYD_RX_D17                         (PMA_TOP_BASE+0x016C)
#define PMA_TOP_PHYD_RX_D18                         (PMA_TOP_BASE+0x0170)
#define PMA_TOP_PHYD_RX_D19                         (PMA_TOP_BASE+0x0174)
#define PMA_TOP_PHYD_RX_D20                         (PMA_TOP_BASE+0x0178)
#define PMA_TOP_PHYD_RX_D21                         (PMA_TOP_BASE+0x017C)
#define PMA_TOP_PHYD_RX_D22                         (PMA_TOP_BASE+0x0180)
#define PMA_TOP_PHYD_RX_D23                         (PMA_TOP_BASE+0x0184)
#define PMA_TOP_PHYD_RX_D24                         (PMA_TOP_BASE+0x0188)
#define PMA_TOP_PHYD_RX_D25                         (PMA_TOP_BASE+0x018C)
#define PMA_TOP_PHYD_RX_RDY0                        (PMA_TOP_BASE+0x0190)
#define PMA_TOP_PHYD_RX_RDY1                        (PMA_TOP_BASE+0x0194)
#define PMA_TOP_PHYD_RX_RDY2                        (PMA_TOP_BASE+0x0198)
#define PMA_TOP_PHYD_RX_RDY3                        (PMA_TOP_BASE+0x019C)
#define PMA_TOP_PHYD_RX_PARITY0                     (PMA_TOP_BASE+0x0200)
#define PMA_TOP_PHYD_RX_PARITY1                     (PMA_TOP_BASE+0x0204)
#define PMA_TOP_PHYD_RX_PARITY2                     (PMA_TOP_BASE+0x0208)
#define PMA_TOP_PHYD_RX_PARITY3                     (PMA_TOP_BASE+0x020C)
#define PMA_TOP_PHYD_TX_EOF0                        (PMA_TOP_BASE+0x0210)
#define PMA_TOP_PHYD_TX_EOF1                        (PMA_TOP_BASE+0x0214)
#define PMA_TOP_PHYD_TX_EOF2                        (PMA_TOP_BASE+0x0218)
#define PMA_TOP_PHYD_TX_EOF3                        (PMA_TOP_BASE+0x021C)
#define PMA_TOP_PHYD_RXEN_SYNC0                     (PMA_TOP_BASE+0x0220)
#define PMA_TOP_PHYD_RXEN_SYNC1                     (PMA_TOP_BASE+0x0224)
#define PMA_TOP_PHYD_RXEN_SYNC2                     (PMA_TOP_BASE+0x0228)
#define PMA_TOP_PHYD_RXEN_SYNC3                     (PMA_TOP_BASE+0x022C)
#define PMA_TOP_PHYD_RX_ALIGN0                      (PMA_TOP_BASE+0x0230)
#define PMA_TOP_PHYD_RX_ALIGN1                      (PMA_TOP_BASE+0x0234)
#define PMA_TOP_PHYD_RX_ALIGN2                      (PMA_TOP_BASE+0x0238)
#define PMA_TOP_PHYD_RX_ALIGN3                      (PMA_TOP_BASE+0x023C)
#define PMA_TOP_PHYD_RX_LOF0                        (PMA_TOP_BASE+0x0240)
#define PMA_TOP_PHYD_RX_LOF1                        (PMA_TOP_BASE+0x0244)
#define PMA_TOP_PHYD_RX_LOF2                        (PMA_TOP_BASE+0x0248)
#define PMA_TOP_PHYD_RX_LOF3                        (PMA_TOP_BASE+0x024C)
#define PMA_TOP_PHYD_CAL_LOS0                       (PMA_TOP_BASE+0x0250)
#define PMA_TOP_PHYD_CAL_LOS1                       (PMA_TOP_BASE+0x0254)
#define PMA_TOP_PHYD_CAL_LOS2                       (PMA_TOP_BASE+0x0258)
#define PMA_TOP_PHYD_CAL_LOS3                       (PMA_TOP_BASE+0x025C)
#define PMA_TOP_PHYD_SEC_EN0                        (PMA_TOP_BASE+0x0260)
#define PMA_TOP_PHYD_SEC_EN1                        (PMA_TOP_BASE+0x0264)
#define PMA_TOP_PHYD_SEC_EN2                        (PMA_TOP_BASE+0x0268)
#define PMA_TOP_PHYD_SEC_EN3                        (PMA_TOP_BASE+0x026C)
#define PMA_TOP_TRAN_BURST_EN0                      (PMA_TOP_BASE+0x0270)
#define PMA_TOP_TRAN_BURST_EN1                      (PMA_TOP_BASE+0x0274)
#define PMA_TOP_TRAN_BURST_EN2                      (PMA_TOP_BASE+0x0278)
#define PMA_TOP_TRAN_BURST_EN3                      (PMA_TOP_BASE+0x027C)
#define PMA_TOP_TRAN_TX_FAULT0                      (PMA_TOP_BASE+0x0280)
#define PMA_TOP_TRAN_TX_FAULT1                      (PMA_TOP_BASE+0x0284)
#define PMA_TOP_TRAN_TX_FAULT2                      (PMA_TOP_BASE+0x0288)
#define PMA_TOP_TRAN_TX_FAULT3                      (PMA_TOP_BASE+0x028C)
#define PMA_TOP_TRAN_TX_SD0                         (PMA_TOP_BASE+0x0290)
#define PMA_TOP_TRAN_TX_SD1                         (PMA_TOP_BASE+0x0294)
#define PMA_TOP_TRAN_TX_SD2                         (PMA_TOP_BASE+0x0298)
#define PMA_TOP_TRAN_TX_SD3                         (PMA_TOP_BASE+0x029C)
#define PMA_TOP_TRAN_RX_SD0                         (PMA_TOP_BASE+0x0300)
#define PMA_TOP_TRAN_RX_SD1                         (PMA_TOP_BASE+0x0304)
#define PMA_TOP_TRAN_RX_SD2                         (PMA_TOP_BASE+0x0308)
#define PMA_TOP_TRAN_RX_SD3                         (PMA_TOP_BASE+0x030C)
#define PMA_TOP_I2C_SDA0                            (PMA_TOP_BASE+0x0310)
#define PMA_TOP_I2C_SDA1                            (PMA_TOP_BASE+0x0314)
#define PMA_TOP_I2C_SDA2                            (PMA_TOP_BASE+0x0318)
#define PMA_TOP_I2C_SDA3                            (PMA_TOP_BASE+0x031C)
#define PMA_TOP_I2C_SCL0                            (PMA_TOP_BASE+0x0320)
#define PMA_TOP_I2C_SCL1                            (PMA_TOP_BASE+0x0324)
#define PMA_TOP_I2C_SCL2                            (PMA_TOP_BASE+0x0328)
#define PMA_TOP_I2C_SCL3                            (PMA_TOP_BASE+0x032C)
#define PMA_TOP_GPIO0                               (PMA_TOP_BASE+0x0330)
#define PMA_TOP_GPIO1                               (PMA_TOP_BASE+0x0334)
#define PMA_TOP_GPIO2                               (PMA_TOP_BASE+0x0338)
#define PMA_TOP_GPIO3                               (PMA_TOP_BASE+0x033C)
#define PMA_TOP_GPIO4                               (PMA_TOP_BASE+0x0340)
#define PMA_TOP_GPIO5                               (PMA_TOP_BASE+0x0344)
#define PMA_TOP_GPIO6                               (PMA_TOP_BASE+0x0348)
#define PMA_TOP_PROBE0                              (PMA_TOP_BASE+0x034C)
#define PMA_TOP_PROBE1                              (PMA_TOP_BASE+0x0350)
#define PMA_TOP_PROBE2                              (PMA_TOP_BASE+0x0354)
#define PMA_TOP_PROBE3                              (PMA_TOP_BASE+0x0358)
#define PMA_TOP_PROBE4                              (PMA_TOP_BASE+0x035C)
#define PMA_TOP_PROBE5                              (PMA_TOP_BASE+0x0360)
#define PMA_TOP_PROBE6                              (PMA_TOP_BASE+0x0364)
#define PMA_TOP_PROBE7                              (PMA_TOP_BASE+0x0368)
#define PMA_TOP_PROBE8                              (PMA_TOP_BASE+0x036C)
#define PMA_TOP_PROBE9                              (PMA_TOP_BASE+0x0370)
#define PMA_TOP_PROBE10                             (PMA_TOP_BASE+0x0374)
#define PMA_TOP_PROBE11                             (PMA_TOP_BASE+0x0378)
#define PMA_TOP_PROBE12                             (PMA_TOP_BASE+0x037C)
#define PMA_TOP_RESETB0                             (PMA_TOP_BASE+0x0380)
#define PMA_TOP_RESETB1                             (PMA_TOP_BASE+0x0384)
#define PMA_TOP_RESETB2                             (PMA_TOP_BASE+0x0388)
#define PMA_TOP_RESETB3                             (PMA_TOP_BASE+0x038C)
#define PMA_TOP_XTAL_SEL0                           (PMA_TOP_BASE+0x0390)
#define PMA_TOP_XTAL_SEL1                           (PMA_TOP_BASE+0x0394)
#define PMA_TOP_XTAL_SEL2                           (PMA_TOP_BASE+0x0398)
#define PMA_TOP_XTAL_SEL3                           (PMA_TOP_BASE+0x039C)
#define PMA_TOP_PON_DGINP0                          (PMA_TOP_BASE+0x0400)
#define PMA_TOP_PON_DGINP1                          (PMA_TOP_BASE+0x0404)
#define PMA_TOP_PON_DGINP2                          (PMA_TOP_BASE+0x0408)
#define PMA_TOP_PON_DGINP3                          (PMA_TOP_BASE+0x040C)
#define PMA_TOP_JTAG_TCK0                           (PMA_TOP_BASE+0x0410)
#define PMA_TOP_JTAG_TCK1                           (PMA_TOP_BASE+0x0414)
#define PMA_TOP_JTAG_TCK2                           (PMA_TOP_BASE+0x0418)
#define PMA_TOP_JTAG_TCK3                           (PMA_TOP_BASE+0x041C)
#define PMA_TOP_JTAG_TDI0                           (PMA_TOP_BASE+0x0420)
#define PMA_TOP_JTAG_TDI1                           (PMA_TOP_BASE+0x0424)
#define PMA_TOP_JTAG_TDI2                           (PMA_TOP_BASE+0x0428)
#define PMA_TOP_JTAG_TDI3                           (PMA_TOP_BASE+0x042C)
#define PMA_TOP_JTAG_TMS0                           (PMA_TOP_BASE+0x0430)
#define PMA_TOP_JTAG_TMS1                           (PMA_TOP_BASE+0x0434)
#define PMA_TOP_JTAG_TMS2                           (PMA_TOP_BASE+0x0438)
#define PMA_TOP_JTAG_TMS3                           (PMA_TOP_BASE+0x043C)
#define PMA_TOP_JTAG_TRST0                          (PMA_TOP_BASE+0x0440)
#define PMA_TOP_JTAG_TRST1                          (PMA_TOP_BASE+0x0444)
#define PMA_TOP_JTAG_TRST2                          (PMA_TOP_BASE+0x0448)
#define PMA_TOP_JTAG_TRST3                          (PMA_TOP_BASE+0x044C)
#define PMA_TOP_JTAG_TDO0                           (PMA_TOP_BASE+0x0450)
#define PMA_TOP_JTAG_TDO1                           (PMA_TOP_BASE+0x0454)
#define PMA_TOP_JTAG_TDO2                           (PMA_TOP_BASE+0x0458)
#define PMA_TOP_JTAG_TDO3                           (PMA_TOP_BASE+0x045C)
#define PMA_TOP_BGPOR_TOP_0                         (PMA_TOP_BASE+0x0500)
#define PMA_TOP_BGPOR_TOP_1                         (PMA_TOP_BASE+0x0504)
#define PMA_TOP_BGPOR_TOP_2                         (PMA_TOP_BASE+0x0508)
#define PMA_TOP_BGPOR_TOP_3                         (PMA_TOP_BASE+0x050C)
#define PMA_TOP_DLY_CHAIN_PHYD_TX_CLK_0             (PMA_TOP_BASE+0x0510)
#define PMA_TOP_DLY_CHAIN_PHYD_TX_CLK_1             (PMA_TOP_BASE+0x0514)
#define PMA_TOP_TRAN_BURST_EN_RD_1                  (PMA_TOP_BASE+0x0518)
#define PMA_TOP_TRAN_TX_FAULT_RD_1                  (PMA_TOP_BASE+0x051C)
#define PMA_TOP_TRAN_TX_SD_RD_1                     (PMA_TOP_BASE+0x0520)
#define PMA_TOP_TRAN_RX_SD_RD_1                     (PMA_TOP_BASE+0x0524)
#define PMA_TOP_I2C_SDA_RD_1                        (PMA_TOP_BASE+0x0528)
#define PMA_TOP_I2C_SCL_RD_1                        (PMA_TOP_BASE+0x052C)
#define PMA_TOP_PON_DGINP_RD_1                      (PMA_TOP_BASE+0x0530)
#define PMA_TOP_TX_DATA_NEG_VLD_0                   (PMA_TOP_BASE+0x0534)
#define PMA_TOP_TX_DATA_NEG_VLD_1                   (PMA_TOP_BASE+0x0538)
#define PMA_TOP_TX_DATA_NEG_VLD_2                   (PMA_TOP_BASE+0x053C)
#define PMA_TOP_TX_DATA_NEG_VLD_3                   (PMA_TOP_BASE+0x0540)
#define PMA_TOP_ADD_MD32_PM_CFG                     (PMA_TOP_BASE+0x0600)
#define PMA_TOP_ADD_MD32_PM_ADDR                    (PMA_TOP_BASE+0x0604)
#define PMA_TOP_ADD_MD32_PM_DATA                    (PMA_TOP_BASE+0x0608)
#define PMA_TOP_ADD_MD32_DM_CFG                     (PMA_TOP_BASE+0x060C)
#define PMA_TOP_ADD_MD32_DM_ADDR                    (PMA_TOP_BASE+0x0610)
#define PMA_TOP_ADD_MD32_DM_DATA                    (PMA_TOP_BASE+0x0614)
#define PMA_TOP_ADD_MD32_EN                         (PMA_TOP_BASE+0x0618)
#define PMA_TOP_ADD_DMEM_ADDR                       (PMA_TOP_BASE+0x061C)
#define PMA_TOP_ADD_R2T_MODE_0                      (PMA_TOP_BASE+0x0620)
#define PMA_TOP_ADD_R2T_MODE_1                      (PMA_TOP_BASE+0x0624)
#define PMA_TOP_ADD_R2T_MODE_2                      (PMA_TOP_BASE+0x0628)
#define PMA_TOP_XPON_TX_RAWDATA_ADDR                (PMA_TOP_BASE+0x0630)
#define PMA_TOP_XPON_TX_RAWDATA_DATA                (PMA_TOP_BASE+0x0634)
#define PMA_TOP_XPON_RX_RAWDATA_ADDR                (PMA_TOP_BASE+0x0638)
#define PMA_TOP_XPON_RX_RAWDATA_DATA                (PMA_TOP_BASE+0x063C)
#define PMA_TOP_XPON_R2T_MODE_EN                    (PMA_TOP_BASE+0x0640)
#define PMA_TOP_TX_PAR_PROBE_PLL_CTRL               (PMA_TOP_BASE+0x0644)
#define PMA_TOP_DUMP_RX_PCSRST_CTRL                 (PMA_TOP_BASE+0x0648)
#define PMA_TOP_RESERVE_2                           (PMA_TOP_BASE+0x064C)
#define PMA_TOP_TX_ASIC_FF_CTRL                     (PMA_TOP_BASE+0x0650)
#define PMA_TOP_add_top_reserve_4                   (PMA_TOP_BASE+0x0654)
#define PMA_TOP_add_BIAS_TUNE_0                     (PMA_TOP_BASE+0x0658)
#define PMA_TOP_add_XPON_TX_AFIFO_0                 (PMA_TOP_BASE+0x0660)
#define PMA_TOP_TX_AFIFO_1                          (PMA_TOP_BASE+0x0664)
#define PMA_TOP_SW_RST_0                            (PMA_TOP_BASE+0x0668)
#define PMA_TOP_PARITY_CHK                          (PMA_TOP_BASE+0x0670)
#define PMA_TOP_XPON_TX_FIFO_STS                    (PMA_TOP_BASE+0x0678)
#define PMA_TOP_XFI_TX_FIFO_STS                     (PMA_TOP_BASE+0x067C)
#define PMA_TOP_TRAN_TX_DIS_0                       (PMA_TOP_BASE+0x0680)
#define PMA_TOP_TRAN_TX_DIS_1                       (PMA_TOP_BASE+0x0684)
#define PMA_TOP_TRAN_TX_DIS_2                       (PMA_TOP_BASE+0x0688)
#define PMA_TOP_TRAN_TX_DIS_3                       (PMA_TOP_BASE+0x068C)
#define PMA_TOP_TRAN_RX_DIS_0                       (PMA_TOP_BASE+0x0690)
#define PMA_TOP_TRAN_RX_DIS_1                       (PMA_TOP_BASE+0x0694)
#define PMA_TOP_TRAN_RX_DIS_2                       (PMA_TOP_BASE+0x0698)
#define PMA_TOP_TRAN_RX_DIS_3                       (PMA_TOP_BASE+0x069C)
#define PMA_TOP_TRAN_TX_DIS_RD_1                    (PMA_TOP_BASE+0x06A0)
#define PMA_TOP_TRAN_RX_DIS_RD_1                    (PMA_TOP_BASE+0x06A4)
#define PMA_TOP_MD32_IREQ_SELECT                    (PMA_TOP_BASE+0x0700)
#define PMA_TOP_PMA_INTERFACE_SELECT                (PMA_TOP_BASE+0x0704)
#define PMA_TOP_XFI_TX_AFIFO_0                      (PMA_TOP_BASE+0x0708)
#define PMA_TOP_XFI_TX_RAWDATA_ADDR                 (PMA_TOP_BASE+0x070C)
#define PMA_TOP_XFI_TX_RAWDATA_DATA                 (PMA_TOP_BASE+0x0710)
#define PMA_TOP_XFI_RX_RAWDATA_ADDR                 (PMA_TOP_BASE+0x0714)
#define PMA_TOP_XFI_RX_RAWDATA_DATA                 (PMA_TOP_BASE+0x0718)
#define PMA_TOP_XFI_R2T_MODE_EN                     (PMA_TOP_BASE+0x071C)
#define PMA_TOP_TRAN_TRX_CNTRL                      (PMA_TOP_BASE+0x0720)
#define PMA_TOP_rg_xfi_tx_rx_mode                   (PMA_TOP_BASE+0x0724)
#define PMA_TOP_XPON_PLL_STB_CNT                    (PMA_TOP_BASE+0x0728)
#define PMA_TOP_XPON_PLL_STOP_CNT                   (PMA_TOP_BASE+0x072C)
#define PMA_TOP_XFI_PLL_STB_CNT                     (PMA_TOP_BASE+0x0730)
#define PMA_TOP_XFI_PLL_STOP_CNT                    (PMA_TOP_BASE+0x0734)
#define PMA_TOP_GPIO_MUX_CTRL                       (PMA_TOP_BASE+0x0738)
#define PMA_TOP_RAWDATA_DUMP_SEL                    (PMA_TOP_BASE+0x073C)

//After A60972 daughter board rework, TX Disable and Enable revert
#define PMA_TOP_TRAN_TRX_CNTRL_TX_DIS				(0)  // (1<<8)
#define PMA_TOP_TRAN_TRX_CNTRL_TX_EN 				(1<<8)  // (0)


/* ===================== A60972 XPON Register ===================== */


#define XPON_PMA_RG_XPON_CMN_EN_0                    (XPON_PMA_BASE+0x1100)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0             (XPON_PMA_BASE+0x1104)
#define XPON_PMA_RG_XPON_RX_MPXSEL_0                 (XPON_PMA_BASE+0x1108)
#define XPON_PMA_RG_XPON_RX_REV_0_0                  (XPON_PMA_BASE+0x110c)
#define XPON_PMA_RG_XPON_RX_PHYCK_DIV_0              (XPON_PMA_BASE+0x1110)
#define XPON_PMA_RG_XPON_CDR_PD_PICAL_CKD8_INV_0     (XPON_PMA_BASE+0x1114)
#define XPON_PMA_RG_XPON_CDR_LPF_MJV_EN_0            (XPON_PMA_BASE+0x1118)
#define XPON_PMA_RG_XPON_CDR_LPF_SETVALUE_0          (XPON_PMA_BASE+0x111c)
#define XPON_PMA_RG_XPON_CDR_PR_INJ_FORCE_OFF_0      (XPON_PMA_BASE+0x1120)
#define XPON_PMA_RG_XPON_CDR_PR_CKREF_DIV_0          (XPON_PMA_BASE+0x1124)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0           (XPON_PMA_BASE+0x1128)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0         (XPON_PMA_BASE+0x112c)
#define XPON_PMA_RG_XPON_PLL_IC_0                    (XPON_PMA_BASE+0x1130)
#define XPON_PMA_RG_XPON_PLL_TCLVAR_BIAS_0           (XPON_PMA_BASE+0x1134)
#define XPON_PMA_RG_XPON_PLL_SDM_ORD_0               (XPON_PMA_BASE+0x1138)
#define XPON_PMA_RG_XPON_PLL_RESERVE0_0              (XPON_PMA_BASE+0x113c)
#define XPON_PMA_RGS_XPON_PLL_AUTOK_BAND_0           (XPON_PMA_BASE+0x1140)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0          (XPON_PMA_BASE+0x1144)
#define XPON_PMA_RG_XPON_TX_EN_0                     (XPON_PMA_BASE+0x1148)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0              (XPON_PMA_BASE+0x114c)
#define XPON_PMA_RG_XPON_TX_RESERVED_0               (XPON_PMA_BASE+0x1150)
#define XPON_PMA_SS_TX_DA_1                          (XPON_PMA_BASE+0x1170)
#define XPON_PMA_SS_LCPLL_PWCTL_SETTING_0            (XPON_PMA_BASE+0x1200)
#define XPON_PMA_SS_LCPLL_PWCTL_SETTING_1            (XPON_PMA_BASE+0x1204)
#define XPON_PMA_SS_LCPLL_PWCTL_SETTING_2            (XPON_PMA_BASE+0x1208)
#define XPON_PMA_SS_LCPLL_PWCTL_DBG_SETTING          (XPON_PMA_BASE+0x120c)
#define XPON_PMA_SS_LCPLL_TDC_PW_0                   (XPON_PMA_BASE+0x1210)
#define XPON_PMA_SS_LCPLL_TDC_PW_1                   (XPON_PMA_BASE+0x1214)
#define XPON_PMA_SS_LCPLL_TDC_PW_2                   (XPON_PMA_BASE+0x1218)
#define XPON_PMA_SS_LCPLL_TDC_PW_3                   (XPON_PMA_BASE+0x121c)
#define XPON_PMA_SS_LCPLL_TDC_PW_4                   (XPON_PMA_BASE+0x1220)
#define XPON_PMA_SS_LCPLL_TDC_PW_5                   (XPON_PMA_BASE+0x1224)
#define XPON_PMA_SS_LCPLL_TDC_FLT_0                  (XPON_PMA_BASE+0x1228)
#define XPON_PMA_SS_LCPLL_TDC_FLT_1                  (XPON_PMA_BASE+0x122c)
#define XPON_PMA_SS_LCPLL_TDC_FLT_2                  (XPON_PMA_BASE+0x1230)
#define XPON_PMA_SS_LCPLL_TDC_FLT_3                  (XPON_PMA_BASE+0x1234)
#define XPON_PMA_SS_LCPLL_TDC_FLT_4                  (XPON_PMA_BASE+0x1238)
#define XPON_PMA_SS_LCPLL_TDC_FLT_5                  (XPON_PMA_BASE+0x123c)
#define XPON_PMA_SS_LCPLL_TDC_FLT_6                  (XPON_PMA_BASE+0x1240)
#define XPON_PMA_SS_LCPLL_TDC_FLT_7                  (XPON_PMA_BASE+0x1244)
#define XPON_PMA_SS_LCPLL_TDC_PCW_1                  (XPON_PMA_BASE+0x1248)
#define XPON_PMA_SS_LCPLL_TDC_PCW_2                  (XPON_PMA_BASE+0x124c)
#define XPON_PMA_SS_LCPLL_TDC_RO_1                   (XPON_PMA_BASE+0x1250)
#define XPON_PMA_SS_LCPLL_TDC_RO_2                   (XPON_PMA_BASE+0x1254)
#define XPON_PMA_SS_LCPLL_TDC_RO_3                   (XPON_PMA_BASE+0x1258)
#define XPON_PMA_SS_LCPLL_TDC_RO_4                   (XPON_PMA_BASE+0x125c)
#define XPON_PMA_SS_LCPLL_TDC_RO_5                   (XPON_PMA_BASE+0x1260)
#define XPON_PMA_SS_LCPLL_TDC_CTRL_0                 (XPON_PMA_BASE+0x1264)
#define XPON_PMA_RX_EYE_TOP_EYEINDEX_CTRL_0          (XPON_PMA_BASE+0x1300)
#define XPON_PMA_RX_EYE_TOP_EYEINDEX_CTRL_1          (XPON_PMA_BASE+0x1304)
#define XPON_PMA_RX_EYE_TOP_EYEINDEX_CTRL_2          (XPON_PMA_BASE+0x1308)
#define XPON_PMA_RX_EYE_TOP_EYEINDEX_CTRL_3          (XPON_PMA_BASE+0x130C)
#define XPON_PMA_RX_EYE_TOP_EYEOPENING_CTRL_0        (XPON_PMA_BASE+0x1320)
#define XPON_PMA_RX_EYE_TOP_EYEOPENING_CTRL_1        (XPON_PMA_BASE+0x1324)
#define XPON_PMA_RX_EYE_TOP_EYECNT_CTRL_0            (XPON_PMA_BASE+0x1330)
#define XPON_PMA_RX_EYE_TOP_EYECNT_CTRL_1            (XPON_PMA_BASE+0x1334)
#define XPON_PMA_RX_EYE_TOP_EYECNT_CTRL_2            (XPON_PMA_BASE+0x1338)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_0             (XPON_PMA_BASE+0x1340)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_1             (XPON_PMA_BASE+0x1344)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_2             (XPON_PMA_BASE+0x1348)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_3             (XPON_PMA_BASE+0x134C)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_4             (XPON_PMA_BASE+0x1350)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_5             (XPON_PMA_BASE+0x1354)
#define XPON_PMA_RX_CTRL_SEQUENCE_CTRL_6             (XPON_PMA_BASE+0x1358)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_0        (XPON_PMA_BASE+0x135C)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1        (XPON_PMA_BASE+0x1360)
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_0       (XPON_PMA_BASE+0x1364)
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1       (XPON_PMA_BASE+0x1368)
#define XPON_PMA_PHY_EQ_CTRL_0                       (XPON_PMA_BASE+0x1370)
#define XPON_PMA_PHY_EQ_CTRL_1                       (XPON_PMA_BASE+0x1374)
#define XPON_PMA_PHY_EQ_CTRL_2                       (XPON_PMA_BASE+0x1378)
#define XPON_PMA_PHY_EQ_CTRL_3                       (XPON_PMA_BASE+0x137C)
#define XPON_PMA_PHY_EQ_CTRL_4                       (XPON_PMA_BASE+0x1380)
#define XPON_PMA_PHY_EQ_CTRL_5                       (XPON_PMA_BASE+0x1384)
#define XPON_PMA_PHY_EQ_CTRL_6                       (XPON_PMA_BASE+0x1388)
#define XPON_PMA_PHY_EQ_CTRL_7                       (XPON_PMA_BASE+0x138C)
#define XPON_PMA_PHY_EQ_CTRL_8                       (XPON_PMA_BASE+0x1390)
#define XPON_PMA_PHY_EQ_CTRL_9                       (XPON_PMA_BASE+0x1394)
#define XPON_PMA_PHY_EQ_CTRL_10                      (XPON_PMA_BASE+0x1398)
#define XPON_PMA_SS_RX_FEOS                          (XPON_PMA_BASE+0x1400)
#define XPON_PMA_SS_RX_BLWC                          (XPON_PMA_BASE+0x1410)
#define XPON_PMA_SS_RX_FREQ_DET_1                    (XPON_PMA_BASE+0x1420)
#define XPON_PMA_SS_RX_FREQ_DET_2                    (XPON_PMA_BASE+0x1424)
#define XPON_PMA_SS_RX_FREQ_DET_3                    (XPON_PMA_BASE+0x1428)
#define XPON_PMA_SS_RX_FREQ_DET_4                    (XPON_PMA_BASE+0x142C)
#define XPON_PMA_SS_RX_PI_CAL                        (XPON_PMA_BASE+0x1430)
#define XPON_PMA_SS_RX_CAL_1                         (XPON_PMA_BASE+0x1440)
#define XPON_PMA_SS_RX_CAL_2                         (XPON_PMA_BASE+0x1444)
#define XPON_PMA_SS_RX_SIGDET_0                      (XPON_PMA_BASE+0x1450)
#define XPON_PMA_SS_RX_SIGDET_1                      (XPON_PMA_BASE+0x1454)
#define XPON_PMA_SS_RX_FLL_0                         (XPON_PMA_BASE+0x1460)
#define XPON_PMA_SS_RX_FLL_1                         (XPON_PMA_BASE+0x1464)
#define XPON_PMA_SS_RX_FLL_2                         (XPON_PMA_BASE+0x1468)
#define XPON_PMA_SS_RX_FLL_3                         (XPON_PMA_BASE+0x146C)
#define XPON_PMA_SS_RX_FLL_4                         (XPON_PMA_BASE+0x1470)
#define XPON_PMA_SS_RX_FLL_5                         (XPON_PMA_BASE+0x1474)
#define XPON_PMA_SS_RX_FLL_6                         (XPON_PMA_BASE+0x1478)
#define XPON_PMA_SS_RX_FLL_7                         (XPON_PMA_BASE+0x147C)
#define XPON_PMA_SS_RX_FLL_8                         (XPON_PMA_BASE+0x1480)
#define XPON_PMA_SS_RX_FLL_9                         (XPON_PMA_BASE+0x1484)
#define XPON_PMA_SS_RX_FLL_a                         (XPON_PMA_BASE+0x1488)
#define XPON_PMA_SS_RX_FLL_b                         (XPON_PMA_BASE+0x148C)
#define XPON_PMA_RX_PDOS_CTRL_0                      (XPON_PMA_BASE+0x1490)
#define XPON_PMA_RX_RESET_0                          (XPON_PMA_BASE+0x1494)
#define XPON_PMA_RX_RESET_1                          (XPON_PMA_BASE+0x1498)
#define XPON_PMA_RX_DEBUG_0                          (XPON_PMA_BASE+0x149C)
#define XPON_PMA_BISTCTL_CONTROL                     (XPON_PMA_BASE+0x1500)
#define XPON_PMA_BISTCTL_ALIGN_PAT                   (XPON_PMA_BASE+0x1504)
#define XPON_PMA_BISTCTL_PROGRAM_PAT_0               (XPON_PMA_BASE+0x1508)
#define XPON_PMA_BISTCTL_PROGRAM_PAT_1               (XPON_PMA_BASE+0x150C)
#define XPON_PMA_BISTCTL_PROGRAM_PAT_2               (XPON_PMA_BASE+0x1510)
#define XPON_PMA_BISTCTL_PRBS_INITIAL_SEED           (XPON_PMA_BASE+0x1514)
#define XPON_PMA_BISTCTL_PRBS_EVENT                  (XPON_PMA_BASE+0x1518)
#define XPON_PMA_BISTCTL_PRBS_ERRCNT                 (XPON_PMA_BASE+0x151C)
#define XPON_PMA_BISTCTL_PRBS_FAIL_THRESHOLD         (XPON_PMA_BASE+0x1520)
#define XPON_PMA_RX_TORGS_DEBUG_0                    (XPON_PMA_BASE+0x1524)
#define XPON_PMA_RX_TORGS_DEBUG_1                    (XPON_PMA_BASE+0x1528)
#define XPON_PMA_RX_TORGS_DEBUG_2                    (XPON_PMA_BASE+0x152C)
#define XPON_PMA_RX_TORGS_DEBUG_3                    (XPON_PMA_BASE+0x1530)
#define XPON_PMA_RX_TORGS_DEBUG_4                    (XPON_PMA_BASE+0x1534)
#define XPON_PMA_RX_TORGS_DEBUG_5                    (XPON_PMA_BASE+0x1538)
#define XPON_PMA_RX_TORGS_DEBUG_6                    (XPON_PMA_BASE+0x153C)
#define XPON_PMA_RX_TORGS_DEBUG_7                    (XPON_PMA_BASE+0x1540)
#define XPON_PMA_RX_TORGS_DEBUG_8                    (XPON_PMA_BASE+0x1544)
#define XPON_PMA_RX_TORGS_DEBUG_9                    (XPON_PMA_BASE+0x1548)
#define XPON_PMA_RX_TORGS_DEBUG_10                   (XPON_PMA_BASE+0x154C)
#define XPON_PMA_SS_TX_RST_B                         (XPON_PMA_BASE+0x1550)
#define XPON_PMA_SS_TX_CALIB_0                       (XPON_PMA_BASE+0x1554)
#define XPON_PMA_SS_TX_CALIB_1                       (XPON_PMA_BASE+0x1558)
#define XPON_PMA_SS_TX_CALIB_2                       (XPON_PMA_BASE+0x155C)
#define XPON_PMA_XPON_SETTING_0                      (XPON_PMA_BASE+0x1600)
#define XPON_PMA_XPON_SETTING_1                      (XPON_PMA_BASE+0x1604)
#define XPON_PMA_XPON_SETTING_2                      (XPON_PMA_BASE+0x1608)
#define XPON_PMA_XPON_STA                            (XPON_PMA_BASE+0x160C)
#define XPON_PMA_XPON_INT_EN_0                       (XPON_PMA_BASE+0x1610)
#define XPON_PMA_XPON_INT_EN_1                       (XPON_PMA_BASE+0x1614)
#define XPON_PMA_XPON_INT_STA_CLR_0                  (XPON_PMA_BASE+0x1618)
#define XPON_PMA_XPON_INT_STA_CLR_1                  (XPON_PMA_BASE+0x161C)
#define XPON_PMA_XPON_INT_STA_0                      (XPON_PMA_BASE+0x1620)
#define XPON_PMA_XPON_INT_STA_1                      (XPON_PMA_BASE+0x1624)
#define XPON_PMA_RX_TORGS_DEBUG_11                   (XPON_PMA_BASE+0x1628)
#define XPON_PMA_RX_FORCE_MODE_0                     (XPON_PMA_BASE+0x1630)
#define XPON_PMA_RX_FORCE_MODE_1                     (XPON_PMA_BASE+0x1634)
#define XPON_PMA_RX_FORCE_MODE_2                     (XPON_PMA_BASE+0x1638)
#define XPON_PMA_RX_DISB_MODE_0                      (XPON_PMA_BASE+0x163C)
#define XPON_PMA_RX_DISB_MODE_1                      (XPON_PMA_BASE+0x1640)
#define XPON_PMA_RX_DISB_MODE_2                      (XPON_PMA_BASE+0x1644)
#define XPON_PMA_RX_FORCE_MODE_3                     (XPON_PMA_BASE+0x1648)
#define XPON_PMA_RX_FORCE_MODE_4                     (XPON_PMA_BASE+0x164C)
#define XPON_PMA_RX_FORCE_MODE_5                     (XPON_PMA_BASE+0x1650)
#define XPON_PMA_RX_FORCE_MODE_6                     (XPON_PMA_BASE+0x1654)
#define XPON_PMA_RX_DISB_MODE_3                      (XPON_PMA_BASE+0x1658)
#define XPON_PMA_RX_DISB_MODE_4                      (XPON_PMA_BASE+0x165C)
#define XPON_PMA_RX_DISB_MODE_5                      (XPON_PMA_BASE+0x1660)
#define XPON_PMA_RX_FORCE_MODE_7                     (XPON_PMA_BASE+0x1664)
#define XPON_PMA_RX_FORCE_MODE_8                     (XPON_PMA_BASE+0x1668)
#define XPON_PMA_RX_FORCE_MODE_9                     (XPON_PMA_BASE+0x166C)
#define XPON_PMA_RX_DISB_MODE_6                      (XPON_PMA_BASE+0x1670)
#define XPON_PMA_RX_DISB_MODE_7                      (XPON_PMA_BASE+0x1674)
#define XPON_PMA_RX_DISB_MODE_8                      (XPON_PMA_BASE+0x1678)
#define XPON_PMA_SS_BIST_0                           (XPON_PMA_BASE+0x1680)
#define XPON_PMA_SS_BIST_1                           (XPON_PMA_BASE+0x1684)
#define XPON_PMA_SS_BIST_2                           (XPON_PMA_BASE+0x1688)
#define XPON_PMA_SS_DA_XPON_PWDB_0                   (XPON_PMA_BASE+0x168C)
#define XPON_PMA_SS_DA_XPON_PWDB_1                   (XPON_PMA_BASE+0x1690)
#define XPON_PMA_SS_LCPLL_0                          (XPON_PMA_BASE+0x1694)
#define XPON_PMA_SS_LCPLL_1                          (XPON_PMA_BASE+0x1698)
#define XPON_PMA_SS_LCPLL_2                          (XPON_PMA_BASE+0x169C)
#define XPON_PMA_ADD_DIG_RESERVE_0                   (XPON_PMA_BASE+0x1700)
#define XPON_PMA_ADD_DIG_RESERVE_1                   (XPON_PMA_BASE+0x1704)
#define XPON_PMA_ADD_DIG_RESERVE_2                   (XPON_PMA_BASE+0x1708)
#define XPON_PMA_ADD_DIG_RESERVE_3                   (XPON_PMA_BASE+0x170C)
#define XPON_PMA_ADD_DIG_RESERVE_4                   (XPON_PMA_BASE+0x1710)
#define XPON_PMA_RG_XPON_RX_RESERVED_1               (XPON_PMA_BASE+0x1714)
#define XPON_PMA_ADD_DIG_RO_RESERVE_0                (XPON_PMA_BASE+0x1718)
#define XPON_PMA_ADD_DIG_RO_RESERVE_1                (XPON_PMA_BASE+0x171C)
#define XPON_PMA_ADD_DIG_RO_RESERVE_2                (XPON_PMA_BASE+0x1720)
#define XPON_PMA_ADD_DIG_RO_RESERVE_3                (XPON_PMA_BASE+0x1724)
#define XPON_PMA_ADD_DIG_RO_RESERVE_4                (XPON_PMA_BASE+0x1728)
#define XPON_PMA_ADD_RX_SYS_EN_SEL_0                 (XPON_PMA_BASE+0x172C)
#define XPON_PMA_PLL_TDC_FREQDET_0                   (XPON_PMA_BASE+0x1730)
#define XPON_PMA_PLL_TDC_FREQDET_1                   (XPON_PMA_BASE+0x1734)
#define XPON_PMA_PLL_TDC_FREQDET_2                   (XPON_PMA_BASE+0x1738)
#define XPON_PMA_PLL_TDC_FREQDET_3                   (XPON_PMA_BASE+0x173C)
#define XPON_PMA_DA_XPON_TX_FORCE_0                  (XPON_PMA_BASE+0x1740)
#define XPON_PMA_DA_XPON_TX_FORCE_1                  (XPON_PMA_BASE+0x1744)
#define XPON_PMA_DA_XPON_TX_FORCE_2                  (XPON_PMA_BASE+0x1748)
#define XPON_PMA_RX_FORCE_MODE_10                    (XPON_PMA_BASE+0x174C)
#define XPON_PMA_ADD_CLKPATH_RST_0                   (XPON_PMA_BASE+0x1750)
#define XPON_PMA_ADD_XPON_MODE_1                     (XPON_PMA_BASE+0x1754)
#define XPON_PMA_ADD_R2T_MODE_1                      (XPON_PMA_BASE+0x1758)
#define XPON_PMA_ADD_T2R_MODE_1                      (XPON_PMA_BASE+0x175C)
#define XPON_PMA_ADD_LCPLL_RO_1                      (XPON_PMA_BASE+0x1760)
#define XPON_PMA_ADD_RO_RX2ANA_1                     (XPON_PMA_BASE+0x1764)
#define XPON_PMA_ADD_RO_RX2ANA_2                     (XPON_PMA_BASE+0x1768)
#define XPON_PMA_ADD_RO_RX2ANA_3                     (XPON_PMA_BASE+0x176C)
#define XPON_PMA_ADD_RO_R2TMODE_1                    (XPON_PMA_BASE+0x1780)
#define XPON_PMA_RG_LCPLL_xpon_CMN_STB_CTRL_0        (XPON_PMA_BASE+0x1784)
#define XPON_PMA_RG_LCPLL_xpon_CMN_STB_CTRL_1        (XPON_PMA_BASE+0x1788)
#define XPON_PMA_RG_TX_HSDATA_EN_EXT_CNT_0           (XPON_PMA_BASE+0x178C)
#define XPON_PMA_PON_TX_COUNTER_0                    (XPON_PMA_BASE+0x1790)
#define XPON_PMA_PON_TX_COUNTER_1                    (XPON_PMA_BASE+0x1794)
#define XPON_PMA_PON_TX_COUNTER_2                    (XPON_PMA_BASE+0x1798)
#define XPON_PMA_PON_TX_COUNTER_3                    (XPON_PMA_BASE+0x179c)



//-------------- XPON BIST-------------- 

#define XPON_PMA_BISTCTL_PRBS_EVENT_BISTCTL_PRBS_DONE 		(1<<16)
#define XPON_PMA_BISTCTL_PRBS_EVENT_BISTCTL_PRBS_FAIL 		(1<<8)
#define XPON_PMA_BISTCTL_PRBS_EVENT_BISTCTL_PRBS_COMPARE 	(1)

#define XPON_PMA_DA_XPON_TX_FORCE_1_NORMAL_MODE_MASK        (0x1000000)
#define XPON_PMA_DA_XPON_TX_FORCE_2_FORCE_MODE_MASK         (0xffff0000)

#define XPON_PMA_XPON_SETTING_1_TX_SD_INV_MASK              (0xFFFFFFFE)
#define XPON_PMA_XPON_SETTING_1_TX_SD_INV_OFFSET			 0
#define XPON_PMA_XPON_SETTING_0_TX_FAULT_INV_MASK           (0xFEFFFFFF)
#define XPON_PMA_XPON_SETTING_0_TX_FAULT_INV_OFFSET			 24
#define XPON_PMA_XPON_SETTING_0_BURST_EN_INV_MASK           (0xFFFFFEFF)
#define XPON_PMA_XPON_SETTING_0_BURST_EN_INV_OFFSET			 8
#define XPON_PMA_XPON_SETTING_0_RX_SD_INV                   (1<<16)

//this bit is not used by PCS #define XPON_PMA_XPON_SETTING_0_RX_SD_INV_MASK              (0xFFFEFFFF)
//this bit is not used by PCS #define XPON_PMA_XPON_SETTING_0_RX_SD_INV_OFFSET			 16

#define XPON_PMA_TX_DLY_CTRL_BIT_DELAY_MASK                 (0xFFFEFF80) 

#define XPON_PMA_BISTCTL_CONTROL_PAT_SEL_MASK               (0xFFFFFFE0) 
#define XPON_PMA_BISTCTL_CONTROL_PAT_TX_EN_MASK             (0xFFFFFEFF) 

#define XPON_PMA_ADD_XPON_MODE_1_R2T_MODE_MASK              (0xFFFFFEFF) 
#define XPON_PMA_ADD_XPON_MODE_1_TX_BIST_MASK               (0xFFFEFFFF) 

#define XPON_PMA_MD32_MEM_CLK_CTRL_CLK_SEL_MASK             (0xFFFFFFFC) 
#define XPON_PMA_TX_DLY_CTRL_OUTBEN_DATA_MASK               (0x8FFFFFFF)

//-------------- XPON RX -------------- 

//RX SIGDET
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_SIGDET_VTH_SEL(i)		((UINT32)((i)&0x1f)<<27)	
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_50OHMS_SEL(i)		((UINT32)((i)&0x3)<<25)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_EQ_HZEN				(1<<24)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_VB_EQ1_EN			(1<<23)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_VB_EQ2_EN			(1<<22)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_VB_EQ3_EN			(1<<21)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_VCM_GEN_PWDB		(1<<20)
#define XPON_PMA_RG_XPON_RX_SIGDET_VTH_SEL_0_FE_VCM_SEL(i)			((UINT32)((i)&0x7)<<17)

//RX CDR PR Reserve
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_TDC_REF_SEL(i)			((UINT32)((i)&0x3)<<22) 
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_COR_HBW_EN				(1<<21)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_LDO_FORCE_ON				(1<<20)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_CKREF_DIV1(i)			((UINT32)((i)&0x3)<<18)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_MONPR_EN					(1<<17)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_MONPI_EN					(1<<16)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_XFICK_EN					(1<<15)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_DAC_MON(i)			((UINT32)((i)&0x1f)<<10)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_DAC_RANG(i)			((UINT32)((i)&0x3)<<8)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_DAC_RANGE_EYE(i)		((UINT32)((i)&0x3)<<6)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_SIGDET_DCTEST_EN		(1<<5)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_SIGDET_LPF_CTRL(i)	((UINT32)((i)&0x3)<<3)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_SIGDET_NOVTH			(1<<2)
#define XPON_PMA_RG_XPON_CDR_PR_RESERVE1_0_RX_SIGDET_PEAK(i)		((UINT32)((i)&0x3))



//RX CDR PWDB
#define XPON_PMA_SS_DA_XPON_PWDB_0_CDR_PD_PWDB						(1<<24)
#define XPON_PMA_SS_DA_XPON_PWDB_0_CDR_PR_PIEYE_PWDB				(1<<16)
#define XPON_PMA_SS_DA_XPON_PWDB_0_CDR_PR_PWDB						(1<<8)
#define XPON_PMA_SS_DA_XPON_PWDB_0_RX_FE_PWDB						(1)


#define XPON_PMA_SS_DA_XPON_PWDB_1_RX_SIGDET_PWDB					(1)


//RX force mode switch
#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_CDR_LPF_RSTB_NORMAL_MODE		(1<<24)
#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_CDR_LPF_RSTB_FORCE_MODE			(0<<24)

#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_CDR_LPF_LCK2DATA_NORMAL_MODE	(1<<16)
#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_CDR_LPF_LCK2DATA_FORCE_MODE		(0<<16)

#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_RX_FE_PEAKING_CTRL_NORMAL_MODE	(1<<8)
#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_RX_FE_PEAKING_CTRL_FORCE_MODE	(0<<8)

#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_RX_FE_GAIN_CTRL_NORMAL_MODE		(1)
#define XPON_PMA_RX_DISB_MODE_0_DA_XPON_RX_FE_GAIN_CTRL_FORCE_MODE		(0)


//		RX force mode set
#define XPON_PMA_RX_FORCE_MODE_0_DA_XPON_CDR_LPF_RSTB				(1<<24)
#define XPON_PMA_RX_FORCE_MODE_0_DA_XPON_CDR_LPF_LCK2DATA			(1<<16)
#define XPON_PMA_RX_FORCE_MODE_0_DA_XPON_CDR_LPF_LCK2REF			(0<<16)
#define XPON_PMA_RX_FORCE_MODE_0_DA_XPON_RX_FE_PEAKING_CTRL(i)		((UINT32)((i)&0x7)<<8)
#define XPON_PMA_RX_FORCE_MODE_0_DA_XPON_RX_FE_GAIN_CTRL(i)			((UINT32)((i)&0x3))


//RX force mode switch
#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_E0_NORMAL_MODE		(1<<24)
#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_E0_FORCE_MODE		(0<<24)

#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_D1_NORMAL_MODE		(1<<16)
#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_D1_FORCE_MODE		(0<<16)

#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_D0_NORMAL_MODE		(1<<8)
#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_DAC_D0_FORCE_MODE		(0<<8)

#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_SIGDET_OS_NORMAL_MODE	(1)
#define XPON_PMA_RX_DISB_MODE_1_DA_XPON_RX_SIGDET_OS_FORCE_MODE		(0)


//		RX force mode set
#define XPON_PMA_RX_FORCE_MODE_1_DA_XPON_RX_DAC_E0(i)				((UINT32)((i)&0x7f)<<24)
#define XPON_PMA_RX_FORCE_MODE_1_DA_XPON_RX_DAC_D1(i)				((UINT32)((i)&0x7f)<<16)
#define XPON_PMA_RX_FORCE_MODE_1_DA_XPON_RX_DAC_D0(i)				((UINT32)((i)&0x7f)<<8)
#define XPON_PMA_RX_FORCE_MODE_1_DA_XPON_RX_SIGDET_OS(i)			((UINT32)((i)&0x1f))




//RX force mode switch
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_RDY_NORMAL_MODE		(1<<24)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_RDY_FORCE_MODE			(0<<24)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_BLWC_EN_NORMAL_MODE	(1<<16)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_BLWC_EN_FORCE_MODE		(0<<16)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_OS_RDY_NORMAL_MODE		(1<<8)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_OS_RDY_FORCE_MODE		(0<<8)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_SDCAL_EN_NORMAL_MODE	(1)
#define XPON_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1_RX_SDCAL_EN_FORCE_MODE	(0)



//		RX force mode set
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1_RX_RDY			(1<<24)
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1_RX_RDY_OFF		(0<<24)

#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1_RX_BLWC_EN		(1<<16)
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1_RX_OS_RDY		(1<<8)
#define XPON_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1_RX_SDCAL_EN		(1)


//TDC filter

#define XPON_PMA_SS_LCPLL_TDC_FLT_1_TDC_GAIN(i)			((UINT32)((i)&0x7ff)<<16)
#define XPON_PMA_SS_LCPLL_TDC_FLT_1_A_TDC(i)			((UINT32)((i)&0xf)<<8)
#define XPON_PMA_SS_LCPLL_TDC_FLT_1_GPON_SEL			(1)


#define XPON_PMA_SS_LCPLL_TDC_FLT_3_TDC_SWRST			(1<<24)
#define XPON_PMA_SS_LCPLL_TDC_FLT_3_NCPO_HOLD			(1<<16)
#define XPON_PMA_SS_LCPLL_TDC_FLT_3_NCPO_LOAD			(1<<8)
#define XPON_PMA_SS_LCPLL_TDC_FLT_3_NCPO_SHIFT(i)		((UINT32)((i)&0x3))


//CLK Path
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_ACBUF_EN			(1<<31)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_DFM_DA(i)			((UINT32)((i)&0xff)<<23)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_LDO_EN				(1<<22)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_LDO_VOD_EN			(1<<21)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_TDC_AUTOEN			(1<<20)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_TDC_FT_CK_EN		(1<<19)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_TDC_MON_RXCK_EN		(1<<18)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_TDC_MON_TXCK_EN		(1<<17)
#define XPON_PMA_RG_XPON_CLKPATH_ACBUF_EN_0_TDC_SYNC_CK_SEL		(1<<16)



//TDC

#define XPON_PMA_SS_LCPLL_TDC_PW_0_DPMA_DDS1_ISO_DISABLE	(1<<24)
#define XPON_PMA_SS_LCPLL_TDC_PW_0_DPMA_DDS1_PWDB			(1<<16)
#define XPON_PMA_SS_LCPLL_TDC_PW_0_DPMA_AUTOPW_EN			(1<<8)
#define XPON_PMA_SS_LCPLL_TDC_PW_0_TDC_DIG_PWDB				(1)


#define XPON_PMA_SS_LCPLL_TDC_PW_4_SIGDET_CG			(1<<24)
#define XPON_PMA_SS_LCPLL_TDC_PW_4_EN					(1<<16)
#define XPON_PMA_SS_LCPLL_TDC_PW_4_CAL_OFFSET			(1<<8)
#define XPON_PMA_SS_LCPLL_TDC_PW_4_CAL_BW				(1)


#define XPON_PMA_SS_LCPLL_TDC_PW_5_SYNC_IN_MODE		(1<<24)
#define XPON_PMA_SS_LCPLL_TDC_PW_5_AUTOK_TDC		(1<<16)
#define XPON_PMA_SS_LCPLL_TDC_PW_5_AUTOEN			(1<<8)
#define XPON_PMA_SS_LCPLL_TDC_PW_5_EN_MUX			(1)




//-------------- XPON TX -------------- 

//XPON BENTX BIAS EN
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_BIAS_EN		(1<<31)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_DRV_EN			(1<<30)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_DRV_IBIAS(i)	((UINT32)((i)&0x3f)<<24)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_DRV_IMP(i)		((UINT32)((i)&0x3f)<<18)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_IMP_EN			(1<<17)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_PRED_EN		(1<<16)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_PRED_IBIAS(i)	((UINT32)((i)&0xf)<<12)
#define XPON_PMA_RG_XPON_BENTX_BIAS_EN_0_PRED_IMP_SMALL	(1<<11)


//XPON TX en
#define XPON_PMA_RG_XPON_TX_EN_0_TX_EN 				(1<<31)
#define XPON_PMA_RG_XPON_TX_EN_0_SER_LOADSEL_T9		(0<<29)
#define XPON_PMA_RG_XPON_TX_EN_0_SER_LOADSEL_T8		(1<<29)
#define XPON_PMA_RG_XPON_TX_EN_0_SER_LOADSEL_T7		(2<<29)
#define XPON_PMA_RG_XPON_TX_EN_0_SER_LOADSEL_T6		(3<<29)
#define XPON_PMA_RG_XPON_TX_EN_0_DIGFF_CK_INV		(1<<28)
#define XPON_PMA_RG_XPON_TX_EN_0_FIR_CN1(i)			((UINT32)((i)&0xf)<<24)
#define XPON_PMA_RG_XPON_TX_EN_0_FIR_INV_C0(i)		((UINT32)((i)&0x1f)<<19)
#define XPON_PMA_RG_XPON_TX_EN_0_FIR_C1(i)			((UINT32)((i)&0x1f)<<14)
#define XPON_PMA_RG_XPON_TX_EN_0_FIR_C2(i)			((UINT32)((i)&0x7)<<11)
#define XPON_PMA_RG_XPON_TX_EN_0_FORCE_CX			(1<<10)
#define XPON_PMA_RG_XPON_TX_EN_0_SR_CTRL(i)			((UINT32)((i)&0xf)<<6)
#define XPON_PMA_RG_XPON_TX_EN_0_LPEIDLE_EN 		(1<<5)
#define XPON_PMA_RG_XPON_TX_EN_0_CKMON_CDR5G_EN		(1<<4)
#define XPON_PMA_RG_XPON_TX_EN_0_CKMON_EN			(1<<3)
#define XPON_PMA_RG_XPON_TX_EN_0_CKMON_SEL(i)		((i)&0x7)


//XPON TX LSDATA_EN 
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_LSDATA_EN		(1<<31)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_LSDATA			(1<<30)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_FIR_CN1_INV		(1<<29)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_FIR_C0_INV		(1<<28)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_FIR_C1_INV		(1<<27)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_FIR_C2_INV		(1<<26)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_MPX_OP_EN		(1<<25)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_MPX_OP_BYPASS	(1<<24)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_MPX_SEL(i)		((UINT32)((i)&0x1f)<<19)
#define XPON_PMA_RG_XPON_TX_LSDATA_EN_0_TXLBRX_EN		(1<<17)


//XPON TX RESERVED
#define XPON_PMA_RG_XPON_TX_RESERVED_0_CKLDO_VOD_EN			(1<15)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_FIRLDO_VOD_EN		(1<14) 
#define XPON_PMA_RG_XPON_TX_RESERVED_0_INT_LPBK_EN			(1<13)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_CKSEL(i)				((UINT32)((i)&0x7)<<10)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_CALI_VREF_H(i)		((UINT32)((i)&0x3)<<8)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_CALI_VREF_L(i)		((UINT32)((i)&0x3)<<6)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_TX_RATE_CTRL_8bit	(0<<4)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_TX_RATE_CTRL_10bit	(1<<4)
#define XPON_PMA_RG_XPON_TX_RESERVED_0_TX_RATE_CTRL_16bit	(2<<4)

//XPON_PMA_SS_TX_RST_B
#define XPON_PMA_SS_TX_RST_B_CALIB_RST_B					(1<<8)
#define XPON_PMA_SS_TX_RST_B_TOP_RST_B						(1)


//XPON_PMA_SS_TX_CALIB_0
#define XPON_PMA_SS_TX_CALIB_0_CALIB_P_EN					(1)


//XPON_PMA_SS_TX_CALIB_1
#define XPON_PMA_SS_TX_CALIB_1_CALIB_N_EN					(1)

//XPON_PMA_ADD_RO_RX2ANA_3
#define XPON_PMA_ADD_RO_RX2ANA_3_FIFO_FULL_CNT_MASK         (0xf)
#define XPON_PMA_ADD_RO_RX2ANA_3_FIFO_FULL_CNT_OFFSET       (16)

#define XPON_PMA_ADD_RO_RX2ANA_3_FIFO_EMPTY_CNT_MASK        (0xf)
#define XPON_PMA_ADD_RO_RX2ANA_3_FIFO_EMPTY_CNT_OFFSET      (8)

#define XPON_PMA_ADD_RO_RX2ANA_3_PI_CAL_DATA_OUT_MASK       (0x7f)
#define XPON_PMA_ADD_RO_RX2ANA_3_PI_CAL_DATA_OUT_OFFSET     (0)

#define XPON_PMA_ADD_LCPLL_RO_1_RO_PLL_FBCK_LOCK2_MASK		(0x10000)

// pma_optimize_value
#define XPON_PMA_OPT_DEFAULT_VALUE_LOW_RATE			(0xc0000420)
#define XPON_PMA_OPT_DEFAULT_VALUE_HIGH_RATE		(0xC11A5C20)	// for en7580 REF board only

/* ===================== A60972 XFI Register ===================== */
#define XFI_PMA_RG_XFI_XTALCK_CGM_EN_0              (XFI_PMA_BASE+0x2000)
#define XFI_PMA_RG_JCPLL_IC_0                       (XFI_PMA_BASE+0x2004)
#define XFI_PMA_RG_JCPLL_TCLVAR_BIAS_0              (XFI_PMA_BASE+0x2008)
#define XFI_PMA_RG_JCPLL_SDM_ORD_0                  (XFI_PMA_BASE+0x200c)
#define XFI_PMA_RG_JCPLL_RESERVE0_0                 (XFI_PMA_BASE+0x2010)
#define XFI_PMA_RGS_JCPLL_AUTOK_BAND_0              (XFI_PMA_BASE+0x2014)
#define XFI_PMA_RG_XFI_CMN_CUREN_0                  (XFI_PMA_BASE+0x2018)
#define XFI_PMA_RG_XFI_CLKPATH_LDO_EN_0             (XFI_PMA_BASE+0x201c)
#define XFI_PMA_RG_XFI_TOP_REV_0_0                  (XFI_PMA_BASE+0x2020)
#define XFI_PMA_RG_XFI_RX_MPXSEL_0                  (XFI_PMA_BASE+0x2024)
#define XFI_PMA_RG_XFI_RX_REV_0_0                   (XFI_PMA_BASE+0x2028)
#define XFI_PMA_RG_XFI_RX_PHYCK_DIV_0               (XFI_PMA_BASE+0x202c)
#define XFI_PMA_RG_XFI_CDR_LPF_KI_GAIN_0            (XFI_PMA_BASE+0x2030)
#define XFI_PMA_RG_XFI_CDR_LPF_TOP_LIM_0            (XFI_PMA_BASE+0x2034)
#define XFI_PMA_RG_XFI_CDR_LPF_SETVALUE_0           (XFI_PMA_BASE+0x2038)
#define XFI_PMA_RG_XFI_CDR_PR_INJ_FORCE_OFF_0       (XFI_PMA_BASE+0x203c)
#define XFI_PMA_RG_XFI_CDR_PR_CKREF_DIV_0           (XFI_PMA_BASE+0x2040)
#define XFI_PMA_RG_XFI_CDR_PR_RESERVE0_0            (XFI_PMA_BASE+0x2044)
#define XFI_PMA_RG_XFI_RX_DAC_RANGE_EYE_0           (XFI_PMA_BASE+0x2048)
#define XFI_PMA_RG_XFI_TXPLL1_IPATH_LOAD_KBAND_EN_0 (XFI_PMA_BASE+0x204c)
#define XFI_PMA_RG_XFI_TXPLL1_BR_0                  (XFI_PMA_BASE+0x2050)
#define XFI_PMA_RG_XFI_TXPLL1_DAC_BAND_0            (XFI_PMA_BASE+0x2054)
#define XFI_PMA_RG_XFI_TXPLL1_DDS_MONEN_0           (XFI_PMA_BASE+0x2058)
#define XFI_PMA_RG_XFI_TXPLL1_DDS_SSC_DELTA_0       (XFI_PMA_BASE+0x205c)
#define XFI_PMA_RG_XFI_TXPLL1_DDS_SSC_EN_0          (XFI_PMA_BASE+0x2060)
#define XFI_PMA_RGS_XFI_TXPLL1_SDM_TD_0             (XFI_PMA_BASE+0x2064)
#define XFI_PMA_RG_XFI_TX_EN_0                      (XFI_PMA_BASE+0x2068)
#define XFI_PMA_RG_XFI_TX_LSDATA_EN_0               (XFI_PMA_BASE+0x206c)
#define XFI_PMA_RG_XFI_TX_RESERVED_0                (XFI_PMA_BASE+0x2070)
#define XFI_PMA_SS_TX_DA_1                          (XFI_PMA_BASE+0x2170)
#define XFI_PMA_SS_LCPLL_PWCTL_SETTING_0            (XFI_PMA_BASE+0x2200)
#define XFI_PMA_SS_LCPLL_PWCTL_SETTING_1            (XFI_PMA_BASE+0x2204)
#define XFI_PMA_SS_LCPLL_PWCTL_SETTING_2            (XFI_PMA_BASE+0x2208)
#define XFI_PMA_SS_LCPLL_PWCTL_DBG_SETTING          (XFI_PMA_BASE+0x220c)
#define XFI_PMA_SS_LCPLL_TDC_PW_0                   (XFI_PMA_BASE+0x2210)
#define XFI_PMA_SS_LCPLL_TDC_PW_1                   (XFI_PMA_BASE+0x2214)
#define XFI_PMA_SS_LCPLL_TDC_PW_2                   (XFI_PMA_BASE+0x2218)
#define XFI_PMA_SS_LCPLL_TDC_PW_3                   (XFI_PMA_BASE+0x221c)
#define XFI_PMA_SS_LCPLL_TDC_PW_4                   (XFI_PMA_BASE+0x2220)
#define XFI_PMA_SS_LCPLL_TDC_PW_5                   (XFI_PMA_BASE+0x2224)
#define XFI_PMA_SS_LCPLL_TDC_FLT_0                  (XFI_PMA_BASE+0x2228)
#define XFI_PMA_SS_LCPLL_TDC_FLT_1                  (XFI_PMA_BASE+0x222c)
#define XFI_PMA_SS_LCPLL_TDC_FLT_2                  (XFI_PMA_BASE+0x2230)
#define XFI_PMA_SS_LCPLL_TDC_FLT_3                  (XFI_PMA_BASE+0x2234)
#define XFI_PMA_SS_LCPLL_TDC_FLT_4                  (XFI_PMA_BASE+0x2238)
#define XFI_PMA_SS_LCPLL_TDC_FLT_5                  (XFI_PMA_BASE+0x223c)
#define XFI_PMA_SS_LCPLL_TDC_FLT_6                  (XFI_PMA_BASE+0x2240)
#define XFI_PMA_SS_LCPLL_TDC_FLT_7                  (XFI_PMA_BASE+0x2244)
#define XFI_PMA_SS_LCPLL_TDC_PCW_1                  (XFI_PMA_BASE+0x2248)
#define XFI_PMA_SS_LCPLL_TDC_PCW_2                  (XFI_PMA_BASE+0x224c)
#define XFI_PMA_SS_LCPLL_TDC_RO_1                   (XFI_PMA_BASE+0x2250)
#define XFI_PMA_SS_LCPLL_TDC_RO_2                   (XFI_PMA_BASE+0x2254)
#define XFI_PMA_SS_LCPLL_TDC_RO_3                   (XFI_PMA_BASE+0x2258)
#define XFI_PMA_SS_LCPLL_TDC_RO_4                   (XFI_PMA_BASE+0x225c)
#define XFI_PMA_SS_LCPLL_TDC_RO_5                   (XFI_PMA_BASE+0x2260)
#define XFI_PMA_SS_LCPLL_TDC_CTRL_0                 (XFI_PMA_BASE+0x2264)
#define XFI_PMA_RX_EYE_TOP_EYEINDEX_CTRL_0          (XFI_PMA_BASE+0x2300)
#define XFI_PMA_RX_EYE_TOP_EYEINDEX_CTRL_1          (XFI_PMA_BASE+0x2304)
#define XFI_PMA_RX_EYE_TOP_EYEINDEX_CTRL_2          (XFI_PMA_BASE+0x2308)
#define XFI_PMA_RX_EYE_TOP_EYEINDEX_CTRL_3          (XFI_PMA_BASE+0x230C)
#define XFI_PMA_RX_EYE_TOP_EYEOPENING_CTRL_0        (XFI_PMA_BASE+0x2320)
#define XFI_PMA_RX_EYE_TOP_EYEOPENING_CTRL_1        (XFI_PMA_BASE+0x2324)
#define XFI_PMA_RX_EYE_TOP_EYECNT_CTRL_0            (XFI_PMA_BASE+0x2330)
#define XFI_PMA_RX_EYE_TOP_EYECNT_CTRL_1            (XFI_PMA_BASE+0x2334)
#define XFI_PMA_RX_EYE_TOP_EYECNT_CTRL_2            (XFI_PMA_BASE+0x2338)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_0             (XFI_PMA_BASE+0x2340)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_1             (XFI_PMA_BASE+0x2344)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_2             (XFI_PMA_BASE+0x2348)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_3             (XFI_PMA_BASE+0x234C)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_4             (XFI_PMA_BASE+0x2350)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_5             (XFI_PMA_BASE+0x2354)
#define XFI_PMA_RX_CTRL_SEQUENCE_CTRL_6             (XFI_PMA_BASE+0x2358)
#define XFI_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_0        (XFI_PMA_BASE+0x235C)
#define XFI_PMA_RX_CTRL_SEQUENCE_DISB_CTRL_1        (XFI_PMA_BASE+0x2360)
#define XFI_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_0       (XFI_PMA_BASE+0x2364)
#define XFI_PMA_RX_CTRL_SEQUENCE_FORCE_CTRL_1       (XFI_PMA_BASE+0x2368)
#define XFI_PMA_PHY_EQ_CTRL_0                       (XFI_PMA_BASE+0x2370)
#define XFI_PMA_PHY_EQ_CTRL_1                       (XFI_PMA_BASE+0x2374)
#define XFI_PMA_PHY_EQ_CTRL_2                       (XFI_PMA_BASE+0x2378)
#define XFI_PMA_PHY_EQ_CTRL_3                       (XFI_PMA_BASE+0x237C)
#define XFI_PMA_PHY_EQ_CTRL_4                       (XFI_PMA_BASE+0x2380)
#define XFI_PMA_PHY_EQ_CTRL_5                       (XFI_PMA_BASE+0x2384)
#define XFI_PMA_PHY_EQ_CTRL_6                       (XFI_PMA_BASE+0x2388)
#define XFI_PMA_PHY_EQ_CTRL_7                       (XFI_PMA_BASE+0x238C)
#define XFI_PMA_PHY_EQ_CTRL_8                       (XFI_PMA_BASE+0x2390)
#define XFI_PMA_PHY_EQ_CTRL_9                       (XFI_PMA_BASE+0x2394)
#define XFI_PMA_PHY_EQ_CTRL_10                      (XFI_PMA_BASE+0x2398)
#define XFI_PMA_SS_RX_FEOS                          (XFI_PMA_BASE+0x2400)
#define XFI_PMA_SS_RX_BLWC                          (XFI_PMA_BASE+0x2410)
#define XFI_PMA_SS_RX_FREQ_DET_1                    (XFI_PMA_BASE+0x2420)
#define XFI_PMA_SS_RX_FREQ_DET_2                    (XFI_PMA_BASE+0x2424)
#define XFI_PMA_SS_RX_FREQ_DET_3                    (XFI_PMA_BASE+0x2428)
#define XFI_PMA_SS_RX_FREQ_DET_4                    (XFI_PMA_BASE+0x242C)
#define XFI_PMA_SS_RX_PI_CAL                        (XFI_PMA_BASE+0x2430)
#define XFI_PMA_SS_RX_CAL_1                         (XFI_PMA_BASE+0x2440)
#define XFI_PMA_SS_RX_CAL_2                         (XFI_PMA_BASE+0x2444)
#define XFI_PMA_SS_RX_SIGDET_0                      (XFI_PMA_BASE+0x2450)
#define XFI_PMA_SS_RX_SIGDET_1                      (XFI_PMA_BASE+0x2454)
#define XFI_PMA_SS_RX_FLL_0                         (XFI_PMA_BASE+0x2460)
#define XFI_PMA_SS_RX_FLL_1                         (XFI_PMA_BASE+0x2464)
#define XFI_PMA_SS_RX_FLL_2                         (XFI_PMA_BASE+0x2468)
#define XFI_PMA_SS_RX_FLL_3                         (XFI_PMA_BASE+0x246C)
#define XFI_PMA_SS_RX_FLL_4                         (XFI_PMA_BASE+0x2470)
#define XFI_PMA_SS_RX_FLL_5                         (XFI_PMA_BASE+0x2474)
#define XFI_PMA_SS_RX_FLL_6                         (XFI_PMA_BASE+0x2478)
#define XFI_PMA_SS_RX_FLL_7                         (XFI_PMA_BASE+0x247C)
#define XFI_PMA_SS_RX_FLL_8                         (XFI_PMA_BASE+0x2480)
#define XFI_PMA_SS_RX_FLL_9                         (XFI_PMA_BASE+0x2484)
#define XFI_PMA_SS_RX_FLL_a                         (XFI_PMA_BASE+0x2488)
#define XFI_PMA_SS_RX_FLL_b                         (XFI_PMA_BASE+0x248C)
#define XFI_PMA_RX_PDOS_CTRL_0                      (XFI_PMA_BASE+0x2490)
#define XFI_PMA_RX_RESET_0                          (XFI_PMA_BASE+0x2494)
#define XFI_PMA_RX_RESET_1                          (XFI_PMA_BASE+0x2498)
#define XFI_PMA_RX_DEBUG_0                          (XFI_PMA_BASE+0x249C)
#define XFI_PMA_BISTCTL_CONTROL                     (XFI_PMA_BASE+0x2500)
#define XFI_PMA_BISTCTL_ALIGN_PAT                   (XFI_PMA_BASE+0x2504)
#define XFI_PMA_BISTCTL_PROGRAM_PAT_0               (XFI_PMA_BASE+0x2508)
#define XFI_PMA_BISTCTL_PROGRAM_PAT_1               (XFI_PMA_BASE+0x250C)
#define XFI_PMA_BISTCTL_PROGRAM_PAT_2               (XFI_PMA_BASE+0x2510)
#define XFI_PMA_BISTCTL_PRBS_INITIAL_SEED           (XFI_PMA_BASE+0x2514)
#define XFI_PMA_BISTCTL_PRBS_EVENT                  (XFI_PMA_BASE+0x2518)
#define XFI_PMA_BISTCTL_PRBS_ERRCNT                 (XFI_PMA_BASE+0x251C)
#define XFI_PMA_BISTCTL_PRBS_FAIL_THRESHOLD         (XFI_PMA_BASE+0x2520)
#define XFI_PMA_RX_TORGS_DEBUG_0                    (XFI_PMA_BASE+0x2524)
#define XFI_PMA_RX_TORGS_DEBUG_1                    (XFI_PMA_BASE+0x2528)
#define XFI_PMA_RX_TORGS_DEBUG_2                    (XFI_PMA_BASE+0x252C)
#define XFI_PMA_RX_TORGS_DEBUG_3                    (XFI_PMA_BASE+0x2530)
#define XFI_PMA_RX_TORGS_DEBUG_4                    (XFI_PMA_BASE+0x2534)
#define XFI_PMA_RX_TORGS_DEBUG_5                    (XFI_PMA_BASE+0x2538)
#define XFI_PMA_RX_TORGS_DEBUG_6                    (XFI_PMA_BASE+0x253C)
#define XFI_PMA_RX_TORGS_DEBUG_7                    (XFI_PMA_BASE+0x2540)
#define XFI_PMA_RX_TORGS_DEBUG_8                    (XFI_PMA_BASE+0x2544)
#define XFI_PMA_RX_TORGS_DEBUG_9                    (XFI_PMA_BASE+0x2548)
#define XFI_PMA_RX_TORGS_DEBUG_10                   (XFI_PMA_BASE+0x254C)
#define XFI_PMA_SS_TX_RST_B                         (XFI_PMA_BASE+0x2550)
#define XFI_PMA_SS_TX_CALIB_0                       (XFI_PMA_BASE+0x2554)
#define XFI_PMA_SS_TX_CALIB_1                       (XFI_PMA_BASE+0x2558)
#define XFI_PMA_SS_TX_CALIB_2                       (XFI_PMA_BASE+0x255C)
#define XFI_PMA_XFI_SETTING_0                       (XFI_PMA_BASE+0x2600)
#define XFI_PMA_XFI_SETTING_1                       (XFI_PMA_BASE+0x2604)
#define XFI_PMA_XFI_SETTING_2                       (XFI_PMA_BASE+0x2608)
#define XFI_PMA_XFI_STA                             (XFI_PMA_BASE+0x260C)
#define XFI_PMA_XFI_INT_EN_0                        (XFI_PMA_BASE+0x2610)
#define XFI_PMA_XFI_INT_EN_1                        (XFI_PMA_BASE+0x2614)
#define XFI_PMA_XFI_INT_STA_CLR_0                   (XFI_PMA_BASE+0x2618)
#define XFI_PMA_XFI_INT_STA_CLR_1                   (XFI_PMA_BASE+0x261C)
#define XFI_PMA_XFI_INT_STA_0                       (XFI_PMA_BASE+0x2620)
#define XFI_PMA_XFI_INT_STA_1                       (XFI_PMA_BASE+0x2624)
#define XFI_PMA_RX_TORGS_DEBUG_11                   (XFI_PMA_BASE+0x2628)
#define XFI_PMA_RX_FORCE_MODE_0                     (XFI_PMA_BASE+0x2630)
#define XFI_PMA_RX_FORCE_MODE_1                     (XFI_PMA_BASE+0x2634)
#define XFI_PMA_RX_FORCE_MODE_2                     (XFI_PMA_BASE+0x2638)
#define XFI_PMA_RX_DISB_MODE_0                      (XFI_PMA_BASE+0x263C)
#define XFI_PMA_RX_DISB_MODE_1                      (XFI_PMA_BASE+0x2640)
#define XFI_PMA_RX_DISB_MODE_2                      (XFI_PMA_BASE+0x2644)
#define XFI_PMA_RX_FORCE_MODE_3                     (XFI_PMA_BASE+0x2648)
#define XFI_PMA_RX_FORCE_MODE_4                     (XFI_PMA_BASE+0x264C)
#define XFI_PMA_RX_FORCE_MODE_5                     (XFI_PMA_BASE+0x2650)
#define XFI_PMA_RX_FORCE_MODE_6                     (XFI_PMA_BASE+0x2654)
#define XFI_PMA_RX_DISB_MODE_3                      (XFI_PMA_BASE+0x2658)
#define XFI_PMA_RX_DISB_MODE_4                      (XFI_PMA_BASE+0x265C)
#define XFI_PMA_RX_DISB_MODE_5                      (XFI_PMA_BASE+0x2660)
#define XFI_PMA_RX_FORCE_MODE_7                     (XFI_PMA_BASE+0x2664)
#define XFI_PMA_RX_FORCE_MODE_8                     (XFI_PMA_BASE+0x2668)
#define XFI_PMA_RX_FORCE_MODE_9                     (XFI_PMA_BASE+0x266C)
#define XFI_PMA_RX_DISB_MODE_6                      (XFI_PMA_BASE+0x2670)
#define XFI_PMA_RX_DISB_MODE_7                      (XFI_PMA_BASE+0x2674)
#define XFI_PMA_RX_DISB_MODE_8                      (XFI_PMA_BASE+0x2678)
#define XFI_PMA_SS_BIST_0                           (XFI_PMA_BASE+0x2680)
#define XFI_PMA_SS_BIST_1                           (XFI_PMA_BASE+0x2684)
#define XFI_PMA_SS_BIST_2                           (XFI_PMA_BASE+0x2688)
#define XFI_PMA_SS_DA_XFI_PWDB_0                    (XFI_PMA_BASE+0x268C)
#define XFI_PMA_SS_DA_XFI_PWDB_1                    (XFI_PMA_BASE+0x2690)
#define XFI_PMA_SS_LCPLL_0                          (XFI_PMA_BASE+0x2694)
#define XFI_PMA_SS_LCPLL_1                          (XFI_PMA_BASE+0x2698)
#define XFI_PMA_SS_LCPLL_2                          (XFI_PMA_BASE+0x269C)
#define XFI_PMA_ADD_DIG_RESERVE_0                   (XFI_PMA_BASE+0x2700)
#define XFI_PMA_ADD_DIG_RESERVE_1                   (XFI_PMA_BASE+0x2704)
#define XFI_PMA_ADD_DIG_RESERVE_2                   (XFI_PMA_BASE+0x2708)
#define XFI_PMA_ADD_DIG_RESERVE_3                   (XFI_PMA_BASE+0x270C)
#define XFI_PMA_ADD_DIG_RESERVE_4                   (XFI_PMA_BASE+0x2710)
#define XFI_PMA_RG_XFI_RX_RESERVED_1                (XFI_PMA_BASE+0x2714)
#define XFI_PMA_ADD_DIG_RO_RESERVE_0                (XFI_PMA_BASE+0x2718)
#define XFI_PMA_ADD_DIG_RO_RESERVE_1                (XFI_PMA_BASE+0x271C)
#define XFI_PMA_ADD_DIG_RO_RESERVE_2                (XFI_PMA_BASE+0x2720)
#define XFI_PMA_ADD_DIG_RO_RESERVE_3                (XFI_PMA_BASE+0x2724)
#define XFI_PMA_ADD_DIG_RO_RESERVE_4                (XFI_PMA_BASE+0x2728)
#define XFI_PMA_ADD_RX_SYS_EN_SEL_0                 (XFI_PMA_BASE+0x272C)
#define XFI_PMA_PLL_TDC_FREQDET_0                   (XFI_PMA_BASE+0x2730)
#define XFI_PMA_PLL_TDC_FREQDET_1                   (XFI_PMA_BASE+0x2734)
#define XFI_PMA_PLL_TDC_FREQDET_2                   (XFI_PMA_BASE+0x2738)
#define XFI_PMA_PLL_TDC_FREQDET_3                   (XFI_PMA_BASE+0x273C)
#define XFI_PMA_DA_XFI_TX_FORCE_0                   (XFI_PMA_BASE+0x2740)
#define XFI_PMA_DA_XFI_TX_FORCE_1                   (XFI_PMA_BASE+0x2744)
#define XFI_PMA_DA_XFI_TX_FORCE_2                   (XFI_PMA_BASE+0x2748)
#define XFI_PMA_RX_FORCE_MODE_10                    (XFI_PMA_BASE+0x274C)
#define XFI_PMA_ADD_CLKPATH_RST_0                   (XFI_PMA_BASE+0x2750)
#define XFI_PMA_ADD_XFI_MODE_1                      (XFI_PMA_BASE+0x2754)
#define XFI_PMA_ADD_R2T_MODE_1                      (XFI_PMA_BASE+0x2758)
#define XFI_PMA_ADD_T2R_MODE_1                      (XFI_PMA_BASE+0x275C)
#define XFI_PMA_ADD_LCPLL_RO_1                      (XFI_PMA_BASE+0x2760)
#define XFI_PMA_ADD_RO_RX2ANA_1                     (XFI_PMA_BASE+0x2764)
#define XFI_PMA_ADD_RO_RX2ANA_2                     (XFI_PMA_BASE+0x2768)
#define XFI_PMA_ADD_RO_RX2ANA_3                     (XFI_PMA_BASE+0x276C)
#define XFI_PMA_ADD_RO_R2TMODE_1                    (XFI_PMA_BASE+0x2780)
#define XFI_PMA_SS_JCPLL_PWCTL_SETTING_0            (XFI_PMA_BASE+0x2800)
#define XFI_PMA_SS_JCPLL_PWCTL_SETTING_1            (XFI_PMA_BASE+0x2804)
#define XFI_PMA_SS_JCPLL_TDC_FLT_2                  (XFI_PMA_BASE+0x2808)
#define XFI_PMA_JCPLL_CHG                           (XFI_PMA_BASE+0x280C)
#define XFI_PMA_RG_JCPLL_SDM_PCW_CTRL               (XFI_PMA_BASE+0x2810)
#define XFI_PMA_RG_JCPLL_SDM_PCW_CHG_CTRL           (XFI_PMA_BASE+0x2814)
#define XFI_PMA_RG_JCPLL_XFI_CMN_STB_CTRL           (XFI_PMA_BASE+0x2818)
#define XFI_PMA_PLL_TDC_TX_FREQDET_0                (XFI_PMA_BASE+0x2820)
#define XFI_PMA_PLL_TDC_TX_FREQDET_1                (XFI_PMA_BASE+0x2824)
#define XFI_PMA_PLL_TDC_TX_FREQDET_2                (XFI_PMA_BASE+0x2828)
#define XFI_PMA_PLL_TDC_TX_FREQDET_3                (XFI_PMA_BASE+0x282C)
#define XFI_PMA_XFI_IPATH_CTRL_0                    (XFI_PMA_BASE+0x2830)
#define XFI_PMA_XFI_IPATH_CTRL_1                    (XFI_PMA_BASE+0x2834)
#define XFI_PMA_XFI_IPATH_CTRL_2                    (XFI_PMA_BASE+0x2838)
#define XFI_PMA_XFI_IPATH_CTRL_3                    (XFI_PMA_BASE+0x283C)
#define XFI_PMA_XFI_IPATH_CTRL_4                    (XFI_PMA_BASE+0x2840)
#define XFI_PMA_XFI_IPATH_CTRL_5                    (XFI_PMA_BASE+0x2844)
#define XFI_PMA_XFI_IPATH_CTRL_6                    (XFI_PMA_BASE+0x2848)
#define XFI_PMA_PLL_JCPLL_FT_FREQDET_0              (XFI_PMA_BASE+0x284C)
#define XFI_PMA_PLL_JCPLL_FT_FREQDET_1              (XFI_PMA_BASE+0x2850)
#define XFI_PMA_PLL_JCPLL_FT_FREQDET_2              (XFI_PMA_BASE+0x2854)
#define XFI_PMA_PLL_JCPLL_FT_FREQDET_3              (XFI_PMA_BASE+0x2858)
#define XFI_PMA_JCPLL_FT_CK_MUX                     (XFI_PMA_BASE+0x285C)
#define XFI_PMA_JCPLL_DA_RG_CTRL_0                  (XFI_PMA_BASE+0x2860)
#define XFI_PMA_JCPLL_DA_RG_CTRL_1                  (XFI_PMA_BASE+0x2864)
#define XFI_PMA_JCPLL_DA_RG_CTRL_2                  (XFI_PMA_BASE+0x2868)
#define XFI_PMA_XFI_PLL_DA_RG_CTRL_0                (XFI_PMA_BASE+0x286C)
#define XFI_PMA_XFI_PLL_DA_RG_CTRL_1                (XFI_PMA_BASE+0x2870)
#define XFI_PMA_XFI_PLL_DA_RG_CTRL_2                (XFI_PMA_BASE+0x2874)
#define XFI_PMA_AD_DA_PROBE_STS_0                   (XFI_PMA_BASE+0x2878)
#define XFI_PMA_AD_DA_PROBE_STS_1                   (XFI_PMA_BASE+0x287C)
#define XFI_PMA_JCPLL_SCAN_CTRL                     (XFI_PMA_BASE+0x2880)
#define XFI_PMA_XFI_TX_COUNTER_0                    (XFI_PMA_BASE+0x2884)
#define XFI_PMA_XFI_TX_COUNTER_1                    (XFI_PMA_BASE+0x2888)
#define XFI_PMA_XFI_TX_COUNTER_2                    (XFI_PMA_BASE+0x288c)
#define XFI_PMA_XFI_TX_COUNTER_3                    (XFI_PMA_BASE+0x2890)
#define XFI_PMA_XFI_GPIO_SEL_0                      (XFI_PMA_BASE+0x2894)
#define XFI_PMA_TXPLL_SCAN                          (XFI_PMA_BASE+0x2898)

typedef enum{
	RX_pll_10p3125G=0,
	RX_pll_9p95328G=1,
	Rx_pll_2p48832G=2,
	Rx_pll_1p25G=3
}A60972_XPON_PMA_LCPLL_Mode_t;


typedef struct {
    A60972_XPON_PMA_LCPLL_Mode_t		LCPLL_Mode;
	XPON_PMA_FM_Mode_t					FM_Mode;	//added by ASIC period
    XPON_PMA_RX_Mode_t					RX_Mode;
    XPON_PMA_TX_Mode_t					TX_Mode;
    XPON_PMA_TX_Bist_Pattern_t			TX_Bist_Pattern;
    XPON_PMA_LoopBack_Path_t			LoopBack_Path;
	XPON_PMA_Trans_Ben_Active_Level_t	Trans_Ben_Active_Level;
} A60972_XPON_PMA_Param_T ;


#endif

#endif

#endif
