#!/bin/sh
# Copyright (C) 2007 OpenWrt.org

/etc/init.d/sfe enabled && {

	[ "$ACTION" = ifup -o "$ACTION" = wan ] && {
		/etc/init.d/sfe restart
	}
	
	[ "$ACTION" = ifdown -o "$ACTION" = lan ] && {
		/etc/init.d/sfe restart
	}

	[ "$ACTION" = ifup -o "$ACTION" = lan ] && {
		/etc/init.d/sfe restart
	}
	
	[ "$ACTION" = ifdown -o "$ACTION" = lan ] && {
		/etc/init.d/sfe restart
	}
	
}
