#!/bin/sh

uci delete firewall.mproxy
uci add firewall rule 
uci rename firewall.@rule[-1]="mproxy"
uci set firewall.@rule[-1].name="mproxy"
uci set firewall.@rule[-1].target="ACCEPT"
uci set firewall.@rule[-1].src="wan"
uci set firewall.@rule[-1].proto="tcp"
uci set firewall.@rule[-1].dest_port="9090"
uci commit firewall;

/etc/init.d/mproxy enable

rm -f /tmp/luci-indexcache
exit 0
