#ifndef _CMGR_GPON_CONST_H_
#define _CMGR_GPON_CONST_H_

#include "common/mgr_sdi.h"

#define CONST_GPON_SN_LENS				GPON_SN_LENS		/* GPON_SN_LENS */
#define CONST_GPON_PASSWD_LENS			GPON_PASSWD_LENS		/* GPON_PASSWD_LENS */
#define CONST_GPON_HEX_PASSWD_LENS	    22						/*HEX_PASSWD_LENS*/
#define CONST_GPON_ENCRYPT_KEY_LENS		GPON_ENCRYPT_KEY_LENS		/* GPON_ENCRYPT_KEY_LENS */

#define CONST_MAX_GEMPORT_ID			GPON_MAX_GEM_ID		/* GPON_MAX_GEM_ID */
#define CONST_MAX_TCONT_ID				GPON_MAX_ALLOC_ID	/* GPON_MAX_ALLOC_ID */

#define CONST_MAX_BRIDGE_PORT			GPON_MAX_ANI_INTERFACE
#define CONST_GPON_OMCI_INTERFACE		GPON_OMCI_INTERFACE

#endif /* _CMGR_GPON_CONST_H_ */
