#ifndef _CMGR_GPON_ENUM_H_
#define _CMGR_GPON_ENUM_H_

#include "common/mgr_cmd.h"

typedef enum {
	ENUM_GPON_STATE_O1 = 1, 
	ENUM_GPON_STATE_O2, 
	ENUM_GPON_STATE_O3, 
	ENUM_GPON_STATE_O4, 
	ENUM_GPON_STATE_O5, 
	ENUM_GPON_STATE_O6, 
	ENUM_GPON_STATE_O7 
} MGR_GponState_t ;


typedef enum {
	ENUM_GPON_GEM_TYPE_UNICAST = 0,
	ENUM_GPON_GEM_TYPE_MULTICAST
} MGR_GponGemType_t ;

typedef enum {
	ENUM_GPON_TRTCM_SCALE_1B		= XMCS_GPON_TRTCM_SCALE_1B, 
	ENUM_GPON_TRTCM_SCALE_2B		= XMCS_GPON_TRTCM_SCALE_2B,  
	ENUM_GPON_TRTCM_SCALE_4B		= XMCS_GPON_TRTCM_SCALE_4B,  
	ENUM_GPON_TRTCM_SCALE_8B		= XMCS_GPON_TRTCM_SCALE_8B,  
	ENUM_GPON_TRTCM_SCALE_16B		= XMCS_GPON_TRTCM_SCALE_16B, 
	ENUM_GPON_TRTCM_SCALE_32B		= XMCS_GPON_TRTCM_SCALE_32B, 
	ENUM_GPON_TRTCM_SCALE_64B		= XMCS_GPON_TRTCM_SCALE_64B, 
	ENUM_GPON_TRTCM_SCALE_128B		= XMCS_GPON_TRTCM_SCALE_128B,
	ENUM_GPON_TRTCM_SCALE_256B		= XMCS_GPON_TRTCM_SCALE_256B,
	ENUM_GPON_TRTCM_SCALE_512B		= XMCS_GPON_TRTCM_SCALE_512B,
	ENUM_GPON_TRTCM_SCALE_1K		= XMCS_GPON_TRTCM_SCALE_1K,  
	ENUM_GPON_TRTCM_SCALE_2K		= XMCS_GPON_TRTCM_SCALE_2K,  
	ENUM_GPON_TRTCM_SCALE_4K		= XMCS_GPON_TRTCM_SCALE_4K,  
	ENUM_GPON_TRTCM_SCALE_8K		= XMCS_GPON_TRTCM_SCALE_8K,  
	ENUM_GPON_TRTCM_SCALE_16K		= XMCS_GPON_TRTCM_SCALE_16K, 
	ENUM_GPON_TRTCM_SCALE_32K		= XMCS_GPON_TRTCM_SCALE_32K, 
	ENUM_GPON_TRTCM_SCALE_ITEMS     = XMCS_GPON_TRTCM_SCALE_ITEMS
} MGR_GponTrtcmScale_t ;

#endif /* _CMGR_GPON_ENUM_H_ */

