#ifndef _CMGR_PWAN_ENUM_H_
#define _CMGR_PWAN_ENUM_H_

#include "common/mgr_sdi.h"

typedef enum {
	ENUM_WEIGHT_TYPE_PACKET 	= XMCS_IF_WEIGHT_TYPE_PACKET,
	ENUM_WEIGHT_TYPE_BYTE		= XMCS_IF_WEIGHT_TYPE_BYTE
} MGR_QoSWeightType_t ;

typedef enum {
	ENUM_WEIGHT_SCALE_64B 		= XMCS_IF_WEIGHT_SCALE_64B,
	ENUM_WEIGHT_SCALE_16B		= XMCS_IF_WEIGHT_SCALE_16B
} MGR_QoSWeightScale_t ;

typedef enum {
	ENUM_QOS_TYPE_WRR 			= XMCS_IF_QOS_TYPE_WRR,
	ENUM_QOS_TYPE_SP			= XMCS_IF_QOS_TYPE_SP,
	ENUM_QOS_TYPE_SPWRR7		= XMCS_IF_QOS_TYPE_SPWRR7, 
	ENUM_QOS_TYPE_SPWRR6		= XMCS_IF_QOS_TYPE_SPWRR6, 
	ENUM_QOS_TYPE_SPWRR5		= XMCS_IF_QOS_TYPE_SPWRR5, 
	ENUM_QOS_TYPE_SPWRR4		= XMCS_IF_QOS_TYPE_SPWRR4, 
	ENUM_QOS_TYPE_SPWRR3		= XMCS_IF_QOS_TYPE_SPWRR3, 
	ENUM_QOS_TYPE_SPWRR2		= XMCS_IF_QOS_TYPE_SPWRR2
} MGR_QosType_t ;

typedef enum {
	ENUM_CONGESTIOM_SCALE_2		= XMCS_IF_CONGESTIOM_SCALE_2,
	ENUM_CONGESTIOM_SCALE_4		= XMCS_IF_CONGESTIOM_SCALE_4, 
	ENUM_CONGESTIOM_SCALE_8		= XMCS_IF_CONGESTIOM_SCALE_8, 
	ENUM_CONGESTIOM_SCALE_16	= XMCS_IF_CONGESTIOM_SCALE_16
} MGR_CongestionScale_t ;

typedef enum {
	ENUM_IF_TRTCM_SCALE_1B			= XMCS_IF_TRTCM_SCALE_1B, 
	ENUM_IF_TRTCM_SCALE_2B			= XMCS_IF_TRTCM_SCALE_2B,  
	ENUM_IF_TRTCM_SCALE_4B			= XMCS_IF_TRTCM_SCALE_4B,  
	ENUM_IF_TRTCM_SCALE_8B			= XMCS_IF_TRTCM_SCALE_8B,  
	ENUM_IF_TRTCM_SCALE_16B			= XMCS_IF_TRTCM_SCALE_16B, 
	ENUM_IF_TRTCM_SCALE_32B			= XMCS_IF_TRTCM_SCALE_32B, 
	ENUM_IF_TRTCM_SCALE_64B			= XMCS_IF_TRTCM_SCALE_64B, 
	ENUM_IF_TRTCM_SCALE_128B		= XMCS_IF_TRTCM_SCALE_128B,
	ENUM_IF_TRTCM_SCALE_256B		= XMCS_IF_TRTCM_SCALE_256B,
	ENUM_IF_TRTCM_SCALE_512B		= XMCS_IF_TRTCM_SCALE_512B,
	ENUM_IF_TRTCM_SCALE_1K			= XMCS_IF_TRTCM_SCALE_1K,  
	ENUM_IF_TRTCM_SCALE_2K			= XMCS_IF_TRTCM_SCALE_2K,  
	ENUM_IF_TRTCM_SCALE_4K			= XMCS_IF_TRTCM_SCALE_4K,  
	ENUM_IF_TRTCM_SCALE_8K			= XMCS_IF_TRTCM_SCALE_8K,  
	ENUM_IF_TRTCM_SCALE_16K			= XMCS_IF_TRTCM_SCALE_16K, 
	ENUM_IF_TRTCM_SCALE_32K			= XMCS_IF_TRTCM_SCALE_32K, 
	ENUM_IF_TRTCM_SCALE_ITEMS  	  	= XMCS_IF_TRTCM_SCALE_ITEMS
} MGR_TrtcmScale_t ;

typedef enum {
	ENUM_IF_PCP_MODE_DISABLE		= XMCS_IF_PCP_MODE_DISABLE,
	ENUM_IF_PCP_MODE_8B0D			= XMCS_IF_PCP_MODE_8B0D,
	ENUM_IF_PCP_MODE_7B1D			= XMCS_IF_PCP_MODE_7B1D,
	ENUM_IF_PCP_MODE_6B2D			= XMCS_IF_PCP_MODE_6B2D,
	ENUM_IF_PCP_MODE_5B3D			= XMCS_IF_PCP_MODE_5B3D
} MGR_PcpMode_t ;    

#endif /* _CMGR_PWAN_ENUM_H_ */

