#!/bin/sh

NSS_PATH="/sys/kernel/debug/qca-nss-drv/stats"

cpu_usage="$(top -n1 | awk '/^CPU/ {printf("%d%", 100 - $8)}')"

[ ! -d "$NSS_PATH" ] || \
npu_usage="$(grep '%' "$NSS_PATH"/cpu_load_ubi | awk -F ' ' '{print $2}')"

if [ -d "$NSS_PATH" ]; then
	echo -n "CPU: ${cpu_usage}, NPU: ${npu_usage}"
else
	echo -n "CPU: ${cpu_usage}"
fi
