#!/bin/sh

DAEMON=/usr/sbin/polipo
PIDFILE=`uci get polipo.daemon.pidFile`
CFGFILE=/var/etc/polipo.conf

[ -e "$PIDFILE" ] && {
	PID=`cat $PIDFILE`

	# send Polipo USR1 signal to write its in-memory cache to disk
	kill -USR1 $PID
	sleep 2
	# start polipo with -x flag to purge the on-disk cache
	polipo -c $CFGFILE -x
	# send Polipo USR2 signal to discard its in-memory cache
	kill -USR2 $PID
}

