#!/bin/sh /etc/rc.common

START=79
USE_PROCD=1

service_triggers()
{
	procd_add_reload_trigger "luci_statistics"
}

start_service() {
	### replace shipped config with symlink
	mkdir -p /var/etc
	if [ ! -L /etc/collectd.conf ]; then
		test -f /etc/collectd.conf && mv /etc/collectd.conf /etc/collectd.conf.bak
		ln -s /var/etc/collectd.conf /etc/collectd.conf
	fi

	### create config
	/usr/bin/stat-genconfig > /var/etc/collectd.conf

	### workaround broken permissions on /tmp
	chmod 1777 /tmp
}

reload_service() {
	restart "$@"
}

restart() {
	### regenerate config / prepare environment
	start

	### restart collectd
	/etc/init.d/collectd restart
}
