#!/bin/sh /etc/rc.common
# Copyright (C) 2021 KFERMercer <KFER.Mercer@gmail.com>
# 

START=99
STOP=10

start() {
	state=`pgrep -f "uuplugin"`
	if [ ! -z "$state" ]; then
		restart
	else
		/usr/share/uugamebooster/uuplugin /usr/share/uugamebooster/uu.conf >/tmp/uugamebooster.log 2>&1 &
	fi
	echo "start uugamebooster"
}

stop() {
	kill -9 `pgrep -f "uuplugin"` 2>/dev/null
	echo "exit uugamebooster"
}

restart(){
	stop
	sleep 1
	start
	echo "restart uugamebooster"
}
