#!/bin/bash
cd /root &&
curl -sL https://github.com/eysp/public/archive/public.tar.gz | tar xz &&
mv public-public public &&
docker run -d --restart=always --name="portainer" -p 9999:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data -v /root/public:/public portainer/portainer-ce
