#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for dump1090
LUCI_DEPENDS:=+dump1090

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
