#!/bin/sh /etc/rc.common
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

START=96
USE_PROCD=1
OAFD_BIN="/usr/bin/oafd"

service_triggers()
{
	procd_add_reload_trigger "appfilter"
}

stop_service(){
	killall -9 oafd
	rmmod oaf
}

start_service(){
	gen_class.sh /etc/appfilter/feature.cfg
	insmod oaf
	/usr/bin/oaf_rule reload
	procd_open_instance
	procd_set_param respawn 60 5 5
	procd_set_param stderr 1
	procd_set_param command "$OAFD_BIN"
	procd_close_instance
}
