#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aliyundrive-webdav[-1]
	add ucitrack aliyundrive-webdav
	set ucitrack.@aliyundrive-webdav[-1].init=aliyundrive-webdav
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
