#!/bin/sh
touch /etc/config/serverchan

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@serverchan[-1]
	add ucitrack serverchan
	set ucitrack.@serverchan[-1].init=serverchan
	commit ucitrack
EOF

chmod 755 /etc/init.d/serverchan
chmod 755 /etc/init.d/sccustom
chmod 755 /usr/bin/serverchan/*
#chmod -R 755 /usr/bin/serverchan/wrtbwmon
rm -f /tmp/luci-indexcache
exit 0
