/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:57 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

#ifndef __AQHostInterfaceEx_h__
#define __AQHostInterfaceEx_h__

/*******************************************************************************
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      **
**                       Module HostInterfaceAxiExtended                      **
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                      **
*******************************************************************************/

/* Register AQSecurityNSAID **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

/* NSAID for security access From AHB */

#define AQSecurityNSAIDRegAddrs                                           0x00A0
#define AQ_SECURITY_NSAID_Address                                        0x00280
#define AQ_SECURITY_NSAID_MSB                                                 15
#define AQ_SECURITY_NSAID_LSB                                                  0
#define AQ_SECURITY_NSAID_BLK                                                  0
#define AQ_SECURITY_NSAID_Count                                                1
#define AQ_SECURITY_NSAID_FieldMask                                   0x00000FFF
#define AQ_SECURITY_NSAID_ReadMask                                    0x00000FFF
#define AQ_SECURITY_NSAID_WriteMask                                   0x00000FFF
#define AQ_SECURITY_NSAID_ResetValue                                  0x00000000

/* NSAID0_S FE access */
#define AQ_SECURITY_NSAID_FE                                                 3:0
#define AQ_SECURITY_NSAID_FE_End                                               3
#define AQ_SECURITY_NSAID_FE_Start                                             0
#define AQ_SECURITY_NSAID_FE_Type                                            U04

/* NSAID0_S TS access */
#define AQ_SECURITY_NSAID_TS                                                 7:4
#define AQ_SECURITY_NSAID_TS_End                                               7
#define AQ_SECURITY_NSAID_TS_Start                                             4
#define AQ_SECURITY_NSAID_TS_Type                                            U04

/* NSAID0_S other access */
#define AQ_SECURITY_NSAID_OTHER                                             11:8
#define AQ_SECURITY_NSAID_OTHER_End                                           11
#define AQ_SECURITY_NSAID_OTHER_Start                                          8
#define AQ_SECURITY_NSAID_OTHER_Type                                         U04

/* Register AQNoSecurityNSAID **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* NSAID for no security access From AHB */

#define AQNoSecurityNSAIDRegAddrs                                         0x00A1
#define AQ_NO_SECURITY_NSAID_Address                                     0x00284
#define AQ_NO_SECURITY_NSAID_MSB                                              15
#define AQ_NO_SECURITY_NSAID_LSB                                               0
#define AQ_NO_SECURITY_NSAID_BLK                                               0
#define AQ_NO_SECURITY_NSAID_Count                                             1
#define AQ_NO_SECURITY_NSAID_FieldMask                                0x00000FFF
#define AQ_NO_SECURITY_NSAID_ReadMask                                 0x00000FFF
#define AQ_NO_SECURITY_NSAID_WriteMask                                0x00000FFF
#define AQ_NO_SECURITY_NSAID_ResetValue                               0x00000000

/* NSAID0_NS FE access */
#define AQ_NO_SECURITY_NSAID_FE                                              3:0
#define AQ_NO_SECURITY_NSAID_FE_End                                            3
#define AQ_NO_SECURITY_NSAID_FE_Start                                          0
#define AQ_NO_SECURITY_NSAID_FE_Type                                         U04

/* NSAID0_NS TS access */
#define AQ_NO_SECURITY_NSAID_TS                                              7:4
#define AQ_NO_SECURITY_NSAID_TS_End                                            7
#define AQ_NO_SECURITY_NSAID_TS_Start                                          4
#define AQ_NO_SECURITY_NSAID_TS_Type                                         U04

/* NSAID0_NS other access */
#define AQ_NO_SECURITY_NSAID_OTHER                                          11:8
#define AQ_NO_SECURITY_NSAID_OTHER_End                                        11
#define AQ_NO_SECURITY_NSAID_OTHER_Start                                       8
#define AQ_NO_SECURITY_NSAID_OTHER_Type                                      U04

/* Register gcFrameTotalBusyCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Engine work total cycles counter per frame/draw. */

#define gcFrameTotalBusyCntRegAddrs                                       0x00A2
#define GC_FRAME_TOTAL_BUSY_CNT_Address                                  0x00288
#define GC_FRAME_TOTAL_BUSY_CNT_MSB                                           15
#define GC_FRAME_TOTAL_BUSY_CNT_LSB                                            0
#define GC_FRAME_TOTAL_BUSY_CNT_BLK                                            0
#define GC_FRAME_TOTAL_BUSY_CNT_Count                                          1
#define GC_FRAME_TOTAL_BUSY_CNT_FieldMask                             0xFFFFFFFF
#define GC_FRAME_TOTAL_BUSY_CNT_ReadMask                              0xFFFFFFFF
#define GC_FRAME_TOTAL_BUSY_CNT_WriteMask                             0xFFFFFFFF
#define GC_FRAME_TOTAL_BUSY_CNT_ResetValue                            0x00000000

#define GC_FRAME_TOTAL_BUSY_CNT_VALUE                                       31:0
#define GC_FRAME_TOTAL_BUSY_CNT_VALUE_End                                     31
#define GC_FRAME_TOTAL_BUSY_CNT_VALUE_Start                                    0
#define GC_FRAME_TOTAL_BUSY_CNT_VALUE_Type                                   U32

/* Register gcFrameBackpressReadCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Frame level total read backpress by AXI. */

#define gcFrameBackpressReadCntRegAddrs                                   0x00A3
#define GC_FRAME_BACKPRESS_READ_CNT_Address                              0x0028C
#define GC_FRAME_BACKPRESS_READ_CNT_MSB                                       15
#define GC_FRAME_BACKPRESS_READ_CNT_LSB                                        0
#define GC_FRAME_BACKPRESS_READ_CNT_BLK                                        0
#define GC_FRAME_BACKPRESS_READ_CNT_Count                                      1
#define GC_FRAME_BACKPRESS_READ_CNT_FieldMask                         0xFFFFFFFF
#define GC_FRAME_BACKPRESS_READ_CNT_ReadMask                          0xFFFFFFFF
#define GC_FRAME_BACKPRESS_READ_CNT_WriteMask                         0xFFFFFFFF
#define GC_FRAME_BACKPRESS_READ_CNT_ResetValue                        0x00000000

#define GC_FRAME_BACKPRESS_READ_CNT_VALUE                                   31:0
#define GC_FRAME_BACKPRESS_READ_CNT_VALUE_End                                 31
#define GC_FRAME_BACKPRESS_READ_CNT_VALUE_Start                                0
#define GC_FRAME_BACKPRESS_READ_CNT_VALUE_Type                               U32

/* Register gcFrameBackpressWriteCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Frame level total write backpress by AXI. */

#define gcFrameBackpressWriteCntRegAddrs                                  0x00A4
#define GC_FRAME_BACKPRESS_WRITE_CNT_Address                             0x00290
#define GC_FRAME_BACKPRESS_WRITE_CNT_MSB                                      15
#define GC_FRAME_BACKPRESS_WRITE_CNT_LSB                                       0
#define GC_FRAME_BACKPRESS_WRITE_CNT_BLK                                       0
#define GC_FRAME_BACKPRESS_WRITE_CNT_Count                                     1
#define GC_FRAME_BACKPRESS_WRITE_CNT_FieldMask                        0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_CNT_ReadMask                         0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_CNT_WriteMask                        0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_CNT_ResetValue                       0x00000000

#define GC_FRAME_BACKPRESS_WRITE_CNT_VALUE                                  31:0
#define GC_FRAME_BACKPRESS_WRITE_CNT_VALUE_End                                31
#define GC_FRAME_BACKPRESS_WRITE_CNT_VALUE_Start                               0
#define GC_FRAME_BACKPRESS_WRITE_CNT_VALUE_Type                              U32

/* Register gcFrameBackpressWriteDataCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Frame level total write data backpress by AXI. */

#define gcFrameBackpressWriteDataCntRegAddrs                              0x00A5
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_Address                        0x00294
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_MSB                                 15
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_LSB                                  0
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_BLK                                  0
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_Count                                1
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_FieldMask                   0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_ReadMask                    0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_WriteMask                   0xFFFFFFFF
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_ResetValue                  0x00000000

#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_VALUE                             31:0
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_VALUE_End                           31
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_VALUE_Start                          0
#define GC_FRAME_BACKPRESS_WRITE_DATA_CNT_VALUE_Type                         U32

/* Register gcFrameTotalLatencyCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Frame leve average latency count. */

#define gcFrameTotalLatencyCntRegAddrs                                    0x00A6
#define GC_FRAME_TOTAL_LATENCY_CNT_Address                               0x00298
#define GC_FRAME_TOTAL_LATENCY_CNT_MSB                                        15
#define GC_FRAME_TOTAL_LATENCY_CNT_LSB                                         0
#define GC_FRAME_TOTAL_LATENCY_CNT_BLK                                         0
#define GC_FRAME_TOTAL_LATENCY_CNT_Count                                       1
#define GC_FRAME_TOTAL_LATENCY_CNT_FieldMask                          0xFFFFFFFF
#define GC_FRAME_TOTAL_LATENCY_CNT_ReadMask                           0xFFFFFFFF
#define GC_FRAME_TOTAL_LATENCY_CNT_WriteMask                          0xFFFFFFFF
#define GC_FRAME_TOTAL_LATENCY_CNT_ResetValue                         0x00000000

#define GC_FRAME_TOTAL_LATENCY_CNT_VALUE                                    31:0
#define GC_FRAME_TOTAL_LATENCY_CNT_VALUE_End                                  31
#define GC_FRAME_TOTAL_LATENCY_CNT_VALUE_Start                                 0
#define GC_FRAME_TOTAL_LATENCY_CNT_VALUE_Type                                U32

/* Register gcFrameTotalRdReqCnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Frame leve average latency count. */

#define gcFrameTotalRdReqCntRegAddrs                                      0x00A7
#define GC_FRAME_TOTAL_RD_REQ_CNT_Address                                0x0029C
#define GC_FRAME_TOTAL_RD_REQ_CNT_MSB                                         15
#define GC_FRAME_TOTAL_RD_REQ_CNT_LSB                                          0
#define GC_FRAME_TOTAL_RD_REQ_CNT_BLK                                          0
#define GC_FRAME_TOTAL_RD_REQ_CNT_Count                                        1
#define GC_FRAME_TOTAL_RD_REQ_CNT_FieldMask                           0xFFFFFFFF
#define GC_FRAME_TOTAL_RD_REQ_CNT_ReadMask                            0xFFFFFFFF
#define GC_FRAME_TOTAL_RD_REQ_CNT_WriteMask                           0xFFFFFFFF
#define GC_FRAME_TOTAL_RD_REQ_CNT_ResetValue                          0x00000000

#define GC_FRAME_TOTAL_RD_REQ_CNT_VALUE                                     31:0
#define GC_FRAME_TOTAL_RD_REQ_CNT_VALUE_End                                   31
#define GC_FRAME_TOTAL_RD_REQ_CNT_VALUE_Start                                  0
#define GC_FRAME_TOTAL_RD_REQ_CNT_VALUE_Type                                 U32

/* Register gcLatencyMap0Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 0-100. */

#define gcLatencyMap0CntRegAddrs                                          0x00A8
#define GC_LATENCY_MAP0_CNT_Address                                      0x002A0
#define GC_LATENCY_MAP0_CNT_MSB                                               15
#define GC_LATENCY_MAP0_CNT_LSB                                                0
#define GC_LATENCY_MAP0_CNT_BLK                                                0
#define GC_LATENCY_MAP0_CNT_Count                                              1
#define GC_LATENCY_MAP0_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP0_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP0_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP0_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP0_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP0_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP0_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP0_CNT_VALUE_Type                                       U32

/* Register gcLatencyMap1Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 101-200. */

#define gcLatencyMap1CntRegAddrs                                          0x00A9
#define GC_LATENCY_MAP1_CNT_Address                                      0x002A4
#define GC_LATENCY_MAP1_CNT_MSB                                               15
#define GC_LATENCY_MAP1_CNT_LSB                                                0
#define GC_LATENCY_MAP1_CNT_BLK                                                0
#define GC_LATENCY_MAP1_CNT_Count                                              1
#define GC_LATENCY_MAP1_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP1_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP1_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP1_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP1_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP1_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP1_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP1_CNT_VALUE_Type                                       U32

/* Register gcLatencyMap2Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 201-300. */

#define gcLatencyMap2CntRegAddrs                                          0x00AA
#define GC_LATENCY_MAP2_CNT_Address                                      0x002A8
#define GC_LATENCY_MAP2_CNT_MSB                                               15
#define GC_LATENCY_MAP2_CNT_LSB                                                0
#define GC_LATENCY_MAP2_CNT_BLK                                                0
#define GC_LATENCY_MAP2_CNT_Count                                              1
#define GC_LATENCY_MAP2_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP2_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP2_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP2_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP2_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP2_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP2_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP2_CNT_VALUE_Type                                       U32

/* Register gcLatencyMap3Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 301-400. */

#define gcLatencyMap3CntRegAddrs                                          0x00AB
#define GC_LATENCY_MAP3_CNT_Address                                      0x002AC
#define GC_LATENCY_MAP3_CNT_MSB                                               15
#define GC_LATENCY_MAP3_CNT_LSB                                                0
#define GC_LATENCY_MAP3_CNT_BLK                                                0
#define GC_LATENCY_MAP3_CNT_Count                                              1
#define GC_LATENCY_MAP3_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP3_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP3_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP3_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP3_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP3_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP3_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP3_CNT_VALUE_Type                                       U32

/* Register gcLatencyMap4Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 401-500. */

#define gcLatencyMap4CntRegAddrs                                          0x00AC
#define GC_LATENCY_MAP4_CNT_Address                                      0x002B0
#define GC_LATENCY_MAP4_CNT_MSB                                               15
#define GC_LATENCY_MAP4_CNT_LSB                                                0
#define GC_LATENCY_MAP4_CNT_BLK                                                0
#define GC_LATENCY_MAP4_CNT_Count                                              1
#define GC_LATENCY_MAP4_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP4_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP4_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP4_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP4_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP4_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP4_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP4_CNT_VALUE_Type                                       U32

/* Register gcLatencyMap5Cnt **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Latency map 501-1000. */

#define gcLatencyMap5CntRegAddrs                                          0x00AD
#define GC_LATENCY_MAP5_CNT_Address                                      0x002B4
#define GC_LATENCY_MAP5_CNT_MSB                                               15
#define GC_LATENCY_MAP5_CNT_LSB                                                0
#define GC_LATENCY_MAP5_CNT_BLK                                                0
#define GC_LATENCY_MAP5_CNT_Count                                              1
#define GC_LATENCY_MAP5_CNT_FieldMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP5_CNT_ReadMask                                  0xFFFFFFFF
#define GC_LATENCY_MAP5_CNT_WriteMask                                 0xFFFFFFFF
#define GC_LATENCY_MAP5_CNT_ResetValue                                0x00000000

#define GC_LATENCY_MAP5_CNT_VALUE                                           31:0
#define GC_LATENCY_MAP5_CNT_VALUE_End                                         31
#define GC_LATENCY_MAP5_CNT_VALUE_Start                                        0
#define GC_LATENCY_MAP5_CNT_VALUE_Type                                       U32

/* Register AQContextIdFEBypass **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* FE bypass axuser. */

#define AQContextIdFEBypassRegAddrs                                       0x00AE
#define AQ_CONTEXT_ID_FE_BYPASS_Address                                  0x002B8
#define AQ_CONTEXT_ID_FE_BYPASS_MSB                                           15
#define AQ_CONTEXT_ID_FE_BYPASS_LSB                                            0
#define AQ_CONTEXT_ID_FE_BYPASS_BLK                                            0
#define AQ_CONTEXT_ID_FE_BYPASS_Count                                          1
#define AQ_CONTEXT_ID_FE_BYPASS_FieldMask                             0x0000FFFF
#define AQ_CONTEXT_ID_FE_BYPASS_ReadMask                              0x0000FFFF
#define AQ_CONTEXT_ID_FE_BYPASS_WriteMask                             0x0000FFFF
#define AQ_CONTEXT_ID_FE_BYPASS_ResetValue                            0x00000000

/* Context id FE bypass axuser. */
#define AQ_CONTEXT_ID_FE_BYPASS_VALUE                                       15:0
#define AQ_CONTEXT_ID_FE_BYPASS_VALUE_End                                     15
#define AQ_CONTEXT_ID_FE_BYPASS_VALUE_Start                                    0
#define AQ_CONTEXT_ID_FE_BYPASS_VALUE_Type                                   U16

/* Register AQFEAxiAddress **
** ~~~~~~~~~~~~~~~~~~~~~~~ */

/* High 32bit of fe axi address. */

#define AQFEAxiAddressRegAddrs                                            0x00AF
#define AQFE_AXI_ADDRESS_Address                                         0x002BC
#define AQFE_AXI_ADDRESS_MSB                                                  15
#define AQFE_AXI_ADDRESS_LSB                                                   0
#define AQFE_AXI_ADDRESS_BLK                                                   0
#define AQFE_AXI_ADDRESS_Count                                                 1
#define AQFE_AXI_ADDRESS_FieldMask                                    0xFFFFFFFF
#define AQFE_AXI_ADDRESS_ReadMask                                     0xFFFFFFFF
#define AQFE_AXI_ADDRESS_WriteMask                                    0xFFFFFFFF
#define AQFE_AXI_ADDRESS_ResetValue                                   0x00000000

#define AQFE_AXI_ADDRESS_ADDRESS                                            31:0
#define AQFE_AXI_ADDRESS_ADDRESS_End                                          31
#define AQFE_AXI_ADDRESS_ADDRESS_Start                                         0
#define AQFE_AXI_ADDRESS_ADDRESS_Type                                        U32


#endif /* __AQHostInterfaceEx_h__ */
