/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:57 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

#ifndef __AQSetupReg_h__
#define __AQSetupReg_h__

/*******************************************************************************
**                             ~~~~~~~~~~~~~~~~~~                             **
**                             Module SetupEngine                             **
**                             ~~~~~~~~~~~~~~~~~~                             **
*******************************************************************************/

/* Register AQSetupClipLeft **
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Left coordinate of the clipping window */

#define AQSetupClipLeftRegAddrs                                           0x0300
#define AQ_SETUP_CLIP_LEFT_Address                                       0x00C00
#define AQ_SETUP_CLIP_LEFT_MSB                                                15
#define AQ_SETUP_CLIP_LEFT_LSB                                                 0
#define AQ_SETUP_CLIP_LEFT_BLK                                                 0
#define AQ_SETUP_CLIP_LEFT_Count                                               1
#define AQ_SETUP_CLIP_LEFT_FieldMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_ReadMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_WriteMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_LEFT_ResetValue                                 0x00000000

/* The left coordinate of the clipping window in float. */
#define AQ_SETUP_CLIP_LEFT_CLIP                                             31:0
#define AQ_SETUP_CLIP_LEFT_CLIP_End                                           31
#define AQ_SETUP_CLIP_LEFT_CLIP_Start                                          0
#define AQ_SETUP_CLIP_LEFT_CLIP_Type                                         U32

/* Register AQSetupClipTop **
** ~~~~~~~~~~~~~~~~~~~~~~~ */

/* Top coordinate of the clipping window */

#define AQSetupClipTopRegAddrs                                            0x0301
#define AQ_SETUP_CLIP_TOP_Address                                        0x00C04
#define AQ_SETUP_CLIP_TOP_MSB                                                 15
#define AQ_SETUP_CLIP_TOP_LSB                                                  0
#define AQ_SETUP_CLIP_TOP_BLK                                                  0
#define AQ_SETUP_CLIP_TOP_Count                                                1
#define AQ_SETUP_CLIP_TOP_FieldMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_ReadMask                                    0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_WriteMask                                   0xFFFFFFFF
#define AQ_SETUP_CLIP_TOP_ResetValue                                  0x00000000

/* The top coordinate of the clipping window in float. */
#define AQ_SETUP_CLIP_TOP_CLIP                                              31:0
#define AQ_SETUP_CLIP_TOP_CLIP_End                                            31
#define AQ_SETUP_CLIP_TOP_CLIP_Start                                           0
#define AQ_SETUP_CLIP_TOP_CLIP_Type                                          U32

/* Register AQSetupClipRight **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Right coordinate of the clipping window */

#define AQSetupClipRightRegAddrs                                          0x0302
#define AQ_SETUP_CLIP_RIGHT_Address                                      0x00C08
#define AQ_SETUP_CLIP_RIGHT_MSB                                               15
#define AQ_SETUP_CLIP_RIGHT_LSB                                                0
#define AQ_SETUP_CLIP_RIGHT_BLK                                                0
#define AQ_SETUP_CLIP_RIGHT_Count                                              1
#define AQ_SETUP_CLIP_RIGHT_FieldMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_ReadMask                                  0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_WriteMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_RIGHT_ResetValue                                0x45000000

/* The right coordinate of the clipping window in float. This coordinate is   **
** exclusive, meaning the width is computed as Right - Left.                  */
#define AQ_SETUP_CLIP_RIGHT_CLIP                                            31:0
#define AQ_SETUP_CLIP_RIGHT_CLIP_End                                          31
#define AQ_SETUP_CLIP_RIGHT_CLIP_Start                                         0
#define AQ_SETUP_CLIP_RIGHT_CLIP_Type                                        U32

/* Register AQSetupClipBottom **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Bottom coordinate of the clipping window */

#define AQSetupClipBottomRegAddrs                                         0x0303
#define AQ_SETUP_CLIP_BOTTOM_Address                                     0x00C0C
#define AQ_SETUP_CLIP_BOTTOM_MSB                                              15
#define AQ_SETUP_CLIP_BOTTOM_LSB                                               0
#define AQ_SETUP_CLIP_BOTTOM_BLK                                               0
#define AQ_SETUP_CLIP_BOTTOM_Count                                             1
#define AQ_SETUP_CLIP_BOTTOM_FieldMask                                0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_ReadMask                                 0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_WriteMask                                0xFFFFFFFF
#define AQ_SETUP_CLIP_BOTTOM_ResetValue                               0x45000000

/* The bottom coordinate of the clipping window in float. This coordinate is  **
** exclusive, meaning the height is computed as Bottom - Top.                 */
#define AQ_SETUP_CLIP_BOTTOM_CLIP                                           31:0
#define AQ_SETUP_CLIP_BOTTOM_CLIP_End                                         31
#define AQ_SETUP_CLIP_BOTTOM_CLIP_Start                                        0
#define AQ_SETUP_CLIP_BOTTOM_CLIP_Type                                       U32

/* Register AQSetupSlopeScaledDepthBias **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* depthFactor */

#define AQSetupSlopeScaledDepthBiasRegAddrs                               0x0304
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_Address                         0x00C10
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_MSB                                  15
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_LSB                                   0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BLK                                   0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_Count                                 1
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_FieldMask                    0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_ReadMask                     0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_WriteMask                    0xFFFFFFFF
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_ResetValue                   0x00000000

/* The multiplicative part depthFactor in the formula: zInit += m *           **
** depthFactor + depthBias, in float.                                         */
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS                               31:0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS_End                             31
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS_Start                            0
#define AQ_SETUP_SLOPE_SCALED_DEPTH_BIAS_BIAS_Type                           U32

/* Register AQSetupDepthBias **
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* depthBias */

#define AQSetupDepthBiasRegAddrs                                          0x0305
#define AQ_SETUP_DEPTH_BIAS_Address                                      0x00C14
#define AQ_SETUP_DEPTH_BIAS_MSB                                               15
#define AQ_SETUP_DEPTH_BIAS_LSB                                                0
#define AQ_SETUP_DEPTH_BIAS_BLK                                                0
#define AQ_SETUP_DEPTH_BIAS_Count                                              1
#define AQ_SETUP_DEPTH_BIAS_FieldMask                                 0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_ReadMask                                  0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_WriteMask                                 0xFFFFFFFF
#define AQ_SETUP_DEPTH_BIAS_ResetValue                                0x00000000

/* The additive part depthBias in the the formula: zInit += m*depthFactor +   **
** depthBiasm in float.                                                       */
#define AQ_SETUP_DEPTH_BIAS_BIAS                                            31:0
#define AQ_SETUP_DEPTH_BIAS_BIAS_End                                          31
#define AQ_SETUP_DEPTH_BIAS_BIAS_Start                                         0
#define AQ_SETUP_DEPTH_BIAS_BIAS_Type                                        U32

/* Register AQSetupConfig **
** ~~~~~~~~~~~~~~~~~~~~~~ */

/* Render last pixel in lines */

#define AQSetupConfigRegAddrs                                             0x0306
#define AQ_SETUP_CONFIG_Address                                          0x00C18
#define AQ_SETUP_CONFIG_MSB                                                   15
#define AQ_SETUP_CONFIG_LSB                                                    0
#define AQ_SETUP_CONFIG_BLK                                                    0
#define AQ_SETUP_CONFIG_Count                                                  1
#define AQ_SETUP_CONFIG_FieldMask                                     0x00000031
#define AQ_SETUP_CONFIG_ReadMask                                      0x00000031
#define AQ_SETUP_CONFIG_WriteMask                                     0x00000031
#define AQ_SETUP_CONFIG_ResetValue                                    0x00000000

/* Enable rendering of the last pixel in a line. */
#define AQ_SETUP_CONFIG_LAST_PIXEL                                           0:0
#define AQ_SETUP_CONFIG_LAST_PIXEL_End                                         0
#define AQ_SETUP_CONFIG_LAST_PIXEL_Start                                       0
#define AQ_SETUP_CONFIG_LAST_PIXEL_Type                                      U01
#define   AQ_SETUP_CONFIG_LAST_PIXEL_DISABLE                                 0x0
#define   AQ_SETUP_CONFIG_LAST_PIXEL_ENABLE                                  0x1

/* Bugfix 15 control. */
#define AQ_SETUP_CONFIG_BUGFIX15_DISABLE                                     4:4
#define AQ_SETUP_CONFIG_BUGFIX15_DISABLE_End                                   4
#define AQ_SETUP_CONFIG_BUGFIX15_DISABLE_Start                                 4
#define AQ_SETUP_CONFIG_BUGFIX15_DISABLE_Type                                U01
#define   AQ_SETUP_CONFIG_BUGFIX15_DISABLE_ENABLE                            0x0
#define   AQ_SETUP_CONFIG_BUGFIX15_DISABLE_DISABLE                           0x1

/* Bug1773 fix. Render one line by 4 edges */
#define AQ_SETUP_CONFIG_LINE_FOUR_EDGE                                       5:5
#define AQ_SETUP_CONFIG_LINE_FOUR_EDGE_End                                     5
#define AQ_SETUP_CONFIG_LINE_FOUR_EDGE_Start                                   5
#define AQ_SETUP_CONFIG_LINE_FOUR_EDGE_Type                                  U01
#define   AQ_SETUP_CONFIG_LINE_FOUR_EDGE_ENABLE                              0x0
#define   AQ_SETUP_CONFIG_LINE_FOUR_EDGE_DISABLE                             0x1

/* Register gcregSEAreaThreshold **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Specify the threshold of the area of a triangle at which the triangle is   **
** considered large and wil be rasterized using a super-tile hierarchy to     **
** improve super-tile and linear texture locality.                            */

#define gcregSEAreaThresholdRegAddrs                                      0x0307
#define GCREG_SE_AREA_THRESHOLD_Address                                  0x00C1C
#define GCREG_SE_AREA_THRESHOLD_MSB                                           15
#define GCREG_SE_AREA_THRESHOLD_LSB                                            0
#define GCREG_SE_AREA_THRESHOLD_BLK                                            0
#define GCREG_SE_AREA_THRESHOLD_Count                                          1
#define GCREG_SE_AREA_THRESHOLD_FieldMask                             0xFFFFFFFF
#define GCREG_SE_AREA_THRESHOLD_ReadMask                              0xFFFFFFFF
#define GCREG_SE_AREA_THRESHOLD_WriteMask                             0xFFFFFFFF
#define GCREG_SE_AREA_THRESHOLD_ResetValue                            0x42000000

/* Threshold value in floating point. */
#define GCREG_SE_AREA_THRESHOLD_THRESHOLD                                   31:0
#define GCREG_SE_AREA_THRESHOLD_THRESHOLD_End                                 31
#define GCREG_SE_AREA_THRESHOLD_THRESHOLD_Start                                0
#define GCREG_SE_AREA_THRESHOLD_THRESHOLD_Type                               U32

/* Register gcregSEClipCompareRight **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* There is a precision issue in SE with very large triangles. When it        **
** computes the intersection of a point with the clipping box, it gets off by **
** a fraction of the pixel, which in some cases could cause the entire        **
** triangle to be culled. The next set of registers will add another value    **
** where SE has to compare against in order to determine in/out. In case of   **
** false positives, RA will still have valid edge equations to throw these    **
** pixels out.                                                                */

#define gcregSEClipCompareRightRegAddrs                                   0x0308
#define GCREG_SE_CLIP_COMPARE_RIGHT_Address                              0x00C20
#define GCREG_SE_CLIP_COMPARE_RIGHT_MSB                                       15
#define GCREG_SE_CLIP_COMPARE_RIGHT_LSB                                        0
#define GCREG_SE_CLIP_COMPARE_RIGHT_BLK                                        0
#define GCREG_SE_CLIP_COMPARE_RIGHT_Count                                      1
#define GCREG_SE_CLIP_COMPARE_RIGHT_FieldMask                         0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_ReadMask                          0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_WriteMask                         0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_ResetValue                        0x00000000

/* Right X value to compare against. */
#define GCREG_SE_CLIP_COMPARE_RIGHT_FL32                                    31:0
#define GCREG_SE_CLIP_COMPARE_RIGHT_FL32_End                                  31
#define GCREG_SE_CLIP_COMPARE_RIGHT_FL32_Start                                 0
#define GCREG_SE_CLIP_COMPARE_RIGHT_FL32_Type                                U32

/* Register gcregSEClipCompareBottom **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* See gcregSEClipCompareRight. */

#define gcregSEClipCompareBottomRegAddrs                                  0x0309
#define GCREG_SE_CLIP_COMPARE_BOTTOM_Address                             0x00C24
#define GCREG_SE_CLIP_COMPARE_BOTTOM_MSB                                      15
#define GCREG_SE_CLIP_COMPARE_BOTTOM_LSB                                       0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_BLK                                       0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_Count                                     1
#define GCREG_SE_CLIP_COMPARE_BOTTOM_FieldMask                        0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_ReadMask                         0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_WriteMask                        0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_ResetValue                       0x00000000

/* Right X value to compare against. */
#define GCREG_SE_CLIP_COMPARE_BOTTOM_FL32                                   31:0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_FL32_End                                 31
#define GCREG_SE_CLIP_COMPARE_BOTTOM_FL32_Start                                0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_FL32_Type                               U32

/* Register gcregSEDepthBiasClamp **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Depth bias clamping. */

#define gcregSEDepthBiasClampRegAddrs                                     0x030A
#define GCREG_SE_DEPTH_BIAS_CLAMP_Address                                0x00C28
#define GCREG_SE_DEPTH_BIAS_CLAMP_MSB                                         15
#define GCREG_SE_DEPTH_BIAS_CLAMP_LSB                                          0
#define GCREG_SE_DEPTH_BIAS_CLAMP_BLK                                          0
#define GCREG_SE_DEPTH_BIAS_CLAMP_Count                                        1
#define GCREG_SE_DEPTH_BIAS_CLAMP_FieldMask                           0xFFFFFFFF
#define GCREG_SE_DEPTH_BIAS_CLAMP_ReadMask                            0xFFFFFFFF
#define GCREG_SE_DEPTH_BIAS_CLAMP_WriteMask                           0xFFFFFFFF
#define GCREG_SE_DEPTH_BIAS_CLAMP_ResetValue                          0x00000000

/* Value for depth bias clamping. */
#define GCREG_SE_DEPTH_BIAS_CLAMP_CLAMP                                     31:0
#define GCREG_SE_DEPTH_BIAS_CLAMP_CLAMP_End                                   31
#define GCREG_SE_DEPTH_BIAS_CLAMP_CLAMP_Start                                  0
#define GCREG_SE_DEPTH_BIAS_CLAMP_CLAMP_Type                                 U32

/*******************************************************************************
**                            ~~~~~~~~~~~~~~~~~~~~                            **
**                            Module SetupEngineEx                            **
**                            ~~~~~~~~~~~~~~~~~~~~                            **
*******************************************************************************/

/* Register gcregSEClipLeftEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Left coordinate of the clipping window */

#define gcregSEClipLeftExRegAddrs                                         0x0310
#define GCREG_SE_CLIP_LEFT_EX_Address                                    0x00C40
#define GCREG_SE_CLIP_LEFT_EX_MSB                                             15
#define GCREG_SE_CLIP_LEFT_EX_LSB                                              4
#define GCREG_SE_CLIP_LEFT_EX_BLK                                              4
#define GCREG_SE_CLIP_LEFT_EX_Count                                           15
#define GCREG_SE_CLIP_LEFT_EX_FieldMask                               0xFFFFFFFF
#define GCREG_SE_CLIP_LEFT_EX_ReadMask                                0xFFFFFFFF
#define GCREG_SE_CLIP_LEFT_EX_WriteMask                               0xFFFFFFFF
#define GCREG_SE_CLIP_LEFT_EX_ResetValue                              0x00000000

/* The left coordinate of the clipping window in float. */
#define GCREG_SE_CLIP_LEFT_EX_CLIP                                          31:0
#define GCREG_SE_CLIP_LEFT_EX_CLIP_End                                        31
#define GCREG_SE_CLIP_LEFT_EX_CLIP_Start                                       0
#define GCREG_SE_CLIP_LEFT_EX_CLIP_Type                                      U32

/* Register gcregSEClipTopEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Top coordinate of the clipping window */

#define gcregSEClipTopExRegAddrs                                          0x0320
#define GCREG_SE_CLIP_TOP_EX_Address                                     0x00C80
#define GCREG_SE_CLIP_TOP_EX_MSB                                              15
#define GCREG_SE_CLIP_TOP_EX_LSB                                               4
#define GCREG_SE_CLIP_TOP_EX_BLK                                               4
#define GCREG_SE_CLIP_TOP_EX_Count                                            15
#define GCREG_SE_CLIP_TOP_EX_FieldMask                                0xFFFFFFFF
#define GCREG_SE_CLIP_TOP_EX_ReadMask                                 0xFFFFFFFF
#define GCREG_SE_CLIP_TOP_EX_WriteMask                                0xFFFFFFFF
#define GCREG_SE_CLIP_TOP_EX_ResetValue                               0x00000000

/* The top coordinate of the clipping window in float. */
#define GCREG_SE_CLIP_TOP_EX_CLIP                                           31:0
#define GCREG_SE_CLIP_TOP_EX_CLIP_End                                         31
#define GCREG_SE_CLIP_TOP_EX_CLIP_Start                                        0
#define GCREG_SE_CLIP_TOP_EX_CLIP_Type                                       U32

/* Register gcregSEClipRightEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Right coordinate of the clipping window */

#define gcregSEClipRightExRegAddrs                                        0x0330
#define GCREG_SE_CLIP_RIGHT_EX_Address                                   0x00CC0
#define GCREG_SE_CLIP_RIGHT_EX_MSB                                            15
#define GCREG_SE_CLIP_RIGHT_EX_LSB                                             4
#define GCREG_SE_CLIP_RIGHT_EX_BLK                                             4
#define GCREG_SE_CLIP_RIGHT_EX_Count                                          15
#define GCREG_SE_CLIP_RIGHT_EX_FieldMask                              0xFFFFFFFF
#define GCREG_SE_CLIP_RIGHT_EX_ReadMask                               0xFFFFFFFF
#define GCREG_SE_CLIP_RIGHT_EX_WriteMask                              0xFFFFFFFF
#define GCREG_SE_CLIP_RIGHT_EX_ResetValue                             0x45000000

/* The right coordinate of the clipping window in float. This coordinate is   **
** exclusive, meaning the width is computed as Right - Left.                  */
#define GCREG_SE_CLIP_RIGHT_EX_CLIP                                         31:0
#define GCREG_SE_CLIP_RIGHT_EX_CLIP_End                                       31
#define GCREG_SE_CLIP_RIGHT_EX_CLIP_Start                                      0
#define GCREG_SE_CLIP_RIGHT_EX_CLIP_Type                                     U32

/* Register gcregSEClipBottomEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Bottom coordinate of the clipping window */

#define gcregSEClipBottomExRegAddrs                                       0x0340
#define GCREG_SE_CLIP_BOTTOM_EX_Address                                  0x00D00
#define GCREG_SE_CLIP_BOTTOM_EX_MSB                                           15
#define GCREG_SE_CLIP_BOTTOM_EX_LSB                                            4
#define GCREG_SE_CLIP_BOTTOM_EX_BLK                                            4
#define GCREG_SE_CLIP_BOTTOM_EX_Count                                         15
#define GCREG_SE_CLIP_BOTTOM_EX_FieldMask                             0xFFFFFFFF
#define GCREG_SE_CLIP_BOTTOM_EX_ReadMask                              0xFFFFFFFF
#define GCREG_SE_CLIP_BOTTOM_EX_WriteMask                             0xFFFFFFFF
#define GCREG_SE_CLIP_BOTTOM_EX_ResetValue                            0x45000000

/* The bottom coordinate of the clipping window in float. This coordinate is  **
** exclusive, meaning the height is computed as Bottom - Top.                 */
#define GCREG_SE_CLIP_BOTTOM_EX_CLIP                                        31:0
#define GCREG_SE_CLIP_BOTTOM_EX_CLIP_End                                      31
#define GCREG_SE_CLIP_BOTTOM_EX_CLIP_Start                                     0
#define GCREG_SE_CLIP_BOTTOM_EX_CLIP_Type                                    U32

/* Register gcregSEClipCompareRightEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* There is a precision issue in SE with very large triangles. When it        **
** computes the intersection of a point with the clipping box, it gets off by **
** a fraction of the pixel, which in some cases could cause the entire        **
** triangle to be culled. The next set of registers will add another value    **
** where SE has to compare against in order to determine in/out. In case of   **
** false positives, RA will still have valid edge equations to throw these    **
** pixels out.                                                                */

#define gcregSEClipCompareRightExRegAddrs                                 0x0350
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_Address                           0x00D40
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_MSB                                    15
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_LSB                                     4
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_BLK                                     4
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_Count                                  15
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_FieldMask                      0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_ReadMask                       0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_WriteMask                      0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_ResetValue                     0x00000000

/* Right X value to compare against. */
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_FL32                                 31:0
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_FL32_End                               31
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_FL32_Start                              0
#define GCREG_SE_CLIP_COMPARE_RIGHT_EX_FL32_Type                             U32

/* Register gcregSEClipCompareBottomEx (15 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* See gcregSEClipCompareRightEx. */

#define gcregSEClipCompareBottomExRegAddrs                                0x0360
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_Address                          0x00D80
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_MSB                                   15
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_LSB                                    4
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_BLK                                    4
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_Count                                 15
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_FieldMask                     0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_ReadMask                      0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_WriteMask                     0xFFFFFFFF
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_ResetValue                    0x00000000

/* Right X value to compare against. */
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_FL32                                31:0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_FL32_End                              31
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_FL32_Start                             0
#define GCREG_SE_CLIP_COMPARE_BOTTOM_EX_FL32_Type                            U32


#endif /* __AQSetupReg_h__ */
