/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* MC ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_MC_H__
#define __GC_PROBE_MC_H__

#define cmdProbeCount_McFcCCacheReq                                        0x0001
#define cmdProbeCount_McFcCCacheMiss                                       0x0002
#define cmdProbeCount_McFcXCacheReq                                        0x0003
#define cmdProbeCount_McFcXCacheMiss                                       0x0004
#define cmdProbeCount_McFcZCacheReq                                        0x0005
#define cmdProbeCount_McFcZCacheMiss                                       0x0006
#define cmdProbeCount_McMmuMasterCacheReq                                  0x0007
#define cmdProbeCount_McMmuMasterCacheMiss                                 0x0008
#define cmdProbeCount_McMmuSlaveCacheReq                                   0x0009
#define cmdProbeCount_McMmuSlaveCacheMiss                                  0x000A
#define cmdProbeCount_McColorWr8BytePreCompress                            0x000B
#define cmdProbeCount_McColorWr8BytePostCompress                           0x000C
#define cmdProbeCount_McDepthWr8BytePreCompress                            0x000D
#define cmdProbeCount_McDepthWr8BytePostCompress                           0x000E
#define cmdProbeCount_McCompressor0Cycles                                  0x000F
#define cmdProbeCount_McCompressor1Cycles                                  0x0010
#define cmdProbeCount_McDecompressor0Cycles                                0x0011
#define cmdProbeCount_McDecompressor1Cycles                                0x0012
#define cmdProbeCycle_McBusy                                               0x0020
#define cmdProbeCycle_BltWrReqVldAndMcRdy                                  0x0021
#define cmdProbeCycle_BltWrReqVldAndMcNotRdy                               0x0022
#define cmdProbeCycle_BltRdReqVldAndMcRdy                                  0x0023
#define cmdProbeCycle_BltRdReqVldAndMcNotRdy                               0x0024
#define cmdProbeCycle_BltWrDataVldAndMcRdy                                 0x0025
#define cmdProbeCycle_BltWrDataVldAndMcNotRdy                              0x0026
#define cmdProbeCycle_BltRdDataMcRrbVld                                    0x0027
#define cmdProbeCycle_McGlobalTimerStartLo                                 0x00FA
#define cmdProbeCycle_McGlobalTimerStartHi                                 0x00FB
#define cmdProbeCycle_McGlobalTimerEndLo                                   0x00FC
#define cmdProbeCycle_McGlobalTimerEndHi                                   0x00FD
#define cmdProbeCycle_McGlobalTimerLo                                      0x00FE
#define cmdProbeCycle_McGlobalTimerHi                                      0x00FF
#define cmdFPGAProbeCount_PeCRdBytePostCompress                                0x0801
#define cmdFPGAProbeCount_PeCWrBytePostCompress                                0x0802
#define cmdFPGAProbeCount_PeCRdReqPostCompress                                 0x0803
#define cmdFPGAProbeCount_PeCWrReqPostCompress                                 0x0804
#define cmdFPGAProbeCount_PeZRdBytePostCompress                                0x0805
#define cmdFPGAProbeCount_PeZWrBytePostCompress                                0x0806
#define cmdFPGAProbeCount_PeZRdReqPostCompress                                 0x0807
#define cmdFPGAProbeCount_PeZWrReqPostCompress                                 0x0808
#define cmdFPGAProbeCount_TxRdBytePostCompress                                 0x0809
#define cmdFPGAProbeCount_TxRdReqPostCompress                                  0x080A
#define cmdFPGAProbeCount_RaRdBytePostCompress                                 0x080B
#define cmdFPGAProbeCount_RaWrBytePostCompress                                 0x080C
#define cmdFPGAProbeCount_RaRdReqPostCompress                                  0x080D
#define cmdFPGAProbeCount_RaWrReqPostCompress                                  0x080E
#define cmdFPGAProbeCount_BltRdBytePostCompress                                0x080F
#define cmdFPGAProbeCount_BltWrBytePostCompress                                0x0810
#define cmdFPGAProbeCount_BltRdReqPostCompress                                 0x0811
#define cmdFPGAProbeCount_BltWrReqPostCompress                                 0x0812
#define cmdFPGAProbeCount_CCacheReq                                            0x0813
#define cmdFPGAProbeCount_CCacheMissReq                                        0x0814
#define cmdFPGAProbeCount_XCacheReq                                            0x0815
#define cmdFPGAProbeCount_XCacheMissReq                                        0x0816
#define cmdFPGAProbeCount_ZCacheReq                                            0x0817
#define cmdFPGAProbeCount_ZCacheMissReq                                        0x0818
#define cmdFPGAProbeCount_MmuMasterCacheReq                                    0x0819
#define cmdFPGAProbeCount_MmuMasterCacheMissReq                                0x081A
#define cmdFPGAProbeCount_MmuSlaveCacheReq                                     0x081B
#define cmdFPGAProbeCount_MmuSlaveCacheMissReq                                 0x081C

enum cmeMCPROBE
{
    cmvProbeCount_McFcCCacheReq,
    cmvProbeCount_McFcCCacheMiss,
    cmvProbeCount_McFcXCacheReq,
    cmvProbeCount_McFcXCacheMiss,
    cmvProbeCount_McFcZCacheReq,
    cmvProbeCount_McFcZCacheMiss,
    cmvProbeCount_McMmuMasterCacheReq,
    cmvProbeCount_McMmuMasterCacheMiss,
    cmvProbeCount_McMmuSlaveCacheReq,
    cmvProbeCount_McMmuSlaveCacheMiss,
    cmvProbeCount_McColorWr8BytePreCompress,
    cmvProbeCount_McColorWr8BytePostCompress,
    cmvProbeCount_McDepthWr8BytePreCompress,
    cmvProbeCount_McDepthWr8BytePostCompress,
    cmvProbeCount_McCompressor0Cycles,
    cmvProbeCount_McCompressor1Cycles,
    cmvProbeCount_McDecompressor0Cycles,
    cmvProbeCount_McDecompressor1Cycles,
    cmvProbeCycle_McBusy,
    cmvProbeCycle_BltWrReqVldAndMcRdy,
    cmvProbeCycle_BltWrReqVldAndMcNotRdy,
    cmvProbeCycle_BltRdReqVldAndMcRdy,
    cmvProbeCycle_BltRdReqVldAndMcNotRdy,
    cmvProbeCycle_BltWrDataVldAndMcRdy,
    cmvProbeCycle_BltWrDataVldAndMcNotRdy,
    cmvProbeCycle_BltRdDataMcRrbVld,
    cmvProbeCycle_McGlobalTimerStartLo,
    cmvProbeCycle_McGlobalTimerStartHi,
    cmvProbeCycle_McGlobalTimerEndLo,
    cmvProbeCycle_McGlobalTimerEndHi,
    cmvProbeCycle_McGlobalTimerLo,
    cmvProbeCycle_McGlobalTimerHi,
    cmvFPGAProbeCount_PeCRdBytePostCompress,
    cmvFPGAProbeCount_PeCWrBytePostCompress,
    cmvFPGAProbeCount_PeCRdReqPostCompress,
    cmvFPGAProbeCount_PeCWrReqPostCompress,
    cmvFPGAProbeCount_PeZRdBytePostCompress,
    cmvFPGAProbeCount_PeZWrBytePostCompress,
    cmvFPGAProbeCount_PeZRdReqPostCompress,
    cmvFPGAProbeCount_PeZWrReqPostCompress,
    cmvFPGAProbeCount_TxRdBytePostCompress,
    cmvFPGAProbeCount_TxRdReqPostCompress,
    cmvFPGAProbeCount_RaRdBytePostCompress,
    cmvFPGAProbeCount_RaWrBytePostCompress,
    cmvFPGAProbeCount_RaRdReqPostCompress,
    cmvFPGAProbeCount_RaWrReqPostCompress,
    cmvFPGAProbeCount_BltRdBytePostCompress,
    cmvFPGAProbeCount_BltWrBytePostCompress,
    cmvFPGAProbeCount_BltRdReqPostCompress,
    cmvFPGAProbeCount_BltWrReqPostCompress,
    cmvFPGAProbeCount_CCacheReq,
    cmvFPGAProbeCount_CCacheMissReq,
    cmvFPGAProbeCount_XCacheReq,
    cmvFPGAProbeCount_XCacheMissReq,
    cmvFPGAProbeCount_ZCacheReq,
    cmvFPGAProbeCount_ZCacheMissReq,
    cmvFPGAProbeCount_MmuMasterCacheReq,
    cmvFPGAProbeCount_MmuMasterCacheMissReq,
    cmvFPGAProbeCount_MmuSlaveCacheReq,
    cmvFPGAProbeCount_MmuSlaveCacheMissReq,
    cmvMC_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoMCProbeMap
{
public:
    cmoMCProbeMap()
    {
        probeMap[cmvProbeCount_McFcCCacheReq                ] = cmdProbeCount_McFcCCacheReq;
        probeMap[cmvProbeCount_McFcCCacheMiss               ] = cmdProbeCount_McFcCCacheMiss;
        probeMap[cmvProbeCount_McFcXCacheReq                ] = cmdProbeCount_McFcXCacheReq;
        probeMap[cmvProbeCount_McFcXCacheMiss               ] = cmdProbeCount_McFcXCacheMiss;
        probeMap[cmvProbeCount_McFcZCacheReq                ] = cmdProbeCount_McFcZCacheReq;
        probeMap[cmvProbeCount_McFcZCacheMiss               ] = cmdProbeCount_McFcZCacheMiss;
        probeMap[cmvProbeCount_McMmuMasterCacheReq          ] = cmdProbeCount_McMmuMasterCacheReq;
        probeMap[cmvProbeCount_McMmuMasterCacheMiss         ] = cmdProbeCount_McMmuMasterCacheMiss;
        probeMap[cmvProbeCount_McMmuSlaveCacheReq           ] = cmdProbeCount_McMmuSlaveCacheReq;
        probeMap[cmvProbeCount_McMmuSlaveCacheMiss          ] = cmdProbeCount_McMmuSlaveCacheMiss;
        probeMap[cmvProbeCount_McColorWr8BytePreCompress    ] = cmdProbeCount_McColorWr8BytePreCompress;
        probeMap[cmvProbeCount_McColorWr8BytePostCompress   ] = cmdProbeCount_McColorWr8BytePostCompress;
        probeMap[cmvProbeCount_McDepthWr8BytePreCompress    ] = cmdProbeCount_McDepthWr8BytePreCompress;
        probeMap[cmvProbeCount_McDepthWr8BytePostCompress   ] = cmdProbeCount_McDepthWr8BytePostCompress;
        probeMap[cmvProbeCount_McCompressor0Cycles          ] = cmdProbeCount_McCompressor0Cycles;
        probeMap[cmvProbeCount_McCompressor1Cycles          ] = cmdProbeCount_McCompressor1Cycles;
        probeMap[cmvProbeCount_McDecompressor0Cycles        ] = cmdProbeCount_McDecompressor0Cycles;
        probeMap[cmvProbeCount_McDecompressor1Cycles        ] = cmdProbeCount_McDecompressor1Cycles;
        probeMap[cmvProbeCycle_McBusy                       ] = cmdProbeCycle_McBusy;
        probeMap[cmvProbeCycle_BltWrReqVldAndMcRdy          ] = cmdProbeCycle_BltWrReqVldAndMcRdy;
        probeMap[cmvProbeCycle_BltWrReqVldAndMcNotRdy       ] = cmdProbeCycle_BltWrReqVldAndMcNotRdy;
        probeMap[cmvProbeCycle_BltRdReqVldAndMcRdy          ] = cmdProbeCycle_BltRdReqVldAndMcRdy;
        probeMap[cmvProbeCycle_BltRdReqVldAndMcNotRdy       ] = cmdProbeCycle_BltRdReqVldAndMcNotRdy;
        probeMap[cmvProbeCycle_BltWrDataVldAndMcRdy         ] = cmdProbeCycle_BltWrDataVldAndMcRdy;
        probeMap[cmvProbeCycle_BltWrDataVldAndMcNotRdy      ] = cmdProbeCycle_BltWrDataVldAndMcNotRdy;
        probeMap[cmvProbeCycle_BltRdDataMcRrbVld            ] = cmdProbeCycle_BltRdDataMcRrbVld;
        probeMap[cmvProbeCycle_McGlobalTimerStartLo         ] = cmdProbeCycle_McGlobalTimerStartLo;
        probeMap[cmvProbeCycle_McGlobalTimerStartHi         ] = cmdProbeCycle_McGlobalTimerStartHi;
        probeMap[cmvProbeCycle_McGlobalTimerEndLo           ] = cmdProbeCycle_McGlobalTimerEndLo;
        probeMap[cmvProbeCycle_McGlobalTimerEndHi           ] = cmdProbeCycle_McGlobalTimerEndHi;
        probeMap[cmvProbeCycle_McGlobalTimerLo              ] = cmdProbeCycle_McGlobalTimerLo;
        probeMap[cmvProbeCycle_McGlobalTimerHi              ] = cmdProbeCycle_McGlobalTimerHi;
        probeMap[cmvFPGAProbeCount_PeCRdBytePostCompress    ] = cmdFPGAProbeCount_PeCRdBytePostCompress;
        probeMap[cmvFPGAProbeCount_PeCWrBytePostCompress    ] = cmdFPGAProbeCount_PeCWrBytePostCompress;
        probeMap[cmvFPGAProbeCount_PeCRdReqPostCompress     ] = cmdFPGAProbeCount_PeCRdReqPostCompress;
        probeMap[cmvFPGAProbeCount_PeCWrReqPostCompress     ] = cmdFPGAProbeCount_PeCWrReqPostCompress;
        probeMap[cmvFPGAProbeCount_PeZRdBytePostCompress    ] = cmdFPGAProbeCount_PeZRdBytePostCompress;
        probeMap[cmvFPGAProbeCount_PeZWrBytePostCompress    ] = cmdFPGAProbeCount_PeZWrBytePostCompress;
        probeMap[cmvFPGAProbeCount_PeZRdReqPostCompress     ] = cmdFPGAProbeCount_PeZRdReqPostCompress;
        probeMap[cmvFPGAProbeCount_PeZWrReqPostCompress     ] = cmdFPGAProbeCount_PeZWrReqPostCompress;
        probeMap[cmvFPGAProbeCount_TxRdBytePostCompress     ] = cmdFPGAProbeCount_TxRdBytePostCompress;
        probeMap[cmvFPGAProbeCount_TxRdReqPostCompress      ] = cmdFPGAProbeCount_TxRdReqPostCompress;
        probeMap[cmvFPGAProbeCount_RaRdBytePostCompress     ] = cmdFPGAProbeCount_RaRdBytePostCompress;
        probeMap[cmvFPGAProbeCount_RaWrBytePostCompress     ] = cmdFPGAProbeCount_RaWrBytePostCompress;
        probeMap[cmvFPGAProbeCount_RaRdReqPostCompress      ] = cmdFPGAProbeCount_RaRdReqPostCompress;
        probeMap[cmvFPGAProbeCount_RaWrReqPostCompress      ] = cmdFPGAProbeCount_RaWrReqPostCompress;
        probeMap[cmvFPGAProbeCount_BltRdBytePostCompress    ] = cmdFPGAProbeCount_BltRdBytePostCompress;
        probeMap[cmvFPGAProbeCount_BltWrBytePostCompress    ] = cmdFPGAProbeCount_BltWrBytePostCompress;
        probeMap[cmvFPGAProbeCount_BltRdReqPostCompress     ] = cmdFPGAProbeCount_BltRdReqPostCompress;
        probeMap[cmvFPGAProbeCount_BltWrReqPostCompress     ] = cmdFPGAProbeCount_BltWrReqPostCompress;
        probeMap[cmvFPGAProbeCount_CCacheReq                ] = cmdFPGAProbeCount_CCacheReq;
        probeMap[cmvFPGAProbeCount_CCacheMissReq            ] = cmdFPGAProbeCount_CCacheMissReq;
        probeMap[cmvFPGAProbeCount_XCacheReq                ] = cmdFPGAProbeCount_XCacheReq;
        probeMap[cmvFPGAProbeCount_XCacheMissReq            ] = cmdFPGAProbeCount_XCacheMissReq;
        probeMap[cmvFPGAProbeCount_ZCacheReq                ] = cmdFPGAProbeCount_ZCacheReq;
        probeMap[cmvFPGAProbeCount_ZCacheMissReq            ] = cmdFPGAProbeCount_ZCacheMissReq;
        probeMap[cmvFPGAProbeCount_MmuMasterCacheReq        ] = cmdFPGAProbeCount_MmuMasterCacheReq;
        probeMap[cmvFPGAProbeCount_MmuMasterCacheMissReq    ] = cmdFPGAProbeCount_MmuMasterCacheMissReq;
        probeMap[cmvFPGAProbeCount_MmuSlaveCacheReq         ] = cmdFPGAProbeCount_MmuSlaveCacheReq;
        probeMap[cmvFPGAProbeCount_MmuSlaveCacheMissReq     ] = cmdFPGAProbeCount_MmuSlaveCacheMissReq;

        probeCmodelAttributesMap[cmvProbeCount_McFcCCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McFcCCacheMiss               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McFcXCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McFcXCacheMiss               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McFcZCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McFcZCacheMiss               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McMmuMasterCacheReq          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McMmuMasterCacheMiss         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McMmuSlaveCacheReq           ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McMmuSlaveCacheMiss          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McColorWr8BytePreCompress    ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_McColorWr8BytePostCompress   ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_McDepthWr8BytePreCompress    ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_McDepthWr8BytePostCompress   ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_McCompressor0Cycles          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McCompressor1Cycles          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McDecompressor0Cycles        ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_McDecompressor1Cycles        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McBusy                       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltWrReqVldAndMcRdy          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltWrReqVldAndMcNotRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltRdReqVldAndMcRdy          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltRdReqVldAndMcNotRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltWrDataVldAndMcRdy         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltWrDataVldAndMcNotRdy      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltRdDataMcRrbVld            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerStartLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerStartHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerEndLo           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerEndHi           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerLo              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_McGlobalTimerHi              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeCRdBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeCWrBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeCRdReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeCWrReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZRdBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZWrBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZRdReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZWrReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_TxRdBytePostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_TxRdReqPostCompress      ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_RaRdBytePostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_RaWrBytePostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_RaRdReqPostCompress      ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_RaWrReqPostCompress      ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_BltRdBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_BltWrBytePostCompress    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_BltRdReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_BltWrReqPostCompress     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_CCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_CCacheMissReq            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_XCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_XCacheMissReq            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ZCacheReq                ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ZCacheMissReq            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_MmuMasterCacheReq        ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_MmuMasterCacheMissReq    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_MmuSlaveCacheReq         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_MmuSlaveCacheMissReq     ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvMC_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvMC_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvMC_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_MC_H__

