/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* FE ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_FE_H__
#define __GC_PROBE_FE_H__

#define cmdProbeCount_FeVtx                                                0x0001
#define cmdProbeCount_FeIdxCacheMiss                                       0x0002
#define cmdProbeCount_FeIdxCacheReq                                        0x0003
#define cmdProbeCount_FeVldWdRdy                                           0x0004
#define cmdProbeCount_Fe2WdDataRCacheReq                                   0x0005
#define cmdProbeCount_Fe2WdDataRCacheMiss                                  0x0006
#define cmdProbeCycle_FeIdxFsmCycle                                        0x0007
#define cmdProbeCycle_FeBusy                                               0x0010
#define cmdProbeCycle_FeVldWdNotRdyData                                    0x0011
#define cmdProbeCycle_FeVldWdNotRdyStateload                               0x0012
#define cmdProbeCycle_FeWaitForSemaphorePe                                 0x0013
#define cmdProbeCycle_FeWaitForSemaphoreBlt                                0x0014
#define cmdProbeCycle_FeWaitClusterAssign                                  0x0015
#define cmdProbeCycle_Fe2WdNotVldData                                      0x0016
#define cmdProbeCycle_FeGlobalTimerStartLo                                 0x00FA
#define cmdProbeCycle_FeGlobalTimerStartHi                                 0x00FB
#define cmdProbeCycle_FeGlobalTimerEndLo                                   0x00FC
#define cmdProbeCycle_FeGlobalTimerEndHi                                   0x00FD
#define cmdProbeCycle_FeGlobalTimerLo                                      0x00FE
#define cmdProbeCycle_FeGlobalTimerHi                                      0x00FF
#define cmdFPGAProbeCount_Vtx                                                  0x0801
#define cmdFPGAProbeCount_IdxCacheMiss                                         0x0802
#define cmdFPGAProbeCount_IdxCacheReq                                          0x0803
#define cmdFPGAProbeCount_VtxCacheMiss                                         0x0804
#define cmdFPGAProbeCount_VtxCacheReq                                          0x0805
#define cmdFPGAProbeCount_FE2McRdReq                                           0x0806
#define cmdFPGAProbeCount_FE2McRdByte                                          0x0807
#define cmdFPGAProbeCycle_FeBusy                                               0x0C01
#define cmdFPGAProbeCycle_FeVldAndShRdy                                        0x0C02
#define cmdFPGAProbeCycle_FeVldAndShNotRdy                                     0x0C03
#define cmdFPGAProbeCycle_FeNotVldAndShRdy                                     0x0C04
#define cmdFPGAProbeCycle_FeNotVldAndShNotRdy                                  0x0C05
#define cmdFPGAProbeCycle_IdxCacheNotRdy                                       0x0C06
#define cmdFPGAProbeCycle_VtxCacheNotRdy                                       0x0C07
#define cmd64BITProbeCount_FeVtxLo                                              0x1001
#define cmd64BITProbeCount_FeVtxHi                                              0x1002
#define cmd64BITProbeCount_FePrimLo                                             0x1003
#define cmd64BITProbeCount_FePrimHi                                             0x1004

enum cmeFEPROBE
{
    cmvProbeCount_FeVtx,
    cmvProbeCount_FeIdxCacheMiss,
    cmvProbeCount_FeIdxCacheReq,
    cmvProbeCount_FeVldWdRdy,
    cmvProbeCount_Fe2WdDataRCacheReq,
    cmvProbeCount_Fe2WdDataRCacheMiss,
    cmvProbeCycle_FeIdxFsmCycle,
    cmvProbeCycle_FeBusy,
    cmvProbeCycle_FeVldWdNotRdyData,
    cmvProbeCycle_FeVldWdNotRdyStateload,
    cmvProbeCycle_FeWaitForSemaphorePe,
    cmvProbeCycle_FeWaitForSemaphoreBlt,
    cmvProbeCycle_FeWaitClusterAssign,
    cmvProbeCycle_Fe2WdNotVldData,
    cmvProbeCycle_FeGlobalTimerStartLo,
    cmvProbeCycle_FeGlobalTimerStartHi,
    cmvProbeCycle_FeGlobalTimerEndLo,
    cmvProbeCycle_FeGlobalTimerEndHi,
    cmvProbeCycle_FeGlobalTimerLo,
    cmvProbeCycle_FeGlobalTimerHi,
    cmvFPGAProbeCount_Vtx,
    cmvFPGAProbeCount_IdxCacheMiss,
    cmvFPGAProbeCount_IdxCacheReq,
    cmvFPGAProbeCount_VtxCacheMiss,
    cmvFPGAProbeCount_VtxCacheReq,
    cmvFPGAProbeCount_FE2McRdReq,
    cmvFPGAProbeCount_FE2McRdByte,
    cmvFPGAProbeCycle_FeBusy,
    cmvFPGAProbeCycle_FeVldAndShRdy,
    cmvFPGAProbeCycle_FeVldAndShNotRdy,
    cmvFPGAProbeCycle_FeNotVldAndShRdy,
    cmvFPGAProbeCycle_FeNotVldAndShNotRdy,
    cmvFPGAProbeCycle_IdxCacheNotRdy,
    cmvFPGAProbeCycle_VtxCacheNotRdy,
    cmv64BITProbeCount_FeVtxLo,
    cmv64BITProbeCount_FeVtxHi,
    cmv64BITProbeCount_FePrimLo,
    cmv64BITProbeCount_FePrimHi,
    cmvFE_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoFEProbeMap
{
public:
    cmoFEProbeMap()
    {
        probeMap[cmvProbeCount_FeVtx                        ] = cmdProbeCount_FeVtx;
        probeMap[cmvProbeCount_FeIdxCacheMiss               ] = cmdProbeCount_FeIdxCacheMiss;
        probeMap[cmvProbeCount_FeIdxCacheReq                ] = cmdProbeCount_FeIdxCacheReq;
        probeMap[cmvProbeCount_FeVldWdRdy                   ] = cmdProbeCount_FeVldWdRdy;
        probeMap[cmvProbeCount_Fe2WdDataRCacheReq           ] = cmdProbeCount_Fe2WdDataRCacheReq;
        probeMap[cmvProbeCount_Fe2WdDataRCacheMiss          ] = cmdProbeCount_Fe2WdDataRCacheMiss;
        probeMap[cmvProbeCycle_FeIdxFsmCycle                ] = cmdProbeCycle_FeIdxFsmCycle;
        probeMap[cmvProbeCycle_FeBusy                       ] = cmdProbeCycle_FeBusy;
        probeMap[cmvProbeCycle_FeVldWdNotRdyData            ] = cmdProbeCycle_FeVldWdNotRdyData;
        probeMap[cmvProbeCycle_FeVldWdNotRdyStateload       ] = cmdProbeCycle_FeVldWdNotRdyStateload;
        probeMap[cmvProbeCycle_FeWaitForSemaphorePe         ] = cmdProbeCycle_FeWaitForSemaphorePe;
        probeMap[cmvProbeCycle_FeWaitForSemaphoreBlt        ] = cmdProbeCycle_FeWaitForSemaphoreBlt;
        probeMap[cmvProbeCycle_FeWaitClusterAssign          ] = cmdProbeCycle_FeWaitClusterAssign;
        probeMap[cmvProbeCycle_Fe2WdNotVldData              ] = cmdProbeCycle_Fe2WdNotVldData;
        probeMap[cmvProbeCycle_FeGlobalTimerStartLo         ] = cmdProbeCycle_FeGlobalTimerStartLo;
        probeMap[cmvProbeCycle_FeGlobalTimerStartHi         ] = cmdProbeCycle_FeGlobalTimerStartHi;
        probeMap[cmvProbeCycle_FeGlobalTimerEndLo           ] = cmdProbeCycle_FeGlobalTimerEndLo;
        probeMap[cmvProbeCycle_FeGlobalTimerEndHi           ] = cmdProbeCycle_FeGlobalTimerEndHi;
        probeMap[cmvProbeCycle_FeGlobalTimerLo              ] = cmdProbeCycle_FeGlobalTimerLo;
        probeMap[cmvProbeCycle_FeGlobalTimerHi              ] = cmdProbeCycle_FeGlobalTimerHi;
        probeMap[cmvFPGAProbeCount_Vtx                      ] = cmdFPGAProbeCount_Vtx;
        probeMap[cmvFPGAProbeCount_IdxCacheMiss             ] = cmdFPGAProbeCount_IdxCacheMiss;
        probeMap[cmvFPGAProbeCount_IdxCacheReq              ] = cmdFPGAProbeCount_IdxCacheReq;
        probeMap[cmvFPGAProbeCount_VtxCacheMiss             ] = cmdFPGAProbeCount_VtxCacheMiss;
        probeMap[cmvFPGAProbeCount_VtxCacheReq              ] = cmdFPGAProbeCount_VtxCacheReq;
        probeMap[cmvFPGAProbeCount_FE2McRdReq               ] = cmdFPGAProbeCount_FE2McRdReq;
        probeMap[cmvFPGAProbeCount_FE2McRdByte              ] = cmdFPGAProbeCount_FE2McRdByte;
        probeMap[cmvFPGAProbeCycle_FeBusy                   ] = cmdFPGAProbeCycle_FeBusy;
        probeMap[cmvFPGAProbeCycle_FeVldAndShRdy            ] = cmdFPGAProbeCycle_FeVldAndShRdy;
        probeMap[cmvFPGAProbeCycle_FeVldAndShNotRdy         ] = cmdFPGAProbeCycle_FeVldAndShNotRdy;
        probeMap[cmvFPGAProbeCycle_FeNotVldAndShRdy         ] = cmdFPGAProbeCycle_FeNotVldAndShRdy;
        probeMap[cmvFPGAProbeCycle_FeNotVldAndShNotRdy      ] = cmdFPGAProbeCycle_FeNotVldAndShNotRdy;
        probeMap[cmvFPGAProbeCycle_IdxCacheNotRdy           ] = cmdFPGAProbeCycle_IdxCacheNotRdy;
        probeMap[cmvFPGAProbeCycle_VtxCacheNotRdy           ] = cmdFPGAProbeCycle_VtxCacheNotRdy;
        probeMap[cmv64BITProbeCount_FeVtxLo                 ] = cmd64BITProbeCount_FeVtxLo;
        probeMap[cmv64BITProbeCount_FeVtxHi                 ] = cmd64BITProbeCount_FeVtxHi;
        probeMap[cmv64BITProbeCount_FePrimLo                ] = cmd64BITProbeCount_FePrimLo;
        probeMap[cmv64BITProbeCount_FePrimHi                ] = cmd64BITProbeCount_FePrimHi;

        probeCmodelAttributesMap[cmvProbeCount_FeVtx                        ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FeIdxCacheMiss               ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FeIdxCacheReq                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FeVldWdRdy                   ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_Fe2WdDataRCacheReq           ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_Fe2WdDataRCacheMiss          ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_FeIdxFsmCycle                ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeBusy                       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeVldWdNotRdyData            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeVldWdNotRdyStateload       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeWaitForSemaphorePe         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeWaitForSemaphoreBlt        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeWaitClusterAssign          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Fe2WdNotVldData              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerStartLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerStartHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerEndLo           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerEndHi           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerLo              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FeGlobalTimerHi              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_Vtx                      ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_IdxCacheMiss             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_IdxCacheReq              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_VtxCacheMiss             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_VtxCacheReq              ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_FE2McRdReq               ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_FE2McRdByte              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_FeBusy                   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_FeVldAndShRdy            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_FeVldAndShNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_FeNotVldAndShRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_FeNotVldAndShNotRdy      ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_IdxCacheNotRdy           ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_VtxCacheNotRdy           ] = 0;
        probeCmodelAttributesMap[cmv64BITProbeCount_FeVtxLo                 ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_FeVtxHi                 ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_FePrimLo                ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_FePrimHi                ] = 1;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvFE_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvFE_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvFE_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_FE_H__

