/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* TFB ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_TFB_H__
#define __GC_PROBE_TFB_H__

#define cmdProbeCount_TfbUscRdReq                                          0x0001
#define cmdProbeCount_TfbUscWrReq                                          0x0002
#define cmdProbeCount_TfbVldAndPpaRdy                                      0x0003
#define cmdProbeCycle_TfbVldAndPpaNotRdy                                   0x0015
#define cmdProbeCycle_TfbBusy                                              0x0010
#define cmdProbeCycle_Tfb2UscRdTotalLatency                                0x0011
#define cmdProbeCycle_Tfb2UscWrTotalLatency                                0x0012
#define cmdProbeCycle_TfbRdReqAndUscNotRdy                                 0x0013
#define cmdProbeCycle_TfbWrReqAndUscNotRdy                                 0x0014
#define cmdProbeCycle_TfbDataUscVldAndTfbRdy                               0x0016
#define cmdProbeCycle_TfbDataUscVldAndTfbNotRdy                            0x0017
#define cmdProbeCycle_TfbDataTfbVldAndUscRdy                               0x0018
#define cmdProbeCycle_TfbDataTfbVldAndUscNotRdy                            0x0019
#define cmdProbeCycle_TfbUscReqStallByCredit                               0x001A
#define cmdProbeCycle_TfbUscDataNotAvailable                               0x001B
#define cmdProbeCycle_TfbGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_TfbGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_TfbGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_TfbGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_TfbGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_TfbGlobalTimerHi                                     0x00FF
#define cmdFPGAProbeCount_Component                                            0x0801
#define cmdFPGAProbeCount_Descriptor                                           0x0802
#define cmd64BITProbeCount_TfbPrimFromGsLo                                      0x1001
#define cmd64BITProbeCount_TfbPrimFromGsHi                                      0x1002

enum cmeTFBPROBE
{
    cmvProbeCount_TfbUscRdReq,
    cmvProbeCount_TfbUscWrReq,
    cmvProbeCount_TfbVldAndPpaRdy,
    cmvProbeCycle_TfbVldAndPpaNotRdy,
    cmvProbeCycle_TfbBusy,
    cmvProbeCycle_Tfb2UscRdTotalLatency,
    cmvProbeCycle_Tfb2UscWrTotalLatency,
    cmvProbeCycle_TfbRdReqAndUscNotRdy,
    cmvProbeCycle_TfbWrReqAndUscNotRdy,
    cmvProbeCycle_TfbDataUscVldAndTfbRdy,
    cmvProbeCycle_TfbDataUscVldAndTfbNotRdy,
    cmvProbeCycle_TfbDataTfbVldAndUscRdy,
    cmvProbeCycle_TfbDataTfbVldAndUscNotRdy,
    cmvProbeCycle_TfbUscReqStallByCredit,
    cmvProbeCycle_TfbUscDataNotAvailable,
    cmvProbeCycle_TfbGlobalTimerStartLo,
    cmvProbeCycle_TfbGlobalTimerStartHi,
    cmvProbeCycle_TfbGlobalTimerEndLo,
    cmvProbeCycle_TfbGlobalTimerEndHi,
    cmvProbeCycle_TfbGlobalTimerLo,
    cmvProbeCycle_TfbGlobalTimerHi,
    cmvFPGAProbeCount_Component,
    cmvFPGAProbeCount_Descriptor,
    cmv64BITProbeCount_TfbPrimFromGsLo,
    cmv64BITProbeCount_TfbPrimFromGsHi,
    cmvTFB_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoTFBProbeMap
{
public:
    cmoTFBProbeMap()
    {
        probeMap[cmvProbeCount_TfbUscRdReq                  ] = cmdProbeCount_TfbUscRdReq;
        probeMap[cmvProbeCount_TfbUscWrReq                  ] = cmdProbeCount_TfbUscWrReq;
        probeMap[cmvProbeCount_TfbVldAndPpaRdy              ] = cmdProbeCount_TfbVldAndPpaRdy;
        probeMap[cmvProbeCycle_TfbVldAndPpaNotRdy           ] = cmdProbeCycle_TfbVldAndPpaNotRdy;
        probeMap[cmvProbeCycle_TfbBusy                      ] = cmdProbeCycle_TfbBusy;
        probeMap[cmvProbeCycle_Tfb2UscRdTotalLatency        ] = cmdProbeCycle_Tfb2UscRdTotalLatency;
        probeMap[cmvProbeCycle_Tfb2UscWrTotalLatency        ] = cmdProbeCycle_Tfb2UscWrTotalLatency;
        probeMap[cmvProbeCycle_TfbRdReqAndUscNotRdy         ] = cmdProbeCycle_TfbRdReqAndUscNotRdy;
        probeMap[cmvProbeCycle_TfbWrReqAndUscNotRdy         ] = cmdProbeCycle_TfbWrReqAndUscNotRdy;
        probeMap[cmvProbeCycle_TfbDataUscVldAndTfbRdy       ] = cmdProbeCycle_TfbDataUscVldAndTfbRdy;
        probeMap[cmvProbeCycle_TfbDataUscVldAndTfbNotRdy    ] = cmdProbeCycle_TfbDataUscVldAndTfbNotRdy;
        probeMap[cmvProbeCycle_TfbDataTfbVldAndUscRdy       ] = cmdProbeCycle_TfbDataTfbVldAndUscRdy;
        probeMap[cmvProbeCycle_TfbDataTfbVldAndUscNotRdy    ] = cmdProbeCycle_TfbDataTfbVldAndUscNotRdy;
        probeMap[cmvProbeCycle_TfbUscReqStallByCredit       ] = cmdProbeCycle_TfbUscReqStallByCredit;
        probeMap[cmvProbeCycle_TfbUscDataNotAvailable       ] = cmdProbeCycle_TfbUscDataNotAvailable;
        probeMap[cmvProbeCycle_TfbGlobalTimerStartLo        ] = cmdProbeCycle_TfbGlobalTimerStartLo;
        probeMap[cmvProbeCycle_TfbGlobalTimerStartHi        ] = cmdProbeCycle_TfbGlobalTimerStartHi;
        probeMap[cmvProbeCycle_TfbGlobalTimerEndLo          ] = cmdProbeCycle_TfbGlobalTimerEndLo;
        probeMap[cmvProbeCycle_TfbGlobalTimerEndHi          ] = cmdProbeCycle_TfbGlobalTimerEndHi;
        probeMap[cmvProbeCycle_TfbGlobalTimerLo             ] = cmdProbeCycle_TfbGlobalTimerLo;
        probeMap[cmvProbeCycle_TfbGlobalTimerHi             ] = cmdProbeCycle_TfbGlobalTimerHi;
        probeMap[cmvFPGAProbeCount_Component                ] = cmdFPGAProbeCount_Component;
        probeMap[cmvFPGAProbeCount_Descriptor               ] = cmdFPGAProbeCount_Descriptor;
        probeMap[cmv64BITProbeCount_TfbPrimFromGsLo         ] = cmd64BITProbeCount_TfbPrimFromGsLo;
        probeMap[cmv64BITProbeCount_TfbPrimFromGsHi         ] = cmd64BITProbeCount_TfbPrimFromGsHi;

        probeCmodelAttributesMap[cmvProbeCount_TfbUscRdReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TfbUscWrReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TfbVldAndPpaRdy              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbVldAndPpaNotRdy           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Tfb2UscRdTotalLatency        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Tfb2UscWrTotalLatency        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbRdReqAndUscNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbWrReqAndUscNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbDataUscVldAndTfbRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbDataUscVldAndTfbNotRdy    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbDataTfbVldAndUscRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbDataTfbVldAndUscNotRdy    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbUscReqStallByCredit       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbUscDataNotAvailable       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TfbGlobalTimerHi             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_Component                ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_Descriptor               ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_TfbPrimFromGsLo         ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_TfbPrimFromGsHi         ] = 1;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvTFB_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvTFB_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvTFB_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_TFB_H__

