/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* FPA ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_FPA_H__
#define __GC_PROBE_FPA_H__

#define cmdProbeCount_FpaInputVtx                                          0x0001
#define cmdProbeCount_FpaInputPrim                                         0x0002
#define cmdProbeCount_FpaOutputPrim                                        0x0003
#define cmdProbeCount_FpaInputTri                                          0x0004
#define cmdProbeCount_FpaInputLine                                         0x0005
#define cmdProbeCount_FpaInputPoint                                        0x0006
#define cmdProbeCount_FpaDropPrim                                          0x0008
#define cmdProbeCount_FpaCullPrim                                          0x0009
#define cmdProbeCount_FpaFrustumClipPrim                                   0x000A
#define cmdProbeCycle_FpaFrustumClipActive                                 0x000B
#define cmdProbeCycle_FpaBusy                                              0x0010
#define cmdProbeCycle_ReqFpaVldAndUscRdy                                   0x0011
#define cmdProbeCycle_ReqFpaVldAndUscNotRdy                                0x0012
#define cmdProbeCycle_DataUscVldAndFpaRdy                                  0x0013
#define cmdProbeCycle_DataUscVldAndFpaNotRdy                               0x0014
#define cmdProbeCycle_FpaVldAndSeRdy                                       0x0015
#define cmdProbeCycle_FpaVldAndSeNotRdy                                    0x0016
#define cmdProbeCycle_Fpa2UscRdTotalLatency                                0x0017
#define cmdProbeCycle_FpaUscReqStallByCredit                               0x0018
#define cmdProbeCycle_FpaUscDataNotAvailable                               0x0019
#define cmdProbeCount_FpaCommonCorePLAVCycle                               0x001A
#define cmdProbeCount_FpaCommonCoreClipCycle                               0x001B
#define cmdProbeCycle_Fpa2SeNotVldData                                     0x001C
#define cmdProbeCycle_FpaGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_FpaGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_FpaGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_FpaGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_FpaGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_FpaGlobalTimerHi                                     0x00FF
#define cmd64BITProbeCount_ClipOutputPrimLo                                     0x1001
#define cmd64BITProbeCount_ClipOutputPrimHi                                     0x1002

enum cmeFPAPROBE
{
    cmvProbeCount_FpaInputVtx,
    cmvProbeCount_FpaInputPrim,
    cmvProbeCount_FpaOutputPrim,
    cmvProbeCount_FpaInputTri,
    cmvProbeCount_FpaInputLine,
    cmvProbeCount_FpaInputPoint,
    cmvProbeCount_FpaDropPrim,
    cmvProbeCount_FpaCullPrim,
    cmvProbeCount_FpaFrustumClipPrim,
    cmvProbeCycle_FpaFrustumClipActive,
    cmvProbeCycle_FpaBusy,
    cmvProbeCycle_ReqFpaVldAndUscRdy,
    cmvProbeCycle_ReqFpaVldAndUscNotRdy,
    cmvProbeCycle_DataUscVldAndFpaRdy,
    cmvProbeCycle_DataUscVldAndFpaNotRdy,
    cmvProbeCycle_FpaVldAndSeRdy,
    cmvProbeCycle_FpaVldAndSeNotRdy,
    cmvProbeCycle_Fpa2UscRdTotalLatency,
    cmvProbeCycle_FpaUscReqStallByCredit,
    cmvProbeCycle_FpaUscDataNotAvailable,
    cmvProbeCount_FpaCommonCorePLAVCycle,
    cmvProbeCount_FpaCommonCoreClipCycle,
    cmvProbeCycle_Fpa2SeNotVldData,
    cmvProbeCycle_FpaGlobalTimerStartLo,
    cmvProbeCycle_FpaGlobalTimerStartHi,
    cmvProbeCycle_FpaGlobalTimerEndLo,
    cmvProbeCycle_FpaGlobalTimerEndHi,
    cmvProbeCycle_FpaGlobalTimerLo,
    cmvProbeCycle_FpaGlobalTimerHi,
    cmv64BITProbeCount_ClipOutputPrimLo,
    cmv64BITProbeCount_ClipOutputPrimHi,
    cmvFPA_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoFPAProbeMap
{
public:
    cmoFPAProbeMap()
    {
        probeMap[cmvProbeCount_FpaInputVtx                  ] = cmdProbeCount_FpaInputVtx;
        probeMap[cmvProbeCount_FpaInputPrim                 ] = cmdProbeCount_FpaInputPrim;
        probeMap[cmvProbeCount_FpaOutputPrim                ] = cmdProbeCount_FpaOutputPrim;
        probeMap[cmvProbeCount_FpaInputTri                  ] = cmdProbeCount_FpaInputTri;
        probeMap[cmvProbeCount_FpaInputLine                 ] = cmdProbeCount_FpaInputLine;
        probeMap[cmvProbeCount_FpaInputPoint                ] = cmdProbeCount_FpaInputPoint;
        probeMap[cmvProbeCount_FpaDropPrim                  ] = cmdProbeCount_FpaDropPrim;
        probeMap[cmvProbeCount_FpaCullPrim                  ] = cmdProbeCount_FpaCullPrim;
        probeMap[cmvProbeCount_FpaFrustumClipPrim           ] = cmdProbeCount_FpaFrustumClipPrim;
        probeMap[cmvProbeCycle_FpaFrustumClipActive         ] = cmdProbeCycle_FpaFrustumClipActive;
        probeMap[cmvProbeCycle_FpaBusy                      ] = cmdProbeCycle_FpaBusy;
        probeMap[cmvProbeCycle_ReqFpaVldAndUscRdy           ] = cmdProbeCycle_ReqFpaVldAndUscRdy;
        probeMap[cmvProbeCycle_ReqFpaVldAndUscNotRdy        ] = cmdProbeCycle_ReqFpaVldAndUscNotRdy;
        probeMap[cmvProbeCycle_DataUscVldAndFpaRdy          ] = cmdProbeCycle_DataUscVldAndFpaRdy;
        probeMap[cmvProbeCycle_DataUscVldAndFpaNotRdy       ] = cmdProbeCycle_DataUscVldAndFpaNotRdy;
        probeMap[cmvProbeCycle_FpaVldAndSeRdy               ] = cmdProbeCycle_FpaVldAndSeRdy;
        probeMap[cmvProbeCycle_FpaVldAndSeNotRdy            ] = cmdProbeCycle_FpaVldAndSeNotRdy;
        probeMap[cmvProbeCycle_Fpa2UscRdTotalLatency        ] = cmdProbeCycle_Fpa2UscRdTotalLatency;
        probeMap[cmvProbeCycle_FpaUscReqStallByCredit       ] = cmdProbeCycle_FpaUscReqStallByCredit;
        probeMap[cmvProbeCycle_FpaUscDataNotAvailable       ] = cmdProbeCycle_FpaUscDataNotAvailable;
        probeMap[cmvProbeCount_FpaCommonCorePLAVCycle       ] = cmdProbeCount_FpaCommonCorePLAVCycle;
        probeMap[cmvProbeCount_FpaCommonCoreClipCycle       ] = cmdProbeCount_FpaCommonCoreClipCycle;
        probeMap[cmvProbeCycle_Fpa2SeNotVldData             ] = cmdProbeCycle_Fpa2SeNotVldData;
        probeMap[cmvProbeCycle_FpaGlobalTimerStartLo        ] = cmdProbeCycle_FpaGlobalTimerStartLo;
        probeMap[cmvProbeCycle_FpaGlobalTimerStartHi        ] = cmdProbeCycle_FpaGlobalTimerStartHi;
        probeMap[cmvProbeCycle_FpaGlobalTimerEndLo          ] = cmdProbeCycle_FpaGlobalTimerEndLo;
        probeMap[cmvProbeCycle_FpaGlobalTimerEndHi          ] = cmdProbeCycle_FpaGlobalTimerEndHi;
        probeMap[cmvProbeCycle_FpaGlobalTimerLo             ] = cmdProbeCycle_FpaGlobalTimerLo;
        probeMap[cmvProbeCycle_FpaGlobalTimerHi             ] = cmdProbeCycle_FpaGlobalTimerHi;
        probeMap[cmv64BITProbeCount_ClipOutputPrimLo        ] = cmd64BITProbeCount_ClipOutputPrimLo;
        probeMap[cmv64BITProbeCount_ClipOutputPrimHi        ] = cmd64BITProbeCount_ClipOutputPrimHi;

        probeCmodelAttributesMap[cmvProbeCount_FpaInputVtx                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_FpaInputPrim                 ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaOutputPrim                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaInputTri                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaInputLine                 ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaInputPoint                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaDropPrim                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaCullPrim                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_FpaFrustumClipPrim           ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_FpaFrustumClipActive         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_ReqFpaVldAndUscRdy           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_ReqFpaVldAndUscNotRdy        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataUscVldAndFpaRdy          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataUscVldAndFpaNotRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaVldAndSeRdy               ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaVldAndSeNotRdy            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Fpa2UscRdTotalLatency        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaUscReqStallByCredit       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaUscDataNotAvailable       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_FpaCommonCorePLAVCycle       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_FpaCommonCoreClipCycle       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Fpa2SeNotVldData             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_FpaGlobalTimerHi             ] = 0;
        probeCmodelAttributesMap[cmv64BITProbeCount_ClipOutputPrimLo        ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_ClipOutputPrimHi        ] = 1;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvFPA_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvFPA_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvFPA_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_FPA_H__

