/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* SE ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_SE_H__
#define __GC_PROBE_SE_H__

#define cmdProbeCount_SeInputTri                                           0x0001
#define cmdProbeCount_SeOutputTri                                          0x0002
#define cmdProbeCount_SeClipTri                                            0x0003
#define cmdProbeCount_SeInputCycles                                        0x0004
#define cmdProbeCount_SeFloatPipeActiveCycles                              0x0005
#define cmdProbeCycle_SeFloatPipeStarveCycles                              0x0006
#define cmdProbeCycle_SeBusy                                               0x0010
#define cmdProbeCycle_SeVldAndRaRdy                                        0x0011
#define cmdProbeCycle_SeVldAndRaNotRdy                                     0x0012
#define cmdProbeCycle_Se2RaNotVldData                                      0x0013
#define cmdProbeCycle_SeGlobalTimerStartLo                                 0x00FA
#define cmdProbeCycle_SeGlobalTimerStartHi                                 0x00FB
#define cmdProbeCycle_SeGlobalTimerEndLo                                   0x00FC
#define cmdProbeCycle_SeGlobalTimerEndHi                                   0x00FD
#define cmdProbeCycle_SeGlobalTimerLo                                      0x00FE
#define cmdProbeCycle_SeGlobalTimerHi                                      0x00FF
#define cmdFPGAProbeCount_SeInputTri                                           0x0801
#define cmdFPGAProbeCount_OutputTri                                            0x0802
#define cmdFPGAProbeCount_SeInputLine                                          0x0803
#define cmdFPGAProbeCount_OutputLine                                           0x0804
#define cmdFPGAProbeCount_ClipTri                                              0x0805
#define cmdFPGAProbeCount_ClipLine                                             0x0806
#define cmdFPGAProbeCount_CullTri                                              0x0807
#define cmdFPGAProbeCount_CullLine                                             0x0808
#define cmdFPGAProbeCount_ZeroLenLine                                          0x0809
#define cmdFPGAProbeCycle_SeBusy                                               0x0C01
#define cmdFPGAProbeCycle_PaNotVldAndSeRdySeBusy                               0x0C02
#define cmdFPGAProbeCycle_SeVldAndRaRdy                                        0x0C03
#define cmdFPGAProbeCycle_SeVldAndRaNotRdy                                     0x0C04
#define cmdFPGAProbeCycle_SeNotVldAndRaRdy                                     0x0C05
#define cmdFPGAProbeCycle_SeNotVldAndRaNotRdy                                  0x0C06

enum cmeSEPROBE
{
    cmvProbeCount_SeInputTri,
    cmvProbeCount_SeOutputTri,
    cmvProbeCount_SeClipTri,
    cmvProbeCount_SeInputCycles,
    cmvProbeCount_SeFloatPipeActiveCycles,
    cmvProbeCycle_SeFloatPipeStarveCycles,
    cmvProbeCycle_SeBusy,
    cmvProbeCycle_SeVldAndRaRdy,
    cmvProbeCycle_SeVldAndRaNotRdy,
    cmvProbeCycle_Se2RaNotVldData,
    cmvProbeCycle_SeGlobalTimerStartLo,
    cmvProbeCycle_SeGlobalTimerStartHi,
    cmvProbeCycle_SeGlobalTimerEndLo,
    cmvProbeCycle_SeGlobalTimerEndHi,
    cmvProbeCycle_SeGlobalTimerLo,
    cmvProbeCycle_SeGlobalTimerHi,
    cmvFPGAProbeCount_SeInputTri,
    cmvFPGAProbeCount_OutputTri,
    cmvFPGAProbeCount_SeInputLine,
    cmvFPGAProbeCount_OutputLine,
    cmvFPGAProbeCount_ClipTri,
    cmvFPGAProbeCount_ClipLine,
    cmvFPGAProbeCount_CullTri,
    cmvFPGAProbeCount_CullLine,
    cmvFPGAProbeCount_ZeroLenLine,
    cmvFPGAProbeCycle_SeBusy,
    cmvFPGAProbeCycle_PaNotVldAndSeRdySeBusy,
    cmvFPGAProbeCycle_SeVldAndRaRdy,
    cmvFPGAProbeCycle_SeVldAndRaNotRdy,
    cmvFPGAProbeCycle_SeNotVldAndRaRdy,
    cmvFPGAProbeCycle_SeNotVldAndRaNotRdy,
    cmvSE_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoSEProbeMap
{
public:
    cmoSEProbeMap()
    {
        probeMap[cmvProbeCount_SeInputTri                   ] = cmdProbeCount_SeInputTri;
        probeMap[cmvProbeCount_SeOutputTri                  ] = cmdProbeCount_SeOutputTri;
        probeMap[cmvProbeCount_SeClipTri                    ] = cmdProbeCount_SeClipTri;
        probeMap[cmvProbeCount_SeInputCycles                ] = cmdProbeCount_SeInputCycles;
        probeMap[cmvProbeCount_SeFloatPipeActiveCycles      ] = cmdProbeCount_SeFloatPipeActiveCycles;
        probeMap[cmvProbeCycle_SeFloatPipeStarveCycles      ] = cmdProbeCycle_SeFloatPipeStarveCycles;
        probeMap[cmvProbeCycle_SeBusy                       ] = cmdProbeCycle_SeBusy;
        probeMap[cmvProbeCycle_SeVldAndRaRdy                ] = cmdProbeCycle_SeVldAndRaRdy;
        probeMap[cmvProbeCycle_SeVldAndRaNotRdy             ] = cmdProbeCycle_SeVldAndRaNotRdy;
        probeMap[cmvProbeCycle_Se2RaNotVldData              ] = cmdProbeCycle_Se2RaNotVldData;
        probeMap[cmvProbeCycle_SeGlobalTimerStartLo         ] = cmdProbeCycle_SeGlobalTimerStartLo;
        probeMap[cmvProbeCycle_SeGlobalTimerStartHi         ] = cmdProbeCycle_SeGlobalTimerStartHi;
        probeMap[cmvProbeCycle_SeGlobalTimerEndLo           ] = cmdProbeCycle_SeGlobalTimerEndLo;
        probeMap[cmvProbeCycle_SeGlobalTimerEndHi           ] = cmdProbeCycle_SeGlobalTimerEndHi;
        probeMap[cmvProbeCycle_SeGlobalTimerLo              ] = cmdProbeCycle_SeGlobalTimerLo;
        probeMap[cmvProbeCycle_SeGlobalTimerHi              ] = cmdProbeCycle_SeGlobalTimerHi;
        probeMap[cmvFPGAProbeCount_SeInputTri               ] = cmdFPGAProbeCount_SeInputTri;
        probeMap[cmvFPGAProbeCount_OutputTri                ] = cmdFPGAProbeCount_OutputTri;
        probeMap[cmvFPGAProbeCount_SeInputLine              ] = cmdFPGAProbeCount_SeInputLine;
        probeMap[cmvFPGAProbeCount_OutputLine               ] = cmdFPGAProbeCount_OutputLine;
        probeMap[cmvFPGAProbeCount_ClipTri                  ] = cmdFPGAProbeCount_ClipTri;
        probeMap[cmvFPGAProbeCount_ClipLine                 ] = cmdFPGAProbeCount_ClipLine;
        probeMap[cmvFPGAProbeCount_CullTri                  ] = cmdFPGAProbeCount_CullTri;
        probeMap[cmvFPGAProbeCount_CullLine                 ] = cmdFPGAProbeCount_CullLine;
        probeMap[cmvFPGAProbeCount_ZeroLenLine              ] = cmdFPGAProbeCount_ZeroLenLine;
        probeMap[cmvFPGAProbeCycle_SeBusy                   ] = cmdFPGAProbeCycle_SeBusy;
        probeMap[cmvFPGAProbeCycle_PaNotVldAndSeRdySeBusy   ] = cmdFPGAProbeCycle_PaNotVldAndSeRdySeBusy;
        probeMap[cmvFPGAProbeCycle_SeVldAndRaRdy            ] = cmdFPGAProbeCycle_SeVldAndRaRdy;
        probeMap[cmvFPGAProbeCycle_SeVldAndRaNotRdy         ] = cmdFPGAProbeCycle_SeVldAndRaNotRdy;
        probeMap[cmvFPGAProbeCycle_SeNotVldAndRaRdy         ] = cmdFPGAProbeCycle_SeNotVldAndRaRdy;
        probeMap[cmvFPGAProbeCycle_SeNotVldAndRaNotRdy      ] = cmdFPGAProbeCycle_SeNotVldAndRaNotRdy;

        probeCmodelAttributesMap[cmvProbeCount_SeInputTri                   ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_SeOutputTri                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_SeClipTri                    ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_SeInputCycles                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_SeFloatPipeActiveCycles      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeFloatPipeStarveCycles      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeBusy                       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeVldAndRaRdy                ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_SeVldAndRaNotRdy             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Se2RaNotVldData              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerStartLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerStartHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerEndLo           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerEndHi           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerLo              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_SeGlobalTimerHi              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_SeInputTri               ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_OutputTri                ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_SeInputLine              ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_OutputLine               ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ClipTri                  ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ClipLine                 ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_CullTri                  ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_CullLine                 ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ZeroLenLine              ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_SeBusy                   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PaNotVldAndSeRdySeBusy   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_SeVldAndRaRdy            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_SeVldAndRaNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_SeNotVldAndRaRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_SeNotVldAndRaNotRdy      ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvSE_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvSE_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvSE_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_SE_H__

