/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* APPINFO ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_APPINFO_H__
#define __GC_PROBE_APPINFO_H__

#define cmdFPGAProbeState_OpNum                                                0x0401
#define cmdFPGAProbeState_OpTyp                                                0x0402
#define cmdFPGAProbeState_DrawNum                                              0x0403
#define cmdFPGAProbeState_BlitNum                                              0x0404
#define cmdFPGAProbeState_ComputeNum                                           0x0405
#define cmdFPGAProbeState_ResolveNum                                           0x0406
#define cmdFPGAProbeState_VsId                                                 0x0407
#define cmdFPGAProbeState_TcsId                                                0x0408
#define cmdFPGAProbeState_TesId                                                0x0409
#define cmdFPGAProbeState_GsId                                                 0x040A
#define cmdFPGAProbeState_PsId                                                 0x040B
#define cmdFPGAProbeState_CsId                                                 0x040C

enum cmeAPPINFOPROBE
{
    cmvFPGAProbeState_OpNum,
    cmvFPGAProbeState_OpTyp,
    cmvFPGAProbeState_DrawNum,
    cmvFPGAProbeState_BlitNum,
    cmvFPGAProbeState_ComputeNum,
    cmvFPGAProbeState_ResolveNum,
    cmvFPGAProbeState_VsId,
    cmvFPGAProbeState_TcsId,
    cmvFPGAProbeState_TesId,
    cmvFPGAProbeState_GsId,
    cmvFPGAProbeState_PsId,
    cmvFPGAProbeState_CsId,
    cmvAPPINFO_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoAPPINFOProbeMap
{
public:
    cmoAPPINFOProbeMap()
    {
        probeMap[cmvFPGAProbeState_OpNum                    ] = cmdFPGAProbeState_OpNum;
        probeMap[cmvFPGAProbeState_OpTyp                    ] = cmdFPGAProbeState_OpTyp;
        probeMap[cmvFPGAProbeState_DrawNum                  ] = cmdFPGAProbeState_DrawNum;
        probeMap[cmvFPGAProbeState_BlitNum                  ] = cmdFPGAProbeState_BlitNum;
        probeMap[cmvFPGAProbeState_ComputeNum               ] = cmdFPGAProbeState_ComputeNum;
        probeMap[cmvFPGAProbeState_ResolveNum               ] = cmdFPGAProbeState_ResolveNum;
        probeMap[cmvFPGAProbeState_VsId                     ] = cmdFPGAProbeState_VsId;
        probeMap[cmvFPGAProbeState_TcsId                    ] = cmdFPGAProbeState_TcsId;
        probeMap[cmvFPGAProbeState_TesId                    ] = cmdFPGAProbeState_TesId;
        probeMap[cmvFPGAProbeState_GsId                     ] = cmdFPGAProbeState_GsId;
        probeMap[cmvFPGAProbeState_PsId                     ] = cmdFPGAProbeState_PsId;
        probeMap[cmvFPGAProbeState_CsId                     ] = cmdFPGAProbeState_CsId;

        probeCmodelAttributesMap[cmvFPGAProbeState_OpNum                    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_OpTyp                    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_DrawNum                  ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_BlitNum                  ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_ComputeNum               ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_ResolveNum               ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_VsId                     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_TcsId                    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_TesId                    ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_GsId                     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_PsId                     ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_CsId                     ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvAPPINFO_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvAPPINFO_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvAPPINFO_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_APPINFO_H__

