/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* TC ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_TC_H__
#define __GC_PROBE_TC_H__

#define cmdProbeCount_TcTotalReadValidBwGlobalLo                           0x0001
#define cmdProbeCount_TcTotalReadValidBwGlobalHi                           0x0002
#define cmdProbeCount_TcTotalWriteValidBwGlobalLo                          0x0003
#define cmdProbeCount_TcTotalWriteValidBwGlobalHi                          0x0004
#define cmdProbeCount_TcTotalMac                                           0x0005
#define cmdProbeCount_TcZeroCoefSkip                                       0x0006
#define cmdProbeCount_TcNonZeroCoef                                        0x0007
#define cmdProbeCount_TcAXIRdTotalReq                                      0x0008
#define cmdProbeCount_TcAXIWrTotalReq                                      0x0009
#define cmdProbeCount_TcAXIRdByteId0Lo                                     0x000A
#define cmdProbeCount_TcAXIRdByteId0Hi                                     0x000B
#define cmdProbeCount_TcAXIWrByteId0Lo                                     0x000C
#define cmdProbeCount_TcAXIWrByteId0Hi                                     0x000D
#define cmdProbeCount_TcAXIRdByteId1Lo                                     0x000E
#define cmdProbeCount_TcAXIRdByteId1Hi                                     0x000F
#define cmdProbeCount_TcAXIWrByteId1Lo                                     0x0010
#define cmdProbeCount_TcAXIWrByteId1Hi                                     0x0011
#define cmdProbeCount_TcAXIRdByteId2Lo                                     0x0012
#define cmdProbeCount_TcAXIRdByteId2Hi                                     0x0013
#define cmdProbeCount_TcAXIWrByteId2Lo                                     0x0014
#define cmdProbeCount_TcAXIWrByteId2Hi                                     0x0015
#define cmdProbeCount_TcAXIRdByteId3Lo                                     0x0016
#define cmdProbeCount_TcAXIRdByteId3Hi                                     0x0017
#define cmdProbeCount_TcAXIWrByteId3Lo                                     0x0018
#define cmdProbeCount_TcAXIWrByteId3Hi                                     0x0019
#define cmdProbeCount_TcAXIRdByteId4Lo                                     0x001A
#define cmdProbeCount_TcAXIRdByteId4Hi                                     0x001B
#define cmdProbeCount_TcAXIWrByteId4Lo                                     0x001C
#define cmdProbeCount_TcAXIWrByteId4Hi                                     0x001D
#define cmdProbeCount_TcTotalReadGlobalBWLo                                0x001E
#define cmdProbeCount_TcTotalReadGlobalBWHi                                0x001F
#define cmdProbeCount_TcTotalWriteGlobalBWLo                               0x0020
#define cmdProbeCount_TcTotalWriteGlobalBWHi                               0x0021
#define cmdProbeCount_TcTotalReadSramBWLo                                  0x0022
#define cmdProbeCount_TcTotalReadSramBWHi                                  0x0023
#define cmdProbeCount_TcTotalWriteSramBWLo                                 0x0024
#define cmdProbeCount_TcTotalWriteSramBWHi                                 0x0025
#define cmdProbeCycle_TcTotalBusy                                          0x0026
#define cmdProbeCycle_TcIdle                                               0x0027
#define cmdProbeCycle_TcTotalReadGlobal                                    0x0028
#define cmdProbeCycle_TcTotalWriteGlobal                                   0x0029
#define cmdProbeCycle_TcTotalReadSram                                      0x002A
#define cmdProbeCycle_TcTotalWriteSram                                     0x002B
#define cmdProbeCycle_TcTotalMac                                           0x002C
#define cmdProbeCycle_TcAXIRdMaxOutstanding                                0x002D
#define cmdProbeCycle_TcAXIWrMaxOutstanding                                0x002E
#define cmdProbeCycle_TcAXIRdMaxLatency                                    0x002F
#define cmdProbeCycle_TcAXIWrMaxLatency                                    0x0030
#define cmdProbeCycle_TcAXIRdTotalLatency                                  0x0031
#define cmdProbeCycle_TcAXIWrTotalLatency                                  0x0032
#define cmdProbeCycle_TcAXIARVALIDAndNotARREADY                            0x0033
#define cmdProbeCycle_TcAXIAWVALIDAndNotAWREADY                            0x0034
#define cmdProbeCycle_TcAXIWVALIDAndNotWREADY                              0x0035
#define cmdProbeCycle_TcGlobalTimerStartLo                                 0x00FA
#define cmdProbeCycle_TcGlobalTimerStartHi                                 0x00FB
#define cmdProbeCycle_TcGlobalTimerEndLo                                   0x00FC
#define cmdProbeCycle_TcGlobalTimerEndHi                                   0x00FD
#define cmdProbeCycle_TcGlobalTimerLo                                      0x00FE
#define cmdProbeCycle_TcGlobalTimerHi                                      0x00FF

enum cmeTCPROBE
{
    cmvProbeCount_TcTotalReadValidBwGlobalLo,
    cmvProbeCount_TcTotalReadValidBwGlobalHi,
    cmvProbeCount_TcTotalWriteValidBwGlobalLo,
    cmvProbeCount_TcTotalWriteValidBwGlobalHi,
    cmvProbeCount_TcTotalMac,
    cmvProbeCount_TcZeroCoefSkip,
    cmvProbeCount_TcNonZeroCoef,
    cmvProbeCount_TcAXIRdTotalReq,
    cmvProbeCount_TcAXIWrTotalReq,
    cmvProbeCount_TcAXIRdByteId0Lo,
    cmvProbeCount_TcAXIRdByteId0Hi,
    cmvProbeCount_TcAXIWrByteId0Lo,
    cmvProbeCount_TcAXIWrByteId0Hi,
    cmvProbeCount_TcAXIRdByteId1Lo,
    cmvProbeCount_TcAXIRdByteId1Hi,
    cmvProbeCount_TcAXIWrByteId1Lo,
    cmvProbeCount_TcAXIWrByteId1Hi,
    cmvProbeCount_TcAXIRdByteId2Lo,
    cmvProbeCount_TcAXIRdByteId2Hi,
    cmvProbeCount_TcAXIWrByteId2Lo,
    cmvProbeCount_TcAXIWrByteId2Hi,
    cmvProbeCount_TcAXIRdByteId3Lo,
    cmvProbeCount_TcAXIRdByteId3Hi,
    cmvProbeCount_TcAXIWrByteId3Lo,
    cmvProbeCount_TcAXIWrByteId3Hi,
    cmvProbeCount_TcAXIRdByteId4Lo,
    cmvProbeCount_TcAXIRdByteId4Hi,
    cmvProbeCount_TcAXIWrByteId4Lo,
    cmvProbeCount_TcAXIWrByteId4Hi,
    cmvProbeCount_TcTotalReadGlobalBWLo,
    cmvProbeCount_TcTotalReadGlobalBWHi,
    cmvProbeCount_TcTotalWriteGlobalBWLo,
    cmvProbeCount_TcTotalWriteGlobalBWHi,
    cmvProbeCount_TcTotalReadSramBWLo,
    cmvProbeCount_TcTotalReadSramBWHi,
    cmvProbeCount_TcTotalWriteSramBWLo,
    cmvProbeCount_TcTotalWriteSramBWHi,
    cmvProbeCycle_TcTotalBusy,
    cmvProbeCycle_TcIdle,
    cmvProbeCycle_TcTotalReadGlobal,
    cmvProbeCycle_TcTotalWriteGlobal,
    cmvProbeCycle_TcTotalReadSram,
    cmvProbeCycle_TcTotalWriteSram,
    cmvProbeCycle_TcTotalMac,
    cmvProbeCycle_TcAXIRdMaxOutstanding,
    cmvProbeCycle_TcAXIWrMaxOutstanding,
    cmvProbeCycle_TcAXIRdMaxLatency,
    cmvProbeCycle_TcAXIWrMaxLatency,
    cmvProbeCycle_TcAXIRdTotalLatency,
    cmvProbeCycle_TcAXIWrTotalLatency,
    cmvProbeCycle_TcAXIARVALIDAndNotARREADY,
    cmvProbeCycle_TcAXIAWVALIDAndNotAWREADY,
    cmvProbeCycle_TcAXIWVALIDAndNotWREADY,
    cmvProbeCycle_TcGlobalTimerStartLo,
    cmvProbeCycle_TcGlobalTimerStartHi,
    cmvProbeCycle_TcGlobalTimerEndLo,
    cmvProbeCycle_TcGlobalTimerEndHi,
    cmvProbeCycle_TcGlobalTimerLo,
    cmvProbeCycle_TcGlobalTimerHi,
    cmvTC_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoTCProbeMap
{
public:
    cmoTCProbeMap()
    {
        probeMap[cmvProbeCount_TcTotalReadValidBwGlobalLo   ] = cmdProbeCount_TcTotalReadValidBwGlobalLo;
        probeMap[cmvProbeCount_TcTotalReadValidBwGlobalHi   ] = cmdProbeCount_TcTotalReadValidBwGlobalHi;
        probeMap[cmvProbeCount_TcTotalWriteValidBwGlobalLo  ] = cmdProbeCount_TcTotalWriteValidBwGlobalLo;
        probeMap[cmvProbeCount_TcTotalWriteValidBwGlobalHi  ] = cmdProbeCount_TcTotalWriteValidBwGlobalHi;
        probeMap[cmvProbeCount_TcTotalMac                   ] = cmdProbeCount_TcTotalMac;
        probeMap[cmvProbeCount_TcZeroCoefSkip               ] = cmdProbeCount_TcZeroCoefSkip;
        probeMap[cmvProbeCount_TcNonZeroCoef                ] = cmdProbeCount_TcNonZeroCoef;
        probeMap[cmvProbeCount_TcAXIRdTotalReq              ] = cmdProbeCount_TcAXIRdTotalReq;
        probeMap[cmvProbeCount_TcAXIWrTotalReq              ] = cmdProbeCount_TcAXIWrTotalReq;
        probeMap[cmvProbeCount_TcAXIRdByteId0Lo             ] = cmdProbeCount_TcAXIRdByteId0Lo;
        probeMap[cmvProbeCount_TcAXIRdByteId0Hi             ] = cmdProbeCount_TcAXIRdByteId0Hi;
        probeMap[cmvProbeCount_TcAXIWrByteId0Lo             ] = cmdProbeCount_TcAXIWrByteId0Lo;
        probeMap[cmvProbeCount_TcAXIWrByteId0Hi             ] = cmdProbeCount_TcAXIWrByteId0Hi;
        probeMap[cmvProbeCount_TcAXIRdByteId1Lo             ] = cmdProbeCount_TcAXIRdByteId1Lo;
        probeMap[cmvProbeCount_TcAXIRdByteId1Hi             ] = cmdProbeCount_TcAXIRdByteId1Hi;
        probeMap[cmvProbeCount_TcAXIWrByteId1Lo             ] = cmdProbeCount_TcAXIWrByteId1Lo;
        probeMap[cmvProbeCount_TcAXIWrByteId1Hi             ] = cmdProbeCount_TcAXIWrByteId1Hi;
        probeMap[cmvProbeCount_TcAXIRdByteId2Lo             ] = cmdProbeCount_TcAXIRdByteId2Lo;
        probeMap[cmvProbeCount_TcAXIRdByteId2Hi             ] = cmdProbeCount_TcAXIRdByteId2Hi;
        probeMap[cmvProbeCount_TcAXIWrByteId2Lo             ] = cmdProbeCount_TcAXIWrByteId2Lo;
        probeMap[cmvProbeCount_TcAXIWrByteId2Hi             ] = cmdProbeCount_TcAXIWrByteId2Hi;
        probeMap[cmvProbeCount_TcAXIRdByteId3Lo             ] = cmdProbeCount_TcAXIRdByteId3Lo;
        probeMap[cmvProbeCount_TcAXIRdByteId3Hi             ] = cmdProbeCount_TcAXIRdByteId3Hi;
        probeMap[cmvProbeCount_TcAXIWrByteId3Lo             ] = cmdProbeCount_TcAXIWrByteId3Lo;
        probeMap[cmvProbeCount_TcAXIWrByteId3Hi             ] = cmdProbeCount_TcAXIWrByteId3Hi;
        probeMap[cmvProbeCount_TcAXIRdByteId4Lo             ] = cmdProbeCount_TcAXIRdByteId4Lo;
        probeMap[cmvProbeCount_TcAXIRdByteId4Hi             ] = cmdProbeCount_TcAXIRdByteId4Hi;
        probeMap[cmvProbeCount_TcAXIWrByteId4Lo             ] = cmdProbeCount_TcAXIWrByteId4Lo;
        probeMap[cmvProbeCount_TcAXIWrByteId4Hi             ] = cmdProbeCount_TcAXIWrByteId4Hi;
        probeMap[cmvProbeCount_TcTotalReadGlobalBWLo        ] = cmdProbeCount_TcTotalReadGlobalBWLo;
        probeMap[cmvProbeCount_TcTotalReadGlobalBWHi        ] = cmdProbeCount_TcTotalReadGlobalBWHi;
        probeMap[cmvProbeCount_TcTotalWriteGlobalBWLo       ] = cmdProbeCount_TcTotalWriteGlobalBWLo;
        probeMap[cmvProbeCount_TcTotalWriteGlobalBWHi       ] = cmdProbeCount_TcTotalWriteGlobalBWHi;
        probeMap[cmvProbeCount_TcTotalReadSramBWLo          ] = cmdProbeCount_TcTotalReadSramBWLo;
        probeMap[cmvProbeCount_TcTotalReadSramBWHi          ] = cmdProbeCount_TcTotalReadSramBWHi;
        probeMap[cmvProbeCount_TcTotalWriteSramBWLo         ] = cmdProbeCount_TcTotalWriteSramBWLo;
        probeMap[cmvProbeCount_TcTotalWriteSramBWHi         ] = cmdProbeCount_TcTotalWriteSramBWHi;
        probeMap[cmvProbeCycle_TcTotalBusy                  ] = cmdProbeCycle_TcTotalBusy;
        probeMap[cmvProbeCycle_TcIdle                       ] = cmdProbeCycle_TcIdle;
        probeMap[cmvProbeCycle_TcTotalReadGlobal            ] = cmdProbeCycle_TcTotalReadGlobal;
        probeMap[cmvProbeCycle_TcTotalWriteGlobal           ] = cmdProbeCycle_TcTotalWriteGlobal;
        probeMap[cmvProbeCycle_TcTotalReadSram              ] = cmdProbeCycle_TcTotalReadSram;
        probeMap[cmvProbeCycle_TcTotalWriteSram             ] = cmdProbeCycle_TcTotalWriteSram;
        probeMap[cmvProbeCycle_TcTotalMac                   ] = cmdProbeCycle_TcTotalMac;
        probeMap[cmvProbeCycle_TcAXIRdMaxOutstanding        ] = cmdProbeCycle_TcAXIRdMaxOutstanding;
        probeMap[cmvProbeCycle_TcAXIWrMaxOutstanding        ] = cmdProbeCycle_TcAXIWrMaxOutstanding;
        probeMap[cmvProbeCycle_TcAXIRdMaxLatency            ] = cmdProbeCycle_TcAXIRdMaxLatency;
        probeMap[cmvProbeCycle_TcAXIWrMaxLatency            ] = cmdProbeCycle_TcAXIWrMaxLatency;
        probeMap[cmvProbeCycle_TcAXIRdTotalLatency          ] = cmdProbeCycle_TcAXIRdTotalLatency;
        probeMap[cmvProbeCycle_TcAXIWrTotalLatency          ] = cmdProbeCycle_TcAXIWrTotalLatency;
        probeMap[cmvProbeCycle_TcAXIARVALIDAndNotARREADY    ] = cmdProbeCycle_TcAXIARVALIDAndNotARREADY;
        probeMap[cmvProbeCycle_TcAXIAWVALIDAndNotAWREADY    ] = cmdProbeCycle_TcAXIAWVALIDAndNotAWREADY;
        probeMap[cmvProbeCycle_TcAXIWVALIDAndNotWREADY      ] = cmdProbeCycle_TcAXIWVALIDAndNotWREADY;
        probeMap[cmvProbeCycle_TcGlobalTimerStartLo         ] = cmdProbeCycle_TcGlobalTimerStartLo;
        probeMap[cmvProbeCycle_TcGlobalTimerStartHi         ] = cmdProbeCycle_TcGlobalTimerStartHi;
        probeMap[cmvProbeCycle_TcGlobalTimerEndLo           ] = cmdProbeCycle_TcGlobalTimerEndLo;
        probeMap[cmvProbeCycle_TcGlobalTimerEndHi           ] = cmdProbeCycle_TcGlobalTimerEndHi;
        probeMap[cmvProbeCycle_TcGlobalTimerLo              ] = cmdProbeCycle_TcGlobalTimerLo;
        probeMap[cmvProbeCycle_TcGlobalTimerHi              ] = cmdProbeCycle_TcGlobalTimerHi;

        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadValidBwGlobalLo   ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadValidBwGlobalHi   ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteValidBwGlobalLo  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteValidBwGlobalHi  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalMac                   ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcZeroCoefSkip               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcNonZeroCoef                ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdTotalReq              ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrTotalReq              ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId0Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId0Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId0Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId0Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId1Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId1Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId1Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId1Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId2Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId2Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId2Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId2Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId3Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId3Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId3Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId3Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId4Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIRdByteId4Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId4Lo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcAXIWrByteId4Hi             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadGlobalBWLo        ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadGlobalBWHi        ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteGlobalBWLo       ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteGlobalBWHi       ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadSramBWLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalReadSramBWHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteSramBWLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_TcTotalWriteSramBWHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalBusy                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_TcIdle                       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalReadGlobal            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalWriteGlobal           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalReadSram              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalWriteSram             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcTotalMac                   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIRdMaxOutstanding        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIWrMaxOutstanding        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIRdMaxLatency            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIWrMaxLatency            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIRdTotalLatency          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIWrTotalLatency          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIARVALIDAndNotARREADY    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIAWVALIDAndNotAWREADY    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcAXIWVALIDAndNotWREADY      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerStartLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerStartHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerEndLo           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerEndHi           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerLo              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_TcGlobalTimerHi              ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvTC_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvTC_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvTC_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_TC_H__

