/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* USC ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_USC_H__
#define __GC_PROBE_USC_H__

#define cmdProbeCount_UscCc0CacheReq                                       0x0001
#define cmdProbeCount_UscCc1CacheReq                                       0x0002
#define cmdProbeCount_UscCc0CacheLocalMiss                                 0x0003
#define cmdProbeCount_UscCc1CacheLocalMiss                                 0x0004
#define cmdProbeCount_UscCc0CacheReqGlbNonTx                               0x0025
#define cmdProbeCount_UscCc1CacheReqGlbNonTx                               0x0026
#define cmdProbeCount_UscCc0CacheReqGlbTx                                  0x0027
#define cmdProbeCount_UscCc1CacheReqGlbTx                                  0x0028
#define cmdProbeCount_UscCc0CacheGlbNonTxLocalMiss                         0x0029
#define cmdProbeCount_UscCc1CacheGlbNonTxLocalMiss                         0x002A
#define cmdProbeCount_UscCc0CacheGlbTxLocalMiss                            0x002B
#define cmdProbeCount_UscCc1CacheGlbTxLocalMiss                            0x002C
#define cmdProbeCycle_UscCc0CacheStalled                                   0x0005
#define cmdProbeCycle_UscCc1CacheStalled                                   0x0006
#define cmdProbeCount_UscSh2McWrRequests                                   0x0007
#define cmdProbeCycle_UscSh2McWrTotalLatency                               0x0008
#define cmdProbeCount_UscSh2McRdRequests                                   0x0009
#define cmdProbeCycle_UscSh2McRdTotalLatency                               0x000A
#define cmdProbeCount_UscSh2McWrDatacycles                                 0x000B
#define cmdProbeCount_UscMc2ShRdDataCycles_Usc                             0x000C
#define cmdProbeCount_UscMc2ShRdDataCycles_Icache                          0x000D
#define cmdProbeCycle_UscBusy                                              0x000E
#define cmdProbeCount_UscRmwRamTotalWrDataCycles                           0x000F
#define cmdProbeCount_UscRmwRamTotalRdDataCycles                           0x0010
#define cmdProbeCount_DirCc0AttribInputReq                                 0x0011
#define cmdProbeCount_DirCc1AttribInputReq                                 0x0012
#define cmdProbeCycle_DirCc0AttribInputStalled                             0x0013
#define cmdProbeCycle_DirCc1AttribInputStalled                             0x0014
#define cmdProbeCount_DirCc0CacheInputReqSelected                          0x0015
#define cmdProbeCount_DirCc1CacheInputReqSelected                          0x0016
#define cmdProbeCycle_DirCc0CacheInputReqStalled                           0x0017
#define cmdProbeCycle_DirCc1CacheInputReqStalled                           0x0018
#define cmdProbeCycle_DirCc0LookupOutputReqStalled                         0x0019
#define cmdProbeCycle_DirCc1LookupOutputReqStalled                         0x001A
#define cmdProbeCycle_DirCc0CacheReqSelectedRemoteHit                      0x001B
#define cmdProbeCycle_DirCc1CacheReqSelectedRemoteHit                      0x001C
#define cmdProbeCycle_DcacheSnooperOutDataVldAndRdy                        0x001D
#define cmdProbeCycle_HighwayDcacheInputDataVldAndRdy                      0x001E
#define cmdProbeCycle_HighwayXbarBus0OutDataVld                            0x001F
#define cmdProbeCycle_HighwayXbarBus1OutDataVld                            0x0020
#define cmdProbeCycle_HighwayXbarBus2OutDataVld                            0x0021
#define cmdProbeCycle_HighwayXbarBus3OutDataVld                            0x0022
#define cmdProbeCycle_UscTotalClientRmwRamWrites                           0x0023
#define cmdProbeCycle_UscTotalClientRmwRamBytesWritten                     0x0024
#define cmdProbeCycle_UscGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_UscGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_UscGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_UscGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_UscGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_UscGlobalTimerHi                                     0x00FF
#define cmdFPGAProbeCycle_USC_RmwRam0_WrDataCycles                             0xC00
#define cmdFPGAProbeCycle_USC_RmwRam1_WrDataCycles                             0xC01
#define cmdFPGAProbeCycle_USC_RmwRam2_WrDataCycles                             0xC02
#define cmdFPGAProbeCycle_USC_RmwRam3_WrDataCycles                             0xC03
#define cmdFPGAProbeCycle_USC_RmwRam0_RdDataCycles                             0xC04
#define cmdFPGAProbeCycle_USC_RmwRam1_RdDataCycles                             0xC05
#define cmdFPGAProbeCycle_USC_RmwRam2_RdDataCycles                             0xC06
#define cmdFPGAProbeCycle_USC_RmwRam3_RdDataCycles                             0xC07
#define cmdFPGAProbeCycle_DcacheSnooperOutDataVldAndNotRdy                     0xC08
#define cmdFPGAProbeCycle_HighwayDcacheInputDataVldAndNotRdy                   0xC09
#define cmdFPGAProbeCount_DirCc0CacheInputReqAll                               0x0C0A
#define cmdFPGAProbeCount_DirCc1CacheInputReqAll                               0x0C0B
#define cmdFPGAProbeCount_DirCc0CacheInputReqGblTx                             0x0C0C
#define cmdFPGAProbeCount_DirCc1CacheInputReqGblTx                             0x0C0D
#define cmdFPGAProbeCount_DirCc0CacheInputReqGblNonTx                          0x0C0E
#define cmdFPGAProbeCount_DirCc1CacheInputReqGblNonTx                          0x0C0F
#define cmdFPGAProbeCount_DirCc0CacheInputReqGblAttrib                         0x0C10
#define cmdFPGAProbeCount_DirCc1CacheInputReqGblAttrib                         0x0C11
#define cmdFPGAProbeCycle_DirCc0CacheReqAllRemoteHit                           0x0C12
#define cmdFPGAProbeCycle_DirCc1CacheReqAllRemoteHit                           0x0C13
#define cmdFPGAProbeCycle_DirCc0CacheReqGblTxRemoteHit                         0x0C14
#define cmdFPGAProbeCycle_DirCc1CacheReqGblTxRemoteHit                         0x0C15
#define cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxRdRemoteHit                    0x0C16
#define cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxRdRemoteHit                    0x0C17
#define cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxWrRemoteHit                    0x0C18
#define cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxWrRemoteHit                    0x0C19
#define cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxRmwRemoteHit                   0x0C1A
#define cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxRmwRemoteHit                   0x0C1B

enum cmeUSCPROBE
{
    cmvProbeCount_UscCc0CacheReq,
    cmvProbeCount_UscCc1CacheReq,
    cmvProbeCount_UscCc0CacheLocalMiss,
    cmvProbeCount_UscCc1CacheLocalMiss,
    cmvProbeCount_UscCc0CacheReqGlbNonTx,
    cmvProbeCount_UscCc1CacheReqGlbNonTx,
    cmvProbeCount_UscCc0CacheReqGlbTx,
    cmvProbeCount_UscCc1CacheReqGlbTx,
    cmvProbeCount_UscCc0CacheGlbNonTxLocalMiss,
    cmvProbeCount_UscCc1CacheGlbNonTxLocalMiss,
    cmvProbeCount_UscCc0CacheGlbTxLocalMiss,
    cmvProbeCount_UscCc1CacheGlbTxLocalMiss,
    cmvProbeCycle_UscCc0CacheStalled,
    cmvProbeCycle_UscCc1CacheStalled,
    cmvProbeCount_UscSh2McWrRequests,
    cmvProbeCycle_UscSh2McWrTotalLatency,
    cmvProbeCount_UscSh2McRdRequests,
    cmvProbeCycle_UscSh2McRdTotalLatency,
    cmvProbeCount_UscSh2McWrDatacycles,
    cmvProbeCount_UscMc2ShRdDataCycles_Usc,
    cmvProbeCount_UscMc2ShRdDataCycles_Icache,
    cmvProbeCycle_UscBusy,
    cmvProbeCount_UscRmwRamTotalWrDataCycles,
    cmvProbeCount_UscRmwRamTotalRdDataCycles,
    cmvProbeCount_DirCc0AttribInputReq,
    cmvProbeCount_DirCc1AttribInputReq,
    cmvProbeCycle_DirCc0AttribInputStalled,
    cmvProbeCycle_DirCc1AttribInputStalled,
    cmvProbeCount_DirCc0CacheInputReqSelected,
    cmvProbeCount_DirCc1CacheInputReqSelected,
    cmvProbeCycle_DirCc0CacheInputReqStalled,
    cmvProbeCycle_DirCc1CacheInputReqStalled,
    cmvProbeCycle_DirCc0LookupOutputReqStalled,
    cmvProbeCycle_DirCc1LookupOutputReqStalled,
    cmvProbeCycle_DirCc0CacheReqSelectedRemoteHit,
    cmvProbeCycle_DirCc1CacheReqSelectedRemoteHit,
    cmvProbeCycle_DcacheSnooperOutDataVldAndRdy,
    cmvProbeCycle_HighwayDcacheInputDataVldAndRdy,
    cmvProbeCycle_HighwayXbarBus0OutDataVld,
    cmvProbeCycle_HighwayXbarBus1OutDataVld,
    cmvProbeCycle_HighwayXbarBus2OutDataVld,
    cmvProbeCycle_HighwayXbarBus3OutDataVld,
    cmvProbeCycle_UscTotalClientRmwRamWrites,
    cmvProbeCycle_UscTotalClientRmwRamBytesWritten,
    cmvProbeCycle_UscGlobalTimerStartLo,
    cmvProbeCycle_UscGlobalTimerStartHi,
    cmvProbeCycle_UscGlobalTimerEndLo,
    cmvProbeCycle_UscGlobalTimerEndHi,
    cmvProbeCycle_UscGlobalTimerLo,
    cmvProbeCycle_UscGlobalTimerHi,
    cmvFPGAProbeCycle_USC_RmwRam0_WrDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam1_WrDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam2_WrDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam3_WrDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam0_RdDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam1_RdDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam2_RdDataCycles,
    cmvFPGAProbeCycle_USC_RmwRam3_RdDataCycles,
    cmvFPGAProbeCycle_DcacheSnooperOutDataVldAndNotRdy,
    cmvFPGAProbeCycle_HighwayDcacheInputDataVldAndNotRdy,
    cmvFPGAProbeCount_DirCc0CacheInputReqAll,
    cmvFPGAProbeCount_DirCc1CacheInputReqAll,
    cmvFPGAProbeCount_DirCc0CacheInputReqGblTx,
    cmvFPGAProbeCount_DirCc1CacheInputReqGblTx,
    cmvFPGAProbeCount_DirCc0CacheInputReqGblNonTx,
    cmvFPGAProbeCount_DirCc1CacheInputReqGblNonTx,
    cmvFPGAProbeCount_DirCc0CacheInputReqGblAttrib,
    cmvFPGAProbeCount_DirCc1CacheInputReqGblAttrib,
    cmvFPGAProbeCycle_DirCc0CacheReqAllRemoteHit,
    cmvFPGAProbeCycle_DirCc1CacheReqAllRemoteHit,
    cmvFPGAProbeCycle_DirCc0CacheReqGblTxRemoteHit,
    cmvFPGAProbeCycle_DirCc1CacheReqGblTxRemoteHit,
    cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRdRemoteHit,
    cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRdRemoteHit,
    cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxWrRemoteHit,
    cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxWrRemoteHit,
    cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRmwRemoteHit,
    cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRmwRemoteHit,
    cmvUSC_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoUSCProbeMap
{
public:
    cmoUSCProbeMap()
    {
        probeMap[cmvProbeCount_UscCc0CacheReq               ] = cmdProbeCount_UscCc0CacheReq;
        probeMap[cmvProbeCount_UscCc1CacheReq               ] = cmdProbeCount_UscCc1CacheReq;
        probeMap[cmvProbeCount_UscCc0CacheLocalMiss         ] = cmdProbeCount_UscCc0CacheLocalMiss;
        probeMap[cmvProbeCount_UscCc1CacheLocalMiss         ] = cmdProbeCount_UscCc1CacheLocalMiss;
        probeMap[cmvProbeCount_UscCc0CacheReqGlbNonTx       ] = cmdProbeCount_UscCc0CacheReqGlbNonTx;
        probeMap[cmvProbeCount_UscCc1CacheReqGlbNonTx       ] = cmdProbeCount_UscCc1CacheReqGlbNonTx;
        probeMap[cmvProbeCount_UscCc0CacheReqGlbTx          ] = cmdProbeCount_UscCc0CacheReqGlbTx;
        probeMap[cmvProbeCount_UscCc1CacheReqGlbTx          ] = cmdProbeCount_UscCc1CacheReqGlbTx;
        probeMap[cmvProbeCount_UscCc0CacheGlbNonTxLocalMiss ] = cmdProbeCount_UscCc0CacheGlbNonTxLocalMiss;
        probeMap[cmvProbeCount_UscCc1CacheGlbNonTxLocalMiss ] = cmdProbeCount_UscCc1CacheGlbNonTxLocalMiss;
        probeMap[cmvProbeCount_UscCc0CacheGlbTxLocalMiss    ] = cmdProbeCount_UscCc0CacheGlbTxLocalMiss;
        probeMap[cmvProbeCount_UscCc1CacheGlbTxLocalMiss    ] = cmdProbeCount_UscCc1CacheGlbTxLocalMiss;
        probeMap[cmvProbeCycle_UscCc0CacheStalled           ] = cmdProbeCycle_UscCc0CacheStalled;
        probeMap[cmvProbeCycle_UscCc1CacheStalled           ] = cmdProbeCycle_UscCc1CacheStalled;
        probeMap[cmvProbeCount_UscSh2McWrRequests           ] = cmdProbeCount_UscSh2McWrRequests;
        probeMap[cmvProbeCycle_UscSh2McWrTotalLatency       ] = cmdProbeCycle_UscSh2McWrTotalLatency;
        probeMap[cmvProbeCount_UscSh2McRdRequests           ] = cmdProbeCount_UscSh2McRdRequests;
        probeMap[cmvProbeCycle_UscSh2McRdTotalLatency       ] = cmdProbeCycle_UscSh2McRdTotalLatency;
        probeMap[cmvProbeCount_UscSh2McWrDatacycles         ] = cmdProbeCount_UscSh2McWrDatacycles;
        probeMap[cmvProbeCount_UscMc2ShRdDataCycles_Usc     ] = cmdProbeCount_UscMc2ShRdDataCycles_Usc;
        probeMap[cmvProbeCount_UscMc2ShRdDataCycles_Icache  ] = cmdProbeCount_UscMc2ShRdDataCycles_Icache;
        probeMap[cmvProbeCycle_UscBusy                      ] = cmdProbeCycle_UscBusy;
        probeMap[cmvProbeCount_UscRmwRamTotalWrDataCycles   ] = cmdProbeCount_UscRmwRamTotalWrDataCycles;
        probeMap[cmvProbeCount_UscRmwRamTotalRdDataCycles   ] = cmdProbeCount_UscRmwRamTotalRdDataCycles;
        probeMap[cmvProbeCount_DirCc0AttribInputReq         ] = cmdProbeCount_DirCc0AttribInputReq;
        probeMap[cmvProbeCount_DirCc1AttribInputReq         ] = cmdProbeCount_DirCc1AttribInputReq;
        probeMap[cmvProbeCycle_DirCc0AttribInputStalled     ] = cmdProbeCycle_DirCc0AttribInputStalled;
        probeMap[cmvProbeCycle_DirCc1AttribInputStalled     ] = cmdProbeCycle_DirCc1AttribInputStalled;
        probeMap[cmvProbeCount_DirCc0CacheInputReqSelected  ] = cmdProbeCount_DirCc0CacheInputReqSelected;
        probeMap[cmvProbeCount_DirCc1CacheInputReqSelected  ] = cmdProbeCount_DirCc1CacheInputReqSelected;
        probeMap[cmvProbeCycle_DirCc0CacheInputReqStalled   ] = cmdProbeCycle_DirCc0CacheInputReqStalled;
        probeMap[cmvProbeCycle_DirCc1CacheInputReqStalled   ] = cmdProbeCycle_DirCc1CacheInputReqStalled;
        probeMap[cmvProbeCycle_DirCc0LookupOutputReqStalled ] = cmdProbeCycle_DirCc0LookupOutputReqStalled;
        probeMap[cmvProbeCycle_DirCc1LookupOutputReqStalled ] = cmdProbeCycle_DirCc1LookupOutputReqStalled;
        probeMap[cmvProbeCycle_DirCc0CacheReqSelectedRemoteHit] = cmdProbeCycle_DirCc0CacheReqSelectedRemoteHit;
        probeMap[cmvProbeCycle_DirCc1CacheReqSelectedRemoteHit] = cmdProbeCycle_DirCc1CacheReqSelectedRemoteHit;
        probeMap[cmvProbeCycle_DcacheSnooperOutDataVldAndRdy] = cmdProbeCycle_DcacheSnooperOutDataVldAndRdy;
        probeMap[cmvProbeCycle_HighwayDcacheInputDataVldAndRdy] = cmdProbeCycle_HighwayDcacheInputDataVldAndRdy;
        probeMap[cmvProbeCycle_HighwayXbarBus0OutDataVld    ] = cmdProbeCycle_HighwayXbarBus0OutDataVld;
        probeMap[cmvProbeCycle_HighwayXbarBus1OutDataVld    ] = cmdProbeCycle_HighwayXbarBus1OutDataVld;
        probeMap[cmvProbeCycle_HighwayXbarBus2OutDataVld    ] = cmdProbeCycle_HighwayXbarBus2OutDataVld;
        probeMap[cmvProbeCycle_HighwayXbarBus3OutDataVld    ] = cmdProbeCycle_HighwayXbarBus3OutDataVld;
        probeMap[cmvProbeCycle_UscTotalClientRmwRamWrites   ] = cmdProbeCycle_UscTotalClientRmwRamWrites;
        probeMap[cmvProbeCycle_UscTotalClientRmwRamBytesWritten] = cmdProbeCycle_UscTotalClientRmwRamBytesWritten;
        probeMap[cmvProbeCycle_UscGlobalTimerStartLo        ] = cmdProbeCycle_UscGlobalTimerStartLo;
        probeMap[cmvProbeCycle_UscGlobalTimerStartHi        ] = cmdProbeCycle_UscGlobalTimerStartHi;
        probeMap[cmvProbeCycle_UscGlobalTimerEndLo          ] = cmdProbeCycle_UscGlobalTimerEndLo;
        probeMap[cmvProbeCycle_UscGlobalTimerEndHi          ] = cmdProbeCycle_UscGlobalTimerEndHi;
        probeMap[cmvProbeCycle_UscGlobalTimerLo             ] = cmdProbeCycle_UscGlobalTimerLo;
        probeMap[cmvProbeCycle_UscGlobalTimerHi             ] = cmdProbeCycle_UscGlobalTimerHi;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam0_WrDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam0_WrDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam1_WrDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam1_WrDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam2_WrDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam2_WrDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam3_WrDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam3_WrDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam0_RdDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam0_RdDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam1_RdDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam1_RdDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam2_RdDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam2_RdDataCycles;
        probeMap[cmvFPGAProbeCycle_USC_RmwRam3_RdDataCycles ] = cmdFPGAProbeCycle_USC_RmwRam3_RdDataCycles;
        probeMap[cmvFPGAProbeCycle_DcacheSnooperOutDataVldAndNotRdy] = cmdFPGAProbeCycle_DcacheSnooperOutDataVldAndNotRdy;
        probeMap[cmvFPGAProbeCycle_HighwayDcacheInputDataVldAndNotRdy] = cmdFPGAProbeCycle_HighwayDcacheInputDataVldAndNotRdy;
        probeMap[cmvFPGAProbeCount_DirCc0CacheInputReqAll   ] = cmdFPGAProbeCount_DirCc0CacheInputReqAll;
        probeMap[cmvFPGAProbeCount_DirCc1CacheInputReqAll   ] = cmdFPGAProbeCount_DirCc1CacheInputReqAll;
        probeMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblTx ] = cmdFPGAProbeCount_DirCc0CacheInputReqGblTx;
        probeMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblTx ] = cmdFPGAProbeCount_DirCc1CacheInputReqGblTx;
        probeMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblNonTx] = cmdFPGAProbeCount_DirCc0CacheInputReqGblNonTx;
        probeMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblNonTx] = cmdFPGAProbeCount_DirCc1CacheInputReqGblNonTx;
        probeMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblAttrib] = cmdFPGAProbeCount_DirCc0CacheInputReqGblAttrib;
        probeMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblAttrib] = cmdFPGAProbeCount_DirCc1CacheInputReqGblAttrib;
        probeMap[cmvFPGAProbeCycle_DirCc0CacheReqAllRemoteHit] = cmdFPGAProbeCycle_DirCc0CacheReqAllRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc1CacheReqAllRemoteHit] = cmdFPGAProbeCycle_DirCc1CacheReqAllRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc0CacheReqGblTxRemoteHit] = cmdFPGAProbeCycle_DirCc0CacheReqGblTxRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc1CacheReqGblTxRemoteHit] = cmdFPGAProbeCycle_DirCc1CacheReqGblTxRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRdRemoteHit] = cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxRdRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRdRemoteHit] = cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxRdRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxWrRemoteHit] = cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxWrRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxWrRemoteHit] = cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxWrRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRmwRemoteHit] = cmdFPGAProbeCycle_DirCc0CacheReqGblNonTxRmwRemoteHit;
        probeMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRmwRemoteHit] = cmdFPGAProbeCycle_DirCc1CacheReqGblNonTxRmwRemoteHit;

        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheReq               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheReq               ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheLocalMiss         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheLocalMiss         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheReqGlbNonTx       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheReqGlbNonTx       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheReqGlbTx          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheReqGlbTx          ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheGlbNonTxLocalMiss ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheGlbNonTxLocalMiss ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc0CacheGlbTxLocalMiss    ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscCc1CacheGlbTxLocalMiss    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscCc0CacheStalled           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscCc1CacheStalled           ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscSh2McWrRequests           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscSh2McWrTotalLatency       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscSh2McRdRequests           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscSh2McRdTotalLatency       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscSh2McWrDatacycles         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscMc2ShRdDataCycles_Usc     ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscMc2ShRdDataCycles_Icache  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscRmwRamTotalWrDataCycles   ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_UscRmwRamTotalRdDataCycles   ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_DirCc0AttribInputReq         ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_DirCc1AttribInputReq         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc0AttribInputStalled     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc1AttribInputStalled     ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_DirCc0CacheInputReqSelected  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_DirCc1CacheInputReqSelected  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc0CacheInputReqStalled   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc1CacheInputReqStalled   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc0LookupOutputReqStalled ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc1LookupOutputReqStalled ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc0CacheReqSelectedRemoteHit] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCc1CacheReqSelectedRemoteHit] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DcacheSnooperOutDataVldAndRdy] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_HighwayDcacheInputDataVldAndRdy] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_HighwayXbarBus0OutDataVld    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_HighwayXbarBus1OutDataVld    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_HighwayXbarBus2OutDataVld    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_HighwayXbarBus3OutDataVld    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscTotalClientRmwRamWrites   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscTotalClientRmwRamBytesWritten] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_UscGlobalTimerHi             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam0_WrDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam1_WrDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam2_WrDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam3_WrDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam0_RdDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam1_RdDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam2_RdDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_USC_RmwRam3_RdDataCycles ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DcacheSnooperOutDataVldAndNotRdy] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_HighwayDcacheInputDataVldAndNotRdy] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc0CacheInputReqAll   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc1CacheInputReqAll   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblTx ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblTx ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblNonTx] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblNonTx] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc0CacheInputReqGblAttrib] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DirCc1CacheInputReqGblAttrib] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc0CacheReqAllRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc1CacheReqAllRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc0CacheReqGblTxRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc1CacheReqGblTxRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRdRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRdRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxWrRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxWrRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc0CacheReqGblNonTxRmwRemoteHit] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_DirCc1CacheReqGblNonTxRmwRemoteHit] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvUSC_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvUSC_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvUSC_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_USC_H__

