/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* PE ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_PE_H__
#define __GC_PROBE_PE_H__

#define cmdProbeState_PeAQAlphaBlendEn                                     0x0301
#define cmdProbeState_PeGcregPEConfig                                      0x0302
#define cmdProbeState_PeGcregPEConfigEx                                    0x0303
#define cmdProbeState_PeColorFormatRt0_3                                   0x0304
#define cmdProbeState_PeColorFormatRt4_7                                   0x0305
#define cmdProbeCount_PeDepthKillPixel                                     0x0001
#define cmdProbeCount_PeDepthDrawPixel                                     0x0002
#define cmdProbeCount_PeColorKillPixel                                     0x0003
#define cmdProbeCount_PeColorDrawPixel                                     0x0004
#define cmdProbeCount_PeC2CacheTotalReq                                    0x0005
#define cmdProbeCount_PeC2CacheMissReq                                     0x0006
#define cmdProbeCount_PeZ2CacheTotalReq                                    0x0007
#define cmdProbeCount_PeZ2CacheMissReq                                     0x0008
#define cmdProbeCount_PeC2McRdReq                                          0x0009
#define cmdProbeCount_PeC2McWrReq                                          0x000A
#define cmdProbeCount_PeZ2McRdReq                                          0x000B
#define cmdProbeCount_PeZ2McWrReq                                          0x000C
#define cmdProbeCycle_PeCBusy                                              0x0010
#define cmdProbeCycle_PeZBusy                                              0x0011
#define cmdProbeCycle_ShVldAndPeRdy                                        0x0012
#define cmdProbeCycle_ShVldAndPeNotRdy                                     0x0013
#define cmdProbeCycle_PeCZVldMcNotRdy                                      0x0014
#define cmdProbeCycle_DataPeCRrbVld                                        0x0015
#define cmdProbeCycle_DataPeZRrbVld                                        0x0016
#define cmdProbeCycle_DataPeCWrVldMcRdy                                    0x0017
#define cmdProbeCycle_DataPeCWrVldMcNotRdy                                 0x0018
#define cmdProbeCycle_DataPeZWrVldMcRdy                                    0x0019
#define cmdProbeCycle_DataPeZWrVldMcNotRdy                                 0x001A
#define cmdProbeCycle_PeC2McRdTotalLatency                                 0x001B
#define cmdProbeCycle_PeC2McWrTotalLatency                                 0x001C
#define cmdProbeCycle_PeZ2McRdTotalLatency                                 0x001D
#define cmdProbeCycle_PeZ2McWrTotalLatency                                 0x001E
#define cmdProbeCycle_PeCCacheDataNotAvailable                             0x001F
#define cmdProbeCycle_PeZCacheDataNotAvailable                             0x0020
#define cmdProbeCycle_PeCCacheReqStalledMissNoLineAvailable                0x0021
#define cmdProbeCycle_PeZCacheReqStalledMissNoLineAvailable                0x0022
#define cmdProbeCycle_PeCCacheReqStalledAny                                0x0023
#define cmdProbeCycle_PeZCacheReqStalledAny                                0x0024
#define cmdProbeCycle_PeCCacheReqStalledCoherency                          0x0025
#define cmdProbeCycle_PeZCacheReqStalledCoherency                          0x0026
#define cmdProbeCycle_Sh2PeNotVldData                                      0x0027
#define cmdProbeCycle_PeGlobalTimerStartLo                                 0x00FA
#define cmdProbeCycle_PeGlobalTimerStartHi                                 0x00FB
#define cmdProbeCycle_PeGlobalTimerEndLo                                   0x00FC
#define cmdProbeCycle_PeGlobalTimerEndHi                                   0x00FD
#define cmdProbeCycle_PeGlobalTimerLo                                      0x00FE
#define cmdProbeCycle_PeGlobalTimerHi                                      0x00FF
#define cmdFPGAProbeState_PeAQDepthConfig                                      0x0401
#define cmdFPGAProbeState_AQAlphaBlend                                         0x0402
#define cmdFPGAProbeState_gcregPEConfigEx                                      0x0403
#define cmdFPGAProbeState_PegcregMultiSampleConfig                             0x0404
#define cmdFPGAProbeCount_DepthKillPixel                                       0x0801
#define cmdFPGAProbeCount_DepthDrawPixel                                       0x0802
#define cmdFPGAProbeCount_ColorKillPixel                                       0x0803
#define cmdFPGAProbeCount_ColorDrawPixel                                       0x0804
#define cmdFPGAProbeCount_PeC2McRdByte                                         0x0805
#define cmdFPGAProbeCount_PeC2McWrByte                                         0x0806
#define cmdFPGAProbeCount_PeZ2McRdByte                                         0x0807
#define cmdFPGAProbeCount_PeZ2McWrByte                                         0x0808
#define cmdFPGAProbeCount_PeC2CacheReq                                         0x0809
#define cmdFPGAProbeCount_PeC2CacheMissReq                                     0x080A
#define cmdFPGAProbeCount_PeZ2CacheReq                                         0x080B
#define cmdFPGAProbeCount_PeZ2CacheMissReq                                     0x080C
#define cmdFPGAProbeCount_PeC2McRdReq                                          0x080D
#define cmdFPGAProbeCount_PeC2McWrReq                                          0x080E
#define cmdFPGAProbeCount_PeZ2McRdReq                                          0x080F
#define cmdFPGAProbeCount_PeZ2McWrReq                                          0x0810
#define cmdFPGAProbeCycle_ShVldAndPeRdy                                        0x0C01
#define cmdFPGAProbeCycle_ShVldAndPeNotRdy                                     0x0C02
#define cmdFPGAProbeCycle_ShNotVldAndPeRdy                                     0x0C03
#define cmdFPGAProbeCycle_ShNotVldAndPeNotRdy                                  0x0C04
#define cmdFPGAProbeCycle_PeBusy                                               0x0C05
#define cmdFPGAProbeCycle_PeCBusy                                              0x0C06
#define cmdFPGAProbeCycle_PeZBusy                                              0x0C07
#define cmdFPGAProbeCycle_PeCPfifoStall                                        0x0C08
#define cmdFPGAProbeCycle_PeZPfifoStall                                        0x0C09
#define cmdFPGAProbeCycle_PeC2McRdStall                                        0x0C0A
#define cmdFPGAProbeCycle_PeC2McWrStall                                        0x0C0B
#define cmdFPGAProbeCycle_PeZ2McRdStall                                        0x0C0C
#define cmdFPGAProbeCycle_PeZ2McWrStall                                        0x0C0D
#define cmdFPGAProbeCycle_PeC2CacheStall                                       0x0C0E
#define cmdFPGAProbeCycle_PeZ2CacheStall                                       0x0C0F

enum cmePEPROBE
{
    cmvProbeState_PeAQAlphaBlendEn,
    cmvProbeState_PeGcregPEConfig,
    cmvProbeState_PeGcregPEConfigEx,
    cmvProbeState_PeColorFormatRt0_3,
    cmvProbeState_PeColorFormatRt4_7,
    cmvProbeCount_PeDepthKillPixel,
    cmvProbeCount_PeDepthDrawPixel,
    cmvProbeCount_PeColorKillPixel,
    cmvProbeCount_PeColorDrawPixel,
    cmvProbeCount_PeC2CacheTotalReq,
    cmvProbeCount_PeC2CacheMissReq,
    cmvProbeCount_PeZ2CacheTotalReq,
    cmvProbeCount_PeZ2CacheMissReq,
    cmvProbeCount_PeC2McRdReq,
    cmvProbeCount_PeC2McWrReq,
    cmvProbeCount_PeZ2McRdReq,
    cmvProbeCount_PeZ2McWrReq,
    cmvProbeCycle_PeCBusy,
    cmvProbeCycle_PeZBusy,
    cmvProbeCycle_ShVldAndPeRdy,
    cmvProbeCycle_ShVldAndPeNotRdy,
    cmvProbeCycle_PeCZVldMcNotRdy,
    cmvProbeCycle_DataPeCRrbVld,
    cmvProbeCycle_DataPeZRrbVld,
    cmvProbeCycle_DataPeCWrVldMcRdy,
    cmvProbeCycle_DataPeCWrVldMcNotRdy,
    cmvProbeCycle_DataPeZWrVldMcRdy,
    cmvProbeCycle_DataPeZWrVldMcNotRdy,
    cmvProbeCycle_PeC2McRdTotalLatency,
    cmvProbeCycle_PeC2McWrTotalLatency,
    cmvProbeCycle_PeZ2McRdTotalLatency,
    cmvProbeCycle_PeZ2McWrTotalLatency,
    cmvProbeCycle_PeCCacheDataNotAvailable,
    cmvProbeCycle_PeZCacheDataNotAvailable,
    cmvProbeCycle_PeCCacheReqStalledMissNoLineAvailable,
    cmvProbeCycle_PeZCacheReqStalledMissNoLineAvailable,
    cmvProbeCycle_PeCCacheReqStalledAny,
    cmvProbeCycle_PeZCacheReqStalledAny,
    cmvProbeCycle_PeCCacheReqStalledCoherency,
    cmvProbeCycle_PeZCacheReqStalledCoherency,
    cmvProbeCycle_Sh2PeNotVldData,
    cmvProbeCycle_PeGlobalTimerStartLo,
    cmvProbeCycle_PeGlobalTimerStartHi,
    cmvProbeCycle_PeGlobalTimerEndLo,
    cmvProbeCycle_PeGlobalTimerEndHi,
    cmvProbeCycle_PeGlobalTimerLo,
    cmvProbeCycle_PeGlobalTimerHi,
    cmvFPGAProbeState_PeAQDepthConfig,
    cmvFPGAProbeState_AQAlphaBlend,
    cmvFPGAProbeState_gcregPEConfigEx,
    cmvFPGAProbeState_PegcregMultiSampleConfig,
    cmvFPGAProbeCount_DepthKillPixel,
    cmvFPGAProbeCount_DepthDrawPixel,
    cmvFPGAProbeCount_ColorKillPixel,
    cmvFPGAProbeCount_ColorDrawPixel,
    cmvFPGAProbeCount_PeC2McRdByte,
    cmvFPGAProbeCount_PeC2McWrByte,
    cmvFPGAProbeCount_PeZ2McRdByte,
    cmvFPGAProbeCount_PeZ2McWrByte,
    cmvFPGAProbeCount_PeC2CacheReq,
    cmvFPGAProbeCount_PeC2CacheMissReq,
    cmvFPGAProbeCount_PeZ2CacheReq,
    cmvFPGAProbeCount_PeZ2CacheMissReq,
    cmvFPGAProbeCount_PeC2McRdReq,
    cmvFPGAProbeCount_PeC2McWrReq,
    cmvFPGAProbeCount_PeZ2McRdReq,
    cmvFPGAProbeCount_PeZ2McWrReq,
    cmvFPGAProbeCycle_ShVldAndPeRdy,
    cmvFPGAProbeCycle_ShVldAndPeNotRdy,
    cmvFPGAProbeCycle_ShNotVldAndPeRdy,
    cmvFPGAProbeCycle_ShNotVldAndPeNotRdy,
    cmvFPGAProbeCycle_PeBusy,
    cmvFPGAProbeCycle_PeCBusy,
    cmvFPGAProbeCycle_PeZBusy,
    cmvFPGAProbeCycle_PeCPfifoStall,
    cmvFPGAProbeCycle_PeZPfifoStall,
    cmvFPGAProbeCycle_PeC2McRdStall,
    cmvFPGAProbeCycle_PeC2McWrStall,
    cmvFPGAProbeCycle_PeZ2McRdStall,
    cmvFPGAProbeCycle_PeZ2McWrStall,
    cmvFPGAProbeCycle_PeC2CacheStall,
    cmvFPGAProbeCycle_PeZ2CacheStall,
    cmvPE_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoPEProbeMap
{
public:
    cmoPEProbeMap()
    {
        probeMap[cmvProbeState_PeAQAlphaBlendEn             ] = cmdProbeState_PeAQAlphaBlendEn;
        probeMap[cmvProbeState_PeGcregPEConfig              ] = cmdProbeState_PeGcregPEConfig;
        probeMap[cmvProbeState_PeGcregPEConfigEx            ] = cmdProbeState_PeGcregPEConfigEx;
        probeMap[cmvProbeState_PeColorFormatRt0_3           ] = cmdProbeState_PeColorFormatRt0_3;
        probeMap[cmvProbeState_PeColorFormatRt4_7           ] = cmdProbeState_PeColorFormatRt4_7;
        probeMap[cmvProbeCount_PeDepthKillPixel             ] = cmdProbeCount_PeDepthKillPixel;
        probeMap[cmvProbeCount_PeDepthDrawPixel             ] = cmdProbeCount_PeDepthDrawPixel;
        probeMap[cmvProbeCount_PeColorKillPixel             ] = cmdProbeCount_PeColorKillPixel;
        probeMap[cmvProbeCount_PeColorDrawPixel             ] = cmdProbeCount_PeColorDrawPixel;
        probeMap[cmvProbeCount_PeC2CacheTotalReq            ] = cmdProbeCount_PeC2CacheTotalReq;
        probeMap[cmvProbeCount_PeC2CacheMissReq             ] = cmdProbeCount_PeC2CacheMissReq;
        probeMap[cmvProbeCount_PeZ2CacheTotalReq            ] = cmdProbeCount_PeZ2CacheTotalReq;
        probeMap[cmvProbeCount_PeZ2CacheMissReq             ] = cmdProbeCount_PeZ2CacheMissReq;
        probeMap[cmvProbeCount_PeC2McRdReq                  ] = cmdProbeCount_PeC2McRdReq;
        probeMap[cmvProbeCount_PeC2McWrReq                  ] = cmdProbeCount_PeC2McWrReq;
        probeMap[cmvProbeCount_PeZ2McRdReq                  ] = cmdProbeCount_PeZ2McRdReq;
        probeMap[cmvProbeCount_PeZ2McWrReq                  ] = cmdProbeCount_PeZ2McWrReq;
        probeMap[cmvProbeCycle_PeCBusy                      ] = cmdProbeCycle_PeCBusy;
        probeMap[cmvProbeCycle_PeZBusy                      ] = cmdProbeCycle_PeZBusy;
        probeMap[cmvProbeCycle_ShVldAndPeRdy                ] = cmdProbeCycle_ShVldAndPeRdy;
        probeMap[cmvProbeCycle_ShVldAndPeNotRdy             ] = cmdProbeCycle_ShVldAndPeNotRdy;
        probeMap[cmvProbeCycle_PeCZVldMcNotRdy              ] = cmdProbeCycle_PeCZVldMcNotRdy;
        probeMap[cmvProbeCycle_DataPeCRrbVld                ] = cmdProbeCycle_DataPeCRrbVld;
        probeMap[cmvProbeCycle_DataPeZRrbVld                ] = cmdProbeCycle_DataPeZRrbVld;
        probeMap[cmvProbeCycle_DataPeCWrVldMcRdy            ] = cmdProbeCycle_DataPeCWrVldMcRdy;
        probeMap[cmvProbeCycle_DataPeCWrVldMcNotRdy         ] = cmdProbeCycle_DataPeCWrVldMcNotRdy;
        probeMap[cmvProbeCycle_DataPeZWrVldMcRdy            ] = cmdProbeCycle_DataPeZWrVldMcRdy;
        probeMap[cmvProbeCycle_DataPeZWrVldMcNotRdy         ] = cmdProbeCycle_DataPeZWrVldMcNotRdy;
        probeMap[cmvProbeCycle_PeC2McRdTotalLatency         ] = cmdProbeCycle_PeC2McRdTotalLatency;
        probeMap[cmvProbeCycle_PeC2McWrTotalLatency         ] = cmdProbeCycle_PeC2McWrTotalLatency;
        probeMap[cmvProbeCycle_PeZ2McRdTotalLatency         ] = cmdProbeCycle_PeZ2McRdTotalLatency;
        probeMap[cmvProbeCycle_PeZ2McWrTotalLatency         ] = cmdProbeCycle_PeZ2McWrTotalLatency;
        probeMap[cmvProbeCycle_PeCCacheDataNotAvailable     ] = cmdProbeCycle_PeCCacheDataNotAvailable;
        probeMap[cmvProbeCycle_PeZCacheDataNotAvailable     ] = cmdProbeCycle_PeZCacheDataNotAvailable;
        probeMap[cmvProbeCycle_PeCCacheReqStalledMissNoLineAvailable] = cmdProbeCycle_PeCCacheReqStalledMissNoLineAvailable;
        probeMap[cmvProbeCycle_PeZCacheReqStalledMissNoLineAvailable] = cmdProbeCycle_PeZCacheReqStalledMissNoLineAvailable;
        probeMap[cmvProbeCycle_PeCCacheReqStalledAny        ] = cmdProbeCycle_PeCCacheReqStalledAny;
        probeMap[cmvProbeCycle_PeZCacheReqStalledAny        ] = cmdProbeCycle_PeZCacheReqStalledAny;
        probeMap[cmvProbeCycle_PeCCacheReqStalledCoherency  ] = cmdProbeCycle_PeCCacheReqStalledCoherency;
        probeMap[cmvProbeCycle_PeZCacheReqStalledCoherency  ] = cmdProbeCycle_PeZCacheReqStalledCoherency;
        probeMap[cmvProbeCycle_Sh2PeNotVldData              ] = cmdProbeCycle_Sh2PeNotVldData;
        probeMap[cmvProbeCycle_PeGlobalTimerStartLo         ] = cmdProbeCycle_PeGlobalTimerStartLo;
        probeMap[cmvProbeCycle_PeGlobalTimerStartHi         ] = cmdProbeCycle_PeGlobalTimerStartHi;
        probeMap[cmvProbeCycle_PeGlobalTimerEndLo           ] = cmdProbeCycle_PeGlobalTimerEndLo;
        probeMap[cmvProbeCycle_PeGlobalTimerEndHi           ] = cmdProbeCycle_PeGlobalTimerEndHi;
        probeMap[cmvProbeCycle_PeGlobalTimerLo              ] = cmdProbeCycle_PeGlobalTimerLo;
        probeMap[cmvProbeCycle_PeGlobalTimerHi              ] = cmdProbeCycle_PeGlobalTimerHi;
        probeMap[cmvFPGAProbeState_PeAQDepthConfig          ] = cmdFPGAProbeState_PeAQDepthConfig;
        probeMap[cmvFPGAProbeState_AQAlphaBlend             ] = cmdFPGAProbeState_AQAlphaBlend;
        probeMap[cmvFPGAProbeState_gcregPEConfigEx          ] = cmdFPGAProbeState_gcregPEConfigEx;
        probeMap[cmvFPGAProbeState_PegcregMultiSampleConfig ] = cmdFPGAProbeState_PegcregMultiSampleConfig;
        probeMap[cmvFPGAProbeCount_DepthKillPixel           ] = cmdFPGAProbeCount_DepthKillPixel;
        probeMap[cmvFPGAProbeCount_DepthDrawPixel           ] = cmdFPGAProbeCount_DepthDrawPixel;
        probeMap[cmvFPGAProbeCount_ColorKillPixel           ] = cmdFPGAProbeCount_ColorKillPixel;
        probeMap[cmvFPGAProbeCount_ColorDrawPixel           ] = cmdFPGAProbeCount_ColorDrawPixel;
        probeMap[cmvFPGAProbeCount_PeC2McRdByte             ] = cmdFPGAProbeCount_PeC2McRdByte;
        probeMap[cmvFPGAProbeCount_PeC2McWrByte             ] = cmdFPGAProbeCount_PeC2McWrByte;
        probeMap[cmvFPGAProbeCount_PeZ2McRdByte             ] = cmdFPGAProbeCount_PeZ2McRdByte;
        probeMap[cmvFPGAProbeCount_PeZ2McWrByte             ] = cmdFPGAProbeCount_PeZ2McWrByte;
        probeMap[cmvFPGAProbeCount_PeC2CacheReq             ] = cmdFPGAProbeCount_PeC2CacheReq;
        probeMap[cmvFPGAProbeCount_PeC2CacheMissReq         ] = cmdFPGAProbeCount_PeC2CacheMissReq;
        probeMap[cmvFPGAProbeCount_PeZ2CacheReq             ] = cmdFPGAProbeCount_PeZ2CacheReq;
        probeMap[cmvFPGAProbeCount_PeZ2CacheMissReq         ] = cmdFPGAProbeCount_PeZ2CacheMissReq;
        probeMap[cmvFPGAProbeCount_PeC2McRdReq              ] = cmdFPGAProbeCount_PeC2McRdReq;
        probeMap[cmvFPGAProbeCount_PeC2McWrReq              ] = cmdFPGAProbeCount_PeC2McWrReq;
        probeMap[cmvFPGAProbeCount_PeZ2McRdReq              ] = cmdFPGAProbeCount_PeZ2McRdReq;
        probeMap[cmvFPGAProbeCount_PeZ2McWrReq              ] = cmdFPGAProbeCount_PeZ2McWrReq;
        probeMap[cmvFPGAProbeCycle_ShVldAndPeRdy            ] = cmdFPGAProbeCycle_ShVldAndPeRdy;
        probeMap[cmvFPGAProbeCycle_ShVldAndPeNotRdy         ] = cmdFPGAProbeCycle_ShVldAndPeNotRdy;
        probeMap[cmvFPGAProbeCycle_ShNotVldAndPeRdy         ] = cmdFPGAProbeCycle_ShNotVldAndPeRdy;
        probeMap[cmvFPGAProbeCycle_ShNotVldAndPeNotRdy      ] = cmdFPGAProbeCycle_ShNotVldAndPeNotRdy;
        probeMap[cmvFPGAProbeCycle_PeBusy                   ] = cmdFPGAProbeCycle_PeBusy;
        probeMap[cmvFPGAProbeCycle_PeCBusy                  ] = cmdFPGAProbeCycle_PeCBusy;
        probeMap[cmvFPGAProbeCycle_PeZBusy                  ] = cmdFPGAProbeCycle_PeZBusy;
        probeMap[cmvFPGAProbeCycle_PeCPfifoStall            ] = cmdFPGAProbeCycle_PeCPfifoStall;
        probeMap[cmvFPGAProbeCycle_PeZPfifoStall            ] = cmdFPGAProbeCycle_PeZPfifoStall;
        probeMap[cmvFPGAProbeCycle_PeC2McRdStall            ] = cmdFPGAProbeCycle_PeC2McRdStall;
        probeMap[cmvFPGAProbeCycle_PeC2McWrStall            ] = cmdFPGAProbeCycle_PeC2McWrStall;
        probeMap[cmvFPGAProbeCycle_PeZ2McRdStall            ] = cmdFPGAProbeCycle_PeZ2McRdStall;
        probeMap[cmvFPGAProbeCycle_PeZ2McWrStall            ] = cmdFPGAProbeCycle_PeZ2McWrStall;
        probeMap[cmvFPGAProbeCycle_PeC2CacheStall           ] = cmdFPGAProbeCycle_PeC2CacheStall;
        probeMap[cmvFPGAProbeCycle_PeZ2CacheStall           ] = cmdFPGAProbeCycle_PeZ2CacheStall;

        probeCmodelAttributesMap[cmvProbeState_PeAQAlphaBlendEn             ] = 1;
        probeCmodelAttributesMap[cmvProbeState_PeGcregPEConfig              ] = 1;
        probeCmodelAttributesMap[cmvProbeState_PeGcregPEConfigEx            ] = 1;
        probeCmodelAttributesMap[cmvProbeState_PeColorFormatRt0_3           ] = 1;
        probeCmodelAttributesMap[cmvProbeState_PeColorFormatRt4_7           ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PeDepthKillPixel             ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PeDepthDrawPixel             ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PeColorKillPixel             ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PeColorDrawPixel             ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PeC2CacheTotalReq            ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeC2CacheMissReq             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeZ2CacheTotalReq            ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeZ2CacheMissReq             ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeC2McRdReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeC2McWrReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeZ2McRdReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PeZ2McWrReq                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_ShVldAndPeRdy                ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_ShVldAndPeNotRdy             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCZVldMcNotRdy              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeCRrbVld                ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeZRrbVld                ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeCWrVldMcRdy            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeCWrVldMcNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeZWrVldMcRdy            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataPeZWrVldMcNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeC2McRdTotalLatency         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeC2McWrTotalLatency         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZ2McRdTotalLatency         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZ2McWrTotalLatency         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCCacheDataNotAvailable     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZCacheDataNotAvailable     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCCacheReqStalledMissNoLineAvailable] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZCacheReqStalledMissNoLineAvailable] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCCacheReqStalledAny        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZCacheReqStalledAny        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeCCacheReqStalledCoherency  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeZCacheReqStalledCoherency  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Sh2PeNotVldData              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerStartLo         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerStartHi         ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerEndLo           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerEndHi           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerLo              ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PeGlobalTimerHi              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeState_PeAQDepthConfig          ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeState_AQAlphaBlend             ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeState_gcregPEConfigEx          ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeState_PegcregMultiSampleConfig ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DepthKillPixel           ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_DepthDrawPixel           ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ColorKillPixel           ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_ColorDrawPixel           ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2McRdByte             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2McWrByte             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2McRdByte             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2McWrByte             ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2CacheReq             ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2CacheMissReq         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2CacheReq             ] = 1;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2CacheMissReq         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2McRdReq              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeC2McWrReq              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2McRdReq              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCount_PeZ2McWrReq              ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_ShVldAndPeRdy            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_ShVldAndPeNotRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_ShNotVldAndPeRdy         ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_ShNotVldAndPeNotRdy      ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeBusy                   ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeCBusy                  ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeZBusy                  ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeCPfifoStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeZPfifoStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeC2McRdStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeC2McWrStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeZ2McRdStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeZ2McWrStall            ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeC2CacheStall           ] = 0;
        probeCmodelAttributesMap[cmvFPGAProbeCycle_PeZ2CacheStall           ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvPE_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvPE_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvPE_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_PE_H__

