/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* BLT ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_BLT_H__
#define __GC_PROBE_BLT_H__

#define cmdProbeState_BltExecutionCmd                                      0x0001
#define cmdProbeState_BltWindowSize                                        0x0002
#define cmdProbeState_BltCopySize                                          0x0003
#define cmdProbeState_BltFillerCount                                       0x0004
#define cmdProbeCycle_BltBusy                                              0x0010
#define cmdProbeCycle_Mc2BltRdDataCycle                                    0x0011
#define cmdProbeCycle_Blt2McWrDataCycle                                    0x0012
#define cmdProbeCycle_BltSrcWalkerAddrCycle                                0x0013
#define cmdProbeCycle_BltDstWalkerAddrCycle                                0x0014
#define cmdProbeCycle_BltRdStall                                           0x0015
#define cmdProbeCycle_BltWrStall                                           0x0016
#define cmdProbeCycle_BltDstAddrRtsCycle                                   0x0017
#define cmdProbeCycle_BltDstPipeBusyCycle                                  0x0018
#define cmdProbeCycle_BltFillerBusyCycle                                   0x0019
#define cmdProbeCycle_BltGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_BltGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_BltGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_BltGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_BltGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_BltGlobalTimerHi                                     0x00FF

enum cmeBLTPROBE
{
    cmvProbeState_BltExecutionCmd,
    cmvProbeState_BltWindowSize,
    cmvProbeState_BltCopySize,
    cmvProbeState_BltFillerCount,
    cmvProbeCycle_BltBusy,
    cmvProbeCycle_Mc2BltRdDataCycle,
    cmvProbeCycle_Blt2McWrDataCycle,
    cmvProbeCycle_BltSrcWalkerAddrCycle,
    cmvProbeCycle_BltDstWalkerAddrCycle,
    cmvProbeCycle_BltRdStall,
    cmvProbeCycle_BltWrStall,
    cmvProbeCycle_BltDstAddrRtsCycle,
    cmvProbeCycle_BltDstPipeBusyCycle,
    cmvProbeCycle_BltFillerBusyCycle,
    cmvProbeCycle_BltGlobalTimerStartLo,
    cmvProbeCycle_BltGlobalTimerStartHi,
    cmvProbeCycle_BltGlobalTimerEndLo,
    cmvProbeCycle_BltGlobalTimerEndHi,
    cmvProbeCycle_BltGlobalTimerLo,
    cmvProbeCycle_BltGlobalTimerHi,
    cmvBLT_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoBLTProbeMap
{
public:
    cmoBLTProbeMap()
    {
        probeMap[cmvProbeState_BltExecutionCmd              ] = cmdProbeState_BltExecutionCmd;
        probeMap[cmvProbeState_BltWindowSize                ] = cmdProbeState_BltWindowSize;
        probeMap[cmvProbeState_BltCopySize                  ] = cmdProbeState_BltCopySize;
        probeMap[cmvProbeState_BltFillerCount               ] = cmdProbeState_BltFillerCount;
        probeMap[cmvProbeCycle_BltBusy                      ] = cmdProbeCycle_BltBusy;
        probeMap[cmvProbeCycle_Mc2BltRdDataCycle            ] = cmdProbeCycle_Mc2BltRdDataCycle;
        probeMap[cmvProbeCycle_Blt2McWrDataCycle            ] = cmdProbeCycle_Blt2McWrDataCycle;
        probeMap[cmvProbeCycle_BltSrcWalkerAddrCycle        ] = cmdProbeCycle_BltSrcWalkerAddrCycle;
        probeMap[cmvProbeCycle_BltDstWalkerAddrCycle        ] = cmdProbeCycle_BltDstWalkerAddrCycle;
        probeMap[cmvProbeCycle_BltRdStall                   ] = cmdProbeCycle_BltRdStall;
        probeMap[cmvProbeCycle_BltWrStall                   ] = cmdProbeCycle_BltWrStall;
        probeMap[cmvProbeCycle_BltDstAddrRtsCycle           ] = cmdProbeCycle_BltDstAddrRtsCycle;
        probeMap[cmvProbeCycle_BltDstPipeBusyCycle          ] = cmdProbeCycle_BltDstPipeBusyCycle;
        probeMap[cmvProbeCycle_BltFillerBusyCycle           ] = cmdProbeCycle_BltFillerBusyCycle;
        probeMap[cmvProbeCycle_BltGlobalTimerStartLo        ] = cmdProbeCycle_BltGlobalTimerStartLo;
        probeMap[cmvProbeCycle_BltGlobalTimerStartHi        ] = cmdProbeCycle_BltGlobalTimerStartHi;
        probeMap[cmvProbeCycle_BltGlobalTimerEndLo          ] = cmdProbeCycle_BltGlobalTimerEndLo;
        probeMap[cmvProbeCycle_BltGlobalTimerEndHi          ] = cmdProbeCycle_BltGlobalTimerEndHi;
        probeMap[cmvProbeCycle_BltGlobalTimerLo             ] = cmdProbeCycle_BltGlobalTimerLo;
        probeMap[cmvProbeCycle_BltGlobalTimerHi             ] = cmdProbeCycle_BltGlobalTimerHi;

        probeCmodelAttributesMap[cmvProbeState_BltExecutionCmd              ] = 0;
        probeCmodelAttributesMap[cmvProbeState_BltWindowSize                ] = 0;
        probeCmodelAttributesMap[cmvProbeState_BltCopySize                  ] = 0;
        probeCmodelAttributesMap[cmvProbeState_BltFillerCount               ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Mc2BltRdDataCycle            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Blt2McWrDataCycle            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltSrcWalkerAddrCycle        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltDstWalkerAddrCycle        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltRdStall                   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltWrStall                   ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltDstAddrRtsCycle           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltDstPipeBusyCycle          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltFillerBusyCycle           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_BltGlobalTimerHi             ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvBLT_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvBLT_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvBLT_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_BLT_H__

