/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* PPA ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_PPA_H__
#define __GC_PROBE_PPA_H__

#define cmdProbeCount_PpaInputVtx                                          0x0001
#define cmdProbeCount_PpaInputPrim                                         0x0002
#define cmdProbeCount_PpaOutputPrim                                        0x0003
#define cmdProbeCount_PpaInputTri                                          0x0004
#define cmdProbeCount_PpaInputLine                                         0x0005
#define cmdProbeCount_PpaInputPoint                                        0x0006
#define cmdProbeCount_PpaTrivialRejPrim                                    0x0007
#define cmdProbeCount_PpaDropPrim                                          0x0008
#define cmdProbeCount_PpaCullPrim                                          0x0009
#define cmdProbeCount_PpaFrustumClipPrim                                   0x000A
#define cmdProbeCycle_PpaBusy                                              0x0010
#define cmdProbeCycle_ReqPpaVldAndUscRdy                                   0x0011
#define cmdProbeCycle_ReqPpaVldAndUscNotRdy                                0x0012
#define cmdProbeCycle_DataUscVldAndPpaRdy                                  0x0013
#define cmdProbeCycle_DataUscVldAndPpaNotRdy                               0x0014
#define cmdProbeCycle_PpaVldAndWdRdy                                       0x0015
#define cmdProbeCycle_PpaVldAndWdNotRdy                                    0x0016
#define cmdProbeCycle_Ppa2UscRdTotalLatency                                0x0017
#define cmdProbeCycle_PpaUscReqStallByCredit                               0x0018
#define cmdProbeCycle_PpaUscDataNotAvailable                               0x0019
#define cmdProbeCount_PpaCommonCorePLAVCycle                               0x001A
#define cmdProbeCount_PpaCommonCoreClipCycle                               0x001B
#define cmdProbeCycle_PpaGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_PpaGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_PpaGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_PpaGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_PpaGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_PpaGlobalTimerHi                                     0x00FF
#define cmd64BITProbeCount_ClipInputPrimLo                                      0x1001
#define cmd64BITProbeCount_ClipInputPrimHi                                      0x1002

enum cmePPAPROBE
{
    cmvProbeCount_PpaInputVtx,
    cmvProbeCount_PpaInputPrim,
    cmvProbeCount_PpaOutputPrim,
    cmvProbeCount_PpaInputTri,
    cmvProbeCount_PpaInputLine,
    cmvProbeCount_PpaInputPoint,
    cmvProbeCount_PpaTrivialRejPrim,
    cmvProbeCount_PpaDropPrim,
    cmvProbeCount_PpaCullPrim,
    cmvProbeCount_PpaFrustumClipPrim,
    cmvProbeCycle_PpaBusy,
    cmvProbeCycle_ReqPpaVldAndUscRdy,
    cmvProbeCycle_ReqPpaVldAndUscNotRdy,
    cmvProbeCycle_DataUscVldAndPpaRdy,
    cmvProbeCycle_DataUscVldAndPpaNotRdy,
    cmvProbeCycle_PpaVldAndWdRdy,
    cmvProbeCycle_PpaVldAndWdNotRdy,
    cmvProbeCycle_Ppa2UscRdTotalLatency,
    cmvProbeCycle_PpaUscReqStallByCredit,
    cmvProbeCycle_PpaUscDataNotAvailable,
    cmvProbeCount_PpaCommonCorePLAVCycle,
    cmvProbeCount_PpaCommonCoreClipCycle,
    cmvProbeCycle_PpaGlobalTimerStartLo,
    cmvProbeCycle_PpaGlobalTimerStartHi,
    cmvProbeCycle_PpaGlobalTimerEndLo,
    cmvProbeCycle_PpaGlobalTimerEndHi,
    cmvProbeCycle_PpaGlobalTimerLo,
    cmvProbeCycle_PpaGlobalTimerHi,
    cmv64BITProbeCount_ClipInputPrimLo,
    cmv64BITProbeCount_ClipInputPrimHi,
    cmvPPA_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoPPAProbeMap
{
public:
    cmoPPAProbeMap()
    {
        probeMap[cmvProbeCount_PpaInputVtx                  ] = cmdProbeCount_PpaInputVtx;
        probeMap[cmvProbeCount_PpaInputPrim                 ] = cmdProbeCount_PpaInputPrim;
        probeMap[cmvProbeCount_PpaOutputPrim                ] = cmdProbeCount_PpaOutputPrim;
        probeMap[cmvProbeCount_PpaInputTri                  ] = cmdProbeCount_PpaInputTri;
        probeMap[cmvProbeCount_PpaInputLine                 ] = cmdProbeCount_PpaInputLine;
        probeMap[cmvProbeCount_PpaInputPoint                ] = cmdProbeCount_PpaInputPoint;
        probeMap[cmvProbeCount_PpaTrivialRejPrim            ] = cmdProbeCount_PpaTrivialRejPrim;
        probeMap[cmvProbeCount_PpaDropPrim                  ] = cmdProbeCount_PpaDropPrim;
        probeMap[cmvProbeCount_PpaCullPrim                  ] = cmdProbeCount_PpaCullPrim;
        probeMap[cmvProbeCount_PpaFrustumClipPrim           ] = cmdProbeCount_PpaFrustumClipPrim;
        probeMap[cmvProbeCycle_PpaBusy                      ] = cmdProbeCycle_PpaBusy;
        probeMap[cmvProbeCycle_ReqPpaVldAndUscRdy           ] = cmdProbeCycle_ReqPpaVldAndUscRdy;
        probeMap[cmvProbeCycle_ReqPpaVldAndUscNotRdy        ] = cmdProbeCycle_ReqPpaVldAndUscNotRdy;
        probeMap[cmvProbeCycle_DataUscVldAndPpaRdy          ] = cmdProbeCycle_DataUscVldAndPpaRdy;
        probeMap[cmvProbeCycle_DataUscVldAndPpaNotRdy       ] = cmdProbeCycle_DataUscVldAndPpaNotRdy;
        probeMap[cmvProbeCycle_PpaVldAndWdRdy               ] = cmdProbeCycle_PpaVldAndWdRdy;
        probeMap[cmvProbeCycle_PpaVldAndWdNotRdy            ] = cmdProbeCycle_PpaVldAndWdNotRdy;
        probeMap[cmvProbeCycle_Ppa2UscRdTotalLatency        ] = cmdProbeCycle_Ppa2UscRdTotalLatency;
        probeMap[cmvProbeCycle_PpaUscReqStallByCredit       ] = cmdProbeCycle_PpaUscReqStallByCredit;
        probeMap[cmvProbeCycle_PpaUscDataNotAvailable       ] = cmdProbeCycle_PpaUscDataNotAvailable;
        probeMap[cmvProbeCount_PpaCommonCorePLAVCycle       ] = cmdProbeCount_PpaCommonCorePLAVCycle;
        probeMap[cmvProbeCount_PpaCommonCoreClipCycle       ] = cmdProbeCount_PpaCommonCoreClipCycle;
        probeMap[cmvProbeCycle_PpaGlobalTimerStartLo        ] = cmdProbeCycle_PpaGlobalTimerStartLo;
        probeMap[cmvProbeCycle_PpaGlobalTimerStartHi        ] = cmdProbeCycle_PpaGlobalTimerStartHi;
        probeMap[cmvProbeCycle_PpaGlobalTimerEndLo          ] = cmdProbeCycle_PpaGlobalTimerEndLo;
        probeMap[cmvProbeCycle_PpaGlobalTimerEndHi          ] = cmdProbeCycle_PpaGlobalTimerEndHi;
        probeMap[cmvProbeCycle_PpaGlobalTimerLo             ] = cmdProbeCycle_PpaGlobalTimerLo;
        probeMap[cmvProbeCycle_PpaGlobalTimerHi             ] = cmdProbeCycle_PpaGlobalTimerHi;
        probeMap[cmv64BITProbeCount_ClipInputPrimLo         ] = cmd64BITProbeCount_ClipInputPrimLo;
        probeMap[cmv64BITProbeCount_ClipInputPrimHi         ] = cmd64BITProbeCount_ClipInputPrimHi;

        probeCmodelAttributesMap[cmvProbeCount_PpaInputVtx                  ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PpaInputPrim                 ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaOutputPrim                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaInputTri                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaInputLine                 ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaInputPoint                ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaTrivialRejPrim            ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaDropPrim                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaCullPrim                  ] = 1;
        probeCmodelAttributesMap[cmvProbeCount_PpaFrustumClipPrim           ] = 1;
        probeCmodelAttributesMap[cmvProbeCycle_PpaBusy                      ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_ReqPpaVldAndUscRdy           ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_ReqPpaVldAndUscNotRdy        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataUscVldAndPpaRdy          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DataUscVldAndPpaNotRdy       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaVldAndWdRdy               ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaVldAndWdNotRdy            ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_Ppa2UscRdTotalLatency        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaUscReqStallByCredit       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaUscDataNotAvailable       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PpaCommonCorePLAVCycle       ] = 0;
        probeCmodelAttributesMap[cmvProbeCount_PpaCommonCoreClipCycle       ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_PpaGlobalTimerHi             ] = 0;
        probeCmodelAttributesMap[cmv64BITProbeCount_ClipInputPrimLo         ] = 1;
        probeCmodelAttributesMap[cmv64BITProbeCount_ClipInputPrimHi         ] = 1;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvPPA_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvPPA_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvPPA_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_PPA_H__

