/******************************************************************************
 |* Copyright (c) 2025, Phytium Technology Co., Ltd.  All Rights Reserved.             *|
 |*                                                                            *|
 |* The material in this file is confidential and contains trade secrets of    *|
 |* of Phytium Corporation.  This is proprietary information owned by Phytium  *|
 |* Corporation.  No part of this work may be disclosed, reproduced, copied,   *|
 |* transmitted, or used in any way for any purpose, without the express       *|
 |* written permission of Phytium Corporation.                                 *|
 |*                                                                            *|
 |* DIR ProbeCounter. Generated by $(AQARCH)/reg/Probe/Probe.mak        *|
 |*                                                                            *|
 ******************************************************************************/
#ifndef __GC_PROBE_DIR_H__
#define __GC_PROBE_DIR_H__

#define cmdProbeCycle_DirBank0OutOfPendingTags                             0x0001
#define cmdProbeCycle_DirBank1OutOfPendingTags                             0x0002
#define cmdProbeCycle_DirBank2OutOfPendingTags                             0x0003
#define cmdProbeCycle_DirBank3OutOfPendingTags                             0x0004
#define cmdProbeCycle_DirCcxCacheReqGblTxRemoteHit                         0x0005
#define cmdProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit                    0x0006
#define cmdProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit                    0x0007
#define cmdProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit                   0x0008
#define cmdProbeCycle_DirCcxCacheInputReqGblTx                             0x0009
#define cmdProbeCycle_DirCcxCacheInputReqGblNonTx                          0x000A
#define cmdProbeCycle_DirCcxCacheInputReqAttrib                            0x000B
#define cmdProbeCycle_DirBankCoherencyStall                                0x000C
#define cmdProbeCycle_DirGlobalTimerStartLo                                0x00FA
#define cmdProbeCycle_DirGlobalTimerStartHi                                0x00FB
#define cmdProbeCycle_DirGlobalTimerEndLo                                  0x00FC
#define cmdProbeCycle_DirGlobalTimerEndHi                                  0x00FD
#define cmdProbeCycle_DirGlobalTimerLo                                     0x00FE
#define cmdProbeCycle_DirGlobalTimerHi                                     0x00FF

enum cmeDIRPROBE
{
    cmvProbeCycle_DirBank0OutOfPendingTags,
    cmvProbeCycle_DirBank1OutOfPendingTags,
    cmvProbeCycle_DirBank2OutOfPendingTags,
    cmvProbeCycle_DirBank3OutOfPendingTags,
    cmvProbeCycle_DirCcxCacheReqGblTxRemoteHit,
    cmvProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit,
    cmvProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit,
    cmvProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit,
    cmvProbeCycle_DirCcxCacheInputReqGblTx,
    cmvProbeCycle_DirCcxCacheInputReqGblNonTx,
    cmvProbeCycle_DirCcxCacheInputReqAttrib,
    cmvProbeCycle_DirBankCoherencyStall,
    cmvProbeCycle_DirGlobalTimerStartLo,
    cmvProbeCycle_DirGlobalTimerStartHi,
    cmvProbeCycle_DirGlobalTimerEndLo,
    cmvProbeCycle_DirGlobalTimerEndHi,
    cmvProbeCycle_DirGlobalTimerLo,
    cmvProbeCycle_DirGlobalTimerHi,
    cmvDIR_PROBE_COUNT,
};

#ifdef __cplusplus
class cmoDIRProbeMap
{
public:
    cmoDIRProbeMap()
    {
        probeMap[cmvProbeCycle_DirBank0OutOfPendingTags     ] = cmdProbeCycle_DirBank0OutOfPendingTags;
        probeMap[cmvProbeCycle_DirBank1OutOfPendingTags     ] = cmdProbeCycle_DirBank1OutOfPendingTags;
        probeMap[cmvProbeCycle_DirBank2OutOfPendingTags     ] = cmdProbeCycle_DirBank2OutOfPendingTags;
        probeMap[cmvProbeCycle_DirBank3OutOfPendingTags     ] = cmdProbeCycle_DirBank3OutOfPendingTags;
        probeMap[cmvProbeCycle_DirCcxCacheReqGblTxRemoteHit ] = cmdProbeCycle_DirCcxCacheReqGblTxRemoteHit;
        probeMap[cmvProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit] = cmdProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit;
        probeMap[cmvProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit] = cmdProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit;
        probeMap[cmvProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit] = cmdProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit;
        probeMap[cmvProbeCycle_DirCcxCacheInputReqGblTx     ] = cmdProbeCycle_DirCcxCacheInputReqGblTx;
        probeMap[cmvProbeCycle_DirCcxCacheInputReqGblNonTx  ] = cmdProbeCycle_DirCcxCacheInputReqGblNonTx;
        probeMap[cmvProbeCycle_DirCcxCacheInputReqAttrib    ] = cmdProbeCycle_DirCcxCacheInputReqAttrib;
        probeMap[cmvProbeCycle_DirBankCoherencyStall        ] = cmdProbeCycle_DirBankCoherencyStall;
        probeMap[cmvProbeCycle_DirGlobalTimerStartLo        ] = cmdProbeCycle_DirGlobalTimerStartLo;
        probeMap[cmvProbeCycle_DirGlobalTimerStartHi        ] = cmdProbeCycle_DirGlobalTimerStartHi;
        probeMap[cmvProbeCycle_DirGlobalTimerEndLo          ] = cmdProbeCycle_DirGlobalTimerEndLo;
        probeMap[cmvProbeCycle_DirGlobalTimerEndHi          ] = cmdProbeCycle_DirGlobalTimerEndHi;
        probeMap[cmvProbeCycle_DirGlobalTimerLo             ] = cmdProbeCycle_DirGlobalTimerLo;
        probeMap[cmvProbeCycle_DirGlobalTimerHi             ] = cmdProbeCycle_DirGlobalTimerHi;

        probeCmodelAttributesMap[cmvProbeCycle_DirBank0OutOfPendingTags     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirBank1OutOfPendingTags     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirBank2OutOfPendingTags     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirBank3OutOfPendingTags     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheReqGblTxRemoteHit ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheReqGblNonTxRdRemoteHit] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheReqGblNonTxWrRemoteHit] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheReqGblNonTxRmwRemoteHit] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheInputReqGblTx     ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheInputReqGblNonTx  ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirCcxCacheInputReqAttrib    ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirBankCoherencyStall        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerStartLo        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerStartHi        ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerEndLo          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerEndHi          ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerLo             ] = 0;
        probeCmodelAttributesMap[cmvProbeCycle_DirGlobalTimerHi             ] = 0;
    };

    U16 readSel(U32 probeSel)
    {
        for(U32 i = 0; i < cmvDIR_PROBE_COUNT; i++)
        {
            if(probeMap[i] == probeSel)
                return i;
        };
        return 0xffff;
    };
public:
    U16 probeMap[cmvDIR_PROBE_COUNT];
    U16 probeCmodelAttributesMap[cmvDIR_PROBE_COUNT];
};

#endif // #ifdef __cplusplus
#endif // #ifndef __GC_PROBE_DIR_H__

