/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

#ifndef __gcregAHBMCFE_h__
#define __gcregAHBMCFE_h__

/*******************************************************************************
**                                 ~~~~~~~~~~~                                **
**                                 Module MCFE                                **
**                                 ~~~~~~~~~~~                                **
*******************************************************************************/

/* Register gcregMCFEStdDescRingBufStartAddr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE Standard Descriptor Ring Buffer Start Address Register.  Start        **
** address of the Ring Buffer containing the Standard Command Descriptors.    **
** The least 6 bits must be zeros.                                            */

#define gcregMCFEStdDescRingBufStartAddrRegAddrs                          0x0900
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_Address                  0x02400
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_MSB                           15
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_LSB                            6
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_BLK                            0
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_Count                         64
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_FieldMask             0xFFFFFFFF
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ReadMask              0xFFFFFFFF
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_WriteMask             0xFFFFFFFF
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ResetValue            0x00000000

#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ADDRESS                     31:0
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ADDRESS_End                   31
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ADDRESS_Start                  0
#define GCREG_MCFE_STD_DESC_RING_BUF_START_ADDR_ADDRESS_Type                 U32

/* Register gcregMCFEStdDescFifoDepthExp (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE Standard Descriptor Fifo Depth Exponent Register.  Sets the depth     **
** size of the Standard Command Descriptor FIFO for the indexed FE (Front     **
** End).  The FIFO depth in units of command descriptor is 2^Value.           */

#define gcregMCFEStdDescFifoDepthExpRegAddrs                              0x0940
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_Address                       0x02500
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_MSB                                15
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_LSB                                 6
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_BLK                                 0
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_Count                              64
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_FieldMask                  0x0000001F
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_ReadMask                   0x0000001F
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_WriteMask                  0x0000001F
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_ResetValue                 0x00000000

/* Exponent of the FIFO depth. DescFifoDepth = 2^DescDepthExp.  */
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_VALUE                             4:0
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_VALUE_End                           4
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_VALUE_Start                         0
#define GCREG_MCFE_STD_DESC_FIFO_DEPTH_EXP_VALUE_Type                        U05

/* Register gcregMCFEStdDescFifoWrPtr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE Standard Description Fifo Write Pointer Register.  Offset of the      **
** first invalid command desccriptor in the Standard Command Descriptor FIFO  **
** for the indeced FE.  The value is in units of command descriptor.          */

#define gcregMCFEStdDescFifoWrPtrRegAddrs                                 0x0980
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_Address                          0x02600
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_MSB                                   15
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_LSB                                    6
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_BLK                                    0
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_Count                                 64
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_FieldMask                     0x0000FFFF
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_ReadMask                      0x00000000
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_WriteMask                     0x0000FFFF
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_ResetValue                    0x00000000

/* Write pointer to the first invalid command descriptor the Standard Command **
** Descriptor List FIFO.                                                      */
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_VALUE                               15:0
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_VALUE_End                             15
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_VALUE_Start                            0
#define GCREG_MCFE_STD_DESC_FIFO_WR_PTR_VALUE_Type                           U16

/* Register gcregMCFEStdDescFifoRdPtr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE Standard Descriptor Fifo Read Pointer Register.  Offset of the next   **
** command descriptor to fetch to the FE from the Standard Command Descriptor **
** FIFO for the indexed FE.  The value is in units of command descriptor.     */

#define gcregMCFEStdDescFifoRdPtrRegAddrs                                 0x09C0
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_Address                          0x02700
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_MSB                                   15
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_LSB                                    6
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_BLK                                    0
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_Count                                 64
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_FieldMask                     0x0000FFFF
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_ReadMask                      0x0000FFFF
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_WriteMask                     0x00000000
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_ResetValue                    0x00000000

/* Read pointer to the next command descriptor in the Standard Command        **
** Descriptor List FIFO.                                                      */
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_VALUE                               15:0
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_VALUE_End                             15
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_VALUE_Start                            0
#define GCREG_MCFE_STD_DESC_FIFO_RD_PTR_VALUE_Type                           U16

/* Register gcregMCFEPriDescRingBufStartAddr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE High Priority Descriptor Ring Buffer Start Address Register.  Start   **
** address of the ring buffer containing a list of the High Priority Command  **
** Descriptors.  The least 6 bits must be zeros.                              */

#define gcregMCFEPriDescRingBufStartAddrRegAddrs                          0x0A00
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_Address                  0x02800
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_MSB                           15
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_LSB                            6
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_BLK                            0
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_Count                         64
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_FieldMask             0xFFFFFFFF
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ReadMask              0xFFFFFFFF
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_WriteMask             0xFFFFFFFF
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ResetValue            0x00000000

#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ADDRESS                     31:0
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ADDRESS_End                   31
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ADDRESS_Start                  0
#define GCREG_MCFE_PRI_DESC_RING_BUF_START_ADDR_ADDRESS_Type                 U32

/* Register gcregMCFEPriDescFifoDepthExp (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE High Priority Descriptor Fifo Depth Exponent Register. Sets the depth **
** size of the High Priority Command Descriptor FIFO for the indexed FE.  The **
** FIFO depth in units of command descriptor is 2^Value.                      */

#define gcregMCFEPriDescFifoDepthExpRegAddrs                              0x0A40
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_Address                       0x02900
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_MSB                                15
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_LSB                                 6
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_BLK                                 0
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_Count                              64
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_FieldMask                  0x0000001F
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_ReadMask                   0x0000001F
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_WriteMask                  0x0000001F
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_ResetValue                 0x00000000

/* Exponent of the FIFO depth. DescFifoDepth = 2^DescDepthExp  */
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_VALUE                             4:0
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_VALUE_End                           4
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_VALUE_Start                         0
#define GCREG_MCFE_PRI_DESC_FIFO_DEPTH_EXP_VALUE_Type                        U05

/* Register gcregMCFEPriDescFifoWrPtr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE High Priority Descriptor Fifo Write Pointer Register.  Offset of the  **
** next command descriptor to fetch to FE from the High Priority Command      **
** Descriptor FIFO for the indexed FE.  The value is in units of command      **
** descriptor.                                                                */

#define gcregMCFEPriDescFifoWrPtrRegAddrs                                 0x0A80
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_Address                          0x02A00
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_MSB                                   15
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_LSB                                    6
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_BLK                                    0
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_Count                                 64
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_FieldMask                     0x0000FFFF
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_ReadMask                      0x00000000
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_WriteMask                     0x0000FFFF
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_ResetValue                    0x00000000

/* Write pointer to the first invalide command descriptor in the High         **
** Priority Command Descriptor List FIFO.                                     */
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_VALUE                               15:0
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_VALUE_End                             15
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_VALUE_Start                            0
#define GCREG_MCFE_PRI_DESC_FIFO_WR_PTR_VALUE_Type                           U16

/* Register gcregMCFEPriDescFifoRdPtr (64 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* MCFE High Priority Descriptor Fifo Read Pointer Register. Offset of the    **
** next command descriptor to fetch to FE from the High Priority Command      **
** Descriptor FIFO for the indexed FE.  The value is in units of command      **
** descriptor.                                                                */

#define gcregMCFEPriDescFifoRdPtrRegAddrs                                 0x0AC0
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_Address                          0x02B00
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_MSB                                   15
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_LSB                                    6
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_BLK                                    0
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_Count                                 64
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_FieldMask                     0x0000FFFF
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_ReadMask                      0x0000FFFF
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_WriteMask                     0x00000000
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_ResetValue                    0x00000000

/* Read pointer to the next command descriptor in the High Priority Command   **
** Descriptor List FIFO.                                                      */
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_VALUE                               15:0
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_VALUE_End                             15
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_VALUE_Start                            0
#define GCREG_MCFE_PRI_DESC_FIFO_RD_PTR_VALUE_Type                           U16

/*******************************************************************************
**                            ~~~~~~~~~~~~~~~~~~~~                            **
**                            Command MCFE_COMMAND                            **
**                            ~~~~~~~~~~~~~~~~~~~~                            **
*******************************************************************************/

/* Offset MCFE_COMMAND
** ~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_OPCODE                                                31:27
#define MCFE_COMMAND_OPCODE_End                                               31
#define MCFE_COMMAND_OPCODE_Start                                             27
#define MCFE_COMMAND_OPCODE_Type                                             U05
#define   MCFE_COMMAND_OPCODE_LOAD_STATE                                    0x01
#define   MCFE_COMMAND_OPCODE_NOP                                           0x03
#define   MCFE_COMMAND_OPCODE_SUB_COMMAND                                   0x16

/* Offset MCFE_COMMAND
** ~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SUB_OPCODE                                            25:16
#define MCFE_COMMAND_SUB_OPCODE_End                                           25
#define MCFE_COMMAND_SUB_OPCODE_Start                                         16
#define MCFE_COMMAND_SUB_OPCODE_Type                                         U10
#define   MCFE_COMMAND_SUB_OPCODE_SUBMIT_JOB                               0x001
#define   MCFE_COMMAND_SUB_OPCODE_SEND_SEMAPHORE                           0x002
#define   MCFE_COMMAND_SUB_OPCODE_WAIT_SEMAPHORE                           0x003
#define   MCFE_COMMAND_SUB_OPCODE_LOCK                                     0x004
#define   MCFE_COMMAND_SUB_OPCODE_UNLOCK                                   0x005
#define   MCFE_COMMAND_SUB_OPCODE_INTERRUPT_EVENT                          0x006

/*******************************************************************************
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
**                       Command MCFE_COMMAND_LOADSTATE                       **
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
*******************************************************************************/

/* Offset MCFE_COMMAND_LOADSTATE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_LOADSTATE_OPCODE                                      31:27
#define MCFE_COMMAND_LOADSTATE_OPCODE_End                                     31
#define MCFE_COMMAND_LOADSTATE_OPCODE_Start                                   27
#define MCFE_COMMAND_LOADSTATE_OPCODE_Type                                   U05
#define   MCFE_COMMAND_LOADSTATE_OPCODE_LOAD_STATE                          0x01
#define   MCFE_COMMAND_LOADSTATE_OPCODE_NOP                                 0x03
#define   MCFE_COMMAND_LOADSTATE_OPCODE_SUB_COMMAND                         0x16

/* Offset MCFE_COMMAND_LOADSTATE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_LOADSTATE_COUNT                                       25:16
#define MCFE_COMMAND_LOADSTATE_COUNT_End                                      25
#define MCFE_COMMAND_LOADSTATE_COUNT_Start                                    16
#define MCFE_COMMAND_LOADSTATE_COUNT_Type                                    U10

/* Offset MCFE_COMMAND_LOADSTATE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_LOADSTATE_ADDRESS                                      15:0
#define MCFE_COMMAND_LOADSTATE_ADDRESS_End                                    15
#define MCFE_COMMAND_LOADSTATE_ADDRESS_Start                                   0
#define MCFE_COMMAND_LOADSTATE_ADDRESS_Type                                  U16

/*******************************************************************************
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
**                       Command MCFE_COMMAND_SUBMITJOB                       **
**                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                       **
*******************************************************************************/

/* Offset MCFE_COMMAND_SUBMITJOB
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SUBMITJOB_OPCODE                                      31:27
#define MCFE_COMMAND_SUBMITJOB_OPCODE_End                                     31
#define MCFE_COMMAND_SUBMITJOB_OPCODE_Start                                   27
#define MCFE_COMMAND_SUBMITJOB_OPCODE_Type                                   U05
#define   MCFE_COMMAND_SUBMITJOB_OPCODE_LOAD_STATE                          0x01
#define   MCFE_COMMAND_SUBMITJOB_OPCODE_NOP                                 0x03
#define   MCFE_COMMAND_SUBMITJOB_OPCODE_SUB_COMMAND                         0x16

/* Offset MCFE_COMMAND_SUBMITJOB
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SUBMITJOB_SUB_OPCODE                                  25:16
#define MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_End                                 25
#define MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_Start                               16
#define MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_Type                               U10
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_SUBMIT_JOB                     0x001
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_SEND_SEMAPHORE                 0x002
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_WAIT_SEMAPHORE                 0x003
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_LOCK                           0x004
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_UNLOCK                         0x005
#define   MCFE_COMMAND_SUBMITJOB_SUB_OPCODE_INTERRUPT_EVENT                0x006

/*******************************************************************************
**                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     **
**                     Command MCFE_COMMAND_SENDSEMAPHORE                     **
**                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     **
*******************************************************************************/

/* Offset MCFE_COMMAND_SENDSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SENDSEMAPHORE_OPCODE                                  31:27
#define MCFE_COMMAND_SENDSEMAPHORE_OPCODE_End                                 31
#define MCFE_COMMAND_SENDSEMAPHORE_OPCODE_Start                               27
#define MCFE_COMMAND_SENDSEMAPHORE_OPCODE_Type                               U05
#define   MCFE_COMMAND_SENDSEMAPHORE_OPCODE_LOAD_STATE                      0x01
#define   MCFE_COMMAND_SENDSEMAPHORE_OPCODE_NOP                             0x03
#define   MCFE_COMMAND_SENDSEMAPHORE_OPCODE_SUB_COMMAND                     0x16

/* Offset MCFE_COMMAND_SENDSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE                              25:16
#define MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_End                             25
#define MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_Start                           16
#define MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_Type                           U10
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_SUBMIT_JOB                 0x001
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_SEND_SEMAPHORE             0x002
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_WAIT_SEMAPHORE             0x003
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_LOCK                       0x004
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_UNLOCK                     0x005
#define   MCFE_COMMAND_SENDSEMAPHORE_SUB_OPCODE_INTERRUPT_EVENT            0x006

/* Offset MCFE_COMMAND_SENDSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_SENDSEMAPHORE_SEMAPHORE_ID                             15:0
#define MCFE_COMMAND_SENDSEMAPHORE_SEMAPHORE_ID_End                           15
#define MCFE_COMMAND_SENDSEMAPHORE_SEMAPHORE_ID_Start                          0
#define MCFE_COMMAND_SENDSEMAPHORE_SEMAPHORE_ID_Type                         U16

/*******************************************************************************
**                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     **
**                     Command MCFE_COMMAND_WAITSEMAPHORE                     **
**                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                     **
*******************************************************************************/

/* Offset MCFE_COMMAND_WAITSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_WAITSEMAPHORE_OPCODE                                  31:27
#define MCFE_COMMAND_WAITSEMAPHORE_OPCODE_End                                 31
#define MCFE_COMMAND_WAITSEMAPHORE_OPCODE_Start                               27
#define MCFE_COMMAND_WAITSEMAPHORE_OPCODE_Type                               U05
#define   MCFE_COMMAND_WAITSEMAPHORE_OPCODE_LOAD_STATE                      0x01
#define   MCFE_COMMAND_WAITSEMAPHORE_OPCODE_NOP                             0x03
#define   MCFE_COMMAND_WAITSEMAPHORE_OPCODE_SUB_COMMAND                     0x16

/* Offset MCFE_COMMAND_WAITSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE                              25:16
#define MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_End                             25
#define MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_Start                           16
#define MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_Type                           U10
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_SUBMIT_JOB                 0x001
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_SEND_SEMAPHORE             0x002
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_WAIT_SEMAPHORE             0x003
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_LOCK                       0x004
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_UNLOCK                     0x005
#define   MCFE_COMMAND_WAITSEMAPHORE_SUB_OPCODE_INTERRUPT_EVENT            0x006

/* Offset MCFE_COMMAND_WAITSEMAPHORE
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_WAITSEMAPHORE_SEMAPHORE_ID                             15:0
#define MCFE_COMMAND_WAITSEMAPHORE_SEMAPHORE_ID_End                           15
#define MCFE_COMMAND_WAITSEMAPHORE_SEMAPHORE_ID_Start                          0
#define MCFE_COMMAND_WAITSEMAPHORE_SEMAPHORE_ID_Type                         U16

/*******************************************************************************
**                          ~~~~~~~~~~~~~~~~~~~~~~~~~                         **
**                          Command MCFE_COMMAND_LOCK                         **
**                          ~~~~~~~~~~~~~~~~~~~~~~~~~                         **
*******************************************************************************/

/* Offset MCFE_COMMAND_LOCK
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_LOCK_OPCODE                                           31:27
#define MCFE_COMMAND_LOCK_OPCODE_End                                          31
#define MCFE_COMMAND_LOCK_OPCODE_Start                                        27
#define MCFE_COMMAND_LOCK_OPCODE_Type                                        U05
#define   MCFE_COMMAND_LOCK_OPCODE_LOAD_STATE                               0x01
#define   MCFE_COMMAND_LOCK_OPCODE_NOP                                      0x03
#define   MCFE_COMMAND_LOCK_OPCODE_SUB_COMMAND                              0x16

/* Offset MCFE_COMMAND_LOCK
** ~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_LOCK_SUB_OPCODE                                       25:16
#define MCFE_COMMAND_LOCK_SUB_OPCODE_End                                      25
#define MCFE_COMMAND_LOCK_SUB_OPCODE_Start                                    16
#define MCFE_COMMAND_LOCK_SUB_OPCODE_Type                                    U10
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_SUBMIT_JOB                          0x001
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_SEND_SEMAPHORE                      0x002
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_WAIT_SEMAPHORE                      0x003
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_LOCK                                0x004
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_UNLOCK                              0x005
#define   MCFE_COMMAND_LOCK_SUB_OPCODE_INTERRUPT_EVENT                     0x006

/*******************************************************************************
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~                        **
**                         Command MCFE_COMMAND_UNLOCK                        **
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~                        **
*******************************************************************************/

/* Offset MCFE_COMMAND_UNLOCK
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_UNLOCK_OPCODE                                         31:27
#define MCFE_COMMAND_UNLOCK_OPCODE_End                                        31
#define MCFE_COMMAND_UNLOCK_OPCODE_Start                                      27
#define MCFE_COMMAND_UNLOCK_OPCODE_Type                                      U05
#define   MCFE_COMMAND_UNLOCK_OPCODE_LOAD_STATE                             0x01
#define   MCFE_COMMAND_UNLOCK_OPCODE_NOP                                    0x03
#define   MCFE_COMMAND_UNLOCK_OPCODE_SUB_COMMAND                            0x16

/* Offset MCFE_COMMAND_UNLOCK
** ~~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_UNLOCK_SUB_OPCODE                                     25:16
#define MCFE_COMMAND_UNLOCK_SUB_OPCODE_End                                    25
#define MCFE_COMMAND_UNLOCK_SUB_OPCODE_Start                                  16
#define MCFE_COMMAND_UNLOCK_SUB_OPCODE_Type                                  U10
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_SUBMIT_JOB                        0x001
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_SEND_SEMAPHORE                    0x002
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_WAIT_SEMAPHORE                    0x003
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_LOCK                              0x004
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_UNLOCK                            0x005
#define   MCFE_COMMAND_UNLOCK_SUB_OPCODE_INTERRUPT_EVENT                   0x006

/*******************************************************************************
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~                         **
**                         Command MCFE_COMMAND_EVENT                         **
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~                         **
*******************************************************************************/

/* Offset MCFE_COMMAND_EVENT
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_EVENT_OPCODE                                          31:27
#define MCFE_COMMAND_EVENT_OPCODE_End                                         31
#define MCFE_COMMAND_EVENT_OPCODE_Start                                       27
#define MCFE_COMMAND_EVENT_OPCODE_Type                                       U05
#define   MCFE_COMMAND_EVENT_OPCODE_LOAD_STATE                              0x01
#define   MCFE_COMMAND_EVENT_OPCODE_NOP                                     0x03
#define   MCFE_COMMAND_EVENT_OPCODE_SUB_COMMAND                             0x16

/* Offset MCFE_COMMAND_EVENT
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_EVENT_SUB_OPCODE                                      25:16
#define MCFE_COMMAND_EVENT_SUB_OPCODE_End                                     25
#define MCFE_COMMAND_EVENT_SUB_OPCODE_Start                                   16
#define MCFE_COMMAND_EVENT_SUB_OPCODE_Type                                   U10
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_SUBMIT_JOB                         0x001
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_SEND_SEMAPHORE                     0x002
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_WAIT_SEMAPHORE                     0x003
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_LOCK                               0x004
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_UNLOCK                             0x005
#define   MCFE_COMMAND_EVENT_SUB_OPCODE_INTERRUPT_EVENT                    0x006

/* Offset MCFE_COMMAND_EVENT
** ~~~~~~~~~~~~~~~~~~~~~~~~~ */

#define MCFE_COMMAND_EVENT_EVENT_ID                                          5:0
#define MCFE_COMMAND_EVENT_EVENT_ID_End                                        5
#define MCFE_COMMAND_EVENT_EVENT_ID_Start                                      0
#define MCFE_COMMAND_EVENT_EVENT_ID_Type                                     U06


#endif /* __gcregAHBMCFE_h__ */
