/*******************************************************************************
**                                                                            **
** Copyright (c) 2004-2016 by Phytium Corp.  All rights reserved.             **
**                                                                            **
** The material in this file is confidential and contains trade secrets of    **
** Phytium Corporation.  This is proprietary information owned by Phytium     **
** Corporation.  No part of this work may be disclosed, reproduced, copied,   **
** transmitted, or used in any way for any purpose, without the express       **
** written permission of Phytium Corporation.                                 **
**                                                                            **
********************************************************************************
**                                                                            **
** This file is automatically generated on Sat Jan 25 15:39:58 2025           **
**                                                                            **
** Any changes made to this file are lost at the next compile run!            **
** So better make sure you update the source .r files instead!                **
**                                                                            **
*******************************************************************************/

#ifndef __gcregFuSa_h__
#define __gcregFuSa_h__

/*******************************************************************************
**                            ~~~~~~~~~~~~~~~~~~~~~                           **
**                            Module FunctionSafety                           **
**                            ~~~~~~~~~~~~~~~~~~~~~                           **
*******************************************************************************/

/* Register gcregFusaIntrEnable **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Function safety interrupt enable signal, one bit controls one interrupt */

#define gcregFusaIntrEnableRegAddrs                                       0x0085
#define GCREG_FUSA_INTR_ENABLE_Address                                   0x00214
#define GCREG_FUSA_INTR_ENABLE_MSB                                            15
#define GCREG_FUSA_INTR_ENABLE_LSB                                             0
#define GCREG_FUSA_INTR_ENABLE_BLK                                             0
#define GCREG_FUSA_INTR_ENABLE_Count                                           1
#define GCREG_FUSA_INTR_ENABLE_FieldMask                              0xFFFFFFFF
#define GCREG_FUSA_INTR_ENABLE_ReadMask                               0xFFFFFFFF
#define GCREG_FUSA_INTR_ENABLE_WriteMask                              0xFFFFFFFF
#define GCREG_FUSA_INTR_ENABLE_ResetValue                             0x00000000

/* Value. */
#define GCREG_FUSA_INTR_ENABLE_VALUE                                        31:0
#define GCREG_FUSA_INTR_ENABLE_VALUE_End                                      31
#define GCREG_FUSA_INTR_ENABLE_VALUE_Start                                     0
#define GCREG_FUSA_INTR_ENABLE_VALUE_Type                                    U32

/* Register gcregFusaIntrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Function safety interrupt information */

#define gcregFusaIntrStatusRegAddrs                                       0x0086
#define GCREG_FUSA_INTR_STATUS_Address                                   0x00218
#define GCREG_FUSA_INTR_STATUS_MSB                                            15
#define GCREG_FUSA_INTR_STATUS_LSB                                             0
#define GCREG_FUSA_INTR_STATUS_BLK                                             0
#define GCREG_FUSA_INTR_STATUS_Count                                           1
#define GCREG_FUSA_INTR_STATUS_FieldMask                              0x000003FF
#define GCREG_FUSA_INTR_STATUS_ReadMask                               0x000003FF
#define GCREG_FUSA_INTR_STATUS_WriteMask                              0x00000000
#define GCREG_FUSA_INTR_STATUS_ResetValue                             0x00000000

/* AHB parity error . */
#define GCREG_FUSA_INTR_STATUS_AHB_PARITY                                    0:0
#define GCREG_FUSA_INTR_STATUS_AHB_PARITY_End                                  0
#define GCREG_FUSA_INTR_STATUS_AHB_PARITY_Start                                0
#define GCREG_FUSA_INTR_STATUS_AHB_PARITY_Type                               U01

/* AHB timeout error . */
#define GCREG_FUSA_INTR_STATUS_AHB_TIMEOUT                                   1:1
#define GCREG_FUSA_INTR_STATUS_AHB_TIMEOUT_End                                 1
#define GCREG_FUSA_INTR_STATUS_AHB_TIMEOUT_Start                               1
#define GCREG_FUSA_INTR_STATUS_AHB_TIMEOUT_Type                              U01

/* AXI parity error . */
#define GCREG_FUSA_INTR_STATUS_AXI_PARITY                                    2:2
#define GCREG_FUSA_INTR_STATUS_AXI_PARITY_End                                  2
#define GCREG_FUSA_INTR_STATUS_AXI_PARITY_Start                                2
#define GCREG_FUSA_INTR_STATUS_AXI_PARITY_Type                               U01

/* AXI timeout error . */
#define GCREG_FUSA_INTR_STATUS_AXI_TIMEOUT                                   3:3
#define GCREG_FUSA_INTR_STATUS_AXI_TIMEOUT_End                                 3
#define GCREG_FUSA_INTR_STATUS_AXI_TIMEOUT_Start                               3
#define GCREG_FUSA_INTR_STATUS_AXI_TIMEOUT_Type                              U01

/* One bit ECC error . */
#define GCREG_FUSA_INTR_STATUS_ECC_ONE_BIT                                   4:4
#define GCREG_FUSA_INTR_STATUS_ECC_ONE_BIT_End                                 4
#define GCREG_FUSA_INTR_STATUS_ECC_ONE_BIT_Start                               4
#define GCREG_FUSA_INTR_STATUS_ECC_ONE_BIT_Type                              U01

/* Two bit ECC error . */
#define GCREG_FUSA_INTR_STATUS_ECC_TWO_BIT                                   5:5
#define GCREG_FUSA_INTR_STATUS_ECC_TWO_BIT_End                                 5
#define GCREG_FUSA_INTR_STATUS_ECC_TWO_BIT_Start                               5
#define GCREG_FUSA_INTR_STATUS_ECC_TWO_BIT_Type                              U01

/* FIFO/pipeline parity error . */
#define GCREG_FUSA_INTR_STATUS_PIPELINE_PARITY                               6:6
#define GCREG_FUSA_INTR_STATUS_PIPELINE_PARITY_End                             6
#define GCREG_FUSA_INTR_STATUS_PIPELINE_PARITY_Start                           6
#define GCREG_FUSA_INTR_STATUS_PIPELINE_PARITY_Type                          U01

/* Duplication error . */
#define GCREG_FUSA_INTR_STATUS_DUPLICATION                                   7:7
#define GCREG_FUSA_INTR_STATUS_DUPLICATION_End                                 7
#define GCREG_FUSA_INTR_STATUS_DUPLICATION_Start                               7
#define GCREG_FUSA_INTR_STATUS_DUPLICATION_Type                              U01

/* STL error . */
#define GCREG_FUSA_INTR_STATUS_STL                                           8:8
#define GCREG_FUSA_INTR_STATUS_STL_End                                         8
#define GCREG_FUSA_INTR_STATUS_STL_Start                                       8
#define GCREG_FUSA_INTR_STATUS_STL_Type                                      U01

/* Watch dog timeout error . */
#define GCREG_FUSA_INTR_STATUS_WATCH_DOG_TIMEOUT                             9:9
#define GCREG_FUSA_INTR_STATUS_WATCH_DOG_TIMEOUT_End                           9
#define GCREG_FUSA_INTR_STATUS_WATCH_DOG_TIMEOUT_Start                         9
#define GCREG_FUSA_INTR_STATUS_WATCH_DOG_TIMEOUT_Type                        U01

/* Register gcregFusaAHBTimeoutConfig **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* AHB Read timeout counter */

#define gcregFusaAHBTimeoutConfigRegAddrs                                 0x0087
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_Address                            0x0021C
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_MSB                                     15
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_LSB                                      0
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_BLK                                      0
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_Count                                    1
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_FieldMask                       0xFFFFFFFF
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_ReadMask                        0xFFFFFFFF
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_WriteMask                       0xFFFFFFFF
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_ResetValue                      0x00000000

/* Counter. */
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_COUNTER                               31:0
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_COUNTER_End                             31
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_COUNTER_Start                            0
#define GCREG_FUSA_AHB_TIMEOUT_CONFIG_COUNTER_Type                           U32

/* Register gcregFusaAXIParityErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* AXI parity errors.  */

#define gcregFusaAXIParityErrStatusRegAddrs                               0x0088
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_Address                         0x00220
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_MSB                                  15
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_LSB                                   0
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_BLK                                   0
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_Count                                 1
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_FieldMask                    0x000000FF
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_ReadMask                     0x000000FF
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_WriteMask                    0x00000000
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_ResetValue                   0x00000000

/* AXI0 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI0                                0:0
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI0_End                              0
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI0_Start                            0
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI0_Type                           U01

/* AXI1 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI1                                1:1
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI1_End                              1
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI1_Start                            1
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI1_Type                           U01

/* AXI2 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI2                                2:2
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI2_End                              2
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI2_Start                            2
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI2_Type                           U01

/* AXI3 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI3                                3:3
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI3_End                              3
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI3_Start                            3
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI3_Type                           U01

/* AXI4 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI4                                4:4
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI4_End                              4
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI4_Start                            4
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI4_Type                           U01

/* AXI5 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI5                                5:5
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI5_End                              5
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI5_Start                            5
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI5_Type                           U01

/* AXI6 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI6                                6:6
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI6_End                              6
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI6_Start                            6
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI6_Type                           U01

/* AXI7 Parity error.  */
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI7                                7:7
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI7_End                              7
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI7_Start                            7
#define GCREG_FUSA_AXI_PARITY_ERR_STATUS_AXI7_Type                           U01

/* Register gcregFusaAXITimeoutErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* AXI read/write timeout errors. */

#define gcregFusaAXITimeoutErrStatusRegAddrs                              0x0089
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_Address                        0x00224
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_MSB                                 15
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_LSB                                  0
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_BLK                                  0
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_Count                                1
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_FieldMask                   0x00FF00FF
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_ReadMask                    0x00FF00FF
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_WriteMask                   0x00000000
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_ResetValue                  0x00000000

/* AXI0 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_READ_TIMEOUT                  0:0
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_READ_TIMEOUT_End                0
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_READ_TIMEOUT_Start              0
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_READ_TIMEOUT_Type             U01

/* AXI1 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_READ_TIMEOUT                  1:1
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_READ_TIMEOUT_End                1
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_READ_TIMEOUT_Start              1
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_READ_TIMEOUT_Type             U01

/* AXI2 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_READ_TIMEOUT                  2:2
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_READ_TIMEOUT_End                2
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_READ_TIMEOUT_Start              2
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_READ_TIMEOUT_Type             U01

/* AXI3 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_READ_TIMEOUT                  3:3
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_READ_TIMEOUT_End                3
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_READ_TIMEOUT_Start              3
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_READ_TIMEOUT_Type             U01

/* AXI4 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_READ_TIMEOUT                  4:4
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_READ_TIMEOUT_End                4
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_READ_TIMEOUT_Start              4
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_READ_TIMEOUT_Type             U01

/* AXI5 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_READ_TIMEOUT                  5:5
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_READ_TIMEOUT_End                5
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_READ_TIMEOUT_Start              5
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_READ_TIMEOUT_Type             U01

/* AXI6 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_READ_TIMEOUT                  6:6
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_READ_TIMEOUT_End                6
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_READ_TIMEOUT_Start              6
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_READ_TIMEOUT_Type             U01

/* AXI7 Read Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_READ_TIMEOUT                  7:7
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_READ_TIMEOUT_End                7
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_READ_TIMEOUT_Start              7
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_READ_TIMEOUT_Type             U01

/* AXI0 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_WRITE_TIMEOUT               16:16
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_WRITE_TIMEOUT_End              16
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_WRITE_TIMEOUT_Start            16
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI0_WRITE_TIMEOUT_Type            U01

/* AXI1 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_WRITE_TIMEOUT               17:17
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_WRITE_TIMEOUT_End              17
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_WRITE_TIMEOUT_Start            17
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI1_WRITE_TIMEOUT_Type            U01

/* AXI2 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_WRITE_TIMEOUT               18:18
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_WRITE_TIMEOUT_End              18
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_WRITE_TIMEOUT_Start            18
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI2_WRITE_TIMEOUT_Type            U01

/* AXI3 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_WRITE_TIMEOUT               19:19
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_WRITE_TIMEOUT_End              19
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_WRITE_TIMEOUT_Start            19
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI3_WRITE_TIMEOUT_Type            U01

/* AXI4 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_WRITE_TIMEOUT               20:20
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_WRITE_TIMEOUT_End              20
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_WRITE_TIMEOUT_Start            20
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI4_WRITE_TIMEOUT_Type            U01

/* AXI5 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_WRITE_TIMEOUT               21:21
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_WRITE_TIMEOUT_End              21
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_WRITE_TIMEOUT_Start            21
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI5_WRITE_TIMEOUT_Type            U01

/* AXI6 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_WRITE_TIMEOUT               22:22
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_WRITE_TIMEOUT_End              22
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_WRITE_TIMEOUT_Start            22
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI6_WRITE_TIMEOUT_Type            U01

/* AXI7 Write Timeout error. */
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_WRITE_TIMEOUT               23:23
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_WRITE_TIMEOUT_End              23
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_WRITE_TIMEOUT_Start            23
#define GCREG_FUSA_AXI_TIMEOUT_ERR_STATUS_AXI7_WRITE_TIMEOUT_Type            U01

/* Register gcregFusaECCE1ErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* ECC 1 bit error status.. */

#define gcregFusaECCE1ErrStatusRegAddrs                                   0x008A
#define GCREG_FUSA_ECCE1_ERR_STATUS_Address                              0x00228
#define GCREG_FUSA_ECCE1_ERR_STATUS_MSB                                       15
#define GCREG_FUSA_ECCE1_ERR_STATUS_LSB                                        0
#define GCREG_FUSA_ECCE1_ERR_STATUS_BLK                                        0
#define GCREG_FUSA_ECCE1_ERR_STATUS_Count                                      1
#define GCREG_FUSA_ECCE1_ERR_STATUS_FieldMask                         0x00001FFF
#define GCREG_FUSA_ECCE1_ERR_STATUS_ReadMask                          0x00001FFF
#define GCREG_FUSA_ECCE1_ERR_STATUS_WriteMask                         0x00000000
#define GCREG_FUSA_ECCE1_ERR_STATUS_ResetValue                        0x00000000

/* FE ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_FE                                       0:0
#define GCREG_FUSA_ECCE1_ERR_STATUS_FE_End                                     0
#define GCREG_FUSA_ECCE1_ERR_STATUS_FE_Start                                   0
#define GCREG_FUSA_ECCE1_ERR_STATUS_FE_Type                                  U01

/* WD ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_WD                                       1:1
#define GCREG_FUSA_ECCE1_ERR_STATUS_WD_End                                     1
#define GCREG_FUSA_ECCE1_ERR_STATUS_WD_Start                                   1
#define GCREG_FUSA_ECCE1_ERR_STATUS_WD_Type                                  U01

/* DIR ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_DIR                                      2:2
#define GCREG_FUSA_ECCE1_ERR_STATUS_DIR_End                                    2
#define GCREG_FUSA_ECCE1_ERR_STATUS_DIR_Start                                  2
#define GCREG_FUSA_ECCE1_ERR_STATUS_DIR_Type                                 U01

/* HI ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_HI                                       3:3
#define GCREG_FUSA_ECCE1_ERR_STATUS_HI_End                                     3
#define GCREG_FUSA_ECCE1_ERR_STATUS_HI_Start                                   3
#define GCREG_FUSA_ECCE1_ERR_STATUS_HI_Type                                  U01

/* Cluster0 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER0                                 4:4
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER0_End                               4
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER0_Start                             4
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER0_Type                            U01

/* Cluster1 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER1                                 5:5
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER1_End                               5
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER1_Start                             5
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER1_Type                            U01

/* Cluster2 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER2                                 6:6
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER2_End                               6
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER2_Start                             6
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER2_Type                            U01

/* Cluster3 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER3                                 7:7
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER3_End                               7
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER3_Start                             7
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER3_Type                            U01

/* Cluster4 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER4                                 8:8
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER4_End                               8
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER4_Start                             8
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER4_Type                            U01

/* Cluster5 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER5                                 9:9
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER5_End                               9
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER5_Start                             9
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER5_Type                            U01

/* Cluster6 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER6                               10:10
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER6_End                              10
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER6_Start                            10
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER6_Type                            U01

/* Cluster7 ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER7                               11:11
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER7_End                              11
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER7_Start                            11
#define GCREG_FUSA_ECCE1_ERR_STATUS_CLUSTER7_Type                            U01

/* Top rest ECC E1 error. */
#define GCREG_FUSA_ECCE1_ERR_STATUS_TOP_REST                               12:12
#define GCREG_FUSA_ECCE1_ERR_STATUS_TOP_REST_End                              12
#define GCREG_FUSA_ECCE1_ERR_STATUS_TOP_REST_Start                            12
#define GCREG_FUSA_ECCE1_ERR_STATUS_TOP_REST_Type                            U01

/* Register gcregFusaECCE2ErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* ECC 2 bit error status.. */

#define gcregFusaECCE2ErrStatusRegAddrs                                   0x008B
#define GCREG_FUSA_ECCE2_ERR_STATUS_Address                              0x0022C
#define GCREG_FUSA_ECCE2_ERR_STATUS_MSB                                       15
#define GCREG_FUSA_ECCE2_ERR_STATUS_LSB                                        0
#define GCREG_FUSA_ECCE2_ERR_STATUS_BLK                                        0
#define GCREG_FUSA_ECCE2_ERR_STATUS_Count                                      1
#define GCREG_FUSA_ECCE2_ERR_STATUS_FieldMask                         0x00001FFF
#define GCREG_FUSA_ECCE2_ERR_STATUS_ReadMask                          0x00001FFF
#define GCREG_FUSA_ECCE2_ERR_STATUS_WriteMask                         0x00000000
#define GCREG_FUSA_ECCE2_ERR_STATUS_ResetValue                        0x00000000

/* FE ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_FE                                       0:0
#define GCREG_FUSA_ECCE2_ERR_STATUS_FE_End                                     0
#define GCREG_FUSA_ECCE2_ERR_STATUS_FE_Start                                   0
#define GCREG_FUSA_ECCE2_ERR_STATUS_FE_Type                                  U01

/* WD ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_WD                                       1:1
#define GCREG_FUSA_ECCE2_ERR_STATUS_WD_End                                     1
#define GCREG_FUSA_ECCE2_ERR_STATUS_WD_Start                                   1
#define GCREG_FUSA_ECCE2_ERR_STATUS_WD_Type                                  U01

/* DIR ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_DIR                                      2:2
#define GCREG_FUSA_ECCE2_ERR_STATUS_DIR_End                                    2
#define GCREG_FUSA_ECCE2_ERR_STATUS_DIR_Start                                  2
#define GCREG_FUSA_ECCE2_ERR_STATUS_DIR_Type                                 U01

/* HI ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_HI                                       3:3
#define GCREG_FUSA_ECCE2_ERR_STATUS_HI_End                                     3
#define GCREG_FUSA_ECCE2_ERR_STATUS_HI_Start                                   3
#define GCREG_FUSA_ECCE2_ERR_STATUS_HI_Type                                  U01

/* Cluster0 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER0                                 4:4
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER0_End                               4
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER0_Start                             4
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER0_Type                            U01

/* Cluster1 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER1                                 5:5
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER1_End                               5
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER1_Start                             5
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER1_Type                            U01

/* Cluster2 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER2                                 6:6
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER2_End                               6
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER2_Start                             6
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER2_Type                            U01

/* Cluster3 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER3                                 7:7
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER3_End                               7
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER3_Start                             7
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER3_Type                            U01

/* Cluster4 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER4                                 8:8
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER4_End                               8
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER4_Start                             8
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER4_Type                            U01

/* Cluster5 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER5                                 9:9
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER5_End                               9
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER5_Start                             9
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER5_Type                            U01

/* Cluster6 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER6                               10:10
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER6_End                              10
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER6_Start                            10
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER6_Type                            U01

/* Cluster7 ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER7                               11:11
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER7_End                              11
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER7_Start                            11
#define GCREG_FUSA_ECCE2_ERR_STATUS_CLUSTER7_Type                            U01

/* Top rest ECC E2 error. */
#define GCREG_FUSA_ECCE2_ERR_STATUS_TOP_REST                               12:12
#define GCREG_FUSA_ECCE2_ERR_STATUS_TOP_REST_End                              12
#define GCREG_FUSA_ECCE2_ERR_STATUS_TOP_REST_Start                            12
#define GCREG_FUSA_ECCE2_ERR_STATUS_TOP_REST_Type                            U01

/* Register gcregFusaPipeParityErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Exclude cluster module parity error status.. */

#define gcregFusaPipeParityErrStatusRegAddrs                              0x008C
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_Address                        0x00230
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_MSB                                 15
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_LSB                                  0
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_BLK                                  0
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_Count                                1
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_FieldMask                   0x00001FFF
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_ReadMask                    0x00001FFF
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_WriteMask                   0x00000000
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_ResetValue                  0x00000000

/* FE parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_FE                                 0:0
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_FE_End                               0
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_FE_Start                             0
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_FE_Type                            U01

/* WD parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_WD                                 1:1
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_WD_End                               1
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_WD_Start                             1
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_WD_Type                            U01

/* HI parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_HI                                 2:2
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_HI_End                               2
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_HI_Start                             2
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_HI_Type                            U01

/* DIR parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_DIR                                3:3
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_DIR_End                              3
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_DIR_Start                            3
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_DIR_Type                           U01

/* Cluster0 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER0                           4:4
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER0_End                         4
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER0_Start                       4
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER0_Type                      U01

/* Cluster1 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER1                           5:5
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER1_End                         5
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER1_Start                       5
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER1_Type                      U01

/* Cluster2 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER2                           6:6
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER2_End                         6
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER2_Start                       6
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER2_Type                      U01

/* Cluster3 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER3                           7:7
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER3_End                         7
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER3_Start                       7
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER3_Type                      U01

/* Cluster4 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER4                           8:8
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER4_End                         8
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER4_Start                       8
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER4_Type                      U01

/* Cluster5 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER5                           9:9
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER5_End                         9
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER5_Start                       9
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER5_Type                      U01

/* Cluster6 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER6                         10:10
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER6_End                        10
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER6_Start                      10
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER6_Type                      U01

/* Cluster7 parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER7                         11:11
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER7_End                        11
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER7_Start                      11
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_CLUSTER7_Type                      U01

/* Top rest parity error. */
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_TOP_REST                         12:12
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_TOP_REST_End                        12
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_TOP_REST_Start                      12
#define GCREG_FUSA_PIPE_PARITY_ERR_STATUS_TOP_REST_Type                      U01

/* Register gcregFusaDupErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Duplication error status. */

#define gcregFusaDupErrStatusRegAddrs                                     0x008D
#define GCREG_FUSA_DUP_ERR_STATUS_Address                                0x00234
#define GCREG_FUSA_DUP_ERR_STATUS_MSB                                         15
#define GCREG_FUSA_DUP_ERR_STATUS_LSB                                          0
#define GCREG_FUSA_DUP_ERR_STATUS_BLK                                          0
#define GCREG_FUSA_DUP_ERR_STATUS_Count                                        1
#define GCREG_FUSA_DUP_ERR_STATUS_FieldMask                           0x00001FFF
#define GCREG_FUSA_DUP_ERR_STATUS_ReadMask                            0x00001FFF
#define GCREG_FUSA_DUP_ERR_STATUS_WriteMask                           0x00000000
#define GCREG_FUSA_DUP_ERR_STATUS_ResetValue                          0x00000000

/* FE duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_FE                                         0:0
#define GCREG_FUSA_DUP_ERR_STATUS_FE_End                                       0
#define GCREG_FUSA_DUP_ERR_STATUS_FE_Start                                     0
#define GCREG_FUSA_DUP_ERR_STATUS_FE_Type                                    U01

/* WD duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_WD                                         1:1
#define GCREG_FUSA_DUP_ERR_STATUS_WD_End                                       1
#define GCREG_FUSA_DUP_ERR_STATUS_WD_Start                                     1
#define GCREG_FUSA_DUP_ERR_STATUS_WD_Type                                    U01

/* DIR duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_DIR                                        2:2
#define GCREG_FUSA_DUP_ERR_STATUS_DIR_End                                      2
#define GCREG_FUSA_DUP_ERR_STATUS_DIR_Start                                    2
#define GCREG_FUSA_DUP_ERR_STATUS_DIR_Type                                   U01

/* HI duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_HI                                         3:3
#define GCREG_FUSA_DUP_ERR_STATUS_HI_End                                       3
#define GCREG_FUSA_DUP_ERR_STATUS_HI_Start                                     3
#define GCREG_FUSA_DUP_ERR_STATUS_HI_Type                                    U01

/* Cluster0 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER0                                   4:4
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER0_End                                 4
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER0_Start                               4
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER0_Type                              U01

/* Cluster1 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER1                                   5:5
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER1_End                                 5
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER1_Start                               5
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER1_Type                              U01

/* Cluster2 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER2                                   6:6
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER2_End                                 6
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER2_Start                               6
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER2_Type                              U01

/* Cluster3 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER3                                   7:7
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER3_End                                 7
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER3_Start                               7
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER3_Type                              U01

/* Cluster4 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER4                                   8:8
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER4_End                                 8
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER4_Start                               8
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER4_Type                              U01

/* Cluster5 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER5                                   9:9
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER5_End                                 9
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER5_Start                               9
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER5_Type                              U01

/* Cluster6 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER6                                 10:10
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER6_End                                10
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER6_Start                              10
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER6_Type                              U01

/* Cluster7 duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER7                                 11:11
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER7_End                                11
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER7_Start                              11
#define GCREG_FUSA_DUP_ERR_STATUS_CLUSTER7_Type                              U01

/* Top rest duplication error. */
#define GCREG_FUSA_DUP_ERR_STATUS_TOP_REST                                 12:12
#define GCREG_FUSA_DUP_ERR_STATUS_TOP_REST_End                                12
#define GCREG_FUSA_DUP_ERR_STATUS_TOP_REST_Start                              12
#define GCREG_FUSA_DUP_ERR_STATUS_TOP_REST_Type                              U01

/* Register gcregFusaSTLErrStatus **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Cluster STL error status. */

#define gcregFusaSTLErrStatusRegAddrs                                     0x008E
#define GCREG_FUSA_STL_ERR_STATUS_Address                                0x00238
#define GCREG_FUSA_STL_ERR_STATUS_MSB                                         15
#define GCREG_FUSA_STL_ERR_STATUS_LSB                                          0
#define GCREG_FUSA_STL_ERR_STATUS_BLK                                          0
#define GCREG_FUSA_STL_ERR_STATUS_Count                                        1
#define GCREG_FUSA_STL_ERR_STATUS_FieldMask                           0x000000FF
#define GCREG_FUSA_STL_ERR_STATUS_ReadMask                            0x000000FF
#define GCREG_FUSA_STL_ERR_STATUS_WriteMask                           0x00000000
#define GCREG_FUSA_STL_ERR_STATUS_ResetValue                          0x00000000

/* Cluster0 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER0                                   0:0
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER0_End                                 0
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER0_Start                               0
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER0_Type                              U01

/* Cluster1 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER1                                   1:1
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER1_End                                 1
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER1_Start                               1
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER1_Type                              U01

/* Cluster2 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER2                                   2:2
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER2_End                                 2
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER2_Start                               2
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER2_Type                              U01

/* Cluster3 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER3                                   3:3
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER3_End                                 3
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER3_Start                               3
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER3_Type                              U01

/* Cluster4 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER4                                   4:4
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER4_End                                 4
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER4_Start                               4
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER4_Type                              U01

/* Cluster5 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER5                                   5:5
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER5_End                                 5
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER5_Start                               5
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER5_Type                              U01

/* Cluster6 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER6                                   6:6
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER6_End                                 6
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER6_Start                               6
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER6_Type                              U01

/* Cluster7 STL error. */
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER7                                   7:7
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER7_End                                 7
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER7_Start                               7
#define GCREG_FUSA_STL_ERR_STATUS_CLUSTER7_Type                              U01

/* Register gcregFusaWatchDogTimeoutConfig **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Watch dog timeout counter. */

#define gcregFusaWatchDogTimeoutConfigRegAddrs                            0x008F
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_Address                      0x0023C
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_MSB                               15
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_LSB                                0
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_BLK                                0
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_Count                              1
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_FieldMask                 0xFFFFFFFF
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_ReadMask                  0xFFFFFFFF
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_WriteMask                 0xFFFFFFFF
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_ResetValue                0x00000000

/* Counter number. */
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_COUNTER                         31:0
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_COUNTER_End                       31
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_COUNTER_Start                      0
#define GCREG_FUSA_WATCH_DOG_TIMEOUT_CONFIG_COUNTER_Type                     U32

/* Register gcregFusaAXIReadTimeoutConfig (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* AXI read timeout counter. */

#define gcregFusaAXIReadTimeoutConfigRegAddrs                             0x0090
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_Address                       0x00240
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_MSB                                15
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_LSB                                 3
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_BLK                                 3
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_Count                               8
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_FieldMask                  0xFFFFFFFF
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_ReadMask                   0xFFFFFFFF
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_WriteMask                  0xFFFFFFFF
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_ResetValue                 0x00000000

/* Counter number. */
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_COUNTER                          31:0
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_COUNTER_End                        31
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_COUNTER_Start                       0
#define GCREG_FUSA_AXI_READ_TIMEOUT_CONFIG_COUNTER_Type                      U32

/* Register gcregFusaAXIWriteTimeoutConfig (8 in total) **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* AXI write timeout counter. */

#define gcregFusaAXIWriteTimeoutConfigRegAddrs                            0x0098
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_Address                      0x00260
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_MSB                               15
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_LSB                                3
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_BLK                                3
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_Count                              8
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_FieldMask                 0xFFFFFFFF
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_ReadMask                  0xFFFFFFFF
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_WriteMask                 0xFFFFFFFF
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_ResetValue                0x00000000

/* Counter number. */
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_COUNTER                         31:0
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_COUNTER_End                       31
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_COUNTER_Start                      0
#define GCREG_FUSA_AXI_WRITE_TIMEOUT_CONFIG_COUNTER_Type                     U32

/*******************************************************************************
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~                         **
**                         Module FunctionSafetyState                         **
**                         ~~~~~~~~~~~~~~~~~~~~~~~~~~                         **
*******************************************************************************/

/* Register gcregFusaSTLGroupAllocationTrigger **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* STL Group allocation trigger signal. */

#define gcregFusaSTLGroupAllocationTriggerRegAddrs                        0x6A20
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_Address                  0x1A880
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_MSB                           15
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_LSB                            0
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_BLK                            0
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_Count                          1
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_FieldMask             0x00000001
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_ReadMask              0x00000001
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_WriteMask             0x00000001
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_ResetValue            0x00000000

/* Value. */
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_VALUE                        0:0
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_VALUE_End                      0
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_VALUE_Start                    0
#define GCREG_FUSA_STL_GROUP_ALLOCATION_TRIGGER_VALUE_Type                   U01

/* Register gcregFusaSTLGroupDeallocationTrigger **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* STL Group deallocation trigger signal. */

#define gcregFusaSTLGroupDeallocationTriggerRegAddrs                      0x6A21
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_Address                0x1A884
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_MSB                         15
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_LSB                          0
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_BLK                          0
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_Count                        1
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_FieldMask           0x00000001
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_ReadMask            0x00000001
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_WriteMask           0x00000001
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_ResetValue          0x00000000

/* Value. */
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_VALUE                      0:0
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_VALUE_End                    0
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_VALUE_Start                  0
#define GCREG_FUSA_STL_GROUP_DEALLOCATION_TRIGGER_VALUE_Type                 U01

/* Register gcregFusaSTLGroupEnable **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* STL Group configuration. */

#define gcregFusaSTLGroupEnableRegAddrs                                   0x6A22
#define GCREG_FUSA_STL_GROUP_ENABLE_Address                              0x1A888
#define GCREG_FUSA_STL_GROUP_ENABLE_MSB                                       15
#define GCREG_FUSA_STL_GROUP_ENABLE_LSB                                        0
#define GCREG_FUSA_STL_GROUP_ENABLE_BLK                                        0
#define GCREG_FUSA_STL_GROUP_ENABLE_Count                                      1
#define GCREG_FUSA_STL_GROUP_ENABLE_FieldMask                         0xFFFFFFFF
#define GCREG_FUSA_STL_GROUP_ENABLE_ReadMask                          0xFFFFFFFF
#define GCREG_FUSA_STL_GROUP_ENABLE_WriteMask                         0xFFFFFFFF
#define GCREG_FUSA_STL_GROUP_ENABLE_ResetValue                        0x00000000

/* Setup the STL phase, unit is cycle. */
#define GCREG_FUSA_STL_GROUP_ENABLE_PHASE                                   30:0
#define GCREG_FUSA_STL_GROUP_ENABLE_PHASE_End                                 30
#define GCREG_FUSA_STL_GROUP_ENABLE_PHASE_Start                                0
#define GCREG_FUSA_STL_GROUP_ENABLE_PHASE_Type                               U31

/* Value. */
#define GCREG_FUSA_STL_GROUP_ENABLE_ENABLE                                 31:31
#define GCREG_FUSA_STL_GROUP_ENABLE_ENABLE_End                                31
#define GCREG_FUSA_STL_GROUP_ENABLE_ENABLE_Start                              31
#define GCREG_FUSA_STL_GROUP_ENABLE_ENABLE_Type                              U01

/* Register gcregFusaWGWrapShift **
** ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ */

/* Work group wrap switch enable. */

#define gcregFusaWGWrapShiftRegAddrs                                      0x6A23
#define GCREG_FUSA_WG_WRAP_SHIFT_Address                                 0x1A88C
#define GCREG_FUSA_WG_WRAP_SHIFT_MSB                                          15
#define GCREG_FUSA_WG_WRAP_SHIFT_LSB                                           0
#define GCREG_FUSA_WG_WRAP_SHIFT_BLK                                           0
#define GCREG_FUSA_WG_WRAP_SHIFT_Count                                         1
#define GCREG_FUSA_WG_WRAP_SHIFT_FieldMask                            0x0000000F
#define GCREG_FUSA_WG_WRAP_SHIFT_ReadMask                             0x0000000F
#define GCREG_FUSA_WG_WRAP_SHIFT_WriteMask                            0x0000000F
#define GCREG_FUSA_WG_WRAP_SHIFT_ResetValue                           0x00000000

/* Shift number. */
#define GCREG_FUSA_WG_WRAP_SHIFT_SHIFT_NUMBER                                2:0
#define GCREG_FUSA_WG_WRAP_SHIFT_SHIFT_NUMBER_End                              2
#define GCREG_FUSA_WG_WRAP_SHIFT_SHIFT_NUMBER_Start                            0
#define GCREG_FUSA_WG_WRAP_SHIFT_SHIFT_NUMBER_Type                           U03

/* 0 is disable and 1 is enable. */
#define GCREG_FUSA_WG_WRAP_SHIFT_ENABLE                                      3:3
#define GCREG_FUSA_WG_WRAP_SHIFT_ENABLE_End                                    3
#define GCREG_FUSA_WG_WRAP_SHIFT_ENABLE_Start                                  3
#define GCREG_FUSA_WG_WRAP_SHIFT_ENABLE_Type                                 U01


#endif /* __gcregFuSa_h__ */
