#!/bin/sh

# Copyright (C) 2017 Steven Hessing (steven.hessing@live.com)
# This is free software, licensed under the GNU General Public License v3

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@noddos[-1]
	add ucitrack noddos
	set ucitrack.@noddos[-1].init=noddos
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
