#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dnspod[-1]
	add ucitrack dnspod
	set ucitrack.@dnspod[-1].init=dnspod
	commit ucitrack
EOF


/etc/init.d/dnspod stop

rm -f /tmp/luci-indexcache
exit 0
