#!/bin/sh /etc/rc.common
START=99
STOP=10


start() {
flag=$(ps | grep "serverchan/serverchan" | grep -v "grep" | wc -l)
if [ $flag -eq 0 ] ;then
/usr/bin/serverchan/serverchan &
fi
}
stop() {
kill -9 `pgrep -f serverchan/serverchan`
}
