EXTRA_CFLAGS += -Wno-error -Wno-packed-bitfield-compat
ccflags-y += -DCONFIG_SPRD_SIPA
obj-y += sipa_core.o sipa_skb_send.o sipa_skb_recv.o \
							sipa_nic.o sipa_debugfs.o sipa_dele_cmn.o \
							sipa_eth.o sipa_dummy.o
obj-y += sipa_phy_v0/
