#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@vssr[-1]
	add ucitrack vssr
	set ucitrack.@vssr[-1].init=vssr
	commit ucitrack
	delete firewall.vssr
	set firewall.vssr=include
	set firewall.vssr.type=script
	set firewall.vssr.path=/var/etc/vssr.include
	set firewall.vssr.reload=1
	commit firewall
EOF

/usr/share/vssr/gfw2ipset.sh
rm -f /tmp/luci-indexcache
exit 0
