#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

run_failsafe_hook() {
    [ "$pi_preinit_no_failsafe" = "y" ] && return
    if [ "$FAILSAFE" = "true" ]; then
	boot_run_hook failsafe
	lock -w /tmp/.failsafe
    fi
}

boot_hook_add preinit_main run_failsafe_hook
