#!/bin/sh
# Copyright (C) 2006-2015 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

failsafe_netlogin () {
	dropbearkey -t rsa -s 1024 -f /tmp/dropbear_failsafe_host_key
	dropbear -r /tmp/dropbear_failsafe_host_key <> /dev/null 2>&1
}

failsafe_shell() {
	lock /tmp/.failsafe
	ash --login
	echo "Please reboot system when done with failsafe network logins"
	while true; do sleep 1; done
}

boot_hook_add failsafe failsafe_netlogin
boot_hook_add failsafe failsafe_shell
