/*
 *  ## Please DO NOT edit this file!! ##
 *  This file is auto-generated from the register source files.
 *  Any modifications to this file will be LOST when it is re-generated.
 *
 *  ----------------------------------------------------------------
 *  (C) Copyright 2009-2016 Realtek Semiconductor Corp.
 *
 *  This program is the proprietary software of Realtek Semiconductor
 *  Corporation and/or its licensors, and only be used, duplicated,
 *  modified or distributed under the authorized license from Realtek.
 *
 *  ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 *  THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 *  ----------------------------------------------------------------
 *  Purpose: chip register definition and structure of RTL8373
 *
 *  ----------------------------------------------------------------
 */

#ifndef __RTL8373_MACSEC_REG_DEFINITION_H__
#define __RTL8373_MACSEC_REG_DEFINITION_H__

/* follow variable index value from 0 to 15*/
/* 128bit & 256 bit egress register (32 bit packet number)*/
#define RTL8373_MACSEC_TR_CTRL_E(index)    (0x0 + index * 0x60)
#define RTL8373_MACSEC_TR_ID_E(index)        (0x4 + index * 0x60)
#define RTL8373_MACSEC_TR_Key0_E(index)        (0x8 + index * 0x60)
#define RTL8373_MACSEC_TR_Key1_E(index)        (0xc + index * 0x60)
#define RTL8373_MACSEC_TR_Key2_E(index)        (0x10 + index * 0x60)
#define RTL8373_MACSEC_TR_Key3_E(index)        (0x14 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey0_Key4_E(index)        (0x18 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey1_Key5_E(index)        (0x1c + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey2_Key6_E(index)        (0x20 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey3_Key7_E(index)        (0x24 + index * 0x60)
#define RTL8373_MACSEC_TR_Seq_Hkey0_E(index)        (0x28 + index * 0x60)
#define RTL8373_MACSEC_TR_IV0_Hkey1_E(index)        (0x2c + index * 0x60)
#define RTL8373_MACSEC_TR_IV1_Hkey2_E(index)        (0x30 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_Hkey3_E(index)        (0x34 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_Seq_E(index)        (0x38 + index * 0x60)
#define RTL8373_MACSEC_TR_SAupd_IV0_E(index)        (0x3c + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_IV1_E(index)        (0x40 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_SAupd_E(index)        (0x4c + index * 0x60)

/* 128bit & 256 bit ingress(explict or implict) register (32 bit packet number)*/
#define RTL8373_MACSEC_TR_CTRL_I(index)    (0x0 + index * 0x50)
#define RTL8373_MACSEC_TR_ID_I(index)        (0x4 + index * 0x50)
#define RTL8373_MACSEC_TR_Key0_I(index)        (0x8 + index * 0x50)
#define RTL8373_MACSEC_TR_Key1_I(index)        (0xc + index * 0x50)
#define RTL8373_MACSEC_TR_Key2_I(index)        (0x10 + index * 0x50)
#define RTL8373_MACSEC_TR_Key3_I(index)        (0x14 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey0_Key4_I(index)        (0x18 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey1_Key5_I(index)        (0x1c + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey2_Key6_I(index)        (0x20 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey3_Key7_I(index)        (0x24 + index * 0x50)
#define RTL8373_MACSEC_TR_Seq_Hkey0_I(index)        (0x28 + index * 0x50)
#define RTL8373_MACSEC_TR_Mask_Hkey1_I(index)        (0x2c + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_IV0_Hkey2_I(index)        (0x30 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_IV1_Hkey3_I(index)        (0x34 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_Seq_I(index)        (0x38 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_Mask_I(index)        (0x3c + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_Zero_IV0_I(index)        (0x40 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_Zero_IV1_I(index)        (0x44 + index * 0x50)

/* 128bit & 256 bit egress register (64 bit packet number)*/
#define RTL8373_MACSEC_TR_CTRL_E_64(index)    (0x0 + index * 0x60)
#define RTL8373_MACSEC_TR_ID_E_64(index)        (0x4 + index * 0x60)
#define RTL8373_MACSEC_TR_Key0_E_64(index)        (0x8 + index * 0x60)
#define RTL8373_MACSEC_TR_Key1_E_64(index)        (0xc + index * 0x60)
#define RTL8373_MACSEC_TR_Key2_E_64(index)        (0x10 + index * 0x60)
#define RTL8373_MACSEC_TR_Key3_E_64(index)        (0x14 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey0_Key4_E_64(index)        (0x18 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey1_Key5_E_64(index)        (0x1c + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey2_Key6_E_64(index)        (0x20 + index * 0x60)
#define RTL8373_MACSEC_TR_Hkey3_Key7_E_64(index)        (0x24 + index * 0x60)
#define RTL8373_MACSEC_TR_Seq0_Hkey0_E_64(index)        (0x28 + index * 0x60)
#define RTL8373_MACSEC_TR_Seq1_Hkey1_E_64(index)        (0x2c + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_Hkey2_E_64(index)        (0x30 + index * 0x60)
#define RTL8373_MACSEC_TR_IS0_Hkey3_E_64(index)        (0x34 + index * 0x60)
#define RTL8373_MACSEC_TR_IS1_Seq0_E_64(index)        (0x38 + index * 0x60)
#define RTL8373_MACSEC_TR_IS2_Seq1_E_64(index)        (0x3c + index * 0x60)
#define RTL8373_MACSEC_TR_IV0_Zero_E_64(index)        (0x40 + index * 0x60)
#define RTL8373_MACSEC_TR_IV1_IS0_E_64(index)        (0x44 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_IS1_E_64(index)        (0x48 + index * 0x60)
#define RTL8373_MACSEC_TR_SAupd_IS2_E_64(index)        (0x4c + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_IV0_E_64(index)        (0x50 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_IV1_E_64(index)        (0x54 + index * 0x60)
#define RTL8373_MACSEC_TR_Zero_SAupd_E_64(index)        (0x5c + index * 0x60)

/* 128bit & 256 bit ingress register (64 bit packet number)*/
#define RTL8373_MACSEC_TR_CTRL_I_64(index)    (0x0 + index * 0x50)
#define RTL8373_MACSEC_TR_ID_I_64(index)        (0x4 + index * 0x50)
#define RTL8373_MACSEC_TR_Key0_I_64(index)        (0x8 + index * 0x50)
#define RTL8373_MACSEC_TR_Key1_I_64(index)        (0xc + index * 0x50)
#define RTL8373_MACSEC_TR_Key2_I_64(index)        (0x10 + index * 0x50)
#define RTL8373_MACSEC_TR_Key3_I_64(index)        (0x14 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey0_Key4_I_64(index)        (0x18 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey1_Key5_I_64(index)        (0x1c + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey2_Key6_I_64(index)        (0x20 + index * 0x50)
#define RTL8373_MACSEC_TR_Hkey3_Key7_I_64(index)        (0x24 + index * 0x50)
#define RTL8373_MACSEC_TR_Seq0_Hkey0_I_64(index)        (0x28 + index * 0x50)
#define RTL8373_MACSEC_TR_Seq1_Hkey1_I_64(index)        (0x2c + index * 0x50)
#define RTL8373_MACSEC_TR_Mask_Hkey2_I_64(index)        (0x30 + index * 0x50)
#define RTL8373_MACSEC_TR_IV0_Hkey3_I_64(index)        (0x34 + index * 0x50)
#define RTL8373_MACSEC_TR_IV1_Seq0_I_64(index)        (0x38 + index * 0x50)
#define RTL8373_MACSEC_TR_IV2_Seq1_I_64(index)        (0x3c + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_Mask_I_64(index)        (0x40 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_IV0_I_64(index)        (0x44 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_IV1_I_64(index)        (0x48 + index * 0x50)
#define RTL8373_MACSEC_TR_Zero_IV2_I_64(index)        (0x4c + index * 0x50)

/* SA match rule register*/
#define RTL8373_MACSEC_SAM_SA_LO(index)       (0x4000 + index * 0x40)
#define RTL8373_MACSEC_SAM_SA_HI(index)       (0x4004 + index * 0x40)
#define RTL8373_MACSEC_SAM_DA_LO(index)       (0x4008 + index * 0x40)
#define RTL8373_MACSEC_SAM_DA_HI(index)       (0x400c + index * 0x40)
#define RTL8373_MACSEC_SAM_MISC(index)       (0x4010 + index * 0x40)
#define RTL8373_MACSEC_SAM_SCI_LO(index)       (0x4014 + index * 0x40)
#define RTL8373_MACSEC_SAM_SCI_HI(index)       (0x4018 + index * 0x40)
#define RTL8373_MACSEC_SAM_MASK(index)       (0x401c + index * 0x40)
#define RTL8373_MACSEC_SAM_EXT(index)       (0x4020 + index * 0x40)

/*SA match entry enable control register*/
#define RTL8373_MACSEC_SAM_ENTRY_ENABLE       (0x6000)
#define RTL8373_MACSEC_SAM_ENTRY_TOGGLE       (0x6040)
#define RTL8373_MACSEC_SAM_ENTRY_SET     (0x6080)
#define RTL8373_MACSEC_SAM_ENTRY_CLEAR     (0x60c0)
#define RTL8373_MACSEC_SAM_ENTRY_ENBALE_CTRL     (0x6100)
#define RTL8373_MACSEC_SAM_IN_FLIGHT     (0x6104)

/* Flow control words register for MACsec/bypass/drop*/
#define RTL8373_MACSEC_SAM_FLOW_CTRL(index)     (0x7000 + index * 0x4)

/* Control packet classifier register*/
/* the variable index value from 0 to 9*/
#define RTL8373_MACSEC_CP_MAC_DA(index)     (0x7800 + index * 0x8)
#define RTL8373_MACSEC_CP_MAC_DA_ET(index)     (0x7804 + index * 0x8)
#define RTL8373_MACSEC_CP_MAC_ET(index)     (0x7850 + index * 0x4)
#define RTL8373_MACSEC_CP_MAC_DA_START_LO     (0x7880)
#define RTL8373_MACSEC_CP_MAC_DA_START_HI     (0x7884)
#define RTL8373_MACSEC_CP_MAC_DA_END_LO     (0x7888)
#define RTL8373_MACSEC_CP_MAC_DA_END_HI     (0x788c)
#define RTL8373_MACSEC_CP_MAC_DA_44_BITS_LO     (0x7890)
#define RTL8373_MACSEC_CP_MAC_DA_44_BITS_HI     (0x7894)
#define RTL8373_MACSEC_CP_MAC_DA_48_BITS_LO     (0x7898)
#define RTL8373_MACSEC_CP_MAC_DA_48_BITS_HI     (0x789c)
#define RTL8373_MACSEC_CP_MATCH_MODE     (0x78f8)
#define RTL8373_MACSEC_CP_MATCH_ENABLE     (0x78fc)

/* Vlan parser algorithm register*/
#define RTL8373_MACSEC_SAM_CP_TAG     (0x7900)
#define RTL8373_MACSEC_SAM_PP_TAGS     (0x7904)
#define RTL8373_MACSEC_SAM_PP_TAGS2     (0x7908)
#define RTL8373_MACSEC_SAM_CP_TAG2     (0x790c)

/* No-match classifier control*/
#define RTL8373_MACSEC_NM_PARAMS    (0x7940)

/* Non-match flows register*/
#define RTL8373_MACSEC_NM_FLOW_NCP    (0x7944)
#define RTL8373_MACSEC_NM_FLOW_CP    (0x7948)

/* Explicit non-match flow*/
#define RTL8373_MACSEC_NM_FLOW_EXPL    (0x794c)

/* Miscellaneous control*/
#define RTL8373_MACSEC_MISC_CONTROL    (0x797c)

/* Crypt-authenticate mode control*/
#define RTL8373_MACSEC_CRYPT_AUTH_CTRL    (0x7984)

/* Threshold for 32-bit packet numbert*/
#define RTL8373_MACSEC_SEQ_NUM_THRESHOLD    (0xf420)

/* Threshold for 32-bit packet numbert*/
#define RTL8373_MACSEC_SEQ_NUM_THRESHOLD64_LO    (0xf424)
#define RTL8373_MACSEC_SEQ_NUM_THRESHOLD64_HI    (0xf424)

/* MACsec egress or ingress mode register*/
#define RTL8373_MACSEC_EIP160_CONFIG2    (0xfff4)

/* MACsec version register*/
#define RTL8373_MACSEC_EIP160_VERSION    (0xfffc)

/* MACsec context update control register*/
#define RTL8373_MACSEC_EIP62_CONTEXT_UPD_CTRL    (0xf430)

/* MACsec context control register*/
#define RTL8373_MACSEC_EIP62_CONTEXT_CTRL    (0xf408)

/* MACsec statistics counter ingress register*/
#define RTL8373_MACSEC_STA_INOCTETSDEP(index)    (0x8000 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSUNCHECK(index)    (0x8010 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSDELAY(index)    (0x8018 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSLATE(index)    (0x8020 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSOK(index)    (0x8028 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSINVALID(index)    (0x8030 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSNOTVALID(index)    (0x8038 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSNOTUSINGSA(index)    (0x8040 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSUNUSEDSA(index)    (0x8048 + index * 0x80)
#define RTL8373_MACSEC_STA_INPKTSUNTAGHIT(index)    (0x8050 + index * 0x80)

#define RTL8373_MACSEC_STA_TRANSFORMERRORPKTS_IN   (0xc400)
#define RTL8373_MACSEC_STA_INPKTSCTRL    (0xc408)
#define RTL8373_MACSEC_STA_INPKTSNOTAG    (0xc410)
#define RTL8373_MACSEC_STA_INPKTSUNTAG    (0xc418)
#define RTL8373_MACSEC_STA_INPKTSTAG    (0xc420)
#define RTL8373_MACSEC_STA_INPKTSBADTAG    (0xc428)
#define RTL8373_MACSEC_STA_INPKTSUNTAGMISS    (0xc430)
#define RTL8373_MACSEC_STA_INPKTSNOSCI    (0xc438)
#define RTL8373_MACSEC_STA_INPKTSUNKNOWNSCI    (0xc440)
#define RTL8373_MACSEC_STA_INCONSISTCHECKCTRLNOTPASS    (0xc448)
#define RTL8373_MACSEC_STA_INCONSISTCHECKUNCTRLNOTPASS    (0xc450)
#define RTL8373_MACSEC_STA_INCONSISTCHECKCTRLPASS    (0xc458)
#define RTL8373_MACSEC_STA_INCONSISTCHECKUNCTRLPASS    (0xc460)
#define RTL8373_MACSEC_STA_INOVERSIZEPKTS    (0xc468)

/* MACsec statistics counter egress register*/
#define RTL8373_MACSEC_STA_OUTOCTETSENP(index)    (0x8000 + index * 0x80)
#define RTL8373_MACSEC_STA_OUTPKTSENP(index)    (0x8010 + index * 0x80)
#define RTL8373_MACSEC_STA_OUTPKTTOOLONG(index)    (0x8018 + index * 0x80)

#define RTL8373_MACSEC_STA_TRANSFORMERRORPKTS_EG   (0xc400)
#define RTL8373_MACSEC_STA_OUTPKTSCTRL    (0xc408)
#define RTL8373_MACSEC_STA_OUTPKTSUNKNOWNSA    (0xc410)
#define RTL8373_MACSEC_STA_OUTPKTSUNTAG    (0xc418)
#define RTL8373_MACSEC_STA_OUTOVERSIZEPKTS    (0xc420)


#endif




