/*
 *  ## Please DO NOT edit this file!! ##
 *  This file is auto-generated from the register source files.
 *  Any modifications to this file will be LOST when it is re-generated.
 *
 *  ----------------------------------------------------------------
 *  (C) Copyright 2009-2016 Realtek Semiconductor Corp.
 *
 *  This program is the proprietary software of Realtek Semiconductor
 *  Corporation and/or its licensors, and only be used, duplicated,
 *  modified or distributed under the authorized license from Realtek.
 *
 *  ANY USE OF THE SOFTWARE OTHER THAN AS AUTHORIZED UNDER
 *  THIS LICENSE OR COPYRIGHT LAW IS PROHIBITED.
 *
 *  ----------------------------------------------------------------
 *  Purpose: chip register definition and structure of RTL8373
 *
 *  ----------------------------------------------------------------
 */

#ifndef __RTL8373_TABLEFIELD_LIST_H__
#define __RTL8373_TABLEFIELD_LIST_H__

/* Module: 802.1Q VLAN */
extern rtk_tableField_t RTL8373_VLAN_TBL_FIELDS[];
/* Module: MAC Forwarding Control */
extern rtk_tableField_t RTL8373_L2_IPMC_FIELDS[];
extern rtk_tableField_t RTL8373_L2_MC_FIELDS[];
extern rtk_tableField_t RTL8373_L2_UC_FIELDS[];
/* Module: IGMP & MLD */
extern rtk_tableField_t RTL8373_IGMP_GROUP_TBL_FIELDS[];
/* Module: ACL Module */
extern rtk_tableField_t RTL8373_ACL_ACT_ENTRY_FIELDS[];
extern rtk_tableField_t RTL8373_ACL_RULE_DATA_FIELDS[];

#endif    /* __RTL8373_TABLEFIELD_LIST_H__ */

