#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@gowebdav[-1]
	add ucitrack gowebdav
	set ucitrack.@gowebdav[-1].init=gowebdav
	commit ucitrack
	delete firewall.gowebdav
	set firewall.gowebdav=include
	set firewall.gowebdav.type=script
	set firewall.gowebdav.path=/var/etc/gowebdav.include
	set firewall.gowebdav.reload=1
	commit firewall
EOF

rm -f /tmp/luci-indexcache
exit 0
