#!/bin/sh /etc/rc.common

START=99

start() {
	lua /usr/lib/lua/luci/model/cbi/passwall/server/api/app.lua start
}

stop() {
	lua /usr/lib/lua/luci/model/cbi/passwall/server/api/app.lua stop
}

restart() {
	stop
	start
}