#
# Copyright (C) 2019 Jo-Philipp Wich <jo@mein.io>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-newapi

LUCI_TYPE:=mod
LUCI_BASENAME:=newapi

LUCI_TITLE:=LuCI NewAPI
LUCI_DEPENDS:=+luci-base

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature