#!/bin/sh /etc/rc.common

#----------------------------------------------
#Copyright (C) 2019 Twinzo1 <1282055288@qq.com>
#----------------------------------------------
START=50

start(){
	lan_ipaddr=$(uci get network.lan.ipaddr)
	IDNS=$(uci get idns.@idns[0].domain )
	
	if [ -n "$IDNS" ]; then
		/etc/init.d/idns enable
		sed -i '/#added by IDNS/d' /etc/hosts
		echo  "$lan_ipaddr $IDNS #added by IDNS " >> /etc/hosts
		/etc/init.d/dnsmasq restart
	else 
		/etc/init.d/idns disable
		sed -i '/#added by IDNS/d' /etc/hosts
		/etc/init.d/dnsmasq restart
		return
	fi
}
