#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 上游源码同步

on:
# 定时触发
#  schedule:
#    - cron: 0 20 * * *

# 编辑触发
  push:
    branches:
      - master

# 点赞触发
  watch:
    types: [started]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: 效验本地文件
      uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: 设置git身份
      run : |
        git config --global user.email "66666045+cpboy2020@users.noreply.github.com"
        git config --global user.name "cpboy2020"

    - name: 加载上游提交
      run: |
        git pull https://github.com/coolsnowwolf/lede.git --log --no-commit
        
    - name: 应用提交更改
      run: |
        if [ -f ./.git/MERGE_MSG ]; then
        mkdir ./tmp && cp ./.git/MERGE_MSG ./tmp/message
        sed -i "1c [bot] AutoMerging: merge all upstream's changes:" ./tmp/message
        sed -i '/^\#.*/d' ./tmp/message
        git commit --file="./tmp/message"
        else
        echo "There is no merge commits."
        fi

    - name: 推送上游提交
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
