#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: 上游源码同步

on:
# 定时触发
  schedule:
    - cron: 0 20 * * *

# 编辑触发
  push:
    branches:
      - master

# 点赞触发
  watch:
    types: [started]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: 效验本地文件
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: 设置git身份
      run : |
        git config --global user.email "cpboy2020@163.com"
        git config --global user.name "cpboy2020"

    - name: 加载上游提交
      run: |
        git pull https://github.com/coolsnowwolf/lede.git --no-edit --strategy-option ours
        #git pull https://github.com/fw876/helloworld.git --no-edit --ff-only
        #git pull https://github.com/frainzy1477/luci-app-clash.git --ff-only
        git submodule set-url luci-apps/luci-app-aliddns https://github.com/awesome-openwrt/luci-app-aliddns.git
        #git clone https://github.com/frainzy1477/luci-app-clash.git luci-app-clash

        #git submodule add https://github.com/frainzy1477/luci-app-clash.git
        #git remote add upstream https://github.com/octocat/Spoon-Knife.git

    - name: 推送上游提交
      env:
        DOWNSTREAM_BRANCH: master
      run: git push origin $DOWNSTREAM_BRANCH
