#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@olsrd[-1]
	add ucitrack olsrd
	set ucitrack.@olsrd[-1].init=olsrd
	delete ucitrack.@olsrd6[-1]
	add ucitrack olsrd6
	set ucitrack.@olsrd6[-1].init=olsrd6
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
