#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete firewall.softethervpn
	set firewall.softethervpn=include
	set firewall.softethervpn.type=script
	set firewall.softethervpn.path=/etc/softethervpn.include
	set firewall.softethervpn.reload=1
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
  delete firewall.ah
  add firewall rule
  rename firewall.@rule[-1]="ah"
  set firewall.@rule[-1].name="ah"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="ah"
  delete firewall.esp
  add firewall rule
  rename firewall.@rule[-1]="esp"
  set firewall.@rule[-1].name="esp"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="esp"
  delete firewall.ike
  add firewall rule
  rename firewall.@rule[-1]="ike"
  set firewall.@rule[-1].name="ike"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="500"
  delete firewall.443
  add firewall rule 
  rename firewall.@rule[-1]="443"
  set firewall.@rule[-1].name="443"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="443"
  delete firewall.992
  add firewall rule 
  rename firewall.@rule[-1]="992"
  set firewall.@rule[-1].name="992"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="992"
  delete firewall.1194
  add firewall rule 
  rename firewall.@rule[-1]="1194"
  set firewall.@rule[-1].name="1194"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="1194"
  delete firewall.1701
  add firewall rule 
  rename firewall.@rule[-1]="1701"
  set firewall.@rule[-1].name="1701"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="1701"
    delete firewall.ipsec
  add firewall rule 
  rename firewall.@rule[-1]="4500"
  set firewall.@rule[-1].name="4500"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="4500"
  delete firewall.5555
  add firewall rule 
  rename firewall.@rule[-1]="5555"
  set firewall.@rule[-1].name="5555"
  set firewall.@rule[-1].target="ACCEPT"
  set firewall.@rule[-1].src="wan"
  set firewall.@rule[-1].proto="tcp udp"
  set firewall.@rule[-1].dest_port="5555"
  commit firewall
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softethervpn[-1]
	add ucitrack softethervpn
	set ucitrack.@softethervpn[-1].init=softethervpn
	commit ucitrack
EOF



/etc/init.d/softethervpn enable && /etc/init.d/softethervpn restart

rm -f /tmp/luci-indexcache
exit 0
