#!/bin/sh /etc/rc.common

START=99

start() {
	/usr/lib/lua/luci/model/cbi/v2ray_server/api/app.lua start
}

stop() {
	/usr/lib/lua/luci/model/cbi/v2ray_server/api/app.lua stop
}

restart() {
	stop
	start
}
