/* AUTO GEN PLEASE DO NOT MODIFY IT */
/* AUTO GEN PLEASE DO NOT MODIFY IT */


UCHAR BFBackoffvalue_1[] = "! Single SKU Max Power Table (unit is 1 dBm)                                                   	! 2.4G Channel                                                   	"
						   "Band: 2.4G MaxPower_4T MaxPower_3T MaxPower_2T                                                	Ch1 25 25 25                                                	"
						   "Ch2 25 25 25                                                	Ch3 25 25 25                                                	"
						   "Ch4 25 25 25                                                	Ch5 25 25 25                                                	"
						   "Ch6 25 25 25                                                	Ch7 25 25 25                                                	"
						   "Ch8 25 25 25                                                	Ch9 25 25 25                                                	"
						   "Ch10 25 25 25                                                	Ch11 25 25 25                                                	"
						   "Ch12 25 25 25                                                	Ch13 25 25 25                                                	"
						   "Ch14 25 25 25                                                	                                                   	"
						   "! 5G Channel                                                   	Band: 5G MaxPower_4T MaxPower_3T MaxPower_2T                                                	"
						   "Ch184 25 25 25                                                	Ch188 25 25 25                                                	"
						   "Ch192 25 25 25                                                	Ch196 25 25 25                                                	"
						   "Ch8 25 25 25                                                	Ch12 25 25 25                                                	"
						   "Ch16 25 25 25                                                	Ch36 25 25 25                                                	"
						   "Ch40 25 25 25                                                	Ch44 25 25 25                                                	"
						   "Ch48 25 25 25                                                	Ch52 25 25 25                                                	"
						   "Ch56 25 25 25                                                	Ch60 25 25 25                                                	"
						   "Ch64 25 25 25                                                	Ch68 25 25 25                                                	"
						   "Ch72 25 25 25                                                	Ch76 25 25 25                                                	"
						   "Ch80 25 25 25                                                	Ch84 25 25 25                                                	"
						   "Ch88 25 25 25                                                	Ch92 25 25 25                                                	"
						   "Ch96 25 25 25                                                	Ch100 25 25 25                                                	"
						   "Ch104 25 25 25                                                	Ch108 25 25 25                                                	"
						   "Ch112 25 25 25                                                	Ch116 25 25 25                                                	"
						   "Ch120 25 25 25                                                	Ch124 25 25 25                                                	"
						   "Ch128 25 25 25                                                	Ch132 25 25 25                                                	"
						   "Ch136 25 25 25                                                	Ch140 25 25 25                                                	"
						   "Ch144 25 25 25                                                	Ch149 25 25 25                                                	"
						   "Ch153 25 25 25                                                	Ch157 25 25 25                                                	"
						   "Ch161 25 25 25                                                	Ch165 25 25 25                                                	"
						   "Ch169 25 25 25                                                	Ch173 25 25 25                                                	"
						   "Ch177 25 25 25                                                	Ch181 25 25 25                                                	"
						   "                                                   	                                                   	"
						   "                                                   	                                                   	"
						   "                                                   	                                                   	"
						   "                                                   	"
						   ;
