/* AUTO GEN PLEASE DO NOT MODIFY IT */
/* AUTO GEN PLEASE DO NOT MODIFY IT */


UCHAR BFBackoffvalue_9[] = "! Single SKU Max Power Table (unit is 1 dBm)                                                   	! 2.4G Channel                                                   	"
						   "Band: 2.4G MaxPower_4T MaxPower_3T MaxPower_2T                                                	Ch1 30 30 30                                                	"
						   "Ch2 30 30 30                                                	Ch3 30 30 30                                                	"
						   "Ch4 30 30 30                                                	Ch5 30 30 30                                                	"
						   "Ch6 30 30 30                                                	Ch7 30 30 30                                                	"
						   "Ch8 30 30 30                                                	Ch9 30 30 30                                                	"
						   "Ch10 30 30 30                                                	Ch11 30 30 30                                                	"
						   "Ch12 30 30 30                                                	Ch13 30 30 30                                                	"
						   "Ch14 30 30 30                                                	                                                   	"
						   "! 5G Channel                                                   	Band: 5G MaxPower_4T MaxPower_3T MaxPower_2T                                                	"
						   "Ch184 30 30 30                                                	Ch188 30 30 30                                                	"
						   "Ch192 30 30 30                                                	Ch196 30 30 30                                                	"
						   "Ch8 30 30 30                                                	Ch12 30 30 30                                                	"
						   "Ch16 30 30 30                                                	Ch36 30 30 30                                                	"
						   "Ch40 30 30 30                                                	Ch44 30 30 30                                                	"
						   "Ch48 30 30 30                                                	Ch52 30 30 30                                                	"
						   "Ch56 30 30 30                                                	Ch60 30 30 30                                                	"
						   "Ch64 30 30 30                                                	Ch68 30 30 30                                                	"
						   "Ch72 30 30 30                                                	Ch76 30 30 30                                                	"
						   "Ch80 30 30 30                                                	Ch84 30 30 30                                                	"
						   "Ch88 30 30 30                                                	Ch92 30 30 30                                                	"
						   "Ch96 30 30 30                                                	Ch100 30 30 30                                                	"
						   "Ch104 30 30 30                                                	Ch108 30 30 30                                                	"
						   "Ch112 30 30 30                                                	Ch116 30 30 30                                                	"
						   "Ch120 30 30 30                                                	Ch124 30 30 30                                                	"
						   "Ch128 30 30 30                                                	Ch132 30 30 30                                                	"
						   "Ch136 30 30 30                                                	Ch140 30 30 30                                                	"
						   "Ch144 30 30 30                                                	Ch149 30 30 30                                                	"
						   "Ch153 30 30 30                                                	Ch157 30 30 30                                                	"
						   "Ch161 30 30 30                                                	Ch165 30 30 30                                                	"
						   "Ch169 30 30 30                                                	Ch173 30 30 30                                                	"
						   "Ch177 30 30 30                                                	Ch181 30 30 30                                                	"
						   "                                                   	                                                   	"
						   "                                                   	                                                   	"
						   "                                                   	                                                   	"
						   "                                                   	"
						   ;
